### ISSUE TITLE
SC2181 -- Conditional Command

### ISSUE THREAD

**Issue by nps1984** [koalaman/shellcheck#1008]
Looking for best practice help here...

I want to have a conditional test of the exit status of a command, but the command I am executing differs slightly based on a condition. For example, how I have it now:

    if [[ "$version" -eq 2 ]]; then
      /usr/bin/mycmd --version2 option
    else
      /usr/bin/mycmd -v1 option
    fi

    if [[ "$?" -eq 0 ]]; then
      do_this
    else
      do_that
      do_something_else
    fi

I realize I could do:

    if [[ "$version" -eq 2 ]]; then
      if /usr/bin/mycmd --version2 option; then
         do_this
      else
         do_that
         do_something_else
       fi
    else
      if /usr/bin/mycmd -v1 option; then
         do_this
      else
         do_that
         do_something_else
       fi
    fi

But that seems like a bit of duplicate code. I guess I'm just looking for the best way to handle this? Suggestions?

**Comment by koalaman** [comment]
I think your original is the better. Shellcheck should stop warning when the `$?` refers to a compound control flow statement.

You can actually do the regular rewrite, it's just awful:

```
if if foo
    then bar
    else baz
    fi
then
    etc
fi
```

**Comment by nps1984** [comment]
Thank you for the input!
