### ISSUE TITLE
Proper work with Travis CI

### ISSUE THREAD

**Issue by Mauladen** [koalaman/shellcheck#1010]
I want to use ShellCheck to check the syntax of my script in Bash, but there is a small problem.
Even when there are no syntax errors and ShellCheck gives only recommendations, the assembly fails

Is it possible to make so that failure was only in the case of a syntax error?

**Comment by brother** [comment]
I think this is a duplicate report. Check these.

- #837
- #971

**Comment by Nightfirecat** [comment]
If you are only looking for syntax errors, I believe `bash -c` might be sufficient?
