### ISSUE TITLE
Latest update of docker image is borked (executable not found)

### ISSUE THREAD

**Issue by parkr** [koalaman/shellcheck#1025]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): latest
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue
- [x] It's not reproducible on shellcheck.net, but I think that's because it's a Docker container issue

#### Here's a snippet or screenshot that shows the problem:

N/A

#### Here's what shellcheck currently says:

```console
$ docker run --rm koalaman/shellcheck --version
container_linux.go:265: starting container process caused "exec: \"/bin/shellcheck\": stat /bin/shellcheck: not a directory"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/bin/shellcheck\": stat /bin/shellcheck: not a directory"
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

#### Here's what I wanted or expected to see:

```console
$ docker run --rm koalaman/shellcheck --version
ShellCheck - shell script analysis tool
version: 0.4.6
license: GNU General Public License, version 3
website: http://www.shellcheck.net
```

**Comment by SISheogorath** [comment]
Agreed. Same problem over here.

Broke our latest build: https://travis-ci.org/#L2925-L2942

**Comment by composer22** [comment]
Fix this ASAP! 

You are not tagging builds in dockerhub correctly. The last VERSION tag you have is v0.4.6 from 6 months ago. There should at least be a v0.4.7 that corresponds to this latest build form 3 days ago. If you are going to use the LATEST as a tag you need to provide alternative version tags so we can PIN to a previous version that actually WORKS.

**Comment by parkr** [comment]
@composer22 You can pin it to v0.4.6 which does still work just fine. That’s what I did and it’s working like a charm. Only the `latest` tag has this problem.

I would also like to see more tags. Would you be willing to automate this with your CI provider? I know TravisCI offers deployment to docker hub.

As part of any upload step, the script would ideally smoke test the image to ensure it runs properly. It won’t catch all errors, but it would catch most.

Thanks!

**Comment by koalaman** [comment]
Oops. This is now fixed.

I've added a `stable` tag that is currently the same as `v0.4.6` so that you can depend on a stable version without hard coding one. `latest` is still the latest git commit.

Travis already builds and autodeploys. Smoke tests would indeed have been a good idea.

**Comment by parkr** [comment]
> Oops. This is now fixed.

Thank you, @koalaman!

> Travis already builds and autodeploys. Smoke tests would indeed have been a good idea.

Ah ok. Is it possible to add this script to a pre-deploy script?

**Comment by koalaman** [comment]
Yes, I'll make sure the images can at least run `--version` before they're deployed in the future.

**Comment by parkr** [comment]
@koalaman Thank you! I am happy to help if you need any. ✨
