### ISSUE TITLE
"echo done" emits SC1010

### ISSUE THREAD

**Issue by gpakosz** [koalaman/shellcheck#1030]
```
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.4.6
license: GNU General Public License, version 3
website: http://www.shellcheck.net
```

```
$ cat ./foo.sh

#!/bin/sh

echo done
```

```
$ shellcheck ./foo.sh

In ./foo.sh line 3:
echo done
     ^-- SC1010: Use semicolon or linefeed before 'done' (or quote to make it literal).
```

I know this is trivially silenced by replacing `echo done` with `echo "done"` but I wanted to let you know 😀

**Comment by koalaman** [comment]
This is intended behavior, and I've edited to wiki to clarify. Your code obviously works perfectly fine here, but `while true; do echo foo done` and similar is a pretty common mistake, so ShellCheck warns anyways.
