### ISSUE TITLE
Request: Stable Windows binaries

### ISSUE THREAD

**Issue by nickhutchinson** [koalaman/shellcheck#1033]
Hi,

Any chance we could have stable Windows binaries available at https://shellcheck.storage.googleapis.com/index.html as well as Linux ones? At the time of writing there are "latest" builds for both Windows and Linux as well as a `shellcheck-v0.4.6.linux.x86_64.tar.xz` build, but there's no Windows binary for 0.4.6.

Cheers,
Nick

**Comment by koalaman** [comment]
Sure thing! Stable tags were added after the 0.4.6 release, but I've gone back and built 0.4.6 for Windows like I did for Linux.

Obviously, all future releases will automatically be built and tagged as stable as well.
