### ISSUE TITLE
extra comment after disable directive

### ISSUE THREAD

**Issue by brianjmurrell** [koalaman/shellcheck#1040]
It would be nice to be able to add extra comment after a disable directive such as:

```
# shellcheck disable=SC2034 variable FOO is used in other files that import this one
```

to remind oneself and others what is being ignored.

**Comment by koalaman** [comment]
Support for this was recently added:

    # shellcheck disable=SC2034 # variable FOO is used in other files that import this one

**Comment by brianjmurrell** [comment]
Is it in a release yet?  Is the most recent release really back in March?  Will a new release be made soon?

**Comment by koalaman** [comment]
It's not yet in a release, but a new one will come out Any Day Now(tm)
