### ISSUE TITLE
SC2221/2222 don't take into account bash 4 ;;& terminator

### ISSUE THREAD

**Issue by automorphism88** [koalaman/shellcheck#1044]
I tried on shellcheck.net and verified that this is still a problem on the latest commit. It doesn't happen with my locally installed version (0.4.6).

Suppose I have a case statement, where I have shared code between cases. To avoid code duplication, bash 4 allows ending case blocks with `;;&` or `;&` instead of `;;`. When using `;;&`, bash will continue through the remaining case blocks looking for matches, instead of jumping straight to `esac` as with `;;`. 
#### Here's a snippet or screenshot that shows the problem:
```
#!/bin/bash
case $1 in
    foo|bar)
        echo foo bar
        ;;&
    foo)
        echo foo
        ;;
    bar)
        echo bar
        ;;
esac
```

The above is perfectly valid in bash 4 (`$1 = foo` will execute the first and second blocks and `$1 = bar` will execute the first and third), but shellcheck will find two errors, SC2221 with the `foo|bar)` line since it overrides the following lines `foo)` and `bar)`, and SC2222 on the latter two lines for the same reason. Shellcheck should notice that the `foo|bar)` block ends with `;;&` and evaluate the case statement accordingly.

**Comment by koalaman** [comment]
This is a very nifty case that the check indeed fails to account for. Good catch.

**Comment by nihilus** [comment]
Just one thought here, bash version 4 differs much from v3 which is more like dash, wouldn't it make sense to have it as its own variant? If you intend the code to run on v3 it is a legit error.

**Comment by automorphism88** [comment]
> Just one thought here, bash version 4 differs much from v3 which is more like dash, wouldn't it make sense to have it as its own variant? If you intend the code to run on v3 it is a legit error.

The problem is that you can't tell from the shebang if it is intended to be a bash 3+ or bash 4+ script. It's possible a bash 3 mode could be enabled with a command line option, but otherwise, if a bash 4 feature is used, in a script with a bash shebang, it seems a reasonable inference that the script is intended to be used with bash 4, especially considering that it came out in 2009, an eternity ago in software terms. Anyone running a bash version that ancient should expect that it will be likely to break modern scripts. The main reason anyone is still using bash 3 is that Apple doesn't like the GPL v3, so Mac OS users have to install a modern version manually.

Also, this warning isn't even triggered by the bash 4 feature itself being used (i.e., the case block ending with `;;&` instead of `;;`), but just when it's used in a specific way. In general shellcheck does not warn about scripts that will run on bash 4 but not bash 3. Furthermore, bash v4 is not the only time shells have introduced significant new features with different versions. It might be useful to have a tool to identify the oldest version of bash that a script could run on, but shellcheck isn't that tool.

**Comment by marcelpaulo** [comment]
Issue still present on latest git master (5005dc0).

This snippet comes from a bash completion function:

```
case $prev in
    -h) COMPREPLY=() ;;&
    -d) action_or '-q' "$cur" ;;&
    -q) action_or '-d' "$cur" ;;&
    -h|-d|-q)
	debug "COMPREPLY = ${COMPREPLY[*]}"
	return 0
	;;
esac
```

shellcheck is parsing `;;&` as if it were `;;`

```
In torr line 66:
        -h) COMPREPLY=() ;;&
        ^-- SC2221: This pattern always overrides a later one.


In torr line 67:
        -d) action_or '-q' "$cur" ;;&
        ^-- SC2221: This pattern always overrides a later one.


In torr line 68:
        -q) action_or '-d' "$cur" ;;&
        ^-- SC2221: This pattern always overrides a later one.


In torr line 69:
        -h|-d|-q)
        ^-- SC2222: This pattern never matches because of a previous pattern.
           ^-- SC2222: This pattern never matches because of a previous pattern.
              ^-- SC2222: This pattern never matches because of a previous pattern.
```

**Comment by koalaman** [comment]
This check now only triggers on non-fallthrough branches. Thanks!

**Comment by marcelpaulo** [comment]
I've just tested it, it's working fine now ! Thanks a lot !
