### ISSUE TITLE
SC2181 with curl

### ISSUE THREAD

**Issue by fab1an** [koalaman/shellcheck#1049]
#### For bugs
- SC2181
- online

#### Here's a snippet or screenshot that shows the problem:

```bash
#!/bin/bash

OVERRIDE="FAILED"
RES_OVERRIDE=$(curl -m 2 -s ${URL}/override)
if [[ $? -eq 0 ]]; then
    OVERRIDE=$(echo "$RES_OVERRIDE" | jq -cr '.[0].override' 2>&1)
fi
```

#### Here's what shellcheck currently says:
`SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.`

#### Here's what I wanted or expected to see:

I need to check first whether the `curl` request succeeded and then work on the result.

I tried replacing it with

```bash
OVERRIDE="FAILED"
if RES_OVERRIDE=$(curl -m 2 -s ${URL}/override); then
    OVERRIDE=$(echo "$RES_OVERRIDE" | jq -cr '.[0].override' 2>&1)
fi
```

but accessing invalid URLs will still enter the `if / else` then.

**Comment by Nightfirecat** [comment]
I'm not seeing anything wrong with your updated version... `curl -m 2 -s ${URL}/override` gives a non-zero exit code if the host can't be resolved (eg. "exampleeee.com"), but gives a 0 status if the response is HTTP 404. Even when contained in `RES_OVERRIDE=$(...)`, the exit code is the same. Can you explain further what you mean by "invalid URLs"?

**Comment by fab1an** [comment]
You are right. I had some issue with the new solution. But I'm not able to recall it at the moment.
