### ISSUE TITLE
statically linked shellcheck segfaults in default ubuntu docker image

### ISSUE THREAD

**Issue by pan64** [koalaman/shellcheck#1053]
I have downloaded https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz and unpacked shellcheck binary (v0.4.6) - into /tmp as shellcheck.0.4.6
I have also downloaded the default docker image for ubuntu 14.04 and tried to run it:

#### Here's a snippet or screenshot that shows the problem:

 % docker run -t -i --entrypoint /bin/bash --rm -v /tmp:/mnt ubuntu:14.04 
root@b3091cd86b69:/# /mnt/shellcheck.0.4.6 
Segmentation fault (core dumped)
root@b3091cd86b69:/# 

This is basically an ubuntu 14.04 desktop running docker 17.05.0-ce

#### Here's what shellcheck currently says:
the downloaded statically linked shellcheck works properly on the host, but not in docker.

#### Here's what I wanted or expected to see:
want to use it inside docker. I know there is a container available to donwload, but we have our own container (based on ubuntu 14.04) and actually I only wanted to put shellcheck into it.

**Comment by koalaman** [comment]
I was able to reproduce this. It's apparently due to an incompatibility in glibc, which is used for `getpwent` and such even when statically linked. Unfortunately, I don't have any good solutions or workarounds.

I do have a bad workaround though:

    touch /tmp/libc.so.6
    LD_LIBRARY_PATH=/tmp shellcheck

This creates a dummy libc for the binary to try and fail to use, before falling back on its default.

If you base your image off of ubuntu:15.04 or later, this does not appear to be a problem.

**Comment by pan64** [comment]
Thank you. You are right, it is ugly, we found another way:
we have unpacked it from artful and worked.

**Comment by fenollp** [comment]
This is still happening:

```shell
#!/bin/sh -eux

VSN=stable
SHELLCHECK_URL=https://storage.googleapis.com/shellcheck/shellcheck-$VSN.linux.x86_64.tar.xz

docker run --rm --interactive \
       debian:jessie \
       /bin/sh -eux -s <<EOF
apt update && apt upgrade -y && apt install -y curl xz-utils
curl -#fSLo shellcheck.tar.xz $SHELLCHECK_URL
tar --xz -xvf shellcheck.tar.xz
./shellcheck-*/shellcheck --version
EOF
```

```
...
+ ./shellcheck-stable/shellcheck --version
Segmentation fault (core dumped)
```

**Comment by pan64** [comment]
I found somewhere using musl to link this app may help to solve this issue.

**Comment by fenollp** [comment]
Having shellcheck as an alpine package would be fine by me! There's actually some people somewhat working on that:

https://bugs.alpinelinux.org/issues/6417
https://bugs.alpinelinux.org/issues/7105

**Comment by PeterDaveHello** [comment]
Looks not happening how
