### ISSUE TITLE
SC1117 - Escape checking

### ISSUE THREAD

**Issue by jrich523** [koalaman/shellcheck#1055]
#### For bugs
- SC1117 
- online

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/bash
echo -e "\e[92m Color Text! \e[0m"
```

#### Here's what shellcheck currently says:
```sh
echo -e "\e[92m text here \e[0m"
^-- SC1117: Backslash is literal in "\e". Prefer explicit escaping: "\\e".
^-- SC1117: Backslash is literal in "\e". Prefer explicit escaping: "\\e".
```

#### Here's what I wanted or expected to see:
It should pass, recognizing that the -e enables escape chars and that `\e[XXm` is color coding

**Comment by orbea** [comment]
I think the warning is correct, see the explanation here. https://github.com/koalaman/shellcheck/issues/1000#issuecomment-329943333

**Comment by koalaman** [comment]
This is indeed intentional. `\\e` makes it clear that the shell should pass a literal backslash to `echo`, so that `echo` can interpret it. This is what's already happening with `\e`, just in an obscured way.
