### ISSUE TITLE
When I quote it, the result is wrong!

### ISSUE THREAD

**Issue by kamontat** [koalaman/shellcheck#1056]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2062
- My shellcheck version (`shellcheck --version` or "online"): 0.4.6
- [X] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:

```sh
grep -o viewlongc.php\?id=[0-9]*\&chapter=[0-9]* < "test.html"
```

#### Here's what shellcheck currently says:

when it try to quote it, nothing are returned

**Comment by koalaman** [comment]
You've already escaped some of the glob characters, but not all of them. You can either escape the rest, or remove the escaping you already have and quote the whole string:

    grep -o viewlongc.php\?id=\[0-9]\*\&chapter=\[0-9]\* < "test.html"
    # or
    grep -o 'viewlongc.php?id=[0-9]*&chapter=[0-9]*' < "test.html"

Adding quotes around the whole thing leads to some double-escaped characters which is why that fails.

**Comment by kamontat** [comment]
Thank you.
