### ISSUE TITLE
suppress SC2086 in : ${FOO=bar}

### ISSUE THREAD

**Issue by izabera** [koalaman/shellcheck#1057]
#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/bash
: ${FOO=bar}
```

#### Here's what shellcheck currently says:
```
Line 2:
: ${FOO=bar}
  ^-- SC2086: Double quote to prevent globbing and word splitting.
```

#### Here's what I wanted or expected to see:
nothing

**Comment by nihilus** [comment]
Why not? Makes perfect sense to me, however I rarely use bash.

**Comment by koalaman** [comment]
This should be quoted in case `FOO='*/*/*/*/*/*/*'`. I've added it to the wiki

**Comment by izabera** [comment]
sneaky, thanks for pointing it out
