### ISSUE TITLE
Please provide versioned (and preferably signed) statically-linked binaries for releases

### ISSUE THREAD

**Issue by tmc** [koalaman/shellcheck#1062]
having published binaries makes for easier and safer incorporation into CI pipelines.

**Comment by brother** [comment]
These are not enough?
https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
https://storage.googleapis.com/shellcheck/shellcheck-latest.zip

See https://github.com/koalaman/shellcheck/blame/master/README.md#L160 (ugly link, not sure how to hilight a line in the README...)

**Comment by tmc** [comment]
not having tagged tarballs means I can't verify the content being pulled into an environment by checking hashses (as 'lastest' is mutable).

**Comment by koalaman** [comment]
Yes, every new release is automatically built and tagged with an immutable version tag starting with v0.4.7 (v0.4.6 was also built and tagged manually). You can additionally use your distro's package pinning features to install specific versions.
