### ISSUE TITLE
Gitlab CI integration

### ISSUE THREAD

**Issue by dcpc007** [koalaman/shellcheck#1067]
I'm creating a pipeline in Gitlab CI for my shell scripts.
It works.
But sometimes some "errors" are only at informational info and could work well without apply the solution.
In gitlab CI it check the result of command and if != 0 breaks.

=> Is it possible to ignore "info" level in spellcheck binary and get 0 in this case (without real problems) ?
(I'm still trying to look for a solution gitlab side)

**Comment by Nightfirecat** [comment]
Duplicate of #524 and/or #495? Seems like this request is at least related to those.

**Comment by dcpc007** [comment]
Yes right i think it should answer my needs.
Pitty, it's opened since 2015 and not assigned :-(
