### ISSUE TITLE
SC2221/SC2222 wrongly trigger when case fallthrough is used with wildcard

### ISSUE THREAD

**Issue by falconindy** [koalaman/shellcheck#1082]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2221/SC2222
- My shellcheck version (`shellcheck --version` or "online"): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/bash

case $1 in
        foo)
                echo doing something with foo
                ;;
        *)
                echo falling through
                ;;&
        bar)
                echo doing something with bar
                ;;
esac
```
The "bar" case can still be reached due to the use of fallthrough in the wildcard stanza.
#### Here's what shellcheck currently says:

```
Line 7:
        *)
        ^-- SC2221: This pattern always overrides a later one.
 
Line 10:
        bar)
        ^-- SC2222: This pattern never matches because of a previous pattern.
```

#### Here's what I wanted or expected to see:
Expected no lint messages.

**Comment by Nightfirecat** [comment]
Duplicate of #1044?

**Comment by falconindy** [comment]
Yep, looks like the same issue.
