### ISSUE TITLE
Could you use aeson instead of json

### ISSUE THREAD

**Issue by phadej** [koalaman/shellcheck#1085]
Consider `aeson` (http://hackage.haskell.org/package/aeson) instead of `json`. `aeson` is de-facto JSON library for Haskell.

I can do a PR if the change is OK.
  
My motivation is that `aeson` is probably better supported in the long run, given its status in the community.

**Comment by koalaman** [comment]
Sounds good to me. If you want to do a PR, that would be great

**Comment by ngzhian** [comment]
I have opened #1206 for this.
