### ISSUE TITLE
ShellCheck 0.4.7 violates PVP versioning standard

### ISSUE THREAD

**Issue by peti** [koalaman/shellcheck#1096]
The 0.4.7 release is a minor release that's supposed to be API compatible with 0.4.6 according to [PVP](https://pvp.haskell.org/). It is not, however, because the field `csCheckSourced` has been added to https://hackage.haskell.org/package/ShellCheck-0.4.7/docs/ShellCheck-Interface.html#t:CheckSpec. This change requires a version bump to (at least) 0.5.

**Comment by koalaman** [comment]
Ah, you're right. 

There's no breakage when using `emptyCheckSpec { .. }` like ShellCheck itself does, but `CheckSpec` itself *is* public.

**Comment by koalaman** [comment]
The next version has now been released as 0.5.0.
