### ISSUE TITLE
Shell library dialect declaration

### ISSUE THREAD

**Issue by szepeviktor** [koalaman/shellcheck#1108]
Th file `courier-mta-functions` would hold all my Courier MTA-related functions, so no shebang.

```shell
# shellcheck shell=bash
# Common functions for courier-mta-*.sh
```

But shellcheck says

```
In courier-mta-functions line 1:
# shellcheck shell=bash
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
```

Could there be a way to declare dialect within the file?
Thanks!

**Comment by koalaman** [comment]
This was a bug that has since been fixed. Try it again on the latest version (0.4.7) and reopen if it's still an issue.

**Comment by szepeviktor** [comment]
Thank you.
It is not packaged yet: https://tracker.debian.org/pkg/shellcheck
And I know Haskell is a dog-type or a distant star.

**Comment by szepeviktor** [comment]
The Dockerfile helped!
It is OK, Dialect recognized 💯
