### ISSUE TITLE
SC1009 online gives parser error, but wont tell me why it is wrong

### ISSUE THREAD

**Issue by Galvantua** [koalaman/shellcheck#1110]
I am getting a SC1009 error on the online version for the following code:
#!/bin/bash
while true; do
read -p "Do you wish to config Open-SSH Server?: " yn 
case $yn in
[Yy]* ) echo "Starting ssh config";
open my $in,	'<', /etc/ssh/sshd_config	or die "Can't read old file: $!"; 
open my $out,	'>', /etc/ssh/sshd_config	or die "Can't write new file: $!"; 

while( <$in> ) {
function good_value {
#...
}
}

it says that on line 9:
 ^-- SC1009: The mentioned parser error was in this simple command.
            ^-- SC1073: Couldn't parse this redirection. Fix to allow more checks.
              ^-- SC1072: Fix any mentioned problems and try again.

shellcheck wont tell me how to possibly fix it. I figured if any part would work it would be this, since i got it straight from [this](https://learn.perl.org/faq/perlfaq5.html#How-do-I-change-delete-or-insert-a-line-in-a-file-or-append-to-the-beginning-of-a-file )

**Comment by Nightfirecat** [comment]
I'm confused... What you've posted looks like some kind of mix of shell script and Perl code? Perl code would not be valid shell script.

**Comment by Galvantua** [comment]
what about on bash?

**Comment by Nightfirecat** [comment]
Bash is one language that certain shells recognize, and it looks like the first couple lines of your example are valid bash/sh, but you can't mix that with Perl along the way.

**Comment by Galvantua** [comment]
well that explains it then. i guess i got confused as to what perl actually is, but that solved my problem.

**Comment by Galvantua** [comment]
even then, shell check wont give any reason as to why parser errors happen sometimes. Is there a specific reason for this?

**Comment by Nightfirecat** [comment]
What are you hoping that shellcheck will tell you that a regular shell parser wouldn't?

```
$ cat test.sh
#!/bin/bash
while true; do
read -p "Do you wish to config Open-SSH Server?: " yn
case $yn in
[Yy]* ) echo "Starting ssh config";
open my $in, '<', /etc/ssh/sshd_config or die "Can't read old file: $!";
open my $out, '>', /etc/ssh/sshd_config or die "Can't write new file: $!";

while( <$in> ) {
function good_value {
#...
}
}

$ bash -h test.sh
test.sh: line 9: syntax error near unexpected token `)'
test.sh: line 9: `while( <$in> ) {'
```

**Comment by Galvantua** [comment]
that says that there is a syntax error/ unexpected token, which could lead to the conclusion that the code is all wrong, vs shellcheck just says 'parser error'

**Comment by rdebath** [comment]
I think this ends up as a slight (for me) rewording of the error message.

If you Google "parser error" you get all sorts of vague pages with mostly random descriptions.
If you Google "syntax error" you get a Wikipedia page with a definition; it's actually still in reality vague, but it looks better and leads to lots of explanations.
