### ISSUE TITLE
SC2163 For Exporting Functions

### ISSUE THREAD

**Issue by emoshaya** [koalaman/shellcheck#1117]
#### For bugs
- SC2163: 
- My shellcheck version (`0.4.4"): 

I have the following piece of code which gets the "SC2163" warning. How would I resolve?

```
EXPORT_FUNCTIONS='rt_del jf_rt_cmd jf_svc_cmd'
for function in ${EXPORT_FUNCTIONS}; do
  export -f "${function}"
done
```

```
  export -f "${function}"
             ^-- SC2163: Exporting an expansion rather than a variable.
```

**Comment by Nightfirecat** [comment]
Have you read [the wiki page for this error](https://github.com/koalaman/shellcheck/wiki/SC2163)? It specifically says:

> ##Exceptions:
> 
> If you do want to export the variable's value, e.g. due to indirection, you can disable this message with a directive:
> 
> ```
> # shellcheck disable=SC2163
> export "$MYVAR"
> ```

**Comment by koalaman** [comment]
This message was awful. I've improved it, and since no one would expect `export ${foo##*/}` to export the variable `foo`, I've made it skip any expansion with modifiers.

The side effect of this is that you can now use `${function?}` to make ShellCheck quiet without a directive. 

Latest now says 

    This does not export 'function'. Remove $/${} for that, or use ${var?} to quiet.
