### ISSUE TITLE
Yum is deprecated (minor website update)

### ISSUE THREAD

**Issue by gagbo** [koalaman/shellcheck#1138]
Hello,

Since [Fedora 22](https://fedoraproject.org/wiki/Releases/22/ChangeSet#Replace_Yum_With_DNF) the `yum` package manager has been replaced by `dnf`. 

shellcheck website states that `You can cabal, apt-get, yum or brew install it locally right now. `. the yum part of this line should be replaced with dnf now.

Thanks for your work !

**Comment by Nightfirecat** [comment]
FYI, koalaman/shellcheck.net is the correct repository for the website. I've opened koalaman/shellcheck.net#6 for this issue.

**Comment by koalaman** [comment]
Thanks! This has been updated.
