### ISSUE TITLE
Can one submit a PR for the Wiki?

### ISSUE THREAD

**Issue by matthewpersico** [koalaman/shellcheck#1152]
I'd like to contribute a reformat of the https://github.com/koalaman/shellcheck/wiki/Directive page to make a few things clearer (well at least to me), but I don't want to willy nilly edit it - I want to submit a PR so it can be checked and approved.

How does one do that?

**Comment by Nightfirecat** [comment]
As-is, there's no way to do that. Maybe just post your proposed changes as a diff on this issue for discussion?

**Comment by matthewpersico** [comment]
https://gist.github.com/matthewpersico/d8ad66aecd01bed825a1513bb3c625e0/revisions

**Comment by matthewpersico** [comment]
Suggest you create a dummy blank wiki page, put the new stuff in and see what it will look like...

**Comment by koalaman** [comment]
Looks good to me. The only thing is the last sentence.

ShellCheck *will always* stop parsing on a parse error, even if the error message is silenced

**Comment by matthewpersico** [comment]
Silencing parser errors is purely cosmetic; any parser error found will still stop ShellCheck at the point of the error.

**Comment by matthewpersico** [comment]
Updated. Thank you.
