### ISSUE TITLE
Emacs code to generate disable directives

### ISSUE THREAD

**Issue by matthewpersico** [koalaman/shellcheck#1155]
#### For new checks and feature suggestions
- [ ] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

I have been talking with the flycheck folks and have come up with a bit of elisp that adds a new command to the ```Flycheck errors``` buffer - when you press ```d```, the current error is disabled in the code; it adds the shellcheck disable directive,

It's not perfect. You have to make sure that you have the position in the code set to the corresponding error and it doesn't yet comma concat more than one directive. But perhaps if we put it somewhere, someone will be inspired to improve it.

Do you have a place where I can put and document this?

**Comment by koalaman** [comment]
Neat! Put it on the wiki.

**Comment by koalaman** [comment]
I created a wiki page for these kinds of nifty contributions:

https://github.com/koalaman/shellcheck/wiki/Contrib
