### ISSUE TITLE
SC2016 false positive (probably a legit one)

### ISSUE THREAD

**Issue by dereckson** [koalaman/shellcheck#1161]
With ShellCheck 0.4.7 or online, the following code triggers SC2016:

```sh
#!/bin/sh
docker run -it --rm --link "$MYSQL_CONTAINER:mysql" "$MYSQL_IMAGE" \
    sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" ...'
```

Yet, the code intent is to pass as is the expression to sh,
as the environment variables aren't available in the host
but are available in the Docker container running sh.

But I've no idea what's the intent of most people using `sh -c`,
so it's probably best to keep the advice to ask double check.

**Comment by Nightfirecat** [comment]
From [SC2016's wiki page](/koalaman/shellcheck/wiki/SC2016):

> ###Exceptions
> 
> If you want $stuff to be a literal dollar sign followed by the characters "stuff", you can ignore this message.

**Comment by koalaman** [comment]
`sudo` is already blacklisted for this warning because you frequently need to expand variables in a different context. `docker` should probably be blacklisted for the same reason.

**Comment by koalaman** [comment]
And done.  Thanks!

**Comment by dereckson** [comment]
Thanks for the quick fix.
