### ISSUE TITLE
SC2185 requires explicit path for 'find --help'

### ISSUE THREAD

**Issue by per-bohlin** [koalaman/shellcheck#1188]
#### For bugs
- Rule Id: SC2185
- My shellcheck version: 0.4.6
- I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet that shows the problem:

```sh
#!/bin/bash
find --help
```

#### Here's what shellcheck currently says:
find --help
^-- SC2185: Some finds don't have a default path. Specify '.' explicitly.

#### Here's what I wanted or expected to see:
I expected that 'find --help' would not result in any errors.

**Comment by koalaman** [comment]
Kindly fixed by @ngzhian. Thanks!
