### ISSUE TITLE
Need to follow include files and check them too

### ISSUE THREAD

**Issue by nachotech** [koalaman/shellcheck#121]
shellcheck does not check included files in bash.  Here's proof:

# cat test.sh
#!/bin/bash

source include.sh

abc=0

exit 0

# cat include.sh
def=0

# shellcheck test.sh

In test.sh line 5:
abc=0
^-- SC2034: abc appears unused. Verify it or export it.

#

shellcheck should have also warned about "def" being unused, but it did not, because it did not check the included shell script. I use numerous included scripts in my system, and this tool is not very useful since it does not check included files.

**Comment by koalaman** [comment]
It took over a year, but with f31c8bd things like this is gradually starting to be supported.
