### ISSUE TITLE
SC2144 incorrect

### ISSUE THREAD

**Issue by fredjohnsen** [koalaman/shellcheck#1217]
#### For bugs
SC2144
ShellCheck version 0.4.7
only ran on local version

This works:
`touch /tmp/blah_some.string.here_blah.txt`
`if [ -e /tmp/*_some.string.here_*.txt ]; then echo EXISTS; fi`

Single brackets are POSIX compliant.

#### Here's what shellcheck currently says:

          ^-- SC2144: -e doesn't work with globs. Use a for loop.

**Comment by Nightfirecat** [comment]
From [SC2144's wiki entry](/koalaman/shellcheck/wiki/SC2144):

> `[ -e file* ]` only works if there's 0 or 1 matches. If there are multiple, it becomes `[ -e file1 file2 ]`, and the test fails.

Here is an example, which I ran on my own computer:

```
$ touch /tmp/foo_some.string.here_bar.txt

$ ls /tmp/*_some.string.here_*.txt
/tmp/foo_some.string.here_bar.txt

$ [ -e /tmp/*_some.string.here_*.txt ] && echo $?
0

$ touch /tmp/foobar_some.string.here_foobar.txt

$ ls /tmp/*_some.string.here_*.txt
/tmp/foo_some.string.here_bar.txt  /tmp/foobar_some.string.here_foobar.txt

$ [ -e /tmp/*_some.string.here_*.txt ] && echo $?
bash: [: /tmp/foo_some.string.here_bar.txt: binary operator expected
```

**Comment by fredjohnsen** [comment]
This is completely superfluous comment considering I said nothing about searching for more than 1 or 0 instances. You don’t need a for loop for that. The warning is still incorrect.

**Comment by jleffler** [comment]
The warning is correct — the shell script is not reliable because it uses wildcards in the test operator.

**Comment by matthewpersico** [comment]
Whether or not you said anything about searching for 0 or 1 instances, the fact of the matter is that once you have that * in there, there is the potential to get glob expansion that could result in and invalid statement. If you know your environment will not produce such an error, add the disable statement, but shellcheck cannot assume that. I concur with the validity of the check.

**Comment by koalaman** [comment]
You know your expectations better than ShellCheck.  It can only guess the user's intentions based on their script. In this case it guessed that you wanted to check if any matching files exist. 

In this case it may have been wrong, but the heuristic holds up in general. It's more common to want to check if any files exist, than it is to want to show strange errors when you have more than one match.

**Comment by Nightfirecat** [comment]
@fredjohnsen ShellCheck will not be able to make assumptions regarding your filesystem when this script runs. While you may be able to be reasonably certain that you will always have 0 or 1 instances of a file, that does not mean that ShellCheck will adopt that same assumption.

Regardless, making the change suggested would be a better practice in general situations, and would behave similarly for your code.

**Comment by unphased** [comment]
I'm here in the same scenario. It looks like the way to go is to leave a comment in the code to ignore SC2144 if it's clear that the glob would never match more than one file. 

It would be nice if the shellcheck error included language to explain itself better, although I suppose the suggestion to use a for loop in hindsight does hint at the issue.

**Comment by koalaman** [comment]
You can definitely do that. You can also consider making the assumption explicit to fail fast if it's ever violated (which the wiki now also mentions):

```
files=( dir/file* )
[ "${#files[@]}" -ge 2 ] && exit 1
if [ -e "${files[0]}" ]
then 
  echo "The file exists"
else
  echo "No such file"
fi
```

**Comment by schmorp** [comment]
I came here because I also wondered why this is an error as opposed to a warning. ShellCheck can't know if this is an error, and in other cases such as this, it emits a warning or info. For example, SC2086 is a good example - sometimes word splitting is intended, sometimes not. shellcheck can't know that, so it should not make it an error.
