### ISSUE TITLE
builtin cd

### ISSUE THREAD

**Issue by alok** [koalaman/shellcheck#1226]
#### For bugs
- Rule Id (if any, e.g. SC1000): 2164
- My shellcheck version (`shellcheck --version` or "online"): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

I'm not sure if this counts as a bug, but the command `cd foo` gives SC2164, but `builtin cd foo` does not even though it's essentially the same command.

**Comment by ngzhian** [comment]
This is same as #1234 (saw that first cos issues were in descending order :) )

**Comment by koalaman** [comment]
I'll close this is a dupe even though it's the other way around :P
