### ISSUE TITLE
Error parsing regex

### ISSUE THREAD

**Issue by v1s1t0r1sh3r3** [koalaman/shellcheck#1235]
#### For bugs
- Rule Id SC1009 , SC1073 and SC1072
- My shellcheck version 0.4.7
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ X] It's not reproducible on shellcheck.net, <--------- the script is too big to work there.

Address of the repo containing the script producing this error:
https://github.com/v1s1t0r1sh3r3/airgeddon

#### For new checks and feature suggestions
- [ ] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [X ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:
![imagen](https://user-images.githubusercontent.com/17899365/40451042-9bb7af0e-5edd-11e8-95f2-8c524d261c6c.png)

#### Here's what shellcheck currently says:
In airgeddon.sh line 11072:
	elif [[ "${1}" =~ ^${escaped_hintvar}[[:space:]](\\033\[[0-9];[0-9]{1,2}m)?(${escaped_pending_of_translation})[[:space:]](.*) ]]; then
                          ^-- SC1009: The mentioned parser error was in this regex.
                                                        ^-- SC1073: Couldn't parse this regex grouping.
                                                          ^-- SC1072: Unexpected . Fix any mentioned problems and try again.

#### Here's what I wanted or expected to see:
No error as it used to be. That part wasn't modified and with earlier versions it shows no errors using `shellcheck -x airgeddon.sh`

**Comment by koalaman** [comment]
This is indeed an issue in 0.4.7. It was fixed with #1077 and I verified that this script works with the latest git version!
