### ISSUE TITLE
Local scoping bleeds across functions.

### ISSUE THREAD

**Issue by matthewpersico** [koalaman/shellcheck#1244]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2154
- My shellcheck version (`shellcheck --version` or 'online'): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/bash

some_func ()
{
    echo in some_func
    echo "[$onetag]"
    echo "[$twotag]"
}

some_one_func ()
{
    echo in some_one_func
    #local onetag="yuk1"
}

some_two_func ()
{
    echo in some_two_func
    local twotag="yuk2"
}

some_one_func
some_two_func
some_func


```

#### Here's what shellcheck currently says:
```
Line 8	SC2154: onetag is referenced but not assigned.
```
#### Here's what I wanted or expected to see:

Line 8	SC2154: onetag is referenced but not assigned.
Line 9	SC2154: twotag is referenced but not assigned.

Because when you run the script, you get:
in some_one_func
in some_two_func
in some_func
[]
[]

**Comment by koalaman** [comment]
Similar to #1225. This is one of the things I really want to fix properly.
