### ISSUE TITLE
Docker image's `stable` tag broken

### ISSUE THREAD

**Issue by mattmahn** [koalaman/shellcheck#1245]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [x] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:

I'm using ShellCheck as a job in my GitLab pipeline; the job descriptor is
```yaml
---
variables:
  SHELL_SCRIPTS: 'ci_build.sh'

ShellCheck:
  stage: Pre-Build
  image:
    name: koalaman/shellcheck:stable
    entrypoint: [""]
  script: "shellcheck ${SHELL_SCRIPTS:-*.sh}"
```

#### Here's what shellcheck currently says:

This is the output of GitLab job (run at 2018-06-01 10:51 CDT):
```
Running with gitlab-runner 10.6.0 (a3543a27)
  on ip-10-752-9-2 460123f3
Using Docker executor with image koalaman/shellcheck:stable ...
Pulling docker image koalaman/shellcheck:stable ...
Using docker image sha256:0627884de20bc6a3a5d1cb5cec76b8aa8585a5fef914368edb435129b72f956e for koalaman/shellcheck:stable ...
Running on runner-460123f3-project-5128-concurrent-0 via runner-460123f3-shared-prod-1527862520-1350f3b9...
Cloning repository...
Cloning into '/builds/benefits/nodejs-centos'...
Checking out 7e8e606e as master...
Skipping Git submodules setup
ERROR: Job failed (system failure): Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"sh\": executable file not found in $PATH"
```

#### Here's what I wanted or expected to see:

The previous job (checking the same exact script) had the following output at 2018-05-31 13:43 CDT:
```
Running with gitlab-runner 10.6.0 (a3543a27)
  on ip-10-543-9-6 460123f3
Using Docker executor with image koalaman/shellcheck:stable ...
Pulling docker image koalaman/shellcheck:stable ...
Using docker image sha256:ecdc3276f2a9ab72fdd0df638436153ff6d98db468075e3a172059449181edf6 for koalaman/shellcheck:stable ...
Running on runner-460123f3-project-5128-concurrent-0 via runner-460123f3-shared-prod-1527786568-22a30d71...
Cloning repository...
Cloning into '/builds/benefits/nodejs-centos'...
Checking out 1b86209c as ci-template...
Skipping Git submodules setup
$ shellcheck ${SHELL_SCRIPTS:-*.sh}
Job succeeded
```

I expected to this output since there was no change to the script that is being checked nor the GitLab job. Because I'm specifying the `stable` tag, I would also expect that the Docker image would not suddenly stop working, I would rather expect new errors to be shown.

-----

The GitLab job is using the `stable` tag of the [`koalaman/shellcheck`](https://hub.docker.com/r/koalaman/shellcheck) Docker image. I see that `stable` was updated around 2018-05-31 22:57 CDT, but `latest` was not. The `v0.5` tag was also published at the same time, but the changelog doesn't explicitly mention v0.5, so this leads me to think that v0.5 is not actually released yet.

What happened here? Can you revert/fix `stable` back to an actual working image?

**Comment by koalaman** [comment]
Sorry to break your build! tl;dr: switch to:

    name: koalaman/shellcheck-alpine:stable

GitLab requires its images to have a shell. `koalaman/shellcheck` used to be based on Alpine Linux and therefore just happened to contain one. 

Now it only contains a statically compiled `shellcheck` binary, making it significantly smaller. The `shellcheck-alpine` image is there for anyone who wants a more complete image with extra utilities.

**Comment by koalaman** [comment]
Also, with this image you don't need to override the entrypoint ^^

**Comment by mattmahn** [comment]
Thanks for the clarification.

For everyone else, my new job is:
```yaml
ShellCheck:
  stage: Pre-Build
  image: koalaman/shellcheck-alpine:stable
  script: "shellcheck ${SHELL_SCRIPTS:-*.sh}"

```
