### ISSUE TITLE
No support for relative paths or environment variables when sourcing files

### ISSUE THREAD

**Issue by Slaiyer** [koalaman/shellcheck#1250]
#### For bugs
- Rule ID (if any, e.g. SC1000): SC1090, SC1091
- My shellcheck version (`shellcheck --version` or "online"): 0.4.7
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [x] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### For new checks and feature suggestions
- [ ] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/usr/bin/env bash

# Source Bash utilities, if possible
[[ -z "${HOME}" ]] \
    && { "${HOME:?}"; exit 1; }
export bash_utils="${HOME}/bin/bash_utils.sh"
# shellcheck source=${HOME}/bin/bash_utils.sh
if [[ ! -e "${bash_utils}" ]] || ! . "${bash_utils}"; then
    printf '[ERROR] Could not source %s\n' "${bash_utils}" 1>&2
    exit 1
fi
```

#### Here's what shellcheck currently says:
Terminal:
```sh
$ shellcheck -x "$(which rip_up)"
if [[ ! -e "${bash_utils}" ]] || ! . "${bash_utils}"; then
                                   ^-- SC1090: Can't follow non-constant source. Use a directive to specify location.
```
VS Code:
```sh
Not following: ${HOME}/bin/bash_utils.sh: openBinaryFile: does not exist (No such file or directory) [SC1091]
```

#### Here's what I wanted or expected to see:
Support for substituting environment variables should be present.
When someone clones my repo, my home path cannot be expected to match theirs.
Merge conflicts arise for an entirely avoidable reason when the other person updates the shellcheck directive to suit their sourced locations.

Please consider, and thanks for this wonderful tool.

**Comment by matthewpersico** [comment]
Without a solid location shellcheck is, at best, guessing. What if you run it and your copy of bash_utils.sh is fine but the production version has an error? You can complain shellcheck didn’t find an error when you checked it but there it was lurking in production. I say you need to tell shellcheck where the file is or disable the check.

**Comment by Slaiyer** [comment]
I have also tried relative paths, but to no avail.

Absolute paths are very restrictive in terms of collaboration.
What about merge conflicts when all parties have their own source paths hardcoded in?

**Comment by Slaiyer** [comment]
[The POSIX speicification](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) requires HOME to be set by the OS (ref. [this](https://unix.stackexchange.com/a/123859/80676)).

Disabling the check results in dozens of errors about using variables defined in the source script, which is expected, but too much noise to filter through.

**Comment by koalaman** [comment]
I tried to reproduce this issue with relative paths and couldn't:

```
vidar@vidarholen-vm2 ~ $ cat foo
#!/bin/bash
source ./bar

vidar@vidarholen-vm2 ~ $ cat bar
echo foo

vidar@vidarholen-vm2 ~ $ shellcheck -x foo
vidar@vidarholen-vm2 ~ $
```

What's the problem with relative paths?

**Comment by Slaiyer** [comment]
Fixed with this:
```
# Source Bash utilities, if possible
declare script_path
script_path="$(dirname -- "${0}")"
declare -r script_path
declare -rx bash_utils="${script_path}/bash_utils.sh"
if [[ ! -f "${bash_utils}" ]]; then
    printf '[FATAL] Could not find %s\n' "${bash_utils}" 1>&2
    exit 1
fi
# shellcheck source=./bash_utils.sh
if ! . "${bash_utils}"; then
    printf '[FATAL] Could not source %s\n' "${bash_utils}" 1>&2
    exit 1
fi
```
