### ISSUE TITLE
SC2217: mv does read stdin

### ISSUE THREAD

**Issue by s-hamann** [koalaman/shellcheck#1251]
I have code similar to the following:

```sh
while read -r filename; do
  mv -i $filename . < /dev/tty
done < <(something)
```

I get SC2217: "Redirecting to 'mv', a command that doesn't read stdin."
In this case `mv` does read stdin and I am not aware of any way to get the desired behaviour without redirecting into `mv`.

I think the check should be refined to test if `mv`/`cp`/`rm`/... is used with `-i`.

**Comment by koalaman** [comment]
Fixed by @ngzhian, thanks!
