### ISSUE TITLE
TODO: Add title

### ISSUE THREAD

**Issue by kinglrb** [koalaman/shellcheck#1264]
for app in `(cmsadmin  eclp  hffadmin  hpsadmin  report  tcadmin  ucadmin  workflow auction  cmsweb  hpsbank  jresplus-middleserver  openapi  trade  tradeconf ar  eclp-as  five-as  hps-as  ta-as  uc-as)`

do
    sed -n /couchbase.server=10.139.40.12/p $deploy$app/$ser_pro
    sed -n /uat/p $deploy$app/$ser_pro

    # sed -n /couchbase.server=10.139.40.12/p $2$3/$4
    # sed -n /uat/p $2$3/$4
done

**Comment by koalaman** [comment]
Assuming this was accidental. If not, add explanation and reopen.
