### ISSUE TITLE
It used to work, now most of the time it just locks up

### ISSUE THREAD

**Issue by NewtownGal** [koalaman/shellcheck#1269]
I run it online in Chrome. Up until a few weeks ago, it analyzed my scripts (up to a few 1,000 lines) in a few seconds. Now, most of the time, nothing happens in 15 seconds so I give up and exit.

**Comment by matkoniecz** [comment]
See https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

> I run it online in Chrome.

On which website?

> it analyzed my scripts

Can you give an example of smallest script causing lock up?

**Comment by NewtownGal** [comment]
shellcheck.net

Last week, it just hung up. But starting this past weekend, it started saying:

Line 1:
#!/bin/bash
^-- SC0: Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally.

This script has 1203 lines, maybe 10% of which are comments or blank lines.

When it told me to run it locally, I asked about a version that runs in Raspian on a Pi-2 from the console. However, the capacity of the online tool, in terms of size of the script, seems to be less than it used to be.

How would I give you a script that does not become public, although it appears that size is the #1 issue. I much prefer to run it online.

**Comment by koalaman** [comment]
The online version has some resource constraints to avoid accidental DoS from especially large or complex scripts. Up until last week, exceeding them accidentally caused a hang, but now you get an explicit message as you've seen.

I never really expected people to regularly use it on 1000+ line scripts, it was mostly meant for demo purposes. The limits haven't changed in a while, but ram usage tends to creep up as functionality grows.

There is a package available for Raspbian (stretch at least), and I'm working on official builds. I'll also look into better ways of hosting the online version.

**Comment by NewtownGal** [comment]
Thank you for the update. I have to build a machine that runs Stretch from the command line since I've been running earlier Raspians. It has proven very useful to run every bash script through the online shellcheck because it makes it much faster and easier to find and fix dumb typos, as well as teaching better ways to code. The thing I still have the most trouble tracking down is mis-matched brackets of various sorts.

Thank you again for a fantastic tool.

**Comment by sbf-** [comment]
Same here... online no issues before, but script keeps growing (1900 lines now) and I get
`Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally`

So I installed shellcheck locally on my Raspberry Pi (stretch) and now I get
`test-config: test-config: hGetContents: invalid argument (invalid byte sequence)`

What should I do to make it work?

**Comment by sbf-** [comment]
@koalaman Thanks, I have V0.4.4 -- I'll try the newer version asap
In the meantime I was able to fix the issue: file is encoded ANSI but I had a '®' character in a comment line.
ANSI is all characters below or equal 0x7F - '®' is 0xAE
When I remove this invalid ANSI character it works.
