### ISSUE TITLE
grep -v | wc -l can not be replaced by grep -c

### ISSUE THREAD

**Issue by taladar** [koalaman/shellcheck#1271]
SC2126
0.4.6
I tried on shellcheck.net

```sh
#!/bin/bash

set -e -u

changed_files="$(find /etc/letsencrypt -newermt "$(date -d "yesterday 00:00" '+%Y%m%d %H:%M:%S')" | grep -v "^/etc/letsencrypt$"| wc -l)"

if [[ "${changed_files}" -gt 0 ]]; then
  # some files changed in /etc/letsencrypt
  systemctl restart nginx
fi

```

#### Here's what shellcheck currently says:
```

Line 5:
changed_files="$(find /etc/letsencrypt -newermt "$(date -d "yesterday 00:00" '+%Y%m%d %H:%M:%S')" | grep -v "^/etc/letsencrypt$"| wc -l)"
>>                                                                                                  ^-- SC2126: Consider using grep -c instead of grep|wc -l.
```

#### Here's what I wanted or expected to see:

No warning since the grep is meant to filter out one line before counting the rest.

**Comment by pawamoy** [comment]
And you can achieve that with `"$(... | grep -vc "^/etc/letsencrypt$")"` So the `wc -l` pipe is indeed not needed if you use grep's `-c` option.

**Comment by taladar** [comment]
I got that last bit you mentioned in your comment. My mistake was that I made a mistake in the regular expression when i tried the -vc version by leaving out the ^ and $ and obviously considered the resulting 0 a wrong result. Sorry for the hassle.
