### ISSUE TITLE
hGetContents: invalid argument

### ISSUE THREAD

**Issue by Mausy5043** [koalaman/shellcheck#1277]
Over on [gitlab.com](https://gitlab.com/mausy5043/uss_cygnus/-/jobs/78539228) I'm using their web-based CI to run checks on my software.  
One of the checks is a `shellcheck` on the various scripts.  
I get this error:
```
$ shellcheck -V
ShellCheck - shell script analysis tool
version: 0.4.4
license: GNU General Public License, version 3
website: http://www.shellcheck.net
$ shellcheck --format=gcc --external-sources bin/*
bin/include: bin/include: hGetContents: invalid argument (invalid byte sequence)
ERROR: Job failed: exit code 1
```

I've tracked this down to the use of escape codes in the failing script. For example:
```
COL_BOLD='[1m'
```
There is a `<0x1b>` between the `[` and the `1`.
From #846 and #1182 I gather that this has something to do with the locale set on the system.
But I don't get how to fix this.

Given the version that I seem to be stuck with, is there a workaround?

Or is there some way I could force a newer version to be installed somehow?

**Comment by Mausy5043** [comment]
Here is the locale setting of a system:
```
$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by Mausy5043** [comment]
Just got some new testresults in:
Am I doing it right this way?
```
$ LC_ALL=C.UTF-8 shellcheck --format=gcc --external-sources bin/*
Job succeeded
```
OR
```
$ export LC_ALL=C.UTF-8; shellcheck --format=gcc --external-sources *.sh
Job succeeded
```

**Comment by koalaman** [comment]
Huh. I have no idea why a literal escape would be a problem since it's valid ASCII, latin1 and UTF-8. I'm unable to reproduce it.

In any case, yes, setting the locale is the way to work around this. Normally this occurs when your locale is UTF-8 but your files have bytes >= 0x80 that aren't, so I'm surprised that `C.UTF-8` helps at all.

Another option is to run a later version via docker or similar, if Gitlab makes that simple:

    docker run -v "$PWD:/mnt" koalaman/shellcheck:v0.5.0 --format=gcc --external-sources bin/*

**Comment by Mausy5043** [comment]
Yeah, I can use a different docker image. But, I'm used to using `debian:latest`. That currently comes with v0.4.4.
And the workaround works, so...

Anyway, thanks for the suggestion. I'll keep it in mind if I run into problems in the future.

**Comment by koalaman** [comment]
That's a stand-alone command that's not intended to modify any of your existing containers. I don't know what happens if you try to invoke a Docker container from within Docker though ^^
