### ISSUE TITLE
Make ShellCheck.Interface types more opaque and future proof

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#1300]
Currently, all the types in ShellCheck.Interface are highly transparent. This means that simply adding a field or optional setting causes an API incompatibility. Specifically, this affects [hadolint](https://github.com/hadolint/hadolint/blob/master/src/Hadolint/Shell.hs). 

These should probably all be record types with hidden constructors, along with functions like `emptyCheckSpec` that initialize them with useful default values.

**Comment by ngzhian** [comment]
Do we then do something like,
```
module ShellCheck.interface
  (
  SystemInterface(siReadFile)
  CheckSpec(csFilename, csScript, csCheckSourced, csExcludedWarnings, csShellTypeOverride)
  ...
  )
```
Export the Type but not the constructor, and expose the fields?

**Comment by ngzhian** [comment]
I have a WIP at https://github.com/ngzhian/shellcheck/tree/opqaque-interface
Only PositionedComment has been made opaque so far, and I also fixed up areas which depended on the constructor.
Please see if that's an alright way to do things?
