### ISSUE TITLE
SC1117 with grep 'or'

### ISSUE THREAD

**Issue by Pupkur** [koalaman/shellcheck#1301]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC1117, SC1117, SC1117, SC1117, SC1117, SC1117
- My shellcheck version (`shellcheck --version` or 'online'): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [x] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [x ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/bash
flash=$(mount | grep -i sd | grep -i live | cut -c 6-8)
disk=$(lshw -class disk -class storage -short | grep -v "$flash" | grep -i "sd" | grep -vi "rom\|controller\|description\|=" | awk '{print $5" "$6" "$4}' | uniq)
disk_label=$(lshw -class disk -class storage -short | grep -v "$flash" | grep -i "sd" | grep -vi "rom\|controller\|description\|=" | awk '{print $2}'  | uniq)
echo "$disk"
echo "$disk_label"
```

#### Here's what shellcheck currently says:
```
Line 3	SC1117: Backslash is literal in "\|". Prefer explicit escaping: "\\|".
Line 3	SC1117: Backslash is literal in "\|". Prefer explicit escaping: "\\|".
Line 3	SC1117: Backslash is literal in "\|". Prefer explicit escaping: "\\|".
Line 4	SC1117: Backslash is literal in "\|". Prefer explicit escaping: "\\|".
Line 4	SC1117: Backslash is literal in "\|". Prefer explicit escaping: "\\|".
Line 4	SC1117: Backslash is literal in "\|". Prefer explicit escaping: "\\|".
```
#### Here's what I wanted or expected to see:
I think this is a bug. Or maybe there is an another way to use grep with 'or' condition?

**Comment by pawamoy** [comment]
So you mean you want to match `rom` **or** `controller` **or** `description` **or** `=`, and not the concatenated `rom|controller|description|=` string? If yes, you should write it with simple-quotes and no backslash: `grep 'rom|controller|description|='`.

**Comment by koalaman** [comment]
Here's the wiki page with additional information: https://github.com/koalaman/shellcheck/wiki/SC1117

ShellCheck is right.  It's unlikely to cause problems, but `"\|"` is indeed an unknown escape sequence in double quoted bash strings. `grep 'rom\|controller'` and `grep "rom\\|controller"` do the same thing without relying on unknown escape sequences.

Alternatively, `grep -E 'rom|controller'` does the same thing in a POSIX portable way.

**Comment by Pupkur** [comment]
Thanks to all for quick reply. You are right. I`ll fix my code. Thx again. Close the issue please.

**Comment by koalaman** [comment]
For what it's worth, I've retired this warning due to it almost never indicating a fix-worthy issue while being generally noisy.
