### ISSUE TITLE
If there is $(("$X" + "$Y")) in my code, I would shellcheck like to point out my mistakes.

### ISSUE THREAD

**Issue by takenoko-str** [koalaman/shellcheck#1305]
#### For new checks and feature suggestions
- [ ] when codes include the description like $(("$x" +"$y")), shellcheck point out my mistakes.

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/bash

X=1
Y=2
echo $(("$X"+"$Y"))

```

#### Here's what shellcheck currently says:
$ shellcheck myscript
No issues detected!

#### Here's what I wanted or expected to see:
-bash: "1"+"2": syntax error: operand expected (error token is ""1"+"2"")

thank you for readling.

**Comment by koalaman** [comment]
Huh. This is indeed a problem in dash and bash3, but not in bash4.

**Comment by takenoko-str** [comment]
Thanks to your support, I could solve a this problem for now.
```sh
brew install bash
```
This issue is at your discretion.
I will confirm bash version.

**Comment by takenoko-str** [comment]
Maybe, I think this issue needs the SC2004 message.
