### ISSUE TITLE
Discrepancy between checks on command line/docker vs Atom

### ISSUE THREAD

**Issue by indietravel** [koalaman/shellcheck#1307]
I'm trying to bring shellcheck into our CI system, but running into some discrepancies between the Docker image and the Atom version of the linter.

Both OSX (through brew) and Docker (through docker hub's koalaman/shellcheck:stable) are on shellcheck version 0.5.0, and Atom's linter plugin is on 1.4.7.

For a given file, Atom is showing a green light, but running the same file through Docker throws a dozen errors. This is severely slowing down the attempt to get these tests to green.

What can I try to get these tests in sync?

**Comment by indietravel** [comment]
Mechanic's look strike's again! 

Atom has a semi-obscure option to activate notices:
<img width="760" alt="screenshot 2018-07-29 17 45 56" src="https://user-images.githubusercontent.com/1871486/43368582-6398a8fe-9357-11e8-9a5d-31a3348ce1d0.png">

I haven't found the docker equivalent to deactivate notices.

**Comment by croesnick** [comment]
@indietravel The functionality for enabling/disabling notice messages has been added to linter-shellcheck in [this commit](https://github.com/AtomLinter/linter-shellcheck/commit/d3346769de6f21b78a83402a272a0b347be39695). As linter-shellcheck does custom parsing of shellcheck's result, there does not seem to be a way (yet) to get this functionality directly from shellcheck.

**Comment by indietravel** [comment]
Thanks @croesnick 

Since the discrepancies are solved, at least in one direction, I'll close this issue; and leave the bigger picture in the hands of #470 and friends.
