### ISSUE TITLE
BASh/`chmod -r` not flagged as an error

### ISSUE THREAD

**Issue by GrayCatCode** [koalaman/shellcheck#1321]
#### For bugs

ShellCheck - shell script analysis tool
version: 0.3.5
license: GNU Affero General Public License, version 3
website: http://www.shellcheck.net

#### Here's a snippet or screenshot that shows the problem:

The tool actually misses a syntactical error with the `chmod` command where `-r` flag is used instead of the appropriate `-R` flag.

#!/your/interpreter

BASh v4.2.46

#### Here's what shellcheck currently says:

It actually passes the syntax without issue.

#### Here's what I wanted or expected to see:

I would have expected it to pick up the `-r` option for `chmod` as an syntax error.

**Comment by Andrew-Poloni** [comment]
I should have been more specific regarding the context of the error: in my case I was attempting to execute the command recursively which required the uppercase `-R` vs. the lowercase as you mentioned.  A warning would definitely be helpful. :+1:

**Comment by koalaman** [comment]
There's now a warning for this, thanks!
