### ISSUE TITLE
Warn on missing newline character at EOF

### ISSUE THREAD

**Issue by oliv3r** [koalaman/shellcheck#1334]
#### For new checks and feature suggestions
- [x] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

Shellcheck currently does not note that a file is missing a new line character at the EOF. While the content is probably accurate, technically, the last 'line' is not an actual line due to the missing new line character. This is almost always a result of badly configured editors and the like.

Shell check should offer a suggestion this is happening as some smarter tools also do: "No newline at end of file".

**Comment by koalaman** [comment]
Missing trailing linefeeds are awful! Check out [shfmt](https://github.com/mvdan/sh) for any issues relating to whitespace and formatting.

ShellCheck currently doesn't intend to enforce any particular whitespace usage except for where it's required for the script to work.

**Comment by oliv3r** [comment]
unless your final line is missing a newline, and it thus isn't a true line anymore. It seems that all parsers currently handle that appropriately then. Thanks for pointing me to shfmt, it's something useful for sure!
