### ISSUE TITLE
SC2102 is missing a wiki page

### ISSUE THREAD

**Issue by tdmalone** [koalaman/shellcheck#1338]
https://github.com/koalaman/shellcheck/wiki/SC2101
and
https://github.com/koalaman/shellcheck/wiki/SC2103
both exist

But https://github.com/koalaman/shellcheck/wiki/SC2102 does not :)

> SC2102: Ranges can only match single chars (mentioned due to duplicates).

**Comment by koalaman** [comment]
One has been added. Thanks!
