### ISSUE TITLE
Shellcheck documentation/wiki license clarifcation

### ISSUE THREAD

**Issue by redNixon** [koalaman/shellcheck#1343]
I have extended the CodeChecker project(https://github.com/Ericsson/codechecker) to support Shellcheck, however I think I may have implemented support for of the more useful interface features of CodeChecker, the "Show Documentation" button which shows the explantation of the currently selected issue, in a questionable way.  

CodeChecker is licensed under a persmissive license, Shellcheck is GPLv3, on the surface this seems fine since CodeChecker is only injesting the output of Shellcheck for display purposes and is not calling shellcheck(I do have to covert the gcc formatted results to the codechecker supported plist format though).  The documentation for CodeChecker however has to be built during installation and is a part of the same CodeChecker repo as the source code.  By pure happenstance I was able to just clone the shellcheck wiki repo and CodeChecker is able to use the .md files without modification.  Due to this, I am thinking that whatever license the wiki text is licensed under has to be compatible with the CodeChecker permissive license.

I cannot find a license file in the wiki repo though; a reasonable assumption would be that the license of the main project also applies to the wiki since it does not have a license(which would mean I need to abandon this work since GPLv3->Permissive is not allowed).   But before I abandon the work done so far and start trying to make a GPLv3 compatible integration, I figured it was worth making sure that wiki is indeed under the GPLv3.  If wanted, I can stand up a publicly accessible copy of CodeChecker with ShellCheck flagged issues demostration purposes of how the wiki text is being used(it really is a slick interface for shellcheck fwiw, not sure how I missed this licensing issue until the end).

Licensing aside, if this type of integration where ShellCheck wiki data is being imported directly into another project is just unwanted I will also accept a "Please don't do that" response.

**Comment by koalaman** [comment]
The wiki is a part of the project and therefore under the same license. It's essentially an extension of the man page.

I don't know how the GPLv3 works when applied to non-source code, but there it is.
