### ISSUE TITLE
openBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by Grimblee** [koalaman/shellcheck#1356]
Hello,

I have found other github issue with this error but none of those helped me solve my issue.

I tried installing with apt and with snap, both failed to function.

Thing is, it always returns "openBinaryFile: does not exist (No such file or directory)", no matter the script or options it is given:

> thomas @ ntmy in ~/Encrypted/Work/Git/Kanselarij/itrp_scripts on git:master x [14:05:34] 
> $ shellcheck -s bash itrp-ticket-creation.sh 
> itrp-ticket-creation.sh: itrp-ticket-creation.sh: openBinaryFile: does not exist (No such file or directory)
> 
> thomas @ ntmy in ~/Encrypted/Work/Git/Kanselarij/itrp_scripts on git:master x [14:08:02] C:2
> $ sudo /snap/bin/shellcheck -s bash itrp-ticket-creation.sh
> itrp-ticket-creation.sh: itrp-ticket-creation.sh: openBinaryFile: does not exist (No such file or directory)
> 
> thomas @ ntmy in ~/Encrypted/Work/Git/Kanselarij/itrp_scripts on git:master x [14:08:16] C:2
> $ sudo /snap/bin/shellcheck itrp-ticket-creation.sh 
> itrp-ticket-creation.sh: itrp-ticket-creation.sh: openBinaryFile: does not exist (No such file or directory)
> 
> thomas @ ntmy in ~/Encrypted/Work/Git/Kanselarij/itrp_scripts on git:master x [14:08:26] C:2
> $ sudo /snap/bin/shellcheck ../f5_updater/f5_virtualservers_updater.sh 
> ../f5_updater/f5_virtualservers_updater.sh: ../f5_updater/f5_virtualservers_updater.sh: openBinaryFile: does not exist (No such file or directory)

Only working option is --version: 
> $  shellcheck --version                      
> ShellCheck - shell script analysis tool
> version: 0.5.0
> license: GNU General Public License, version 3
> website: https://www.shellcheck.net

Do you have any ideas ?

Thank you,

**Comment by koalaman** [comment]
Very strange. Does `cat itrp-ticket-creation.sh` work fine? 

The snap version does some sandboxing that I don't fully understand, so it would be nice if you could make sure you're using the `apt` version when testing.

**Comment by henri9813** [comment]
Hello,

I have exactly the same problem ( while solving SC1090 ). 

Included file: `./utils/misc.sh`
Current script: `./php/script.sh`

According to the documentation ( https://github.com/koalaman/shellcheck/wiki/SC1090)  i did:
```
shellcheck source=utils/misc.sh php/script.sh
``` 

So, i got this error: 
```
source=/dev/null: source=utils/misc.sh openBinaryFile: does not exist (No such file or directory)
```

I also tried with `/dev/null` but i got the same result.

```
shellcheck source=/dev/null script.sh
```

Regards,

**Comment by scaldwell-atlassian** [comment]
I am having the same issue.  I followed https://github.com/koalaman/shellcheck/wiki/SC1090 to resolve an issue and everything I have tried has failed.

I have confirmed the files exist, permissions work.  The scripts run without error.  But I cannot resolve the SC1090 issues.

**Comment by koalaman** [comment]
When the docs say:

```
# shellcheck source=src/lib.sh
. "$(find_install_dir)/lib.sh"
```

That's a script with a comment directive and not a command prompt with a result. Running the command `shellcheck source=src/lib.sh` is intended to fail with "No such file or directory".

Add the line `# shellcheck source=src/lib.sh` to the script instead.

**Comment by henri9813** [comment]
Thank @koalaman 

It's okay for me.

**Comment by DamianRivas** [comment]
I also have this issue on Ubuntu 18.04 LTS. Any updates @koalaman ?

I just installed shellcheck through `snap` because the version in `apt` is stuck at `v0.4.6` and the VS Code extension kept complaining that I should be using at least v0.4.7. The `snap` version is `v0.6.0`. When I run `shellcheck --version` it outputs just fine, but when I actually try to use it, I get the errors below.

I am on Ubuntu 18.04 LTS. I'll switch back to the one on `apt` for now, but I would like to use the latest version.

```sh

➜  .repl git:(master) ✗ shellcheck -x test/modules_test.sh
test/modules_test.sh: test/modules_test.sh: openBinaryFile: permission denied (Permission denied)
➜  .repl git:(master) ✗ shellcheck -x repl
repl: repl: openBinaryFile: permission denied (Permission denied)
➜  .repl git:(master) ✗ shellcheck install.sh
install.sh: install.sh: openBinaryFile: permission denied (Permission denied)

```

**Comment by DamianRivas** [comment]
Yep, they are within `$HOME`

**Comment by koalaman** [comment]
@DamianRivas I unsuccessfully tried to reproduce this. I:

1. Booted and installed `ubuntu-18.04.1.0-live-server-amd64.iso` in a VM with default options
1. Logged in and ran `sudo snap install shellcheck`
1. Ran `echo $1 > myscript` to create a test file in my home dir
1. Ran `shellcheck myscript`

I got shellcheck output as expected.

Do you have any ideas about what else I can do to reproduce?

**Comment by DamianRivas** [comment]
Thanks @koalaman 
Hmm, try creating a hidden folder in your home dir and move the script in there and run shellcheck from inside that directory. That's probably the closest you can get to repeating my exact scenario.

Otherwise, looks like I'll have to try again.

**Comment by koalaman** [comment]
That was indeed it. I can reproduce it in a hidden directory. According to the [snap docs](https://docs.snapcraft.io/the-home-interface/7838?_ga=2.24410105.2111026388.1547436586-19277213.1487906982), this is intentional behavior from their side:
>home allows access to non-hidden files in the user’s home ($HOME) directory.

There's not much I can do to change the sandboxing, but the workarounds I've found are:
* `sudo snap install --classic shellcheck` to install without a sandbox
* `mount --bind` in such a way that the file is available without going through a hidden dir.
* Not using `snap`, such as by compiling or downloading a binary

Please reopen or file another issue if this does not work or is not sufficient

**Comment by abitrolly** [comment]
I got this error when [executing `shellcheck` with `globstar`](https://travis-ci.org/yakshaveinc/linux/jobs/573358708#L213). The [solution](https://github.com/yakshaveinc/linux/commit/307286785420df64d89f708c7a1c7b2ddf53eb65) was to add `nullglob`.

    $ bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}'

**Comment by cardil** [comment]
Installing `--classic` version of snap do not work:

```
$ sudo snap install --classic shellcheck
Warning: flag --classic ignored for strictly confined snap shellcheck

shellcheck v0.7.0 from Vidar (koalaman) installed

$ shellcheck -x test/e2e-tests.sh
test/e2e-tests.sh: test/e2e-tests.sh: openBinaryFile: permission denied (Permission denied)
```

I'm sure it's because of that I have code in hidden directory: 

```
$ pwd
/home/ksuszynski/.gvm/pkgsets/go1.13/global/src/github.com/openshift-knative/knative-eventing-operator
```

Using statically build binary work without any hiccups:

```
$ export scversion="stable"
$ wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
shellcheck-stable/README.txt
shellcheck-stable/LICENSE.txt
shellcheck-stable/shellcheck
$ sudo install shellcheck-stable/shellcheck /usr/local/bin
$ shellcheck -x test/e2e-tests.sh
```

**Comment by 1605200517** [comment]
thank you for this tool, @koalaman ! This error appears if used with latest Docker image. On same test subject, an older version works fine.

Test subject: one file functions.sh in local directory with a bash fuinction.
```
> shellcheck -V | grep "version:"
> version: 0.4.6

> shellcheck *
> echo $?
> 0

> docker run -it -v $(pwd):/work koalaman/shellcheck:latest *
> functions.sh: functions.sh: openBinaryFile: does not exist (No such file or directory)
```
