### ISSUE TITLE
SC2059's documentation does not recommend/use the %b parameter

### ISSUE THREAD

**Issue by oliv3r** [koalaman/shellcheck#1363]
#### For bugs
- Rule Id: SC2059
- My shellcheck version: "online"
- [x] I read the issue's wiki page, e.g. https://github.com/koalaman/shellcheck/wiki/SC2059
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/sh

var="$(head -c 4 "/dev/urandom")"

printf "${var}"
```

#### Here's what shellcheck currently says:
Exceptions

Sometimes you may actually want to interpret data as a format string, like in:

hexToAscii() { printf "\x$1"; }
hexToAscii 21

or when you have a pattern in a variable:

filepattern="file-%d.jpg"
printf -v filename "$filepattern" "$number"

These are valid use cases with no useful rewrites. Please ignore the warnings with a directive.
#### Here's what I wanted or expected to see:
Of course, I could fully missunderstand (or it not being fully posix compliant) but isn't one way to handle the exception to printf with %b?

e.g. `printf "%b" "\x$1"`

It seems to work in busybox's ash, (but not dash, though dash doesn't even accept "\x$1".

While the directive is one way to solve this, I suppose it should at least mentioned on the wiki that "%b" is acceptable (not acceptable) in certain cases and may be preferred over a directive?

Note, that shellcheck is completly happy with printf "%b" "\x$1" so if it is not acceptable or should be avoided, then there's a missing check.

**Comment by koalaman** [comment]
Very good point! I've updated the wiki.
