### ISSUE TITLE
SC2045 ls -A

### ISSUE THREAD

**Issue by gMan1990** [koalaman/shellcheck#1375]
### Problematic code:

    for f in $(ls *.wav)
    do
      echo "$f"
    done

### Correct code:

    for f in *.wav
    do
      [[ -e $f ]] || break  # handle the case of no *.wav files
      echo "$f"
    done

### how about "ls -A", also can use "for f in *.wav"?

    for f in $(ls -A *.wav)
    do
      echo "$f"
    done

**Comment by Nightfirecat** [comment]
How does that fix the problems mentioned in [the rationale for this warning](https://github.com/koalaman/shellcheck/wiki/SC2045#rationale)?

**Comment by koalaman** [comment]
To loop over all files including hidden files, use `for f in .[^.]* *; do ..` or (in bash) `shopt -s dotglob; for f in *; do ..`

For loops over `ls -A` output is problematic, just like `ls` output.

**Comment by gMan1990** [comment]
how about `ls|sort -V`?

**Comment by coiby** [comment]
> To loop over all files including hidden files, use `for f in .[^.]* *; do ..`

@koalaman It's not equivalent to `ls -A` considering a file could be named `..name`. Why not simply `for f in .* *; do ..`?

**Comment by ddavout** [comment]
What if I got a file name called 'Copy of lts.à.tree" ?
