### ISSUE TITLE
Excuse me，could anybody helps to eliminate the warnings？

### ISSUE THREAD

**Issue by YangQing1989** [koalaman/shellcheck#1377]
#!/bin/bash
date_now=$(date +%H:%M:%S)
date_ago=$(date -d"5 minute ago" +%H:%M:%S)
RS_NEW=$(date +%d)/$(date +%b)/$(date +%Y:)
success=$(awk 'BEGIN{RS="'$RS_NEW'"} $1>"'$date_ago'" && $1<"'$date_now'" {print $0}' /XXX/log | grep -w "$1" | grep -cw 200)
total=$(awk 'BEGIN{RS="'$RS_NEW'"} $1>"'$date_ago'" && $1<"'$date_now'" {print $0}' /XXX/log | grep -cw "$1")
if [ "$total" -gt 0 ];then
    echo "scale=2; ($success / $total) * 100" | bc
else
    echo "100"
fi
```

the shellcheck prompts the following warnings：
[root@ECS ~]# shellcheck yq.sh 

In yq.sh line 8:
success=$(awk 'BEGIN{RS="'$RS_NEW'"} $1>"'$date_ago'" && $1<"'$date_now'" {print $0}' /XXX/log | grep -w "$1" | grep -cw 200)
                          ^-- SC2086: Double quote to prevent globbing and word splitting.
                                          ^-- SC2086: Double quote to prevent globbing and word splitting.
                                                              ^-- SC2086: Double quote to prevent globbing and word splitting.


In yq.sh line 9:
total=$(awk 'BEGIN{RS="'$RS_NEW'"} $1>"'$date_ago'" && $1<"'$date_now'" {print $0}' /XXX/log | grep -cw "$1")
                        ^-- SC2086: Double quote to prevent globbing and word splitting.
                                        ^-- SC2086: Double quote to prevent globbing and word splitting.
                                                            ^-- SC2086: Double quote to prevent globbing and word splitting.

```

**Comment by Nightfirecat** [comment]
This is not the right place to go for script  help, but you should fix lines 8 and 9 to read like this:

```
success=$(awk 'BEGIN{RS="'"$RS_NEW"'"} $1>"'"$date_ago"'" && $1<"'"$date_now"'" {print $0}' /XXX/log | grep -w "$1" | grep -cw 200)
total=$(awk 'BEGIN{RS="'"$RS_NEW"'"} $1>"'"$date_ago"'" && $1<"'"$date_now"'" {print $0}' /XXX/log | grep -cw "$1")
```

That is, adding double quotes `"` around all of the BASH variables in those commands.

**Comment by koalaman** [comment]
For `awk` specifically, you can also use `awk -v` to set an awk variable:

    awk -v myAwkVariable="$myBashVariable" '$1 > myAwkVariable { print; }'
