### ISSUE TITLE
Can't Install on Windows 7

### ISSUE THREAD

**Issue by xpressos** [koalaman/shellcheck#1378]
I'm trying to setup shellcheck on Sublime on a Windows 7-64 machine. When I install the extension via package control the last line says "The is no windows installer".

I used the "shellcheck-stable.exe" - when I run this it doesn't seem to install correctly (attached). 

Noticed on the bottom left corner of sublime "shellcheck (erred).

How can I fix this?
![sublime](https://user-images.githubusercontent.com/22617577/47751285-3ef9f900-dc89-11e8-9c40-0622a3b5f8b8.jpg)
![shellcheck](https://user-images.githubusercontent.com/22617577/47751287-3f928f80-dc89-11e8-90a5-7ca1ed1e3af4.jpg)

**Comment by koalaman** [comment]
It probably just needed shellcheck in the `%PATH%`, and probably without the `-stable` suffix. Glad it worked out!
