### ISSUE TITLE
SC2004 false error with array

### ISSUE THREAD

**Issue by WinEunuuchs2Unix** [koalaman/shellcheck#1381]
#### Here's a snippet or screenshot that shows the problem:

`$ shellcheck /mnt/e/bin/multi-timer

In /mnt/e/bin/multi-timer line 212:
            iSetSaveSec=$(( iSetSaveSec + ${aDuration[i]} ))
                                          ^-- SC2004: $/${} is unnecessary on arithmetic variables.`

If `$` for array is removed then this group of errors:

'$ shellcheck /mnt/e/bin/multi-timer

In /mnt/e/bin/multi-timer line 212:
            iSetSaveSec=$(( iSetSaveSec + {aDuration[i]} ))
                        ^-- SC1073: Couldn't parse this $((..)) expression.
                        ^-- SC1009: The mentioned parser error was in this $((..)) expression.
                                                        ^-- SC1072: Not a brace expression. Fix any mentioned problems and try again.`

Just a minor issue. Overall thanks for creating a wonderful tool.

**Comment by koalaman** [comment]
The intention was for you to remove the $ or ${} i.e. use just `aDuration[i]`. I see how this was not necessarily obvious, and I've updated the wiki with an example. Thanks!
