### ISSUE TITLE
Suggestion: --quiet flag

### ISSUE THREAD

**Issue by l0b0** [koalaman/shellcheck#1393]
#### For new checks and feature suggestions
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### The problem:

When trying to quickly determine whether there is any problem with any of a possibly large amount of files it would be very useful if `shellcheck` could

1. print nothing (or at least not to standard output) and
1. `exit 1` as soon as any issue is detected.

This would be equivalent to grep's `--quiet`, which also prints nothing and exits as soon as a match is found.

**Comment by koalaman** [comment]
Thanks to @Gandalf-  for adding `-f quiet` for this!
