### ISSUE TITLE
SC2063 should not apply to grep --include '*.sh'?

### ISSUE THREAD

**Issue by hrvoj3e** [koalaman/shellcheck#1404]
```
grep -r --include '*.sh' -L "something" .
                   ^ This is OK - GLOB is allowed
```

> http://linuxcommand.org/lc3_man_pages/grep1.html
> ```
> --include=GLOB
>      Search  only  files whose base name matches GLOB (using wildcard
>      matching as described under --exclude).
> ```

**Comment by koalaman** [comment]
You're right, of course. This issue was kindly fixed by @Gandalf-  in 4a2b2c7, thanks!
