### ISSUE TITLE
shellcheck is unresponsive on ">/dev/null"

### ISSUE THREAD

**Issue by szepeviktor** [koalaman/shellcheck#1413]
```bash
#!/bin/bash

Info()
{
    # Informational messages displayed only during `set -x`
    # shellcheck disable=SC2188
    >/dev/null
}

set -e -x

Info "List what boot packages are installed"
```

(strace shows SIGVTALRM)

**Comment by koalaman** [comment]
Wow, this was indeed an infinite loop. ShellCheck tried to look up the tree to see whether the command-less redirection's parent was a `$()`, such as `$(< file)` . When it found an annotation, it was supposed to look one more step up the tree, but instead it went one step down. That took it to the command-less redirection again, and the cycle started over.

Excellent catch, thanks!
