### ISSUE TITLE
Autofix support does not account for tabs

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#1420]
#### For bugs
- Rule Id (if any, e.g. SC1000): n/a
- My shellcheck version (`shellcheck --version` or "online"): ecd61bfc6
- [ ] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
shellcheck - <<< $'\techo $1 hello world'
```

#### Here's what shellcheck currently says:

```
In - line 1:
        echo $1 hello world
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
             ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
        echo $1 hell"o "world
```

#### Here's what I wanted or expected to see:

```
Did you mean:
        echo "$1" hello world
```

**Comment by ngzhian** [comment]
Seems related to the parser?
```
*ShellCheck.Parser> debugParseScript "\te"
ParseResult {prComments = [], prTokenPositions = fromList [(Id 0,(Position {posFile = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 1, posColumn = 9})),(Id 1,(Position {posFi
le = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 1, posColumn = 9})),(Id 2,(Position {posFile = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 
1, posColumn = 10})),(Id 3,(Position {posFile = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 1, posColumn = 10})),(Id 4,(Position {posFile = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 1, posColumn = 10})),(Id 5,(Position {posFile = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 1, posColumn = 10})),(Id 6,(Position
 {posFile = "debug", posLine = 1, posColumn = 9},Position {posFile = "debug", posLine = 1, posColumn = 10})),(Id 7,(Position {posFile = "debug", posLine = 1, posColumn = 1},Position {posFile = "debug", posLine = 1, posColumn = 10}))], prRoot = Just (T_Annotation (Id 0) [] (T_Script (Id 7) "" [T_Pipeline (Id 6) [] [T_Redirecting (Id 4) [] (T_SimpleCommand (Id 5) [] [T_NormalWord (Id 3) [T_Literal (Id 2) "e
"]])]]))}
```
all the posColumns start from 9. I'll look a bit more.

**Comment by ngzhian** [comment]
Hm. See https://hackage.haskell.org/package/parsec3-1.0.1.8/docs/Text-Parsec-Pos.html#v:updatePosChar

> If the character is a newline ('\n') or carriage return ('\r') the line number is incremented by 1. If the character is a tab ('t') the column number is incremented to the nearest 8'th column, ie. column + 8 - ((column-1) `mod` 8). In all other cases, the column is incremented by 1.

This ends up into the token position map, which the fixe uses.
