### ISSUE TITLE
Autofix turns `cd $1` into `cd "$1 || exit"`

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#1431]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2164, SC2086
- My shellcheck version (`shellcheck --version` or "online"): ef811995
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/sh
cd $1
```

#### Here's what shellcheck currently says:

```
In - line 2:
cd $1
^---^ SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
   ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
cd "$1 || exit"
```

#### Here's what I wanted or expected to see:

```
In - line 2:
cd $1
^---^ SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
   ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
cd "$1" || exit

```

**Comment by ngzhian** [comment]
I think the issue is that there is an overlap in the 2 fixes, they both want to add something to the end of the string, and there's a conflict, so only 1 should be applied. There is an off-by-one error in the overlap check. I'll fix that in a PR.

**Comment by ngzhian** [comment]
the previous condition was `(yStart >= xStart && yStart < xEnd)`
so it wouldn't catch cases where you have x start = 3, x end = 3, y start = 3 y end = 3. Which should be an overlay and thus a conflict.

**Comment by koalaman** [comment]
This solution is simple, but doesn't support applying both fixes at once. The optimal solution would be to do AST modifications and re-serializing them, but that would be a lot of work to implement.

Maybe a middle ground would be to prioritize fixes based on the AST depth of the node being modified? Anything added to a deeply nested node should be contained within anything added to a more shallow node. 

For example, if you had a ``x=`${cmd[@]}` `` with a simplified AST:

   assignment:
       backtick (level 2)
         simplecommand
             ${cmd[@]} (level 4)

and you wanted to turn it into `x=$("${cmd[@]}")`, then any `replaceStart` for the level 2 item would be applied before/left-of any overlapping replaceStart for a level 4 item, and vice versa for replaceEnd.

**Comment by ngzhian** [comment]
Very very cool, thanks for writing this up!
