### ISSUE TITLE
Is there an existing cross-platform install script?

### ISSUE THREAD

**Issue by AshleyColemanBigHealth** [koalaman/shellcheck#1450]
I'd like a script to install on OSX & ubuntu. Just wondering if there is something that already exists. Thanks.

**Comment by koalaman** [comment]
No, there is currently no cross-platform install script. 

In general, you can easily install ShellCheck through the OS or distro's package mangers, such as `brew install shellcheck` on macOS and `apt install shellcheck` (or `snap install shellcheck`) on Ubuntu.
