### ISSUE TITLE
How to complete it on Android?

### ISSUE THREAD

**Issue by myfreess** [koalaman/shellcheck#1467]

**Comment by koalaman** [comment]
Sorry, what? Compile? Android is not officially supported. It's probably better to use the online version on shellcheck.net.

I see that the armv6hf binary for ARM RPi crashes with "Bad system call" on my Android device under Termux, that Termux does not have a GHC binary available, so I don't currently have any good suggestions for running natively.

**Comment by myfreess** [comment]
Thanks @koalaman

**Comment by oxr463** [comment]
> I see that the armv6hf binary for ARM RPi crashes with "Bad system call" on my Android device under Termux

This is happening for me with the aarch64 binary.
