### ISSUE TITLE
Alternative commands for suggestions to fix SC2207

### ISSUE THREAD

**Issue by yous** [koalaman/shellcheck#1496]
#### For new checks and feature suggestions
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's what shellcheck currently says:

If it outputs multiple lines, each of which should be an element:
``` sh
# For bash 4.x
mapfile -t array < <(mycommand)

# For bash 3.x+
while IFS=$'\n' read -r line; do array+=("$line"); done < <(mycommand)

# For ksh
mycommand | while IFS="" read -r line; do array+=("$line"); done
```

#### Here's what I wanted or expected to see:

If it outputs multiple lines, each of which should be an element:
``` sh
# For bash 4.x
mapfile -t array < <(mycommand)

# For bash 3.x+
IFS=$'\n' read -d '' -r -a array < <(mycommand)
# or
while IFS=$'\n' read -r line; do array+=("$line"); done < <(mycommand)

# For ksh
mycommand | while IFS="" read -r line; do array+=("$line"); done
```

#### Description

The above excerpts are from wiki.

I found `read` has `-d` option:
> **-d delim**
>        The first character of **delim** is used to terminate the input line, rather than newline.

This can be used for constructing an array from lines. I think the command using `read -d '' -r -a` is quite simpler than using `while`, how do you think?

**Comment by koalaman** [comment]
It's very nifty, though it does have some caveats: it skips blank lines, and it always returns failure.  (It also stops on the first `\0` whereas the loop skips it, but that's less of an issue.)

This is not necessarily a bad thing, especially since `var=( $(foo) )` also strips empty lines, but to avoid surprises regarding that and also when running with `set -e`, the loop is probably a better drop-in replacement. 

Thanks for the suggestion!

**Comment by yous** [comment]
Thank you for the great explanation! I didn't know that it always returns failure.

But I have one more question: in the command for bash 3.x, `array` is appended anyway. So if `array` had some value, the result can be vary.

What's a clean way to ensure that `array` is initialized with an empty array? Is it enough to set `array=()` before the `while`?

**Comment by koalaman** [comment]
Yes indeed. The wiki failed to mention this, thanks!
