### ISSUE TITLE
SC2095 alternative fixing suggestion discussion

### ISSUE THREAD

**Issue by stdedos** [koalaman/shellcheck#1504]
Troubleshooting a SC2095 problem, I realized that:

```sh
while read -r host < hosts.txt
do
  ssh "$host" "uptime" < /dev/null
done
```

Would be a solution (apart from https://github.com/koalaman/shellcheck/wiki/SC2095 suggestions)

I was thinking of adding that to the wiki page, but, I stopped:
Is there something wrong with this command?

**Comment by koalaman** [comment]
Since the file is opened for each `read` rather than once for the loop, it'll just keep reading the first line over and over :P

**Comment by stdedos** [comment]
_Hides in embarrasment_ 😶
