### ISSUE TITLE
Shebang not recognized if too many chars

### ISSUE THREAD

**Issue by LuxAetern** [koalaman/shellcheck#1520]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2148
- My shellcheck version (`shellcheck --version` or 'online'): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:
i could not fit int into the Issue --> [Gist ](https://gist.github.com/LuxAetern/17eb741376fae1784a0969683f7f7303)
```sh
#!/bin/bash
very long string
```

#### Here's what shellcheck currently says:
```
Line 1	SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
```

stops at the check for bash, regardless of what content is afterwards.  
If you want to test it, simply copy the Gist into shellcheck and remove any of the numbers --> shellcheck works
Add it again and you get the error about the shebang

**Comment by koalaman** [comment]
I'm getting no errors on shellcheck.net or locally with the gist provided. If I hold Ctrl-V for a while, I eventually get "Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally."

Could you try it again? At one point in the last few days, ShellCheck's server ran out of disk space which may have caused some temporary glitches.

**Comment by LuxAetern** [comment]
It works now, no idea what changed
Thanks anyway
