### ISSUE TITLE
Can ShellCheck check if a script is POSIX-compliant?

### ISSUE THREAD

**Issue by alexherbo2** [koalaman/shellcheck#1527]
**Example 1** – Using `paste` with no file-name, required for [macOS](https://ss64.com/osx/paste.html)

``` sh
printf '%s\n' foo bar baz | paste -s -d ','
```

**Example 2** – Using `realpath` which is GNU-only

``` sh
realpath file.txt
```

**Comment by mhoes** [comment]
Shellcheck will not let you check your script for POSIX compliance directly, as far as I know at least. However, shellcheck does let you explicitly check for compliance with the 'dash' shell, which aims to be POSIX compliant, which may be 'good enough' for your purpose.

`shellcheck --shell=dash ./myscript.sh`

However, this may not get what you are looking for: 'realpath' is a GNU (coreutils) external command, and not any shell built-in, so it will work with any shell (as long as the external command is available).

**Comment by xPMo** [comment]
`paste` is also an external command.  Shellcheck doesn't check for the presence/absence of _any_ external commands or flags. This will pass just fine:

```
aaaaaa foo bar | paste --nonexistant-flag
```

However, Shellcheck will warn you on _builtins_ which exist in other shells (e.g.: `typeset`) with [SC2039](/koalaman/shellcheck/wiki/SC2039).

**Comment by nitrocode** [comment]
It would be nice if it would also complain when non posix commands are used like `realpath`. Currently this doesn't happen even with `--shell=dash`

**Comment by brother** [comment]
@nitrocode years later. maybe open a separate issue.

**Comment by SuperSandro2000** [comment]
> It would be nice if it would also complain when non posix commands are used like `realpath`. Currently this doesn't happen even with `--shell=dash`

realpath is part of coreutils which is installed everywhere.

**Comment by nitrocode** [comment]
@brother I found this issue from google so I thought I'd add the comment here. Perhaps a new issue is good in addition to my comment.

@supersandro2000 A good example is OSX which does not have coreutils preinstalled.

**Comment by SuperSandro2000** [comment]
> A good example is OSX which does not have coreutils preinstalled.

Darwin also has an ancient versions of git, bash and any other GNU related tools. Don't you have brew installed to get coreutils?

**Comment by nitrocode** [comment]
@SuperSandro2000 yes I do, but brew is not preinstalled and coreutils is not preinstalled on all places I want my script to execute thus my abive request 😄

**Comment by SuperSandro2000** [comment]
> coreutils is not preinstalled on all places I want my script to execute

I can't think of any other place than Darwin and some embedded platforms which usually have their own quirks with busybox/toxboy/etc.
