### ISSUE TITLE
How to enable auto fixes for JSON/console output?

### ISSUE THREAD

**Issue by ignatov** [koalaman/shellcheck#1545]
Hi, thanks a lot for the shellcheck. Is there any way how to enable fixes for JSON output? I didn't find any option for that.

**Comment by koalaman** [comment]
If you run the latest git commit, the JSON output will contain fixes. They're not available in any stable release yet though.

Even if you do have them, the JSON fixes are in the form of raw indexed string replacement instructions that are not trivial to apply. The plan is to add a simple `diff` compatible output before the next release.

**Comment by ignatov** [comment]
Sounds great, merci beaucoup.

**Comment by koalaman** [comment]
Diff output has been added in b1aeee56
