### ISSUE TITLE
Minor comment about recent changes

### ISSUE THREAD

**Issue by Tamaranch** [koalaman/shellcheck#1546]
I think that introducing the [verbose mode](https://github.com/koalaman/shellcheck/commit/9652ccfdbdbfee1290ace8137edc08f94bd25f77) is a good idea. Personally, this allows me to remove `export SHELLCHECK_OPTS="-e SC2244"` from my `.bashrc`. But what do you think about using different colors for "info" and "verbose" type messages?
Moreover, but it's even less important, I think that the verbose mode could have been called "suggestion", "proposal", or something like that.

**Comment by virgilwashere** [comment]
> Moreover, but it's even less important, I think that the verbose mode could have been called "suggestion", "proposal", or something like that.

+1 for suggestion

**Comment by koalaman** [comment]
I think it's a good idea. I tried dark grey but it just disappeared on my terminal, so I set it to the same as `style` and forgot about it. Maybe blue? It tends to be dark and slightly annoying to read though. 

As for the name, I consider quite a lot of shellcheck's warning and style messages suggestions, so I'm not sure how descriptive that is. Maybe "pedantic" (like `gcc -pedantic`)?

**Comment by Tamaranch** [comment]
Blue is almost unreadable on my terminal (black background). Light blue is readable for me, or cyan?
Regarding the name, I'm not sure because my English is too rudimentary, but "verbose" sounds for me as "extended logs", while I see for example SC2244 as a suggestion…

**Comment by pawamoy** [comment]
You shouldn't pick a color because it's readable, or avoid one because it's not. It's everyone's responsibility to set their terminal colors so they are readable.

Other than that, I myself previously used the *faint* (or *dim*) style for something similar (since you said you tried dark gray), and was satisfied.

**Comment by lollipopman** [comment]
@koalaman what about `readability`, clang-tidy uses that as a class, https://clang.llvm.org/extra/clang-tidy/

**Comment by koalaman** [comment]
This issue resolved itself with 5fb1da6, which replaced verbose checks with optional checks.

Instead of getting an indiscriminate pile of suggestions with a new priority, you can instead enable sets of them by name using `-o` or `enable` directives. They reuse existing priority levels.

**Comment by virgilwashere** [comment]
Love your work @koalaman .

You've been very responsive and helpful towards all my recent interactions.

Totally unrelated side note:
>Have you ever seen a [wet koala](https://www.google.com/search?q=wet+koala)?

This is why Aussies talk about dropbears :-)

Virgil
