### ISSUE TITLE
Add –shell=all to warn about all portability problems

### ISSUE THREAD

**Issue by jidanni** [koalaman/shellcheck#1551]
On the man page at
>      -s shell, –shell=shell
>             Specify  Bourne  shell  dialect.  Valid values are sh, bash, dash and ksh.  The default is to use the file's
>             shebang, or bash if the target shell can't be determined.

add --shell=all, to warn in a maximum fashion about all portability problems. Or
mention if --shell=sh already does this.

**Comment by koalaman** [comment]
In 6ccf9d6 this has been updated to say that `sh` refers to POSIX and will warn of portability issues, and not e.g. the system's `sh`. Thanks!
