### ISSUE TITLE
cannot create docker container by both stable and latest version

### ISSUE THREAD

**Issue by mystic-cg** [koalaman/shellcheck#1555]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [ ] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [ ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh

λ docker image pull koalaman/shellcheck:stable
stable: Pulling from koalaman/shellcheck
71311d65e0de: Pull complete
8c52940cc7f8: Pull complete
Digest: sha256:bd13d6dd61da58f26fc665fa3a08ff5c7e4e13749f555876f32750668d341475
Status: Downloaded newer image for koalaman/shellcheck:stable

```
```sh
λ docker container run -d --privileged --name shell-check koalaman/shellcheck:stable myscript
2abb3d7fc8fa498f59d96d87713244eae6f9e5036040f7a8f3c82524084361d3
```

```sh
λ docker container ls -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                      PORTS               NAMES
2abb3d7fc8fa        koalaman/shellcheck:stable   "/bin/shellcheck mys…"   33 seconds ago      Exited (2) 32 seconds ago                       shell-check
```

**Comment by koalaman** [comment]
The docker image `koalaman/shellcheck` is intended to be run on a set of files similar to `shellcheck` itself:

    docker run -v "$PWD:/mnt" koalaman/shellcheck:stable myscript

It's not intended to run as a daemon or service. There is currently no docker image serving up shellcheck.net.
