### ISSUE TITLE
addition to SC2006

### ISSUE THREAD

**Issue by pan64** [koalaman/shellcheck#1557]
for SC2006 the documentation is just wrong:

#### Here's a snippet or screenshot that shows the problem:

Problematic code
echo "Current time: `date`"
Correct code
echo "Current time: $(date)"

The correct explanation should use another example (so in general there is no problem with SC2006)
The correct code in this case would be something like this:
date "+Current time: <date format>"
there is no echo at all. It is a very special (but often used) case - when only echo and date combined. Probably we need another SCXXXX for this.

**Comment by austin987** [comment]
The problem is the backticks, not how date was invoked. `date` and $(date) will still show the date/time info, just maybe not in your preferred format.
```
austin@laptop:~$ echo "Current time: `date`"
Current time: Thu Apr 25 10:42:23 CDT 2019
austin@laptop:~$ echo "Current time: $(date)"
Current time: Thu Apr 25 10:42:28 CDT 2019
```

Your suggested code is even more broken:
```
austin@laptop:~$ date "+Current time: "
Current time: 
```

**Comment by pan64** [comment]
I'm afraid, you misunderstood. There is no problem with SC2006, but the example posted (as explanation) is wrong.
Using `echo "string $(date)"` is a case similar to "useless use of cat".
Would be better to use `date "+string <date format>"` or  something similar. Looks like the engine reformatted what I posted....

**Comment by koalaman** [comment]
This particular example might indeed have been better off as `date "+Current time: %c"` in POSIX or `printf 'Current time: %(%c)T\n' -1` in bash. To avoid derailing the example with unnecessary date details, I've updated the wiki page to use `uname`.
