### ISSUE TITLE
Feature Request: disable by red (error), yellow (warning), and green (info)

### ISSUE THREAD

**Issue by EricLuehrsen** [koalaman/shellcheck#1563]
It appears shellcheck has priority or classes of checks although they are not numbered in such order. However it is not possible to disable by classification. It would be a good option and common with other lint checkers to to be able to disable all green. This would probably also need a `+e` option to add few back (for example note "not following").

`$ shellcheck -egreen +eSC1091 myscript.sh`

**Comment by koalaman** [comment]
You can already specify `--severity=warning` to only show warnings and higher.

You can't add certain warnings back in, but if you want especially fine grained filtering logic, you can e.g. use `jq` on the JSON output.
