### ISSUE TITLE
Unable to disable  SC1073,SC1072,SC1009

### ISSUE THREAD

**Issue by bioinfornatics** [koalaman/shellcheck#1568]
Dear,

I have a script with a dynamic operator and in such case shellcheck is not able to parse it.
Moreover, I do not find a way to tell to shellcheck to skip this statement and continue.

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/usr/bin/env bash
foo(){
        local -i val1="${1}"
        local -r sign="${2}"
        local -i val2="${3}"
        # shellcheck disable=SC1009,SC1072,SC1073
        if (( val1 "${sign}" val2 )); then
                echo 'The expression: "'"${val1}"' '"${sign}"' '"${val2}"'" is correct' 
        else
                echo 'The expression: "'"${val1}"' '"${sign}"' '"${val2}"'" is not correct'
        fi
}

foo 1 '>' 2
```

### Here's the shellcheck output

```sh
shellcheck --shell bash --exclude=SC1009,SC1072,SC1073 test_dynamic_sign.sh

In test_dynamic_sign.sh line 7:
        if (( val1 "${sign}" val2 )); then
        ^-- SC1009: The mentioned parser error was in this if expression.
           ^-- SC1073: Couldn't parse this ((..)) command.
                   ^-- SC1072: Expected "))". Fix any mentioned problems and try again.
```

#### Here's the shellcheck version

```sh
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.3.5
license: GNU Affero General Public License, version 3
website: http://www.shellcheck.net
```

**Comment by koalaman** [comment]
This particular case is not a problem on later versions, because ShellCheck will successfully parse it as `( ( val1 "${sign}" val2 ) )` when it's unable to treat it as `(( .. ))`.

However, there's still no good solution for the more general problem of what to do when ShellCheck fails to parse valid code.

**Comment by bioinfornatics** [comment]
Thanks @koalaman , so  we can close  this issue
And thanks too for this awesome tool
