### ISSUE TITLE
Is there any way where I can get a binary for macOS?

### ISSUE THREAD

**Issue by ignatov** [koalaman/shellcheck#1574]
Hi @koalaman!

Thanks a lot for such a great tool!
I wonder if there any place where I can get a binary for macOS? I found builds for Linux and Windows, which is rather handy – https://github.com/koalaman/shellcheck#installing-the-shellcheck-binary
For macOS, I found only a https://homebrew.bintray.com/bottles/shellcheck-0.6.0_1.mojave.bottle.tar.gz

What do you think is it worth to build a binary for macOS on Travis for every single commit, as far as Travis supports macOS?

**Comment by Gandalf-** [comment]
How would it be distributed though? brew? Or another MacOS package manager perhaps?

**Comment by ignatov** [comment]
We'd like to download with IntelliJ-based products and as an external linter.

**Comment by koalaman** [comment]
I don't see any reason not to. I don't think I'll be able to get to it myself any time soon, but contributions will certainly be considered

**Comment by bt-thiago** [comment]
`shellcheck` is already available on homebrew:

```
$ brew info shellcheck
shellcheck: stable 0.6.0 (bottled), HEAD
Static analysis and lint tool, for (ba)sh scripts
https://www.shellcheck.net/
/usr/local/Cellar/shellcheck/0.6.0_1 (8 files, 7.2MB) *
  Poured from bottle on 2019-03-01 at 11:46:11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/shellcheck.rb
==> Dependencies
Build: cabal-install ✘, ghc ✘, pandoc ✘
```

**Comment by scriptingosx** [comment]
homebrew is great for individuals managing their own devices but is impossible to use if you have to centrally manage a fleet of dozens, hundreds or thousands of Macs. A pre-comiled macOS binary would already be a great help for MacAdmins. A downloadable pkg installer file which drops the spellcheck binary in `/usr/local/bin/` would be perfect.

**Comment by scriptingosx** [comment]
I have a solution to build your own binary without brew here: https://scriptingosx.com/2019/07/build-a-shellcheck-installer-for-macos/

**Comment by koalaman** [comment]
There are now macOS binaries built continuously. I have no idea how binary portability works for macOS, but they run on my macOS 10.14.6:

https://shellcheck.storage.googleapis.com/shellcheck-latest.darwin.x86_64.tar.xz

Please give them a try and let me know if there are any issues
