### ISSUE TITLE
What happened to SC1067?

### ISSUE THREAD

**Issue by luckman212** [koalaman/shellcheck#1590]
- Rule Id **SC1067**
- My shellcheck version: 0.6.0

![image](https://user-images.githubusercontent.com/1992842/58371680-5b89a700-7ee1-11e9-8bda-c628f0b69899.png)

What happened to [SC1067](https://github.com/koalaman/shellcheck/wiki/SC1067)? Seems like a somewhat related page is [SC2082](https://github.com/koalaman/shellcheck/wiki/SC2082) but my linter is still directing me to 1067. Just wondering...

**Comment by koalaman** [comment]
I've added a wiki page for it, and also improved the message a bit in  ba2c20a08a. Thanks!
