### ISSUE TITLE
Would love a new release!

### ISSUE THREAD

**Issue by jez** [koalaman/shellcheck#1598]
I had gotten all the way past cloning, building, and opening up the shellcheck source code before I realized that the feature I wanted to implement had already been implemented here:

https://github.com/koalaman/shellcheck/commit/c6c12f52bdda4ee95db0b8bf65063a1d999ab65c

which is to say, I would love a new release!

I know that I could fetch the `.tar.xz` file for latest on Linux, but

- I'd also like to be able to get my team to use it locally on their macOS laptops
- We have a habit of not depending on un-pinned versions in CI because they can magically break things

Anyways, thanks for implementing features before I knew I wanted them, and thanks for a wonderful project.

Closing this immediately because this isn't a bug or feature request, just a "process" request.

**Comment by juhp** [comment]
+1

**Comment by koalaman** [comment]
Same! There's definitely one coming soon, things have just been busy with the recent launch at my [day job](https://github.com/facebook/hermes).

Most of the P0 features are done, such as `diff` output support. I'm just hoping to get [aarch64](https://github.com/koalaman/shellcheck/issues/1569) and [macOS](https://github.com/koalaman/shellcheck/pull/1594) binaries supported first.

**Comment by koalaman** [comment]
FYI, v0.7.0 has now been released!
