### ISSUE TITLE
Add some relevant GitHub topics

### ISSUE THREAD

**Issue by dominiksalvet** [koalaman/shellcheck#1605]
Hello! It would be great if someone could add some relevant GitHub topics to this repository.

BTW **thank you** for this awesome project! :heart: I use it to develop my POSIX-friendly projects and I just can't imagine to do it without shellcheck.

**Comment by dominiksalvet** [comment]
Hey, is anyone here? :smiley: I think that adding GitHub topics can bring more people to the project and it is really easy to solve.

**Comment by koalaman** [comment]
Thanks, I did not know this was a thing! I've added some.

Happy to hear you're finding the project useful!
