### ISSUE TITLE
SC2236

### ISSUE THREAD

**Issue by wheelq** [koalaman/shellcheck#1613]
#### Here's a snippet or screenshot that shows the problem:

```sh

#!/user/bin/env bash
_myfunc(){
  set -u;
  if ! [ -z "${_MY_VAR+set}" ]; then
    [do something]
  else
    exit 1
}
```

#### Here's what shellcheck currently says:
```Use -n instead of ! -z```

#### Here's what I wanted or expected to see:
I am using set -u. Script will fail if run a check against unbound variable
I can't use `${_MY_VAR-unset}` because I need to perform an action only if variable and its value are set

**Comment by koalaman** [comment]
ShellCheck is right. You can replace `! -z` with `-n`. The `set -u` does not matter, and there is no suggestion to change anything else in the expression:

```
 if [ -n "${_MY_VAR+set}" ]; then true; fi
```
