### ISSUE TITLE
Also handle SCRIPTDIR with source directive

### ISSUE THREAD

**Issue by blueyed** [koalaman/shellcheck#1617]
The following should handle `build.sh` relative to the current script (using `shellcheck -x`):

```sh
# shellcheck source=SCRIPTDIR/build.sh
. "${CI_DIR}/common/build.sh"
```

It should behave as `shellcheck -x -P SCRIPTDIR/` with:

```sh
# shellcheck source=build.sh
. "${CI_DIR}/common/build.sh"
```

I have seen that `source-path=SCRIPTDIR` is supported (https://github.com/koalaman/shellcheck/issues/1577), but this might still make sense by itself.

(Related: https://github.com/koalaman/shellcheck/pull/1553#issuecomment-503314239)

**Comment by koalaman** [comment]
This should now work. Good suggestion, thanks!
