### ISSUE TITLE
About the offline version.

### ISSUE THREAD

**Issue by PengFeiDuan1995** [koalaman/shellcheck#1619]
Hi  how to get and install the offline version?thanks.

**Comment by brother** [comment]
https://github.com/koalaman/shellcheck#installing

**Comment by brother** [comment]
Check the instructions in the README: https://github.com/koalaman/shellcheck#installing

**Comment by PengFeiDuan1995** [comment]
> Check the instructions in the README: https://github.com/koalaman/shellcheck#installing

I have a LAN centos server that doesn't connect to the Internet, so I want a.zip package or.gz package that doesn't require downloading.An offline version that can be unzipped and used on that machine.Do you know how I can get this package?

**Comment by brother** [comment]
Ok. Either get all the moving pieces needed for building the source or download some RPM then. CentOS is not my home turf... this looks like a working repo: https://pkgs.org/download/ShellCheck

**Comment by PengFeiDuan1995** [comment]
> Ok. Either get all the moving pieces needed for building the source or download some RPM then. CentOS is not my home turf... this looks like a working repo: https://pkgs.org/download/ShellCheck

OK，thank you，I go to try。
