### ISSUE TITLE
SC2140 incorrectly triggered with `=` in quoted fixed strings

### ISSUE THREAD

**Issue by evandrocoan** [koalaman/shellcheck#1629]
```
eval "${newvariablename}"="'${fixcommand}'";
                         ^-- SC2140: Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?
```

Related:
1. https://github.com/koalaman/shellcheck/issues/1565
1. https://github.com/koalaman/shellcheck/issues/1589

**Comment by koalaman** [comment]
The suggestion is correct. The inner quotes don't actually do anything. You can just remove them:

    eval "${newvariablename}='${fixcommand}'";

If you prefer your version stylistically, that's a separate matter.

**Comment by evandrocoan** [comment]
Thanks for explaining!
