### ISSUE TITLE
About precompiled versions

### ISSUE THREAD

**Issue by PengFeiDuan1995** [koalaman/shellcheck#1632]
Does shellCheck have any dependencies for the precompiled version?If not, where can I get this precompiled version and its installation method? My system is CentOS, thank you!

**Comment by koalaman** [comment]
I'm assuming you've decided that your distro's version (`yum install shellcheck`) isn't sufficient.

The Linux x86_64 binaries are statically linked and therefore have no external dependencies. You can download the latest release version [here](https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz) or see the complete list of versions (including latest builds) in the [GCE storage bucket listing](https://shellcheck.storage.googleapis.com/index.html).

You can just unpack it and place the `shellcheck` binary somewhere in your `$PATH`.
