### ISSUE TITLE
SC2073 page does not exist

### ISSUE THREAD

**Issue by JamesOBenson** [koalaman/shellcheck#1649]
#### For bugs
- SC2073 online version of shellcheck

command:
                if [ "$vDEVICE" < "$vNAME" ]; then
Error:
                                ^-- SC2073: Escape \< to prevent it redirecting (or switch to [[ .. ]]).
Clicking on SC2073 hyperlink brings me to the option of creating a new page for that bug.

**Comment by koalaman** [comment]
I've added one, thanks!
