### ISSUE TITLE
Certificate for https://www.shellcheck.net/ has expired

### ISSUE THREAD

**Issue by thomasdarimont** [koalaman/shellcheck#1665]
The SSL certificate of the https://www.shellcheck.net/ project website has expired on August 8, 2019.

**Comment by mrnonz** [comment]
Expired: Thursday, 8 August BE 2562 07:54:36 Indochina Time

I confirmed this issue.

**Comment by koalaman** [comment]
Oops. This has now been fixed, thanks!
