### ISSUE TITLE
QUESTION: Standardized configuration for shellcheck?

### ISSUE THREAD

**Issue by Kreyren** [koalaman/shellcheck#1675]
Disclaimer: i wasn't able to find simmilar issue.

I'm using codacy for shellcheck 0.5.0 which allows configuration alike to allow configuration for pattern matches: 
![image](https://user-images.githubusercontent.com/11302521/63105753-fc33b400-bf70-11e9-8208-90a950e12b2d.png)

Is there some standardized file assuming codacy allows config file which should be used by shellcheck?

Notice: Using all option seems to be insane assuming
![image](https://user-images.githubusercontent.com/11302521/63106031-81b76400-bf71-11e9-9ad9-c17d8092925a.png)

Relevant: https://github.com/ohmybash/oh-my-bash/issues/83

**Comment by nntoan** [comment]
There would be a lot of options yeah, I did configure lot of them in the past the first time I adapted Codacy but I don't remember now, to be honest, I will grant you the correct access to change them if you'd like to :)

**Comment by Kreyren** [comment]
EDIT: this seems to be an issue on codacy's side -> closing
