### ISSUE TITLE
Where Can I read all rules for ShellCheck?

### ISSUE THREAD

**Issue by Shineeeee** [koalaman/shellcheck#1686]
Do u have documentation for rules for ShellCheck ?  
I wanna write `.shellcheckrc`; So, I wanna read the description for all rules for ShellCheck.
Where Can I read all rules for ShellCheck ?

**Comment by Nightfirecat** [comment]
They're available at https://github.com/koalaman/shellcheck/wiki
Click to expand the "Pages" sidebar and it will show you all of the pages.

**Comment by Shineeeee** [comment]
@Nightfirecat   
Thx !! I've found it !
