### ISSUE TITLE
Ignore do when used as a literal in a case matcher

### ISSUE THREAD

**Issue by mcandre** [koalaman/shellcheck#1731]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC1010
- My shellcheck version (`shellcheck --version` or "online"): 0.5.0
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
case "$SUBCOMMAND" in
begin)
    export CRASH_STATUS='0'
    ;;
do)
    if [ "$#" -lt 2 ]; then
        usage_crash
        return 1
    fi

    shift
    "$@" || export CRASH_STATUS=1
    ;;
end)
    if [ "$CRASH_STATUS" = '1' ]; then
        return 1
    fi
    ;;
help)
    usage_crash
    ;;
*)
    usage_crash
    return 1
    ;;
esac

```

#### Here's what shellcheck currently says:

```console
In lib/cra.sh line 27:
    do)
    ^-- SC1010: Use semicolon or linefeed before 'do' (or quote to make it literal).
```

#### Here's what I wanted or expected to see:

(No warnings.)

**Comment by koalaman** [comment]
Indeed. This was kindly fixed by @Gandalf-. Thanks!
