### ISSUE TITLE
koalaman/shellcheck:stable fails with `unrecognized option `-c'`

### ISSUE THREAD

**Issue by AloisMahdal** [koalaman/shellcheck#1741]
I'm just experimenting with GitLab CI, so I might be doing something totally wrong, but with this .gitlab-ci.yml:

    shellcheck:
        image: koalaman/shellcheck:stable
        script:
            - find src -name test | xargs shellcheck

I'm getting this:

    Running with gitlab-runner 10.8.0 (079aad9e)
      on oamg-ci-gitlab-runner e4df1ecc
    Using Docker executor with image koalaman/shellcheck:stable ...
    Pulling docker image koalaman/shellcheck:stable ...
    Using docker image sha256:f8917769fe481d0fe28ee934922f2988587f24731499b3201e129b35e0a3fdac for koalaman/shellcheck:stable ...
    Running on runner-e4df1ecc-project-23067-concurrent-0 via vm-171-130.abc.idm.lab.eng.brq.redhat.com...
    Fetching changes...
    HEAD is now at 9120be2 WIP .gitlab-ci.yml
    From https://gitlab.cee.redhat.com/oamg/jats-morf
     + 9120be2...2044f6d glci-sc    -> origin/glci-sc  (forced update)
    Checking out 2044f6d7 as glci-sc...
    Skipping Git submodules setup
    unrecognized option `-c'

    Usage: shellcheck [OPTIONS...] FILES...
      -a                  --check-sourced            Include warnings from sourced files
      -C[WHEN]            --color[=WHEN]             Use color (auto, always, never)
      -i CODE1,CODE2..    --include=CODE1,CODE2..    Consider only given types of warnings
      -e CODE1,CODE2..    --exclude=CODE1,CODE2..    Exclude types of warnings
      -f FORMAT           --format=FORMAT            Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
                          --list-optional            List checks disabled by default
                          --norc                     Don't look for .shellcheckrc files
      -o check1,check2..  --enable=check1,check2..   List of optional checks to enable (or 'all')
      -P SOURCEPATHS      --source-path=SOURCEPATHS  Specify path when looking for sourced files ("SCRIPTDIR" for script's dir)
      -s SHELLNAME        --shell=SHELLNAME          Specify dialect (sh, bash, dash, ksh)
      -S SEVERITY         --severity=SEVERITY        Minimum severity of errors to consider (error, warning, info, style)
      -V                  --version                  Print version information
      -W NUM              --wiki-link-count=NUM      The number of wiki links to show, when applicable
      -x                  --external-sources         Allow 'source' outside of FILES
                          --help                     Show this usage summary and exit

    unrecognized option `-c'

    Usage: shellcheck [OPTIONS...] FILES...
      -a                  --check-sourced            Include warnings from sourced files
      -C[WHEN]            --color[=WHEN]             Use color (auto, always, never)
      -i CODE1,CODE2..    --include=CODE1,CODE2..    Consider only given types of warnings
      -e CODE1,CODE2..    --exclude=CODE1,CODE2..    Exclude types of warnings
      -f FORMAT           --format=FORMAT            Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
                          --list-optional            List checks disabled by default
                          --norc                     Don't look for .shellcheckrc files
      -o check1,check2..  --enable=check1,check2..   List of optional checks to enable (or 'all')
      -P SOURCEPATHS      --source-path=SOURCEPATHS  Specify path when looking for sourced files ("SCRIPTDIR" for script's dir)
      -s SHELLNAME        --shell=SHELLNAME          Specify dialect (sh, bash, dash, ksh)
      -S SEVERITY         --severity=SEVERITY        Minimum severity of errors to consider (error, warning, info, style)
      -V                  --version                  Print version information
      -W NUM              --wiki-link-count=NUM      The number of wiki links to show, when applicable
      -x                  --external-sources         Allow 'source' outside of FILES
                          --help                     Show this usage summary and exit

    ERROR: Job failed: exit code 3

The *find* does not seem to be culprit; same pipe works on Fedora 30; that is, on my workstation, and also with `fedora` docker image.

**Comment by kpankonen** [comment]
The `koalaman/shellcheck:stable` image uses shellcheck as the entrypoint.  I think you will need to override the entrypoint as documented here: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image

**Comment by koalaman** [comment]
The `koalaman/shellcheck` image only contains ShellCheck. If you need additional tools like `sh`, `find` or `xargs`, try the `koalaman/shellcheck-alpine` image instead.

**Comment by AloisMahdal** [comment]
Sorry for lack of response.  I've switched to `koalaman/shellcheck-alpine` in my `.gitlab-ci.yml`:

    shellcheck:
        image: koalaman/shellcheck-alpine
        script:
            - find src -name test | xargs shellcheck

and it works like a charm!  Thanks!
