### ISSUE TITLE
Can you use env vars within rc files?

### ISSUE THREAD

**Issue by lucianposton** [koalaman/shellcheck#1820]
```
source-path=$HOME/bin
source-path=~/bin
```

I'm looking for a way use env vars (particularly HOME or ~) inside shellcheckrc.

My use case is adding shellcheckrc to my dotfiles which includes its own source path. Since my username and HOME vary across my machines, I'm looking for a way to make shellcheckrc aware of the bash libraries included within the dotfiles in a machine-agnostic manner.

Is there currently a way to do something akin to the above within an rc file?

**Comment by koalaman** [comment]
There's currently no way to use variables in this context, no.
