### ISSUE TITLE
Eq and Ord instances for Replacement are incompatible

### ISSUE THREAD

**Issue by josephcsible** [koalaman/shellcheck#1829]
https://github.com/koalaman/shellcheck/blob/61b073d507bc2282f36995518b1b4ee818d2548c/src/ShellCheck/Interface.hs#L246-L260

Given two `Replacement`s `x` and `y`, if their `repStartPos` fields are equal but other fields are not, then you'll have both `x /= y` and  `compare x y == EQ`. However, [the documentation for `Ord`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#t:Ord) says:

> Note that the following operator interactions are expected to hold:
> [...]
> 6. `x == y` = `compare x y == EQ`

Which instance is correct? The derived `Eq` one or the custom `Ord` one?

**Comment by koalaman** [comment]
The Eq one was correct and the Ord one wasn't even used. I've removed it. Thanks!
