### ISSUE TITLE
How to ignore DevOps tokens #{*}#

### ISSUE THREAD

**Issue by spitfire184** [koalaman/shellcheck#1848]
Hi,

I'm trying to get shellcheck to ignore tokens in a file. They take the format #{variableName}#

This is what I have tried in my  VS Code workspace settings:

```
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "bashIde.highlightParsingErrors": false,
    "[shellscript]": {
        
    },
    "shellcheck.ignorePatterns": {
        "#\\{*\\}#": true
    }
}
```
However, this doesn't work. Could anyone offer guidance?

**Comment by gromgit** [comment]
Also asked and answered in https://github.com/timonwong/vscode-shellcheck/issues/84.

**Comment by spitfire184** [comment]
Yeah, ignorance on my part. Nevermind!
