### ISSUE TITLE
Allow to use as pre-commit hook

### ISSUE THREAD

**Issue by IvanBoyko** [koalaman/shellcheck#1861]
#### For new checks and feature suggestions
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

Pre-commit hooks https://pre-commit.com/ is a very conveninent linting method, which needs to be installed once per git repository and then works on every git commit.
I use it for many different checks and languages.
It would be really great if it was possible to wrap `shellcheck` as such hook.

**Comment by gromgit** [comment]
Pre-commit's [Supported hooks](https://pre-commit.com/hooks) page already points to three separate GitHub projects with ready-made solutions, and googling "shellcheck pre-commit hook" surfaces some more.

If none of those fit your use case, you'll have to be more specific about what you need.

**Comment by ArturKlauser** [comment]
There is a pending PR #1782 for this ...

**Comment by l0b0** [comment]
@gromgit I think (and wholeheartedly support) the idea is that it would be more convenient and easier on the security-minded if the *official* project included pre-commit support. I expect the many wrappers are band-aids for this core issue, and don't really provide solutions for any specific use cases other than "I want to configure a shellcheck pre-commit hook".

**Comment by koalaman** [comment]
There is now official `pre-commit` support via https://github.com/koalaman/shellcheck-precommit for anyone who wants to use it.

**Comment by maica1** [comment]
> There is now official `pre-commit` support via https://github.com/koalaman/shellcheck-precommit for anyone who wants to use it.

What are the supported args on the pre-commit shellcheck hook? I didn't find any related doc on the shellcheck-precommit repo

**Comment by ArturKlauser** [comment]
If you run `shellcheck --help` you'll see the available options.
