### ISSUE TITLE
SC2003 expr as octal to decimal converter

### ISSUE THREAD

**Issue by ChillerDragon** [koalaman/shellcheck#1910]
I try to increment numbers prefixed with zeros. I used ``expr`` to convert them to decimal. Because bash thinks they are octal:
```
$ x="0008"
$ echo "$((x + 1))"
-bash: 0008: value too great for base (error token is "0008")

$ echo "$(expr "$x" + 1)" # <- works but throws SC2003
9
```

**Comment by ChillerDragon** [comment]
Okay I solved it using:
```
$ shopt -s extglob
$ x="0008"
$ x="${x##+(0)}"
$ echo "$((x + 1))"
9
```

Maybe it is worth mentioning it at https://github.com/koalaman/shellcheck/wiki/SC2003

**Comment by mnuccioarpae** [comment]
As an alternative to removing the leading zeroes, you can specify the base for the number:

```sh
$ x=0008
$ echo $((10#$x + 1))
9
```
