### ISSUE TITLE
TODO: Add title

### ISSUE THREAD

**Issue by ihanyunhui** [koalaman/shellcheck#1923]
# !/bin/bash
read -p "please input you ip:" -t30 remote_ip  #获取登陆ip内容
echo "$remote_ip"
expect -d <<EOF
spawn ssh $remote_ip
expect {
"*password:" {send "centos\r"}
}
exit
expect eof;
EOF

**Comment by dimo414** [comment]
@ihanyunhui can you fix the issue title, and clarify what you're trying to report? it's not clear what issue you ran into.
