### ISSUE TITLE
SC1083 triggers on nested braces.

### ISSUE THREAD

**Issue by deryni** [koalaman/shellcheck#193]
$ cat shellcheck-test.sh
echo {foo,ba{r,z}}
echo /{{opt,usr},var/run}

$ shellcheck shellcheck-test.sh

In shellcheck-test.sh line 1:
echo {foo,ba{r,z}}
                 ^-- SC1083: This } is literal. Check expression (missing ;/\n?) or quote it.

In shellcheck-test.sh line 2:
echo /{{opt,usr},var/run}
                        ^-- SC1083: This } is literal. Check expression (missing ;/\n?) or quote it.

$ bash shellcheck-test.sh
foo bar baz
/opt /usr /var/run

$ bash --version
GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.

**Comment by DavidStaron** [comment]
I just encountered this error, i think (hope) it is related to the above issue:

     mv /etc/apt/sources.list{,."$(date +%y%m%d-%H%M%S)"}
                             ^-- SC1083: This { is literal. Check expression (missing ;/\n?) or quote it.
                                                        ^-- SC1083: This } is literal. Check expression (missing ;/\n?) or quote it.

**Comment by brother** [comment]
using shellcheck.net that line actually validates clear @DavidStaron .

**Comment by DavidStaron** [comment]
Not sure what that means... fyi i'm using version 0.3.7 installed with HomeBrew on OS X: https://gist.github.com/DavidStaron/071d3cd0b3a3bb979bfa#file-gistfile1-txt

**Comment by brother** [comment]
I mean that the most recent shellcheck does not show the warning you mention. shellcheck.net always uses the latest shellcheck available. if you see some warning it's advised to check it in the latest shellcheck (local or via http://shellcheck.net) before reporting it. your line above ("mv /etc/apt/sources.list{,."$(date +%y%m%d-%H%M%S)"}") does not render a waring (anymore)

**Comment by deryni** [comment]
Hm... none of the commands listed in this issue appear to trigger a warning on shellcheck.net at the moment. It would seem that 6076f0b1daabc55915ffe2de888c4604ebdab815 fixed this.

**Comment by koalaman** [comment]
Yup, this was fixed after 0.3.7, and will be part of the next release.

**Comment by semaley** [comment]
I'm not sure whether to include this on this bug, or a new one?  I'm encountering a similar issue with ksh93 exclusive syntax for direct file access via a file descriptor.  It also uses {\} syntax like the brace expansion.  Although this is technically documented in man ksh, it's not a well know feature, though once performance is realized I bet it could get popular.

Looks like:
```
regex="~(E)^This\sis\the\sline$"
exec {fd}< /path/to/myfile.txt
while {fd}<# $regex && IFS=$' ' read -u $fd this is the line
do
  :
done
{fd}<&-
```
I'm hitting SC1083 and hoping to not need an eval workaround to get past the SDLC police.  It's freakishly fast, so I also want to make sure others know about this feature, and I'm hopeful it makes it's way into bash.

**Comment by brother** [comment]
> I'm not sure whether to include this on this bug, or a new one? 

the original issue was opened 12 years ago and closed 11 years ago. No one would be mad about a new report regardless of how tightly coupled tings may or may not be.
