### ISSUE TITLE
No -P in Debian (Ubuntu) 0.6.0-1build1

### ISSUE THREAD

**Issue by truchi** [koalaman/shellcheck#1953]
Gentlemen,

I (`Ubuntu 19.10`) installed shellcheck (`0.6.0-1build1`) today:
```
$ sudo apt-get update
$ sudo apt-get install shellcheck
```

Yet I find no `-P`/`--source-path` option:
```
$ shellcheck -P SCRIPTDIR ./src/main.sh 
unrecognized option `-P'

<Usage here..., no mentions of -P/--source-path>
```

Reading through the issues suggests its working for other people.
What am I doing wrong?

Thank you

**Comment by brother** [comment]
Use a newer version, [0.7.0 or later](https://github.com/koalaman/shellcheck/blob/HEAD/CHANGELOG.md#v070---2019-07-28).
The [README](https://github.com/koalaman/shellcheck/blob/v0.6.0/README.md#compiling-from-source) has a guide for building from source that might be what you want.

**Comment by koalaman** [comment]
If your Ubuntu release does not offer 0.7.0 or later, you can install it via Snap or manually download a binary release.
