### ISSUE TITLE
TODO: Add title

### ISSUE THREAD

**Issue by TanQiaoming** [koalaman/shellcheck#1958]
#!/bin/sh

cd  `dirname $0`

#定义全局时间
hour=`date +%k`

min=`date +%M`

function run
{
	run_by_min plan/marketing/cron 1						#计划任务
	run_by_min plan/tracking/daily/register 2				# 更新渠道今日实时用户注册
	run_by_min plan/tracking/daily/login 2					# 更新渠道今日实时用户登陆
	run_by_min plan/tracking/daily/click 2					# 更新渠道今日实时用户点击
	run_by_min plan/tracking/daily/click_page 2				# 更新渠道今日实时抵达页点击
	run_by_min plan/tracking/daily/active 2					# 更新渠道今日实时用户激活
	run_by_min plan/tracking/daily/charge 2					# 更新渠道今日实时用户充值
	run_by_min plan/tracking/daily/paynum_new_device 2					# 更新渠道今日实时用户充值
	run_by_min plan/tracking/daily/promote_ltv 2			# 更新渠道今日实时用户充值
	run_by_min plan/tracking/daily/retention 55					# 更新渠道今日实时用户充值
	run_by_min plan/tracking/daily/remain 57				# 更新渠道今日实时用户充值
	run_by_min plan/tracking/daily/keyword 58				# 更新渠道今日实时用户充值
	
	run_by_min plan/marketing/daily/sync_report_ad_hours 9	# 头条广告分时数据报表
	
	run_by_min plan/marketing/daily/report_get_tencent 5	#每5分钟更新百度推广数据
	run_by_min plan/marketing/daily/report_get_toutiao 8		# 每5分钟更新一次市场广告日报数据
	run_by_min plan/marketing/daily/report_get_baidusms 11	#每10分钟更新百度推广数据
	run_by_min plan/marketing/daily/report_get_baidu 12	#每10分钟更新百度推广数据
	
	
	run_by_min plan/marketing/daily/account_ad_hours 5		# 广点通广告分时数据报表
	run_by_min plan/marketing/daily/sync_report_baidu_hourly 9	# 百度信息流广告分时数据报表

	
	#run_by_min plan/marketing/daily/account_report_ad 5		#广点通广告日报
	run_by_min plan/marketing/ad_get_fields/toutiao 10		#头条更新高频变动广告字段
	

	run_by_hour plan/marketing/advertiser_info_get/baidu 5 #更新百度信息流广告账号数据
	run_by_hour plan/marketing/advertiser_info_get/baidusms 8 #更新百度搜索广告账号数据
	run_by_hour plan/marketing/advertiser_info_get/toutiao 10 #更新头条广告账号数据
	run_by_hour plan/marketing/advertiser_info_get/tencent 12 #更新广点通广告账号数据
	
	run_by_hour plan/marketing/keyword_list_get 13 #更新关键词
	
	
	
	run_at_time plan/marketing/sync_campaign 4 11			#每天4时10分钟更新一次市场广告组
	run_at_time plan/marketing/ad_get/toutiao 4 17			#每天4时17分钟更新一次市场广告计划
	run_at_time plan/marketing/ad_get/tencent 4 18			#每天更新一次广点通广告计划
	run_at_time plan/marketing/ad_get/baidu 4 20			#每天更新一次广点通广告计划
	run_at_time plan/marketing/ad_get/baidusms 4 22			#每天更新一次广点通广告计划
	
#	run_at_time plan/marketing/sync_convert 4 18			#每天4时18分钟更新一次市场转化数据
#	run_at_time plan/marketing/sync_audience 4 20			#每天4时20分钟更新一次人群包数据
#	run_at_time plan/marketing/sync_site 4 22				#每天4时22分钟更新一次建站列表
	
	
	
	
	run_by_hour plan/tracking_template/daily/click 35					# 更新渠道今日昨日用户启动
	run_by_hour plan/tracking_template/daily/click_page 34				# 更新渠道今日昨日用户启动
	run_by_hour plan/tracking_template/daily/active 33					# 更新渠道今日昨日用户启动
	run_at_time plan/tracking_template/daily2/smarty_template 1 32
	
	
	#更新各个海外地区数据
	run_by_hour plan/platform/oversea_members 58				# 每58分钟同步一次充值订单
	run_by_hour plan/platform/oversea_payrecords 59				# 每59分钟同步一次充值订单
	run_by_hour plan/platform/oversea 59						# 每小时更新区域3天前至今日的数据
	run_at_time plan/platform/oversea_retention 3 50			# 每天更新15日内留存
	
	#更新仅国服存在的数据
	run_at_time plan/cron/activity 4 19							#每天4时19分钟执行月度礼包
	run_at_time plan/cron/super_vip 0 19						#每天0时19分钟执行超级VIP活动
	run_at_time plan/platform/daily2/account_analysis  2 29		# 更新官网账号数据
	run_at_time plan/platform/daily2/common_check  1 20			# 检查小额订单状态
	
	run_at_time plan/aike/daily/update_extend_fields 1 20		# 更新艾克拓展字段
	run_by_min plan/aike/daily/fetch_friends_new 10				# 更新艾克增量好友
	run_by_hour plan/aike/daily/upload_firends_info 55			# 上传艾克玩家信息
	run_by_min plan/aike/daily/queue_upload_firends_info 1		# 更新艾克增量好友
	
	
}

. ./common.sh

run

**Comment by brother** [comment]
Are you sure the problem at hand is easy to grasp for others? 

I've used google translate on some of the non english strings and I am not actually sure we have any shellcheck problems here.

Adding a title to the issue might be the first step to clear the air of questions...

**Comment by koalaman** [comment]
Please reopen if this was not an accidental post
