### ISSUE TITLE
After installing Shellcheck

### ISSUE THREAD

**Issue by paulgureghian** [koalaman/shellcheck#1963]
I did  'ls -a' and I didn't see anything related to Shellcheck. where do I find Shellcheck folders / files and more specifically the config files to mute or enable error checks ? 

I have Debian Linux.

**Comment by brother** [comment]
You installed it via apt and now want to know where the files are?
In the terminal type
`dpkg -L shellcheck`

Muting a specific rule can be done via a directive in the source code. Via the command line. Or via a config file. All of this is documented in the wiki. Start at https://github.com/koalaman/shellcheck/wiki/Ignore

GL!

**Comment by paulgureghian** [comment]
Would the directive in the command line be permanent or just for that session ?

**Comment by brother** [comment]
For that instance. If you want it permanent you stick it in the shellcheckrc.

Please try to read the entire page I linked, it's in the middle.
https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-one-or-more-type-of-error-forever

**Comment by brother** [comment]
At this current point in time you need backports for debian stable to have the shellcheckrc support - minimum shellcheck version for that is 0.7.0 - pure stable debian only offers 0.5.0. See table below.

```
    old-old-stable: 0.3.4
    oldstable: 0.4.4
    stable: 0.5.0
    stable backports: 0.7.1
    testing: 0.7.1
    unstable: 0.7.1
```

**Comment by brother** [comment]
There are binaries to download or you could build the the application from sources, see the README for that...
