### ISSUE TITLE
Make running on windows / gitbash easier for beginners

### ISSUE THREAD

**Issue by pletnes** [koalaman/shellcheck#1978]
I'd like to have a documented how-to for beginners on windows. Personally, I use docker in git-bash. I don't know if this is a "common setup". I came up with this first attempt, which could go into the wiki:
https://gist.github.com/pletnes/7657d05ab6ae668cb5d90bff42a5b967

It's a shell script which runs under git-bash on windows, but probably not on any other platform, as it relies on `cygpath` to do the mount. Note that the unixy `$(pwd)` doesn't work as expected under git-bash due to its path conversion magic.

**Comment by koalaman** [comment]
I've added this on the [Contrib](https://github.com/koalaman/shellcheck/wiki/Contrib) page. Thanks!
