### ISSUE TITLE
Doc bug in SC1088?

### ISSUE THREAD

**Issue by pihentagy** [koalaman/shellcheck#1982]
Cannot see the difference between the problematic and the correct code here:
https://github.com/koalaman/shellcheck/wiki/SC1088

**Comment by brother** [comment]
Mixups in the edits was revealed via the history feature of the wiki. Changed the block of problems.

**Comment by pihentagy** [comment]
Thanks. Also note the ``` ``*%*%*  ``` footer. Rather not opening a separate issue for that.
