### ISSUE TITLE
more justification for SC2068 "Double quote array expansions to avoid re-splitting elements"

### ISSUE THREAD

**Issue by phs75** [koalaman/shellcheck#1992]
#### For new checks and feature suggestions
- [x] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

It is perhaps a good idea to mention that avoiding globbing and word splitting will also make the script run faster! This has nothing to do with correctness and catching bugs but it can be extra motivation.

**Comment by brother** [comment]
You can edit the wiki at will =)
