### ISSUE TITLE
docker image not working

### ISSUE THREAD

**Issue by oprogramador** [koalaman/shellcheck#2001]
I get this error:
```
⟩ docker run -it koalaman/shellcheck:0.7.1 sh
Unable to find image 'koalaman/shellcheck:0.7.1' locally
docker: Error response from daemon: manifest for koalaman/shellcheck:0.7.1 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

The same for `docker run -it koalaman/shellcheck:0.7.1 shellcheck` or the `0.7.0` version.

**Comment by oprogramador** [comment]
The same for `koalaman/shellcheck-alpine`

**Comment by koalaman** [comment]
The version tags start with `v`, e.g. `v0.7.1`:

    docker run -it koalaman/shellcheck:v0.7.1

Note that this image does not come with a shell.

**Comment by oprogramador** [comment]
thanks
