### ISSUE TITLE
Not really an issue -- just a much more elegant solution than suggested for SC2199

### ISSUE THREAD

**Issue by kieferrj** [koalaman/shellcheck#2004]
SC2199: https://github.com/koalaman/shellcheck/wiki/SC2199

The recommendation employs a loop, which breaks up what the user was doing into multiple lines and incurs an implied more expensive bigO cost.

A solution I used to dismiss this error without distorting my code into an extra loop is something along the lines of:

Old:
[[ ! ${repos[@]} =~ "${repo}" ]]
New/Fixed:
[[ "$(echo "${repos[@]}" | grep -w -c ${repo})" -eq 0 ]]

The old way, if there were repos named burp and burpfoo acting upon this list for a match on burp is ambiguous. The grep -w part is a whole word match and solves that problem.

Context:
```
  envdirs=(/tmp/foo /tmp/bar /tmp/baz /tmp/fizz)
  declare -a repos
  repos=(buzz)
  # shellcheck disable=SC2068,SC2034
  for envdir in ${envdirs[@]}; do
    for repo in $(find "${envdir}" -type f ! -path ".terraform/*" ! -path ".git/*" -name versions.tf -exec grep 'repo_.*_tag' {} \; | cut -d "\"" -f 2 | cut -d "_" -f 2 | tr '\n' ' '); do
      [[ "$(echo "${repos[@]}" | grep -w -c ${repo})" -eq 0 ]] && repos=("${repos[@]}" "${repo}")
    done
  done
```

**Comment by matthewpersico** [comment]
Don’t you need a -q on that grep to squash the output?

**Comment by koalaman** [comment]
Big-O analysis is great, but have you benchmarked your optimization? :P

Over 10k iterations on my system, `[[ ! ${repos[@]} =~ "${repo}" ]]` takes 0.14 seconds, the wiki's loop takes 0.12 seconds, and your suggestion takes 53.3 seconds. In other words, it's a 400x regression.

You can get the same brevity without the overhead of forking with `[[ ! " ${repos[*]} " =~ " ${repo} " ]]`, though it has the same problem as `grep -w` in that it doesn't handle array elements with spaces correctly.

*Here's my test script:

```sh
#!/bin/bash
repos=(burp burpfoo)
repo=burpfoo
old() {
  [[ ! ${repos[@]} =~ "${repo}" ]]
}
new() {
  [[ "$(echo "${repos[@]}" | grep -w -c ${repo})" -eq 0 ]]
}
wiki() {
  for r in "${repos[@]}"
  do
    [[ "$r" == "$repo" ]]
  done
}

time for i in {1..10000}; do "$1"; done
```

And my results:

```
$ ./bench old
real    0m0.141s
user    0m0.140s
sys     0m0.000s

$ ./bench wiki
real    0m0.121s
user    0m0.121s
sys     0m0.000s

$ ./bench new
real    0m53.343s
user    0m31.439s
sys     0m21.025s
```
