### ISSUE TITLE
License question about bundling ShellCheck

### ISSUE THREAD

**Issue by jansorg** [koalaman/shellcheck#2005]
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

(I tried email first, but that likely ended up somewhere else)
I'm developer of the open-source BashSupport and the closed-source BashSupport Pro plugins for
JetBrains IDEs. https://www.bashsupport.com/

BashSupport Pro is a paid plugin and not open-source. I'm looking into bundling ShellCheck binaries with the plugin, of course with the license and sources.

ShellCheck would be executed as a process, then its output is parsed to show the messages in the editor. 
The plugin has many other functionalities, it's not just a frontend for ShellCheck.

As far as I understand, this would be okay with the GPLv3, https://www.gnu.org/licenses/gpl-faq.html#MereAggregation .

But because there's room for interpretation when a thing is an aggregate or not, I'd like to ask here if this is okay with the developers of ShellCheck.
Are there any objections to bundle ShellCheck?

Thank you!

**Comment by jansorg** [comment]
Closing. I won't bundle it, but integrate as a separate download, similar to existing integrations.

**Comment by koalaman** [comment]
No objections either way!
