### ISSUE TITLE
SC1090 - how to follow a remote file?

### ISSUE THREAD

**Issue by joergi** [koalaman/shellcheck#2012]
## SC1090 - Can't follow non-constant source. Use a directive to specify location.

I understand, that if I load a file in a another directory, I have to specify it, as mentioned [here](https://github.com/koalaman/shellcheck/wiki/SC1090) 

If you see my [pull request](https://github.com/joergi/MagPiDownloader/pull/40), I load a script from another github repository.
I haven't seen anything in the documentation, how to follow a remote file.

```sh

#!/bin/bash

# shellcheck source=https://raw.githubusercontent.com/joergi/downloader/master/linux_mac/downloader.sh
source <(curl -s https://raw.githubusercontent.com/joergi/downloader/master/linux_mac/downloader.sh) "$downloadUrl" "$recentIssue" "$@"

```

#### Here's what shellcheck currently says:
```
source <(curl -s https://raw.githubusercontent.com/joergi/downloader/master/linux_mac/downloader.sh) "$downloadUrl" "$recentIssue" "$@"
       ^-- SC1091: Not following: https://raw.githubusercontent.com/joergi/downloader/master/linux_mac/downloader.sh was not specified as input (see shellcheck -x).
```

This is now showing SC1091 - but if I don't have the `# shellcheck source=https://raw.githubusercontent.com/joergi/downloader/master/linux_mac/downloader.sh`, I got the SC1090

#### Here's what I wanted or expected to see:
I wanted to know, if I should ignore the one with `# shellcheck disable=SC1090` of if there is a possibility to check it, even it is a remote file.

**Comment by koalaman** [comment]
ShellCheck does not support downloading files. My suggestion would be one of:

* Use `bash` instead of `source` since it appears that you simply want to run this script, not necessarily source it
* Just `#shellcheck source=/dev/null` to ignore the file, since checking this file would be up to the repo in which it lives and not yours

**Comment by joergi** [comment]
Thx a lot. Maybe a note in the Readme for SC1090 would be nice?

**Comment by rickswe** [comment]
Hello,

How do I do `shellcheck source` for mac and linux?

This would not work on mac:

```sh
# shellcheck source=/home/rick/bin/lib.sh
source "$HOME/bin/lib.sh"
```

I understand I could ignore it with `/dev/null` but that would be a lot of ignoring
if I have scripts outside of $HOME/bin.

I still haven't figured this out... for now I have disabled SC1091. Please see comments in lib.sh.

script.sh
```sh
source "lib/lib.sh"
```

lib.sh
```sh
#!/usr/bin/env bash
# shellcheck shell=bash
# You may need these here later:
# # shellcheck disable=SC2034,SC2154 # Unused Variables, Var is referenced by not assigned
set -euo pipefail
# UPDATE: This don't work, for now added to the snippet shbang to disable SC1091.
# README: 07/27/2025 Common things used in bash.
#
#         USAGE: Put this in your bash script:
#         In a script under ~/bin:
#             source "lib/lib.sh"
#
#         Script outside of ~/bin. Does not work waiting on issue #2012
#               shellcheck source=/dev/null
#               source "$HOME/bin/lib/lib.sh"
#               source "$LIB/something_else.sh"
#
#               If not using a script on mac (e.g., niri.sh) hard-code it:
#               source "/home/ritchie/bin/lib/lib.sh"
#               source "$LIB/something_else.sh" # May not work waiting on issue #2012

# May not work: Waiting on https://github.com/koalaman/shellcheck/issues/2012
# Source on mac and Linux hack.
# Shell Check will inform of SC1091, as a workaround we use this LIB variable.
LIB="$HOME/bin/lib"
export LIB

# Funny thing about it is I don't get SC1091 here.
source "$LIB/colors.sh"
```

Thanks for all your work on shellcheck.

**Comment by koalaman** [comment]
> ```
># shellcheck source=/home/rick/bin/lib.sh
> source "$HOME/bin/lib.sh"
>```

What SC1091 message are you getting when you check this file? Which shellcheck version are you using?

If you get `Not following: /home/rick/bin/lib.sh was not specified as input (see shellcheck -x).` ? If so, use `shellcheck -x` or add `external-sources=true` in your `~/.shellcheckrc`

**Comment by rickswe** [comment]
@koalaman  Here is my reproducible output. The file does exist `"$HOME/bin/lib/lib.sh"`.

`shellcheck --version`

```text
ShellCheck - shell script analysis tool
version: 0.10.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
```

`cd ~/bin/lib && cat del.sh`

```sh
#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

source "$HOME/bin/lib/lib.sh"
```
`shellcheck -x del.sh`

```text
In del.sh line 5:
source "$HOME/bin/lib/lib.sh"
       ^--------------------^ SC1091 (info): Not following: ./bin/lib/lib.sh: openBinaryFile: does not exist (No such file or directory)

For more information:
  https://www.shellcheck.net/wiki/SC1091 -- Not following: ./bin/lib/lib.sh: ...
```

Even with the file `/home/rick/.shellcheckrc` on `external-sources=true` I still get the error.

`file  "$HOME/bin/lib/lib.sh"`
```sh
/home/rick/bin/lib/lib.sh: Bourne-Again shell script, Unicode text, UTF-8 text executable
```

**Comment by koalaman** [comment]
Is the problem that you tried `# shellcheck source=/home/rick/bin/lib.sh` but your actual path is `/home/rick/bin/lib/lib.sh` with an extra `/lib/` in it?

**Comment by rickswe** [comment]
@koalaman I think I changed my setup had it in there at one point and moved everything to lib. However,
here is an easy reproducible setup with del.sh:

```sh
rick bin/lib 
-❯ cat del.sh
#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

source "$HOME/bin/lib/lib.sh"


rick bin/lib 
-❯ shellcheck -x del.sh

In del.sh line 5:
source "$HOME/bin/lib/lib.sh"
       ^--------------------^ SC1091 (info): Not following: ./bin/lib/lib.sh: openBinaryFile: does not exist (No such file or directory)

For more information:
  https://www.shellcheck.net/wiki/SC1091 -- Not following: ./bin/lib/lib.sh: ...

rick bin/lib 
❗ file  "$HOME/bin/lib/lib.sh"
/home/rick/bin/lib/lib.sh: Bourne-Again shell script, Unicode text, UTF-8 text executable

rick bin/lib 
-❯ pwd
/home/rick/bin/lib
```

**Comment by koalaman** [comment]
ShellCheck does not attempt to recognize and expand variables in paths to `source` statements. Not even well known ones like `$HOME`. 

You have to point it to a non-dynamic path using a directive, e.g.

```
# shellcheck source=/home/rick/bin/lib/lib.sh
source "$HOME/bin/lib/lib.sh"
```

You originally posted that this did not work, but the path you gave it in your original example was missing the `/lib/`.

**Comment by rickswe** [comment]
> ShellCheck does not attempt to recognize and expand variables in paths to source statements. 

@koalaman  That would be a nice improvement considering that many people use multi-platform OS so the
script is not portable because the path would need to be hardwired:

For Linux:

```text
/home/username/path/to/script
```

For Mac:

```text
/Users/username/path/to/script
```

I understand I can ignore this with:

```sh
# shellcheck disable=SC1091 # source Not following path issues see: #2021
```

Thanks
