### ISSUE TITLE
Can shellcheck scan recursivly through sub directories on its own?

### ISSUE THREAD

**Issue by huornlmj** [koalaman/shellcheck#2014]
I tried shellcheck **/*.sh but it only scans the first level directory.  I want to avoid using find / exec or xargs as I want to get the return code of shellcheck alone.  Thanks.

**Comment by koalaman** [comment]
@huornlmj In bash you can use `shopt -s globstar` to make `**/*.sh` recursive. Hopefully that works well enough!
