### ISSUE TITLE
Feature request: apply directives to more than one command/block

### ISSUE THREAD

**Issue by Skirmisher** [koalaman/shellcheck#2016]
Hi! I just started using shellcheck and I'm really liking it so far. I've just run into a small rough edge that I don't see a current solution for.

I'm writing a custom dracut module. dracut uses `#!/usr/bin/sh` for scripts in the initramfs, but their scripts make extensive use of `local`, presumably because (while not technically POSIX) it's supported by pretty much any shell you could supply as `sh` in today's Linux distributions. I chose to follow their lead. However, shellcheck warns me about every instance of `local` in my own scripts. Two adjacent lines turn into this output:

```
In crypt-cache-lib.sh line 7:
    local cmd; local prompt; local tries=3
    ^-------^ SC2039: In POSIX sh, 'local' is undefined.
               ^----------^ SC2039: In POSIX sh, 'local' is undefined.
                             ^---------^ SC2039: In POSIX sh, 'local' is undefined.


In crypt-cache-lib.sh line 8:
    local tty_echo_off; local _keyring
    ^----------------^ SC2039: In POSIX sh, 'local' is undefined.
                        ^------------^ SC2039: In POSIX sh, 'local' is undefined.
```

Since SC2039 refers to any POSIX compliance issues, I tried to disable it for just the block of statements at the beginning of my function, preceding them with a `# shellcheck disable=SC2039` directive line. However, this literally only disables the warning for the first command:

```
In crypt-cache-lib.sh line 8:
    local cmd; local prompt; local tries=3
               ^----------^ SC2039: In POSIX sh, 'local' is undefined.
                             ^---------^ SC2039: In POSIX sh, 'local' is undefined.


In crypt-cache-lib.sh line 9:
    local tty_echo_off; local _keyring
    ^----------------^ SC2039: In POSIX sh, 'local' is undefined.
                        ^------------^ SC2039: In POSIX sh, 'local' is undefined.
```

The documented suggestion of creating a subshell to scope the directive is of course useless here, since then the variables would be local to the subshell. (Frankly, I think suggesting a subshell just for directive scoping is a bit dangerous, since it could have subtle, potentially undesirable effects, and forks a process besides.) That only leaves me with separating each statement into its own line just to add a directive before each of them, with isn't acceptable.

For this directive to be more useful, I propose adding some new syntax (to preserve existing functionality for compatibility). One option would have start/end lines that explicitly scope the directive. Another could affect the whole line regardless of statements. Yet another could use heuristics like continuing until a line with only whitespace is found. I don't have a strong opinion about this; I just want a better solution for silencing corner-case warnings like this when I'd rather not remove all POSIX warnings.

An alternative solution to my particular problem would be to separate `local` warnings from SC2039, or possibly turn it into an optional check. However, having more control over scoping directives would likely be more widely beneficial.

**Comment by koalaman** [comment]
You're right on both accounts: SC2039 should really be multiple warnings (though there should be a strategy in place for disabling a range of them), and the docs should definitely not be suggesting subshells. Where are you seeing this?

The man page suggests using a brace group, which may be an acceptable workaround in your case:

              # shellcheck disable=SC2016
              {
                echo 'Modifying $PATH'
                echo 'PATH=foo:$PATH' >> ~/.bashrc
              }

**Comment by Skirmisher** [comment]
My apologies, I mixed up brace groups and subshells, probably because brace groups *can* spawn subshells in certain cases (e.g. if backgrounded, which is where I'm used to seeing them). Seems like they don't affect local statements, which are specific to functions anyway because variable scoping doesn't exist otherwise, which is easy to forget if you're used to C rules! Sorry about that 😅

Would you prefer another issue to track splitting out SC2039?

**Comment by koalaman** [comment]
There's already a few floating around including #1727 ^^
