### ISSUE TITLE
TODO: Add title

### ISSUE THREAD

**Issue by nanqiaokeji** [koalaman/shellcheck#2017]
#!usr/bin/env bash
#author:Cernet_liyang
#data:2020/7/7
#useage:deploy zabbix_agent

set -e

cat <<-EOF
        +----------------------------+
        |      zabbix-aengt-Tools    |
        +----------------------------+
        |         a.Centos6          |
        |         b.Centos7          |
        |         c.Quit             |
        +----------------------------+
EOF

read -p "Please in put your choose ：" var01
case $var01 in
a)
        read -p "please input zabbix-server ip:" var03

        ping -c 1 192.168.51.85
        if [ $? -eq 0 ];
        then
                #Change yum source
                if [ ! -f "/etc/yum.repos.d/nexus.repo" ];
                then
                        mkdir /etc/yum.repos.d/bak
                        if [ -f "/etc/yum.repos.d/epel-6.repo" ];
                        then
                                mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/epel-6.repo /etc/yum.repos.d/bak
                        else
                                mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/bak
                        fi
                        scp root@${var03}:/root/nexus.repo /etc/yum.repos.d/nexus.repo
                else
                        echo "your yum source doesn't need to be changed"
                fi
                #install zabbix-agent 
                yum -y install zabbix-agent
                chkconfig zabbix-agent on
                #Modify configuration file
                sed -i "s/Server=127.0.0.1/Server=${var03}/"  /etc/zabbix/zabbix_agentd.conf
                sed -i "s/ServerActive=127.0.0.1/ServerActive=${var03}/"  /etc/zabbix/zabbix_agentd.conf
                #restart zabbix-agent
                service zabbix-agent start
                #firewall
                sed -i "/-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT/d" /etc/sysconfig/iptables
                sed -i "/-A FORWARD -j REJECT --reject-with icmp-host-prohibited/d" /etc/sysconfig/iptables
                sed -i "s/COMMIT/-A INPUT -m state --state NEW -m tcp -p tcp --dport 10050:10051 -j ACCEPT/" /etc/sysconfig/iptables
                echo "-A INPUT -m state --state NEW -m upd -p upd --dport 10050:10051 -j ACCEPT" >> /etc/sysconfig/iptables
                echo "COMMIT" >> /etc/sysconfig/iptables
                service iptables restart
        else
                echo "Connection to nexus failed"
        fi

        ;;
b)

        read -p "please input zabbix-server ip :" var02

        ping -c 1 192.168.51.85
        if [ $? -eq 0 ];
        then
                #Change yum source
                if [ ! -f "/etc/yum.repos.d/nexus.repo" ];
                then
                        mkdir /etc/yum.repos.d/bak
                        if [ -f "/etc/yum.repos.d/epel-7.repo" ];
                        then
                                mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/epel-7.repo /etc/yum.repos.d/bak
                        else
                                mv /etc/yum.repos.d/CentOS-* /etc/yum.repos.d/bak
                        fi
                        scp root@${var02}:/root/nexus.repo /etc/yum.repos.d/nexus.repo
                else
                        echo "your yum source doesn't need to be changed"
                fi
                #install zabbix-agent 
                yum -y install zabbix-agent
                systemctl enable zabbix-agent
                #Modify configuration file
                sed -i "s/Server=127.0.0.1/Server=${var02}/"  /etc/zabbix/zabbix_agentd.conf
                sed -i "s/ServerActive=127.0.0.1/ServerActive=${var02}/"  /etc/zabbix/zabbix_agentd.conf
                #restart zabbix-agent
                systemctl restart zabbix-agent
                #firewall
                firewall-cmd --permanent --zone=public --add-port=10050-10051/tcp
                firewall-cmd --reload

        else
                echo "Connection to nexus failed"
        fi
        ;;
c)
        exit
        ;;
*)
        echo "Please input a or b or c "
        ;;
esac

**Comment by koalaman** [comment]
Assuming this was filed accidentally. Reopen with additional detail if this is not the case.
