### ISSUE TITLE
Document how to contribute to Wiki

### ISSUE THREAD

**Issue by pm98zz-c** [koalaman/shellcheck#2025]
Hi, I was trying to make a suggestion for https://github.com/koalaman/shellcheck/wiki/SC2141 and was wondering what the process was.

I've noticed quite soon the wiki was open for editing to anyone, but left still a bit confused as whether I should proceed or not, require approval from someone, etc

It would be good to expend a bit on https://github.com/koalaman/shellcheck#contributing in regards to the wiki page, as the statement "Please submit patches to code or documentation as GitHub pull requests" is what confused me (there are no MR for wikis) and https://github.com/koalaman/shellcheck/wiki/DevGuide doesn't expand on it neither.

Cheers (and thanks for shellcheck, livesafer !)

PS: change in question was https://github.com/koalaman/shellcheck/wiki/SC2141/8cbf4755469aedcb00cf10420ceeed9bdad5f1ab just in case.

**Comment by koalaman** [comment]
Looks good to me. I also added a short wiki policy to the Dev Guide. Thanks!
