### ISSUE TITLE
v.0.3.7 - shellcheck not recognizing lastpipe

### ISSUE THREAD

**Issue by DiagonalArg** [koalaman/shellcheck#2032]
Code:

```
shopt -s lastpipe
echo "foo" | read FooOut
```

`shellcheck` output:

```
echo "foo" | read FooOut
                  ^-- SC2030: Modification of FooOut is local (to subshell caused by pipeline).
```

`man bash`:

>               lastpipe
>                       If  set,  and job control is not active, the shell runs the last command of a pipe-
>                       line not executed in the background in the current shell environment.

Shellcheck should be checking if lastpipe is on or not.

**Comment by koalaman** [comment]
Version 0.3.7 is over 5 years old at this point. This issue was fixed three years ago for 0.4.7. Please consider upgrading.
