### ISSUE TITLE
SC2035 documentation should note the -- suggestion is not applicable for echo

### ISSUE THREAD

**Issue by mavik1** [koalaman/shellcheck#2036]
https://github.com/koalaman/shellcheck/wiki/SC2035 suggests using -- so name with dashes won't become options.

It might be worth noting that this suggestion is not applicable to `echo` and a possibly a few other built in commands.

**Comment by koalaman** [comment]
This really shouldn't be emitted for `echo` or `printf` at all. I've suppressed it for these commands, and updated the wiki. Thanks!
