### ISSUE TITLE
Wiki page for rule SC1056 has something wrong

### ISSUE THREAD

**Issue by lolgab** [koalaman/shellcheck#2040]
The wiki page for SC1056 https://github.com/koalaman/shellcheck/wiki/SC1056 is very strange.
I don't know if the wiki is generated or not but apparently there is something wrong there.

**Comment by brother** [comment]
Indeed. Looks like there were no version before either.

`SC1056` is reporting a `missing }` if I [understand the source code](https://github.com/koalaman/shellcheck/blob/c9be7ab2eb7ccb05ca0a5cb75946469a3cee98e0/src/ShellCheck/Parser.hs#L2427) correct.

**Comment by brother** [comment]
Fun fact. The code in the wiki pages actually has a report about SC1056 in it.

![image](https://user-images.githubusercontent.com/243351/91488605-d5ac9680-e8af-11ea-876b-b9a1d3205803.png)


The problematic code in the wiki page is `sigma = ${Fwmh}/sqrt(8*log(2))` and that's not shell syntax.
I am not sure what shell will do `8 times log 2` and `sqrt` math via built in. By replacing that with a temp variable it is revealed that the sigma variable produced on that line is never used... thus commenting the whole lines solves the error. And reveals a pile of errors and warnings ofc =)

The wiki page for SC1056 should be produced though.

**Comment by brother** [comment]
Added a start based on SC1054 at least.
Hopefully accurate.

**Comment by lolgab** [comment]
Thank you very much!
I guess this issue can be closed now. Can I?
