### ISSUE TITLE
sc2034 for `echo`

### ISSUE THREAD

**Issue by TinCanTech** [koalaman/shellcheck#2043]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [X] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [x] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/sh

sc_test ()
{
p='alice
bob
jane'

x="$(printf "%s\n" "$p")"

echo ==$x==

y="${x##* }"

echo ==$y==

z="${x%% *}"

echo ==$z==
}

sc_test


```

#### Here's what shellcheck currently says:

```
$ shellcheck myscript
 
Line 11:
echo ==$x==
     ^-- SC1068: Don't put spaces around the = in assignments (or quote to make it literal).
     ^-- SC1097: Unexpected ==. For assignment, use =. For comparison, use [/[[.
 
Line 15:
echo ==$y==
     ^-- SC1068: Don't put spaces around the = in assignments (or quote to make it literal).
     ^-- SC1097: Unexpected ==. For assignment, use =. For comparison, use [/[[.
 
Line 19:
echo ==$z==
^-- SC2034: echo appears unused. Verify use (or export if used externally).
     ^-- SC1068: Don't put spaces around the = in assignments (or quote to make it literal).
     ^-- SC1097: Unexpected ==. For assignment, use =. For comparison, use [/[[.

$ 
```
#### Here's what I wanted or expected to see:
I did not expect to see 2034 for `echo`
I was pressing buttons with total abandon when this happened.
I have no comment -- I'm only a messenger :)

**Comment by koalaman** [comment]
This is equivalent to #2022 and was just fixed. Thanks!
