### ISSUE TITLE
SC2162 documentation link is broken

### ISSUE THREAD

**Issue by floriancastelain** [koalaman/shellcheck#2056]
#### For new checks and feature suggestions
- [x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

In https://github.com/koalaman/shellcheck/wiki/SC2162#rationale , this [link](https://www.tldp.org/LDP/abs/html/internal.html#READR) is not reachable.

**Comment by SuperSandro2000** [comment]
Probably just down for a short maintenance. Until that is over you can read the page here https://web.archive.org/web/20200804023902/https://www.tldp.org/LDP/abs/html/internal.html.
