### ISSUE TITLE
TODO: Add title

### ISSUE THREAD

**Issue by Funny-Human** [koalaman/shellcheck#2088]
#!/bin/bash
#请在这里输入姓名
read -p "请输入你的姓名(最好拼音):" name
read -p "请输入你的学号后2位:" student_number
#配置网卡文件
read -p "请输入你的MAC地址" hwaddr
echo -e "HWADDR=$hwaddr\nTYPE=Ethernet\nBOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.$student_number.10\nNETMASK=255.255.255.0\nGATEWAY=192.168.$student_number.1\nDNS1=8.8.8.8\nNAME=eno16777736\n" > /etc/sysconfig/network-scripts/ifcfg-eno16777736
#改名
echo -e "$name.localdomain" > /etc/hostname
#配置yum源-请先插好光盘
mkdir /mnt/iso
mount /dev/sr0 /mnt/iso
rpm -rf /etc/yum.repo.d/*
echo -e "[iso]\nname=localyum\nbaseurl=file:///mnt/iso\nenable=1\ngpgcheck=0\ngpgkey=file:///mnt/iso/RPM-GPG-KEY-redhat-release" > /etc/yum.repos.d/ISO.repo
#重启网络服务
systemctl restart network.service

**Comment by brother** [comment]
Translated the chinese to english via google.

`
#!/bin/bash
# Please enter your name here
read -p "Please enter your name (preferably pinyin)" name
read -p "Please enter the last 2 digits of your student ID:" student_number
# Configure network card files
read -p "Please enter your MAC address" hwaddr
echo -e "HWADDR=$hwaddr\nTYPE=Ethernet\nBOOTPROTO=static\nONBOOT=yes\nIPADDR=192.168.$student_number.10\nNETMASK=255.255.255.0\nGATEWAY=192.168.$student_number.1\nDNS1=8.8.8.8\nNAME=eno16777736\n" > /etc/sysconfig/network-scripts/ifcfg-eno16777736
# Renamed
echo -e "$name.localdomain" > /etc/hostname
# Configure yum	source-please insert the CD first
mkdir /mnt/iso
mount /dev/sr0 /mnt/iso
rpm -rf	/etc/yum.repo.d/*
echo -e "[iso]\nname=localyum\nbaseurl=file:///mnt/iso\nenable=1\ngpgcheck=0\ngpgkey=file:///mnt/iso/RPM-GPG-KEY-redhat-release" > /etc/yum.repos.d/ISO.repo
# Restart network service
systemctl restart network.service

`

**Comment by brother** [comment]
It complains about the read without -r, and that sounds reasonable.

> read without -r will mangle backslashes. [SC2162]

@koalaman close this issue. it's bogus.
