### ISSUE TITLE
Support for more shell languages

### ISSUE THREAD

**Issue by mcandre** [koalaman/shellcheck#209]
It's awesome how shellcheck supports bash, sh, ksh, and zsh! Could we add other languages as well?
- csh and tcsh
- ash and dash
- fish

**Comment by krader1961** [comment]
FWIW, someone asked about [lint support for fish on stackoverflow](http://stackoverflow.com/questions/42660371/is-there-a-linter-for-fish-like-there-is-for-bash-with-shellcheck). I pointed out that fish has a `fish_indent` command (similar to `clang-format` or `gofmt`) which could be a starting point for a `fish_lint` command. Doing that makes more sense than trying to teach this tool about fish syntax given that it is quite different from POSIX shells.

**Comment by mmlb** [comment]
@koalaman I just hit a discrepancy between `ash` and `dash` or `sh`.

```
[manny@manny ~]$ docker run --rm -ti ubuntu:xenial sh -c '[[ -e /etc/hosts ]] && echo hosts exists'
sh: 1: [[: not found
[manny@manny ~]$ docker run --rm -ti alpine:3.5 sh -c '[[ -e /etc/hosts ]] && echo hosts exists'
hosts exists
[manny@manny ~]$ docker run --rm -ti alpine:3.2 sh -c '[[ -e /etc/hosts ]] && echo hosts exists'
hosts exists
```
should I open a separate issue?
