### ISSUE TITLE
quotes in arithmetic expression with command substitution

### ISSUE THREAD

**Issue by libXq** [koalaman/shellcheck#2096]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [ x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [ x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [ ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/bash

function get_ram_size() {
  awk '$1 == "MemTotal:" {print $2; exit}' /proc/meminfo 2> /dev/null \
  || { error "${FUNCNAME[0]}"; return 1; }
}

function get_swap_size() {
  echo "$(($(get_ram_size) * 2 + 4))" \
  || { error "${FUNCNAME[0]}"; return 1; }
}

```

or

```sh

#!/bin/bash

function get_ram_size() {
  awk '$1 == "MemTotal:" {print $2; exit}' /proc/meminfo 2> /dev/null \
  || { error "${FUNCNAME[0]}"; return 1; }
}

function get_swap_size() {
  echo "$(("$(get_ram_size)" * 2 + 4))" \
  || { error "${FUNCNAME[0]}"; return 1; }
}

```

or

```sh

#!/bin/bash

function get_ram_size() {
  awk '$1 == "MemTotal:" {print $2; exit}' /proc/meminfo 2> /dev/null \
  || { error "${FUNCNAME[0]}"; return 1; }
}

function get_swap_size() {
  echo $(("$(get_ram_size)" * 2 + 4)) \
  || { error "${FUNCNAME[0]}"; return 1; }
}

```
or

```sh

#!/bin/bash

function get_ram_size() {
  awk '$1 == "MemTotal:" {print $2; exit}' /proc/meminfo 2> /dev/null \
  || { error "${FUNCNAME[0]}"; return 1; }
}

function get_swap_size() {
  echo $(($(get_ram_size) * 2 + 4)) \
  || { error "${FUNCNAME[0]}"; return 1; }
}

```
#### Here's what shellcheck currently says:

Nothing

#### Here's what I wanted or expected to see:

Adding quotes???

**Comment by koalaman** [comment]
$((..)) always expands to a number, so (unless you set `IFS=5`) it doesn't need quoting. You also don't need to quote in arithmetic contexts, and from my reading of POSIX, bash allowing it at all is an extension.

(There's an issue about actively warning about quotes in `$((..))` for sh/dash somewhere.)
