### ISSUE TITLE
Feature Request: Only Critical Errors

### ISSUE THREAD

**Issue by markfaine** [koalaman/shellcheck#2108]
#### For new checks and feature suggestions
- [ n/a] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [ x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

I guess #524 sort of captures this but specifically what I want is to catch errors that would directly result in the script not working at all.  Legitimate syntax errors.  I guess it would also be nice if it would catch code that would result in a catastrophic failure even though it might run, but that might be asking too much.

I would like to use it in Gitlab as a server side hook for shell scripts and I know I will get a lot of push back if I ask old seasoned admins to use mapfile instead of while read, etc.  If they see it as style over substance they will revolt and not want me to use it at all, but if I can say that it just verifies that the script contains no significant errors, that is likely to be accepted.

**Comment by koalaman** [comment]
Have you tried `--severity=error`? If nothing else, it'll be easier to filter.

If you additionally want specific non-error checks, you can do a second run with selected whitelisted warnings like `-i SC2114,SC2115`

**Comment by markfaine** [comment]
Thanks, I'll try this

**Comment by brother** [comment]
Probably nothing more to see here.
