### ISSUE TITLE
DEBUG=true leads to error unbound variable

### ISSUE THREAD

**Issue by stuertz** [koalaman/shellcheck#2138]
#### For bugs
- Version 0.7.0

#### Here's a snippet or screenshot that shows the problem:

```sh
export DEBUG=true
shell-lint.sh: line 8: true: unbound variable
```

**Comment by brother** [comment]
or does it? 
works on shellcheck.net with bash shebang. What shell are you targeting?

**Comment by stuertz** [comment]
Sorry. My error comes from a wrapper script that calls shellcheck. I got things wrong.
