### ISSUE TITLE
Allow for ${@:2} syntax in variable assignment

### ISSUE THREAD

**Issue by DocSalvager** [koalaman/shellcheck#214]
Nice tool! Plan to use it.

But my first experiment revealed it needs a bit of tweaking. Did not allow for the valid syntax in a working script as described below...

In the output below, `local _help_text="${@:2}"` concatenates the function's positional arguments 2 and greater into a string and assigns them to the variable $_help_text...

``` bash
48      local _help_text="${@:2}"`
                           ^––SC2124 Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.
```

**Comment by evandrocoan** [comment]
Related to: 
1. https://github.com/koalaman/shellcheck/issues/1148 "$@" serves a purpose, no?
1. https://github.com/koalaman/shellcheck/issues/127 SC2048 is overly zealous

See also [How to portability use "${@:2}"?](https://stackoverflow.com/questions/56822216/how-to-portability-use)
