### ISSUE TITLE
shellcheck hangs on kubectl bash completion script

### ISSUE THREAD

**Issue by sdhoward** [koalaman/shellcheck#2158]
```sh

kubectl completion bash | shellcheck --shell bash -

```

In the online shellcheck.net tool, pasting the completion script gives the message that shellcheck exceeded the resources of its sandbox. shellcheck 0.7.1 on my machine hangs indefinitely and uses 100% cpu.

kubectl binary can be downloaded to test with

```sh
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
```

[instructions here](https://kubernetes.io/docs/tasks/tools/install-kubectl/)

**Comment by bwenrich** [comment]
I see the same in shellcheck.net, as it appears to run with a max of 5 seconds of CPU time. https://github.com/koalaman/shellcheck.net/blob/master/shellcheck.sh#L6

But I couldn't reproduce this issue using kubectl v1.20.4 and shellcheck 0.7.1 on three different servers:
1. amd64 - 22 seconds - (2009 laptop) - dual-core @ 2.8GHz - Fedora 32
2. amd64 - 15 seconds - (2015 desktop) - quad-core @ 2.5GHz - Ubuntu 20.04
3. ARM - 50 seconds - (RasPi4) - quad-core @ 1.5GHz - Ubuntu 20.04

The output from kubectl is a script with 14,000+ lines and almost 450KB, but I'm not sure what the ordinary performance is for a script of this size. Could you describe your test environment more?

    ## example run
    $ ./kubectl version
    Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", 
    GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", 
    GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
    $ ./shellcheck --version
    ShellCheck - shell script analysis tool
    version: 0.7.1
    
    $ date; ./kubectl completion bash | ./shellcheck --shell bash -; date
    Sat 13 Mar 2021 03:49:01 PM EST
    ## shellcheck output here - about 10 warnings ##
    Sat 13 Mar 2021 03:49:23 PM EST

**Comment by bwenrich** [comment]
FYI I also run a local version of shellcheck.net, so I removed the resource limits from shellcheck.sh script & it ran OK.
That environment is Kubernetes (docker) on a rather slow amd64 PC, and it took about 70 seconds to produce the output.

**Comment by sdhoward** [comment]
I forgot to mention I'm on the latest macOS. I let the program run longer and it does produce output, 2 minutes 44 seconds on mac and 4 minutes 56 seconds in a docker container on a linux vm on the mac. Thanks for reproducing!
