### ISSUE TITLE
SC2064 how to evaluate parameters immediatelly

### ISSUE THREAD

**Issue by aleszeleny** [koalaman/shellcheck#2159]
Hello,

Is there a way in bash to use trap calling a function with a parameter that has to be evaluated immediately and not when the signal is caught?

`trap "my_fn ${expand_me_when_setting_trap}" SIGTERM`

Thanks

**Comment by TriMoon** [comment]
@aleszeleny ,
> `trap "my_fn ${expand_me_when_setting_trap}" SIGTERM`

The way you posted already does what you ask, see explanation at [SC2064](https://github.com/koalaman/shellcheck/wiki/SC2064) 😉 


/close

**Comment by aleszeleny** [comment]
Thanks!

Aleš Zelený

Dne so 13. 3. 2021 12:24 uživatel ©TriMoon™ ***@***.***>
napsal:
