### ISSUE TITLE
SC2072 small typo of &lt; instead of <

### ISSUE THREAD

**Issue by QuantumLibet** [koalaman/shellcheck#2161]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2072

#### Here's what shellcheck currently says:
`[[ $(echo "2 &lt; 3.14" | bc) == 1 ]]  # Use bc`

#### Here's what I wanted or expected to see:
the combination `&lt;` seems to be the html equivalent of `<` (less than) and is not translated in the html view, as this has been embedded in a code block. it should look like this (I assume):
`[[ $(echo "2 < 3.14" | bc) == 1 ]]  # Use bc`

If I am wrong, please excuse my error and discard this message.

**Comment by brother** [comment]
Until next time, the wiki is open for edits.
I have applied your suggestion now.

https://github.com/koalaman/shellcheck/wiki/SC2072

Is the text also included in the source somewhere? 

Consider closing the issue if it was only the wiki that was problematic.
