### ISSUE TITLE
Homebrew bottle not available anymore

### ISSUE THREAD

**Issue by fharper** [koalaman/shellcheck#2162]
When running `brew install shellcheck` as mentioned in the README, it doesn't work anymore. I got this error

![image](https://user-images.githubusercontent.com/1170989/109836451-28298f80-7c12-11eb-8900-8e4b170ce8a0.png)

**Comment by hoylemd** [comment]
Same for me. I'm on a new Apple Silicon M1 arch machine though, so I suspect that may be a factor

I tried running with --build-from-source and I got this error:

```
==> Installing shellcheck dependency: ghc
==> ./configure --prefix=/opt/homebrew/Cellar/ghc/8.10.4/libexec/integer-gmp --with-pic --disable-shared --build=arm_vortex_tempest-apple-darwin20
Last 15 lines from /Users/mikehoyle/Library/Logs/Homebrew/ghc/01.configure:
2021-03-08 14:03:36 -0500

./configure
--prefix=/opt/homebrew/Cellar/ghc/8.10.4/libexec/integer-gmp
--with-pic
--disable-shared
--build=arm_vortex_tempest-apple-darwin20

checking build system type... Invalid configuration `arm_vortex_tempest-apple-darwin20': machine `arm_vortex_tempest-apple' not recognized
configure: error: /bin/sh ./config.sub arm_vortex_tempest-apple-darwin20 failed
```

I think that's a ghc error specifically though. Will keep digging and update this comment with my findings

**Comment by hoylemd** [comment]
Ok, I wasn't able to get it working with brew, but I was able to install from source:

1) install haskell stuff manually (I did the whole platform, but minimal might work too - you need cabal at least) https://www.haskell.org/downloads/
2) clone this repo
3) cd into the repo and do `cabal install`

So there's a workaround for now, but hopefully the homebrew bottle can be restored before long.

**Comment by fharper** [comment]
I'm also on M1 if that can help narrowing down the issue.

**Comment by hoylemd** [comment]
That makes me think the homebrew bottles for hcl & haskell stuff haven't been updated for apple silicon yet.  I'll see if I can find a place to post a request about that.

Hopefully that would resolve this issue, but @koalaman might need to update a homebrew index as well once that's done.

**Comment by silverlyra** [comment]
I just hit this on a brand-new M1 Mac, and did some digging. The Homebrew formula for spellcheck [specifically depends on `ghc@8.8`](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/shellcheck.rb#L18), and [a discussion in homebrew-core](https://github.com/Homebrew/homebrew-core/pull/57892#issuecomment-735851664) ended with “ghc 8.8 may be a lost cause for Apple Silicon.”

If Shellcheck can be compiled under ghc 8.10 or 9, that seems like the path to getting it bottled again for ARM macOS.

**Comment by hoylemd** [comment]
FYI I opened an issue with ghc about it: https://gitlab.haskell.org/ghc/ghc/-/issues/19512. I didn't realize shellcheck was pinned to 8.8 though. that's a complication :(

**Comment by silverlyra** [comment]
Shellcheck is [now built with `ghc`](https://github.com/Homebrew/homebrew-core/pull/73164/files) (i.e., `ghc@8.10`), but ghc still [doesn’t support](https://gitlab.haskell.org/ghc/ghc/-/issues/18664) Apple Silicon. It looks like that work is targeted only for `ghc@9`, too. 😞

@hoylemd I took a look at [ghcup](https://www.haskell.org/ghcup/) from the issue you filed on GHC 🙏, and the instructions for Apple Silicon say to run the installer script with `arch -x86_64 /bin/bash`. Did you end up running ghc under Rosetta 2, and is the shellcheck you built an arm64 binary or x86_64?

**Comment by hoylemd** [comment]
@silverlyra It looks like it turned out intel:

```
➜ file $(which shellcheck)
/Users/hoylemd/.cabal/bin/shellcheck: Mach-O 64-bit executable x86_64
```

**Comment by bhrutledge** [comment]
I was able to `brew install shellcheck` under Rosetta 2, after setting up a Rosetta installation of Homebrew in `/usr/local`, using the instructions at: https://www.wisdomgeek.com/development/installing-intel-based-packages-using-homebrew-on-the-m1-mac/.

```
arch -x86_64 /usr/local/bin/brew install shellcheck
```

**Comment by aduffner** [comment]
You don't need rosetta anymore. GHC has been updated and so can run shellcheck natively.

**Comment by aduffner** [comment]
@koalaman You can close this thread and the other threads:
- [ ] #2229 
- [ ] #2200
