### ISSUE TITLE
New Release, please?

### ISSUE THREAD

**Issue by lorenzo** [koalaman/shellcheck#2173]
Hey, thanks for your great work on Shellcheck 🙂 

I was wondering if you could release a new version soon, as there are many improvements done in the past year that I'm looking forward to getting for github.com/hadolint/hadolint. Is there anything I can do to help with this?

**Comment by avoidik** [comment]
As far I can see you can get latest build artifacts from GitHub pipeline, and DockerHub shellcheck:latest

**Comment by koalaman** [comment]
I've not had anywhere near the amount time that ShellCheck requires or deserves for a while now, but the new build system is finally in place and I'll try to push a new release in the near future.

**Comment by lorenzo** [comment]
Thanks 🙏

**Comment by koalaman** [comment]
0.7.2 is now released
