### ISSUE TITLE
snap: Release v0.7.1 on the stable channel

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [koalaman/shellcheck#2190]
Currently, the stable channel features ShellCheck 0.7.0, which is dated from 2019/8/1.  Suppose that there's no reason to block the 0.7.1 version from promoting I request to release it on the proper channel.

You may do the promotion on the snap's backstage's Releases page: <https://snapcraft.io/shellcheck/releases>.

As the Snap Store's build service is currently not tag-triggered, you may want to hardcode the `source-tag` attribute to force the build system to build the 0.7.1 release, I previously implement a script to work around the problem([Selective-checkout: Check out the tagged release revision if it isn't promoted to the stable channel - doc - snapcraft.io](https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617)) however I doubt it isn't qualified enough to be added to this repo.

**Comment by koalaman** [comment]
Today's 0.7.2 is now tagged as stable.
