### ISSUE TITLE
Add Windows Builds to Github Releases?

### ISSUE THREAD

**Issue by coolaj86** [koalaman/shellcheck#2191]
I'd like to add this to [webinstall.dev](https://webinstall.dev), and we prefer in all possible cases to use official, 1st party builds rather than 3rd party or custom builds.

You have Mac and Linux builds right here on Github Releases (and we support Github Releases builds), but you don't have Windows builds.

What would need to happen to get official Windows builds available?

**Comment by koalaman** [comment]
The official Windows build is available in the `.zip` file on each release. It did not seem necessary to label it "Windows" since only Windows customarily uses `.zip` files for software distribution.

**Comment by coolaj86** [comment]
Ah, I assumed it was source code as typically that's made available in tar.gz and .zip without other identifiers.

Would you consider adding the distro and arch to Windows builds? I can write some custom checks for shellcheck, but it would be nice to have the explicit info.

And I don't know if Haskell will support it anytime soon, but Windows 10 has been running happily on ARM for years (which I'm sure will get a lot of attention soon as things like Parallels and such switch over to Windows 10 ARM for the M1, etc)

Sidenote: Did you know that Windows 10 has always shipped with BSD tar.exe out of the box? And unlike GNU tar, BSD tar also opens zip files, which made supporting windows much less frustrating that I had expected.

Thanks for the reply. Cheers. :D

**Comment by koalaman** [comment]
I agree that it's not necessarily ideal, especially not with ARM on the horizon, but for now I'll leave it the way it is to avoid unnecessarily breaking existing scripts.

**Comment by nos1609** [comment]
@koalaman  necrobump, but considering the fact of the availability in winget, wouldn't it be better to have official binaries here?
https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/koalaman/shellcheck

Can help with building/testing both binaries for x86_64 and aarch64 on W11 26H1
