### ISSUE TITLE
Debugging log

### ISSUE THREAD

**Issue by 030** [koalaman/shellcheck#2195]
What parameter should be used to get debug logging? I would like to know why one file from branch X fails on shellcheck while the other that resides in branch Y passes.

**Comment by koalaman** [comment]
There's no extended debug logging. To find out why one file triggers while another doesn't, you can check whether the wiki page mentions special cases when the error will or won't be suppressed, browse the source code, ask on #shellcheck@irc.freenode.net, or post here (though I struggle to keep up)

**Comment by TinCanTech** [comment]
Also, some errors are only reported by `shellcheck` on the first occurrence, this can also be a little confusing at first.  But, the point is, `shellcheck` is a first-line of defence. It spots definite errors, probable errors and other likely shell coding problems.  Use it as an indicator, **not** as a last-word. And then investigate any issues highlighted.
