### ISSUE TITLE
Question: can this be used as a library?

### ISSUE THREAD

**Issue by shakyShane** [koalaman/shellcheck#2202]
#### For new checks and feature suggestions
- [ ] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

I'm curious if this tool can be built in a way to expose a C api, therefor allowing other languages to use shellcheck?

**Comment by koalaman** [comment]
A Haskell runtime is probably not the most convenient thing to try to link into a program in a different language.

My suggestion would be to instead invoke ShellCheck as an external tool and parse the output as JSON (or XML) in your language of choice. You can see more on that here:

https://github.com/koalaman/shellcheck/wiki/Integration
