### ISSUE TITLE
Question about SC2031 warning after continue

### ISSUE THREAD

**Issue by stdedos** [koalaman/shellcheck#2208]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2031
- My shellcheck version (`shellcheck --version` or "online"): 
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [x] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

https://github.com/stdedos/Extract/commit/8bae25fb304f67db9256bab143f9f39abd9d0771

Is it reasonable that I have added these disable directives?
```bash
# shellcheck disable=SC2031 # Intentional
```

I was thinking that adding `# shellcheck disable=SC2030` would have been enough, and "it is obvious" that from the `continue` onward I won't change the value after that; only reference it.

PS: Suggestions always welcome

**Comment by koalaman** [comment]
I also had to read it a couple of times to see what the purpose of that assignment was, but yes, you're doing it right and can safely disable it.

You can also consider using prefix assignments to explicitly set the variable just for that function call, which eliminates the need for disable directives entirely:

```
if ! ( cd "${in_dir}" && FORCE_DIR="${in_temp_exp_disable}" extract "$n" ) ; then
```

**Comment by stdedos** [comment]
> You can also consider using prefix assignments to explicitly set the variable just for that function call, which eliminates the need for disable directives entirely:
> 
> ```
> if ! ( cd "${in_dir}" && FORCE_DIR="${in_temp_exp_disable}" extract "$n" ) ; then
> ```

I think I have tried it, only to get `No such executable FORCE_DIR="${in_temp_exp_disable}" found` message 😕

**Comment by stdedos** [comment]
Seems that I have been doing something different!

Cheers 😄
