### ISSUE TITLE
New check: cd without verifying pwd

### ISSUE THREAD

**Issue by mjmeehan** [koalaman/shellcheck#221]
Using cd tends to be perilous in beginners' scripts:
```bash
cd /var/log/oldstuff
for file in `./*`; do
    rm $file
done
```

If /var/log/oldstuff doesn't exist, all files in the pwd of the shell will be removed. In general, cd should be avoided in favor of absolute paths. When it is used, you must check the new pwd matches what you expect.

**Comment by koalaman** [comment]
Definitely a commonly overlooked issue. A check for this has been added in de59c35
