### ISSUE TITLE
Haddock generation failure

### ISSUE THREAD

**Issue by jkachmar** [koalaman/shellcheck#2216]
`shellcheck-0.7.2` Haddock generation fails with the following error:

```
    src/ShellCheck/Analytics.hs:4158:13: error:
        parse error on input ‘-- $var==42’
         |
    4158 |             -- $var==42
         |             ^^^^^^^^^^^
```

**Comment by koalaman** [comment]
I still don't understand why Haddock objects to this comment, but I kludged it by adding some single quotes, and added Haddock generation to the release test suite to make sure future releases will be haddock clean. Thanks!

(There are no useful haddock comments, but that's a separate matter)
