### ISSUE TITLE
SC3044 Doesn't Have a Wiki Page

### ISSUE THREAD

**Issue by Justintime50** [koalaman/shellcheck#2225]
#### For new checks and feature suggestions

https://www.shellcheck.net/wiki/SC3044 does not exist but is suggested as the page to look at for more info on this issue.

#### Here's a snippet or screenshot that shows the problem:

```bash
    if declare -f "$1" > /dev/null
Error:        ^-------------------------^ SC3044: In POSIX sh, 'declare' is undefined.

For more information:
  https://www.shellcheck.net/wiki/SC3044 -- In POSIX sh, 'declare' is undefin...
```

#### Here's what I wanted or expected to see:

When I navigate to https://www.shellcheck.net/wiki/SC3044, there is a page waiting for me with useful info on the error and potential solutions on how to resolve it.

**Comment by koalaman** [comment]
This is a tricky one since most of the functionality is not available across shells. In particular I'm not sure about your case, since `type` has an "unspecified format". I added a page with the alternatives I'm aware of though. Thanks!

**Comment by Justintime50** [comment]
Thank you so much! I've learned so much about shell scripting from the feedback of Shellcheck, this article is very helpful.

**Comment by Justintime50** [comment]
If it's helpful to update the page, I was trying to do something along the lines of `if type -t "$1" > /dev/null` which appears to do the same thing. I'm essentially checking for the existence of a function in the file based on the param passed by the user.

**Comment by brother** [comment]
@Justintime50 the wiki is open for edits ;-)
