### ISSUE TITLE
Sh and bash? 

### ISSUE THREAD

**Issue by omexlu** [koalaman/shellcheck#2231]
Hello, 

Can this script check /bin/sh scripts as well /bin/bash?

Thanks.

**Comment by SuperSandro2000** [comment]
That makes no sense. ``/bin/sh`` is usually not symlinked to bash and support less features.

**Comment by omexlu** [comment]
But is a shell to an can have Syntax errors and I search a tool what can check both :)

**Comment by SuperSandro2000** [comment]
That does not work. bash supports syntaxes which are not supported in sh. Either use sh if you want your script to be compatible with it or use bash.

**Comment by omexlu** [comment]
Many thanks :)
