### ISSUE TITLE
.shellcheckrc does not accept external-sources=true (or no documentation specifies how to do it)

### ISSUE THREAD

**Issue by stdedos** [koalaman/shellcheck#2232]
I have tried:

```
external-sources=true
externals=true
external-sources
```
and none will "suppress"

```
  ^-- SC1091: Not following: shell-utils.sh was not specified as input (see shellcheck -x).
```

**Comment by TinCanTech** [comment]
Have you tried `shellcheck -x your-script.sh` ?

**Comment by stdedos** [comment]
I am not interested in providing a command line argument ad infinitum. 

As it is obvious, I want to set that permanently for my account / the project.

**Comment by TinCanTech** [comment]
https://github.com/koalaman/shellcheck/issues/1818

**Comment by stdedos** [comment]
Duplicate of #1818 it is then 😕

**Comment by TinCanTech** [comment]
That was all I could find.

**Comment by stdedos** [comment]
No, that was useful! Shame it's a one-year-old stale issue (and that my search failed to find it)
