### ISSUE TITLE
TODO: Add title

### ISSUE THREAD

**Issue by fenshu123** [koalaman/shellcheck#2246]
#!/bin/bash
redis_dir="/root/h3cloud-base/images/redis-3.2.4.tar"
mq_dir="/root/h3cloud-base/images/rabbitmq-3.6.5.tar"
node=`kubectl get node |awk '{print $1}' |grep -vi  name `
node1=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==1'`
node2=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==2'`
node3=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==3'`

set -x

#tar -zxvf h3cloud-base-pub-20181128-r4.tar.gz -C  /root
kubectl label node $node  nodeType=controller
kubectl label node $node1 node=node1
kubectl label node $node2 node=node2
kubectl label node $node3 node=node3
for i in $node
  do
#!/bin/bash
redis_dir="/root/h3cloud-base/images/redis-3.2.4.tar"
mq_dir="/root/h3cloud-base/images/rabbitmq-3.6.5.tar"
node=`kubectl get node |awk '{print $1}' |grep -vi  name `
node1=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==1'`
node2=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==2'`
node3=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==3'`

set -x

#tar -zxvf h3cloud-base-pub-20181128-r4.tar.gz -C  /root
kubectl label node $node  nodeType=controller
kubectl label node $node1 node=node1
kubectl label node $node2 node=node2
kubectl label node $node3 node=node3
for i in $node
  do
    scp $redis_dir $mq_dir root@$i:/root/
    echo $i
  done

function install_mq()
{
  ansible all -m shell -a  'docker load -i /root/rabbitmq-3.6.5.tar'
  sh /root/h3cloud-base/scripts/prepare_rabbitmq_cluster.sh
  sh /root/h3cloud-base/scripts/post_rabbitmq_cluster.sh
  sleep 5
  for i in `kubectl get pod |grep rabbit|awk '{print $1}'`
    do
      kubectl exec -it $i rabbitmq-plugins enable rabbitmq_management
      echo $i
    done
}

function install_redis()
{
 ansible all -m shell -a 'docker load -i /root/redis-3.2.4.tar'
 sed -i 's/node-1/$node1/' /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 sed -i 's/node-2/$node2/' /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 sed -i 's/node-3/$node3/' /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 bash /root/h3cloud-base/scripts/redisClusterPreCmd.sh
 bash h3cloud-base/scripts/redisClusterPostCmd.sh
 kubectl apply -f /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 kubectl apply -f /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-service.yaml
}

install_mq
install_redis#!/bin/bash
redis_dir="/root/h3cloud-base/images/redis-3.2.4.tar"
mq_dir="/root/h3cloud-base/images/rabbitmq-3.6.5.tar"
node=`kubectl get node |awk '{print $1}' |grep -vi  name `
node1=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==1'`
node2=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==2'`
node3=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==3'`

set -x

#tar -zxvf h3cloud-base-pub-20181128-r4.tar.gz -C  /root
kubectl label node $node  nodeType=controller
kubectl label node $node1 node=node1
kubectl label node $node2 node=node2
kubectl label node $node3 node=node3
for i in $node
  do
#!/bin/bash
redis_dir="/root/h3cloud-base/images/redis-3.2.4.tar"
mq_dir="/root/h3cloud-base/images/rabbitmq-3.6.5.tar"
node=`kubectl get node |awk '{print $1}' |grep -vi  name `
node1=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==1'`
node2=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==2'`
node3=`kubectl get node |awk '{print $1}' |grep -vi  name | awk 'NR==3'`

set -x

#tar -zxvf h3cloud-base-pub-20181128-r4.tar.gz -C  /root
kubectl label node $node  nodeType=controller
kubectl label node $node1 node=node1
kubectl label node $node2 node=node2
kubectl label node $node3 node=node3
for i in $node
  do
    scp $redis_dir $mq_dir root@$i:/root/
    echo $i
  done

function install_mq()
{
  ansible all -m shell -a  'docker load -i /root/rabbitmq-3.6.5.tar'
  sh /root/h3cloud-base/scripts/prepare_rabbitmq_cluster.sh
  sh /root/h3cloud-base/scripts/post_rabbitmq_cluster.sh
  sleep 5
  for i in `kubectl get pod |grep rabbit|awk '{print $1}'`
    do
      kubectl exec -it $i rabbitmq-plugins enable rabbitmq_management
      echo $i
    done
}

function install_redis()
{
 ansible all -m shell -a 'docker load -i /root/redis-3.2.4.tar'
 sed -i 's/node-1/$node1/' /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 sed -i 's/node-2/$node2/' /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 sed -i 's/node-3/$node3/' /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 bash /root/h3cloud-base/scripts/redisClusterPreCmd.sh
 bash h3cloud-base/scripts/redisClusterPostCmd.sh
 kubectl apply -f /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-rc.yaml
 kubectl apply -f /root/h3cloud-base/yaml/confFile-cluster/redis-cluster-service.yaml
}

install_mq
install_redis

**Comment by TinCanTech** [comment]
I believe you can edit and even delete your post, if it was a mistake.
