### ISSUE TITLE
Possible vandalism on wiki _Footer page?

### ISSUE THREAD

**Issue by grantwwu** [koalaman/shellcheck#2259]
The wiki footer now appears to have some weird shell script that's unrelated. It's not entirely clear if the user responsible, https://github.com/Ryan60144 is a real person.

See

https://github.com/koalaman/shellcheck/wiki/_Footer/_history

This is visible on every error page, see https://github.com/koalaman/shellcheck/wiki/SC2162

**Comment by TinCanTech** [comment]
Looks like a noob exposing themself.

The wiki is open to editing, so _random edits_ can be easily recovered.

**Comment by koalaman** [comment]
I've deleted it. Thanks for the notification!
