### ISSUE TITLE
Option --color=auto should check 'dump' & 'unknown' terminals

### ISSUE THREAD

**Issue by return42** [koalaman/shellcheck#2260]
There are use cases where the conditions of `ColorAuto`:

https://github.com/koalaman/shellcheck/blob/163b2f12e2076a643e744774c8408370655bfc09/src/ShellCheck/Formatter/Format.hs#L71-L79

is not enough. E.g. when you run shellcheck in a _dump_ or _unknown_ terminal which is the case in emacs and other integrations. 

Colors should not active when the environment variable `$TERM` is `dump` or `unknow`.

**Comment by koalaman** [comment]
I wasn't able to find anything about "dump" or "unknown", but setting `TERM` to `dumb` or having it unset or empty will now correctly disable colors (in lieu of a full terminfo lookup). Thanks!
