### ISSUE TITLE
SC3004 Not added

### ISSUE THREAD

**Issue by parsharma** [koalaman/shellcheck#2276]
SC3004: In POSIX sh, $".." is undefined
 The doc is not added yet.

**Comment by TinCanTech** [comment]
Please add your edits:
https://github.com/koalaman/shellcheck/wiki/SC3004

**Comment by koalaman** [comment]
I'm not too familiar with this functionality, but I have filled in the wiki page with a suggestion to invoke `gettext` if it exists or use the string directly if it doesn't. Thanks!
