### ISSUE TITLE
Add SC3011

### ISSUE THREAD

**Issue by Billy02357** [koalaman/shellcheck#2278]
My code:
`bc -l <<< "$first*10^$second"`
Shellcheck:
`SC3011: In POSIX sh, here-strings are undefined.`

What would be the correct code?
Please consider adding it to the wiki.
Thanks in advance :^)

**Comment by TinCanTech** [comment]
Add a `shebang` to your script.
eg: On the very first line `#!/bin/bash`

**Comment by Billy02357** [comment]
The thing is i want to make it POSIX
its already `#!/bin/sh`

**Comment by Billy02357** [comment]
I'm asking for the correct POSIX code that is equivalent to what i wrote

**Comment by TinCanTech** [comment]
There is no POSIX version of what you want, that's why it is `undefined` .. :eject_button:

**Comment by Billy02357** [comment]
What I mean is what's the way of obtaining the same result in a POSIX way?

**Comment by TinCanTech** [comment]
Sorry, this is the `shellcheck` issues list not a POSIX code library.

If you find something useful then you can always edit the wiki page yourself.

**Comment by matthewpersico** [comment]
> What I mean is what's the way of obtaining the same result in a POSIX way?

There is no way. You cannot do it. When using `sh`, your shell drops back to the original implementation of Bourne shell and this functionality was not defined when that shell was written. Either change your code or use bash.
