### ISSUE TITLE
Logo in `svg` or in higher quality than the `favicon.ico`

### ISSUE THREAD

**Issue by felipecrs** [koalaman/shellcheck#2293]
I want to add a social preview for https://github.com/vscode-shellcheck/vscode-shellcheck, but the only version of the logo I could find is:

https://github.com/koalaman/shellcheck.net/raw/master/favicon.ico
![icon](https://github.com/koalaman/shellcheck.net/raw/master/favicon.ico)

Any chance you have the `svg` version (and willing to provide of course), or another with higher quality?

**Comment by koalaman** [comment]
Unfortunately this is the only version currently available of this masterpiece. I just drew it up in Gimp long ago to get rid of the default favicon icon. Contributions are welcome ^^

**Comment by felipecrs** [comment]
Hahaha, that's fine. Unfortunately, I have zero skills with such kind of thing.

**Comment by carlocorradini** [comment]
Any update?
Same situation [here](https://github.com/vscode-icons/vscode-icons/issues/2881) 😥

**Comment by koalaman** [comment]
A vector graphic logo is now available: https://github.com/koalaman/shellcheck/blob/master/doc/shellcheck_logo.svg

Feel free to use it wherever you refer to ShellCheck.
