### ISSUE TITLE
Check replacing characters in valiable

### ISSUE THREAD

**Issue by massongit** [koalaman/shellcheck#2294]
#### For bugs
```sh
#!/bin/bash

c="aaaabbbb"
echo "${c##b/a}" # Correct: echo "${c//b/a}"
```

If we want to replace `b` to `a` in valiable `${c}`, we write `${c//b/a}`.
If we mistake this for `${c##b/a}`, `shellcheck` is not pointed out.

#### Here's what shellcheck currently says:
Check at https://www.shellcheck.net/ :

```shell
$ shellcheck myscript
No issues detected!

$
```

#### Here's what I wanted or expected to see:
I want `shellcheck` to say `${c##b/a} is not corect.` or `${c##b/a} is not correct. You may replace ${c//b/a}.`.

**Comment by koalaman** [comment]
I see what you mean, though how would ShellCheck know that you didn't want `${c##b/a}`? This is valid and useful code when you want to strip a directory prefix for example:

```
c="b/a/file.txt"
echo "${c##b/a}" # /file.txt
echo "${c//b/a}" # a/a/file.txt
```

**Comment by massongit** [comment]
I didn't consider that case.
Since it seems difficult to distinguish from the case where `${c##b/a}` is used intentionally, so I will close this Issue.
