### ISSUE TITLE
Warn about possibly dangerous rm commands

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#23]
Consider:
foo=$(something)
rm -r "/usr/$foo"

The assignment could fail due to program errors or ulimit, and rm would then delete /usr/ 

Is there a way to warn about these things that's useful and not full of false positives?

**Comment by HairyFotr** [comment]
The rm -rf / bug in Steam for Linux is making the news these days.

Shellcheck doesn't detect it. Here's a link to the line: https://github.com/indrora/steam_latest/blob/05e3d6efa60af71e11098bf7dd973828604354ce/scripts/steam.sh#L352
