### ISSUE TITLE
SC2140

### ISSUE THREAD

**Issue by rieje** [koalaman/shellcheck#2334]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"):  0.7.2
- [X] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)

```
    #!/usr/bin/env bash

      if [[ -n "${!varname}" ]]; then
        declare -g "$varname"="${!varname}
${line}"
      else
        # If `varname` empty, set it (prevent empty line)
        declare -g "$varname"="$line"
      fi


```

#### Here's what shellcheck currently says:

        declare -g $varname="${!varname}
                   ^------^ SC2086: Double quote to prevent globbing and word splitting.

        Did you mean:
                   declare -g "$varname"="${!varname}

    For more information:
      https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

#### Here's what I wanted or expected to see:

No errors. Or an entry under "Exception" mentioning that user might intend to define a variable to include a multiline string.

**Comment by koalaman** [comment]
The suggestions do not correspond to the code, so I'll assume you meant that this is the current output:

```
        declare -g "$varname"="${!varname}
                             ^-- SC2140: Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?
```

ShellCheck is right in that the inner quotes don't serve a purpose, and that `declare -g "$varname=${!varname}..` would do the same thing but shorter. However, to a human, it's clearly not unintentional and instead a stylistic choice.

The suggestion has been suppressed when the trapped string is `=`, `/` or `:` which appeared to be the most common cases. Thanks!
