### ISSUE TITLE
Cannot Follow DevGuide on POP_OS

### ISSUE THREAD

**Issue by JamesMConroy** [koalaman/shellcheck#2337]
When I try to run the parser with `ghci` the process fails when compiling the first package.

#### Here's a snippet or screenshot that shows the problem:

```sh
cabal build -v
this build was affected by the following (project) config files:
- /home/james/repos/shellcheck/cabal.project.local
Up to date
creating /home/james/repos/shellcheck/dist-newstyle/build
creating /home/james/repos/shellcheck/dist-newstyle/tmp
cd src
ghci ShellCheck/Parser.hs
GHCi, version 8.8.4: https://www.haskell.org/ghc/  :? for help
[1 of 6] Compiling ShellCheck.Regex ( ShellCheck/Regex.hs, interpreted )

ShellCheck/Regex.hs:28:1: error:
    Could not find module ‘Text.Regex.TDFA’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
28 | import Text.Regex.TDFA
   | ^^^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.

```
#### Versions

OS:

`Linux pop-os 5.13.0-7614-generic #14~1631647151~21.04~930e87c-Ubuntu SMP Fri Sep 17 00:24:58 UTC  x86_64 x86_64 x86_64 GNU/Linux`

Cabal:

```
cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.1.0 of the Cabal library
```

I'm not that familiar with cabal or haskell, so I'm sure there's something I'm missing.

**Comment by koalaman** [comment]
This is something that changed in `cabal` at some point and I don't fully understand it. Can you try `cabal repl` followed by `:load src/ShellCheck/Parser.hs`?

**Comment by JamesMConroy** [comment]
That seems to work. I will update the wiki accordingly.

**Comment by JamesMConroy** [comment]
DevGuide updated.
