### ISSUE TITLE
#!/bin/bash echo "enter file"; read file if [ -f file ];  then  echo "file exist";  else  echo "not exist";  exit | ; fi

### ISSUE THREAD

**Issue by vaiju02** [koalaman/shellcheck#2340]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [ ] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [ ] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [ ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/your/interpreter
your script here

```

**Comment by brother** [comment]
I see code in the title but it's not really enough to act on. It's possible to reopen if the issue body get updated in a meaningful way.
