### ISSUE TITLE
What is the syntax of the `.shellcheckrc`?

### ISSUE THREAD

**Issue by felipecrs** [koalaman/shellcheck#2355]
Hi,

I'm adjusting the VS Code extension to contribute the correct syntax for the `.shellcheckrc` file. It's important, because since VS Code 1.60 it tries to infer the syntax of a file automatically when it doesn't know and often [it detects it as a `shellscript`, causing a lot of mess](https://github.com/vscode-shellcheck/vscode-shellcheck/issues/350).

The safest option is of course `plaintext`:

![image](https://user-images.githubusercontent.com/29582865/136815753-978794d7-6550-475c-adb3-428a9b9a4099.png)

But there is also `.ini`, which seems to works well:
![image](https://user-images.githubusercontent.com/29582865/136815533-a2c1b0d2-f815-4350-8ea3-d81a9f1e57c8.png)

`.properties` also does:
![image](https://user-images.githubusercontent.com/29582865/136815635-eb409fab-42d4-4452-9fa3-072773bcda3f.png)

What do you think?

References https://github.com/vscode-shellcheck/vscode-shellcheck/pull/351

**Comment by koalaman** [comment]
It's not a standard format, it's just `# shellcheck` directives but without the leading `# shellcheck`. Is there an option for `.env` files? They're probably the closest thing since they use `key=value` pairs with `#` for comments.

**Comment by koalaman** [comment]
I guess `dotenv` is something unrelated then. Is there anything that supports `/etc/environment` type files?

If not, plaintext seems like the safer option.

**Comment by felipecrs** [comment]
I started to implement syntax highlight for the `shellcheckrc` at https://github.com/vscode-shellcheck/vscode-shellcheck/pull/351. I would appreciate if you have any feedback, as I'm not aware of all the possibilities the `shellcheckrc` could have.
