### ISSUE TITLE
Add `cat <<EOF` exception to `check-extra-masked-returns`

### ISSUE THREAD

**Issue by felipecrs** [koalaman/shellcheck#2359]
As suggested by @DoxasticFox at [this comment](https://github.com/koalaman/shellcheck/issues/2338#issuecomment-946881546), this issue is to discuss if we should add this known exception or not.

I believe it's reasonable: `cat` with a heredoc will never fail, or at least I can't think of when it would fail.

**Comment by koalaman** [comment]
Any command can fail with the right (or wrong) ulimit, though it's not unreasonable to ignore that possibility. The more likely failure in this case is if the shell implements heredocs via files and the tmpdir is out of space: 

    bash: line 1: cannot create temp file for here-document: No space left on device

**Comment by felipecrs** [comment]
Fair enough.
