### ISSUE TITLE
Possible Bug: Rule SC2312 flags scripts even though pipefail option used

### ISSUE THREAD

**Issue by robert914** [koalaman/shellcheck#2368]
#### For bugs
- Rule Id (if any, e.g. SC1000): `SC2312`
- My shellcheck version (`shellcheck --version` or "online"): 0.8.0
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [x] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit
Problem does not happen on `https://www.shellcheck.net/` for some reason, and there's no way to tell what version it's running.

#### Here's a snippet or screenshot that shows the problem:

```bash

#!/usr/bin/env bash
set -ueo pipefail

while IFS="" read -r line; do
    echo "${line}"
done < <(env | grep -E "^(USER|HOME|PATH|TERM)" | sort)

exit 0

```

#### Here's what shellcheck currently says:

```bash
❯ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.8.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
❯ cat .shellcheckrc
# ShellCheck
# Enable all optional checks
enable=all
# Disable checking of `source` commands
disable=SC1090,SC1091
❯ shellcheck foo.sh

In foo.sh line 6:
done < <(env | grep -E "^(USER|HOME|PATH|TERM)" | sort)
         ^-^ SC2312 (info): Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).
               ^-- SC2312 (info): Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).
                                                  ^--^ SC2312 (info): Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).

For more information:
  https://www.shellcheck.net/wiki/SC2312 -- Consider invoking this command se...
```

#### Here's what I wanted or expected to see:

The fact that I have `-o pipefail` defined means anything in a pipe chain *will* cause an error and is *not* masked as the the `SC2312` check indicates. So I think that `shellcheck` should properly detect `pipefail` and appropriately disable this check when the `pipefail` option has been enabled. Otherwise, I have to manually add `disable=SC2312` to each script that has `pipefail` defined even though it's unnecessary in practice.

 Is this possible? Thanks!

**Comment by robert914** [comment]
Actually, there is something weird with this `SC2312` check. If I have the following script instead (which is one of the examples for rule https://github.com/koalaman/shellcheck/wiki/SC2207):
```bash
#!/usr/bin/env bash
array=()
while IFS='' read -r line; do array+=("${line}"); done < <(env)
exit 0
```

The `shellcheck` result for 0.8.0 is:
```bash
❯ shellcheck foo.sh

In foo.sh line 4:
while IFS='' read -r line; do array+=("${line}"); done < <(env)
                                                           ^-^ SC2312 (info): Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).

For more information:
  https://www.shellcheck.net/wiki/SC2312 -- Consider invoking this command se...
```

I don't understand why this would be suggested, as it's not needed.

**Comment by koalaman** [comment]
ShellCheck is right, pipefail does not affect process substitutions. In something like `cat <(exit 1)`, the failure in the process substitution is quietly suppressed.

If you invoke it separately, e.g. with

```
env | grep -E "^(USER|HOME|PATH|TERM)" | sort > tmp
while IFS='' read -r line; do array+=("${line}"); done < tmp
```

then `set -e` will trigger if `env` fails, and you also won't get a warning from the optional `check-extra-masked-returns`

PS: `enable=all` is not like `-Wall`. It's really meant for discovery, and may enable subjective or mutually conflicting checks.

**Comment by robert914** [comment]
@koalaman Thanks for the information and explanation. I may need to not use `enable=all` and be more selective about the additional checks I want. Thanks!
