### ISSUE TITLE
Missing Linux AArch64 wheels on PyPI

### ISSUE THREAD

**Issue by odidev** [koalaman/shellcheck#2394]
#### For bugs
Installing shellcheck via pip on Linux AArch64 machine, pulls x86_64 specific binary.

#### Here's what I wanted or expected to see:
Linux AArch64 wheels must be deployed and pip should pull and install correct wheel package.

**Comment by koalaman** [comment]
I don't have any control over the `shellcheck` pip package and you're already talking to what appears to be the maintainer of it, so I'll close this issue in this repo
