### ISSUE TITLE
321321

### ISSUE THREAD

**Issue by 15942392309** [koalaman/shellcheck#2395]
#date:202109 author:yangrz 
#zcvPf p大写，代表的是相对路径

#!/bin/bash
time=`date +%Y%m%d -d "30 day ago""`
echo $time
list=`find /home/venus/yangrz -maxdepth 1 -name "${time}*.txt"`
for var in $list
do
    echo $var
    tar -zcvPf $var.tar.gz $var

done32131

**Comment by brother** [comment]
No relevant content. Closing.
