### ISSUE TITLE
shellcheck needs to ignore heredocs

### ISSUE THREAD

**Issue by matthewpersico** [koalaman/shellcheck#2409]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2154, SC2154, SC2154
- My shellcheck version (`shellcheck --version` or 'online'): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### For new checks and feature suggestions
- [x] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [ ] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/usr/bin/env bash

# register

# Wrapper for dpkg-register

declare datafile
datafile=$(realpath "$(realpath "$(dirname "$0")")/../data/REGISTER.data")

if [[ ! -s $datafile ]]; then
    cat <<EOD > "$datafile"
repo='--dev-repo bbgithub:foo/bar'
dq='--drqs-group GROUP#'
c='--contact UUID --contact UUID'
b='--branch BRANCH'
dr='--dry-run'
pno='--pkg-name-override notbar'
extra="$b $dr $pno"
EOD
    fi

if x-is-available; then
    xterm -geometry "+${XTERMGEO_X}+${XTERMGEO_Y}" -e bash  -c "vi $datafile"
else
    vi "$datafile"
fi

# shellcheck disable=SC1090
. "$datafile"


# shellcheck disable=SC2154 ## variables are sourced in via $datafile
resp=$(yesno "dpkg-register $repo $dq $c $extra" n)
if [ "$resp" = 'y' ]
then
    set -o pipefail
    # shellcheck disable=SC2086 #https://github.com/koalaman/shellcheck/wiki/SC2086
    dpkg-register $repo $dq $c $extra
    exit $?
fi

```

#### Here's what shellcheck currently says:
```
Line 18	SC2154: b is referenced but not assigned.
Line 18	SC2154: dr is referenced but not assigned.
Line 18	SC2154: pno is referenced but not assigned.
```
#### Here's what I wanted or expected to see:

Nothing. First of all, it's inside a heredoc and nothing says that the heredoc is shell - could be anything. shellcheck should not be syntax checking in a heredoc. Second, it's wrong; see lines 15, 16 and 17,

**Comment by TinCanTech** [comment]
Does this help:
```
-       cat <<EOD > "$datafile"
+       cat <<'EOD' > "$datafile"
```

**Comment by koalaman** [comment]
ShellCheck is right. The variables in the here doc are being expanded, and none of them are assigned, so your text file will end up with empty strings in their place.

To avoid this, quote the here doc delimiter like TinCanTech says. This will cause the shell not to expand values, and instead write them verbatim.
