### ISSUE TITLE
static link does not point to latest version

### ISSUE THREAD

**Issue by loter** [koalaman/shellcheck#2410]
In doc it says static stable link is:
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz

when this is installed we're getting version 0.7.2 and not 0.8.0

**Comment by koalaman** [comment]
Huh, I'm getting 0.8.0 from this URL. Can you please try it from a different machine in case you have some proxy/cache serving you an old version?

**Comment by koalaman** [comment]
Please reopen if you're still seeing this issue
