### ISSUE TITLE
Fatal exception ASTLib.hs:(248,17)-(252,40): Non-exhaustive patterns in case

### ISSUE THREAD

**Issue by CervEdin** [koalaman/shellcheck#2418]
#### For bugs
- src/ShellCheck/ASTLib.hs:(248,17)-(252,40): Non-exhaustive patterns in case
- 0.7.0
- [✔] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:
```
#!/bin/bash

tr '\0' $'\x1' < /tmp/$$.output |  cut -d $'\x1' -f 2
```

#### Here's what shellcheck currently says:

```
shellcheck: src/ShellCheck/ASTLib.hs:(248,17)-(252,40): Non-exhaustive patterns in case
```

on spellcheck.net
```
^-- Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally.
```

#### Here's what I wanted or expected to see:

Not an expection

**Comment by CervEdin** [comment]
It's enough with
```
tr '\0' $'\x1'
```
to reproduce

**Comment by CervEdin** [comment]
Seems the problem is with
```sh
$'\x1'
```

**Comment by TinCanTech** [comment]
`:spellcheck:` needs an avatar :balloon:

**Comment by koalaman** [comment]
This was a problem with ShellCheck trying to match `\xNN` but running out of letters. This has now been fixed (along with multiple other correctness improvements like `\x1z`).  Affected versions can write out `$'\x01'` to avoid a crash.

Great catch, thanks!

**Comment by CervEdin** [comment]
No worries!
Great tool btw
I found it by running it shellcheck on my bash_history
🤖
