### ISSUE TITLE
Can't run shellcheck in RHEL 6.10 (different shellcheck versions tested) 

### ISSUE THREAD

**Issue by smtdev** [koalaman/shellcheck#2429]
#### For bugs
- Rule Id (if any, e.g. SC1000): none
- My shellcheck version (`shellcheck --version` or "online"): I can't check it, as it outputs an error when execute the binary, no matter if I add parameters or not (see below).
- [X] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [ ] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [X] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

![image](https://user-images.githubusercontent.com/2834625/148218715-01bb4097-f11b-4c62-b627-7a1d86600528.png)

#### Here's what shellcheck currently says:

The error is `shellcheck: encountered an exception while trying to report an exception.One possible reason for this is that we failed while trying to encode an error message. Check that your locale is configured properly.` 

I tried t with old versions (0.4.7, 0.4.6), as from 0.5.0 to stable ones it outputs `FATAL: kernel too old`.

![image](https://user-images.githubusercontent.com/2834625/148219557-254f8b93-9bf5-4565-84a8-084c47a19d7c.png)

#### Here's what I wanted or expected to see:

Current version to be printed is expected.

**Comment by koalaman** [comment]
Can you give it a try with the latest binary https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz ? It's linked against musl instead of glibc, and therefore doesn't have this particular restriction (but may have some others).
