### ISSUE TITLE
Enhancement: Undefined variables

### ISSUE THREAD

**Issue by mietek** [koalaman/shellcheck#243]
I am attempting to declare every variable before use, with `local`,`declare`, or `export`.

It would be fantastic if ShellCheck could flag any use of undeclared variables, as these are likely to be typos.

**Comment by mietek** [comment]
Looks like https://github.com/koalaman/shellcheck/commit/63188282e935f9c1628fa62134bc46840ba7bad2 sort of adds this?

**Comment by koalaman** [comment]
It requires an assignment but not necessarily a declaration.

**Comment by nexushoratio** [comment]
Hah!  10 years later, and I was explicitly looking to see if there was already a FR for this.

**Comment by nexushoratio** [comment]
Oh, I do use this snippet in my personal `bl.sh` (bash library)

```shell
# Bash creates some shell vars after the first pipeline is performed
# shellcheck disable=2312
bl::_noop() {
  : | :
}

bl::_before() {
  before_globals=$(mktemp)
  after_globals=$(mktemp)
  new_globals=$(mktemp)
  compgen -A variable > "${before_globals}"
  trap bl::_after EXIT
}

bl::_after() {
  compgen -A variable > "${after_globals}"
  diff -u "${before_globals}" "${after_globals}" > "${new_globals}" || {
    echo 'Leaked global variables:'
    cat "${new_globals}"
  }
}

bl::main() {
  bl::_noop
  bl::_before
  main "$@"
}
```

With my scripts having something like:
```shell
source "$(dirname "$0")/bl.sh"

main() {
 :
}

bl::main "$@"
```

I just need to remember to actually use it more often....
