### ISSUE TITLE
Shellcheck asks for GLIBC_2.34 since arch update

### ISSUE THREAD

**Issue by zakissimo** [koalaman/shellcheck#2447]
#### Here's what shellcheck currently says:
`shellcheck: /usr/lib/libc.so.6: version 'GLIBC_2.34' not found (required by shellcheck)`

Last version installable on arch is 2.33-5 :
https://security.archlinux.org/package/glibc

**Comment by Phundrak** [comment]
The package [`shellcheck-bin`](https://aur.archlinux.org/packages/shellcheck-bin) from the AUR seems to work correctly. However, I get the following error trying to build `shellcheck-git`.
```
Setup.hs:6:3: error:
    Module ‘Distribution.Simple’ does not export ‘UserHooks(preSDist)’
  |
6 |   UserHooks ( preSDist ),
  |   ^^^
```
See the comments of [`shellcheck-git`](https://aur.archlinux.org/packages/shellcheck-git)

**Comment by koalaman** [comment]
The distro packages including Arch are kindly maintained downstream by generous volunteers, and I don't have any control over them. Please file a bug with the distro, I'm sure they'll take care of it.
