### ISSUE TITLE
Add Exception for SC2012 (use find instead of ls) for AIX

### ISSUE THREAD

**Issue by bmarwell** [koalaman/shellcheck#2449]
#### For bugs
- Rule Id (if any, e.g. SC1000):  SC2012
- My shellcheck version (`shellcheck --version` or "online"): any
- [X] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [X] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [X] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [X] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/sh
latest=$(ls -1d "${SOFTDIR}/myapp"* 2>/dev/null | tail -1)
```

#### Here's what shellcheck currently says:

Use find instead of ls to better handle non-alphanumeric filenames.
See SC2012.

#### Here's what I wanted or expected to see:

Use find instead of ls to better handle non-alphanumeric filenames except on AIX.
See SC2012.

#### Update the wiki page

Rationale: -maxdepth is not a valid option on AIX's `find` implementation.

```
# find . -maxdepth 1 -name "test*"
find: 0652-017 -maxdepth is not a valid option.

# uname
AIX

# which find
/usr/bin/find
```

**Comment by koalaman** [comment]
The wiki has been updated to mention that `-maxdepth` is not POSIX and can be written via `-prune` instead. Thanks!
