### ISSUE TITLE
Needles Binaries Installed

### ISSUE THREAD

**Issue by elibroftw** [koalaman/shellcheck#2470]
I'm on Linux x64 but the extension had still installed the arm, arm64, darwin, and win32 binaries!

#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [x] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x[ I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

`ls -R /home/maste/.vscode/extensions/timonwong.shellcheck-0.18.9`

Will show binaries for Windows, Mac, and arm even though I'm on Linux x64

#### Here's what I wanted or expected to see:

No binaries except for Linux x64.

**Comment by koalaman** [comment]
This is a third party extension that I have no control over. Please open an issue with this extension instead.

**Comment by elibroftw** [comment]
Ohh I'm sorry about that
