### ISSUE TITLE
shellcheck.net TLS Certificate expired

### ISSUE THREAD

**Issue by willhughes-au** [koalaman/shellcheck#2472]
Not sure if this is the right place to raise this, but the Shellcheck.net Certificate is expired, as of about 5 hours ago from when this ticket was logged. 

Navigating to https://www.shellcheck.net/ gives an expired certificate warning. 

Checking with a third party tool such as Qualys's SSLLabs https://www.ssllabs.com/ssltest/analyze.html?d=www.shellcheck.net

Shows the certificate expired Mon, 21 Mar 2022 21:46:26 UTC (expired 5 hours and 19 minutes ago)   EXPIRED

**Comment by koalaman** [comment]
Oof. It's now updated. Thanks a lot!
