### ISSUE TITLE
Unable to install shellcheck behind a proxy

### ISSUE THREAD

**Issue by AdorianM** [koalaman/shellcheck#2480]
The global-agent package in download.js overrides the proxy settings. This leads to the proxy error `Error: getaddrinfo ENOTFOUND github.com` when calling `node download.js`

**Comment by brother** [comment]
node?
Are you sure that's the only thing you are doing?

**Comment by AdorianM** [comment]
Actually that's what the package is doing. It crashes when trying to run download.js with node.

I found the problem in the meantime. In my dockerfile I had configured http_proxy instead of HTTP_PROXY. Global-agent requires the uppercase version.

**Comment by brother** [comment]
Great to hear that you solved it. Still do not understand where the node line came from, except from this issue there are no mentions of download.js via the search =)
