### ISSUE TITLE
www.shellcheck.net/wiki has invalid syntax, but github.com/koalaman/shellcheck/wiki is fine

### ISSUE THREAD

**Issue by danielhoherd** [koalaman/shellcheck#2516]
### Description

www.shellcheck.net/wiki has invalid syntax, but github.com/koalaman/shellcheck/wiki is fine

#### Correct `[[ ... ]]`

<https://github.com/koalaman/shellcheck/wiki/SC2292>
<img width="1150" alt="Screen Shot 2022-06-08 at 11 20 03 AM" src="https://user-images.githubusercontent.com/1323808/172688861-daab09ab-1426-411b-bbaf-4ad1736f8e18.png">

#### Incorrect `[[ ... ]]`

<https://www.shellcheck.net/wiki/SC2292>
<img width="964" alt="Screen Shot 2022-06-08 at 11 20 30 AM" src="https://user-images.githubusercontent.com/1323808/172688963-617ad81f-3377-45d8-9c97-b7420bc9c9d8.png">

**Comment by koalaman** [comment]
Oof, thanks. This whole mirror was a rushed response to #2487 and included some overly eager sed expressions to translate between GitHub markdown and Pandoc's mardown_github. It should be at least somewhat improved now.
