### ISSUE TITLE
shellcheck.net certificate issue

### ISSUE THREAD

**Issue by mt-empty** [koalaman/shellcheck#2521]
I think the certificate is expired.

https://www.shellcheck.net

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

I tried on Firefox, Chrome and mobile Firefox

**Comment by dirtyharrycallahan** [comment]
Issued On	Monday, March 21, 2022 at 10:23:07 PM
Expires On	Sunday, June 19, 2022 at 10:23:06 PM

**Comment by 0x326** [comment]
Have you considered using [Caddy](https://caddyserver.com/) as an HTTP server? It automatically performs certificate renewals out of the box and might prevent this issue in the future

**Comment by koalaman** [comment]
Oops, thanks! It's now updated.

Unfortunately there are too many Apache specific configurations to change servers, but I'm trying a crontab entry to automate it.
