### ISSUE TITLE
SC2129 suggested cmd grouping eats stdout/stderr trap output

### ISSUE THREAD

**Issue by johnalotoski** [koalaman/shellcheck#2522]
Regarding SC2129: https://github.com/koalaman/shellcheck/wiki/SC2129

Suggested grouping of commands to improve performance has the side effect of any stdout and/or stderr messages emitted during a trap exit being swallowed.

If the grouping is not used, trap stdout/stderr messages print as expected.

Perhaps this should be mentioned in the SC2129 page as a side-effect.

Example commits https://github.com/input-output-hk/bitte/pull/156/commits/92905f4039e4fe73621f14e78b3a2c629a5c6961 with trap code of [link](https://github.com/input-output-hk/bitte/blob/master/modules/terraform/tf-options.nix#L191-L238)

**Comment by brother** [comment]
@johnalotoski you are welcome to edit the wiki. sounds seinsible to add something.
