### ISSUE TITLE
SC1071 can't be disabled via RC file

### ISSUE THREAD

**Issue by matatk** [koalaman/shellcheck#2534]
If I have

```rc
disable=SC1071
```

as the contents of my `.shellcheckrc` file, I still get errors if I try to check a zsh script, for example.

However, if I use `shellcheck --exclude 1071` the error _is_ ignored.

This sounds like it might be related to https://github.com/koalaman/shellcheck/issues/1931#issuecomment-623262424

Thanks for this tool; it's great!

**Update:** Forgot to say, I'm using 0.8.0; oops!

**Comment by koalaman** [comment]
It was a similar issue in which directives were not applied until the body of the script. This is now fixed. Thanks!

**Comment by luckman212** [comment]
> _Leaving this here in case it helps someone else..._

I was getting annoyed with the nagging from Sublime too. I didn't realize this bug existed, and was wondering why my `~/.shellcheckrc` file wasn't having any effect on SublimeLinter.

To "fix" this, go to Preferences → Package Settings → SublimeLinter → Settings and then paste the stanza below into your User Settings.

```json
{
  "linters": {
    "shellcheck": {
      "args": [ "--exclude=1071" ]
    }
  }
}
```

**Comment by matatk** [comment]
Thanks for fixing this @koalaman; I built it locally and it's working fine. If/when possible, it'd be great if you could make a new release with this fix included.
