### ISSUE TITLE
Sandbox resource constraints but from 366 and above

### ISSUE THREAD

**Issue by Tarch1** [koalaman/shellcheck#2548]
- My shellcheck version: online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

shebang #!/bin/bash

Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally

I've see a closed issue with the same "problem" but to almost 1000 lines , my script was about 380 and I see when deleting empty line to reach 365 the script works fine.

PS: thanks for your awesome work :)

**Comment by koalaman** [comment]
The resource usage has been improved in 77069f744, and I've bumped the resource limit of the shellcheck.net sandbox. Note that it's primarily for demo purposes, not for production use. It's usually easy to get it running straight in your local editor without any restrictions.

Hopefully GHC 9.6's planned WASM support will render server side sandboxing obsolete.

**Comment by Tarch1** [comment]
It would be a great jump.
Thanks

**Comment by alanhe421** [comment]
> The resource usage has been improved in [77069f7](https://github.com/koalaman/shellcheck/commit/77069f7445681747ff88eaa56b6bd23b596eee99), and I've bumped the resource limit of the shellcheck.net sandbox. Note that it's primarily for demo purposes, not for production use. It's usually easy to get it running straight in your local editor without any restrictions.
> 
> Hopefully GHC 9.6's planned WASM support will render server side sandboxing obsolete.


So, can the latest version of shellcheck be run completely in the client browser?

I want Shellcheck to be a fully client-side service that can be used by web editors such as Monaco editor.

**Comment by koalaman** [comment]
Unfortunately not at this time. I was not able to get a WASM build going last time I tried, but that was a while ago and the landscape may have improved.

**Comment by Zlaojie** [comment]
Excuse me, does Shellcheck have WASM now
