### ISSUE TITLE
Some shellcheck wiki links have no content

### ISSUE THREAD

**Issue by danielhoherd** [koalaman/shellcheck#2572]
Originally I thought all the links were broken, but it looks like I had a bad coincidence of broken links in my code, and also the home link. The home link has no content, and same with SC1085.

#### Here's a snippet or screenshot that shows the problem:

<https://www.shellcheck.net/wiki/Home>
<img width="952" alt="Screen Shot 2022-09-12 at 9 21 46 AM" src="https://user-images.githubusercontent.com/1323808/189665362-16c05160-3f55-4352-ad51-20fdad58b8ec.png">

<https://github.com/koalaman/shellcheck/wiki/SC1085>
<img width="1028" alt="Screen Shot 2022-09-12 at 9 22 24 AM" src="https://user-images.githubusercontent.com/1323808/189665489-903e1c0a-dccc-48d9-beb8-0754749f4274.png">

**Comment by danielhoherd** [comment]
Here's the full list of pages that do not have content:

- https://github.com/koalaman/shellcheck/wiki/SC1027
- https://github.com/koalaman/shellcheck/wiki/SC1043
- https://github.com/koalaman/shellcheck/wiki/SC1055
- https://github.com/koalaman/shellcheck/wiki/SC1057
- https://github.com/koalaman/shellcheck/wiki/SC1059
- https://github.com/koalaman/shellcheck/wiki/SC1063
- https://github.com/koalaman/shellcheck/wiki/SC1076
- https://github.com/koalaman/shellcheck/wiki/SC1080
- https://github.com/koalaman/shellcheck/wiki/SC1092
- https://github.com/koalaman/shellcheck/wiki/SC1137
- https://github.com/koalaman/shellcheck/wiki/SC1138
- https://github.com/koalaman/shellcheck/wiki/SC1144
- https://github.com/koalaman/shellcheck/wiki/SC1145
- https://github.com/koalaman/shellcheck/wiki/SC2042
- https://github.com/koalaman/shellcheck/wiki/SC2075
- https://github.com/koalaman/shellcheck/wiki/SC2083
- https://github.com/koalaman/shellcheck/wiki/SC2118
- https://github.com/koalaman/shellcheck/wiki/SC2127
- https://github.com/koalaman/shellcheck/wiki/SC2265
- https://github.com/koalaman/shellcheck/wiki/SC2266
- https://github.com/koalaman/shellcheck/wiki/SC2306
- https://github.com/koalaman/shellcheck/wiki/SC3007
- https://github.com/koalaman/shellcheck/wiki/SC3008
- https://github.com/koalaman/shellcheck/wiki/SC3011
- https://github.com/koalaman/shellcheck/wiki/SC3016
- https://github.com/koalaman/shellcheck/wiki/SC3029
- https://github.com/koalaman/shellcheck/wiki/SC3032
- https://github.com/koalaman/shellcheck/wiki/SC3033
- https://github.com/koalaman/shellcheck/wiki/SC3036
- https://github.com/koalaman/shellcheck/wiki/SC3041
- https://github.com/koalaman/shellcheck/wiki/SC3042
- https://github.com/koalaman/shellcheck/wiki/SC3051
- https://github.com/koalaman/shellcheck/wiki/SC3052

**Comment by brother** [comment]
The wiki is open for edits and we as a community are welcome to refine it. Not sure if this issue need to be open - it's nice to have the list of pages needed to be written prominently displayed as an open issue though.

**Comment by danielhoherd** [comment]
It would be fine with me if this was just closed as won't fix. I originally thought there was a bigger issue, but after investigation realized there wasn't a big problem.

It's cool to know that the community is welcome to edit the wiki.

**Comment by koalaman** [comment]
All of these are now added. Phew!
