### ISSUE TITLE
Certificate expiry for shellcheck.net

### ISSUE THREAD

**Issue by j0nathontayl0r** [koalaman/shellcheck#2578]
#### For bugs
Certificate expiry for shellcheck.net

#### Here's a snippet or screenshot that shows the problem:

Browser errors for shellcheck.net in all browsers. Looks like LetsEncrypt hasn't automatically renewed the cert. 

#### Here's what I wanted or expected to see:

No certificate errors.

**Comment by rabyj** [comment]
I'm confirming that this still has not been fixed. 

More information available through 3rd party tool [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=www.shellcheck.net).

I've attached my print of the result.
[SSL Server Test_ www.shellcheck.net (Powered by Qualys SSL Labs).pdf](https://github.com/koalaman/shellcheck/files/9601052/SSL.Server.Test_.www.shellcheck.net.Powered.by.Qualys.SSL.Labs.pdf)

**Comment by brother** [comment]
Dupe https://github.com/koalaman/shellcheck.net/issues/23

**Comment by koalaman** [comment]
Blerk, previous automation attempt didn't work and I missed the emails. Should be good now.
