### ISSUE TITLE
False positive with SC2069 (redirecting stderr to a pipe)

### ISSUE THREAD

**Issue by asmeurer** [koalaman/shellcheck#260]
`cmd 2>&1 >/dev/null` gives `The order of the 2>&1 and the redirect matters. The 2>&1 has to be last. [SC2069]`. However, this is intentional, as it's the way to pipe stderr (see http://stackoverflow.com/a/2342841/161801).

**Comment by koalaman** [comment]
Fixed in d10c3b2
