### ISSUE TITLE
SPDX-License-Identifier not recognized

### ISSUE THREAD

**Issue by superbonaci** [koalaman/shellcheck#2654]
Maybe it's not POSIX compliant:
```
$ shellcheck samples.sh

In samples.sh line 1:
# SPDX-License-Identifier: MIT
^-- SC2148 (error): Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
```

**Comment by superbonaci** [comment]
I can't do that, since `env` is not `/usr/bin/env` for all operating systems.

**Comment by austin987** [comment]
You can either:
1) set `#!/bin/sh` as the first line of your script
2) set `# shellcheck shell=sh` as the first line of your script
3) call shellcheck with `shellcheck -s sh samples.sh`

**Comment by superbonaci** [comment]
Not all systems have `sh` in `/bin/sh`

**Comment by brother** [comment]
You need to instruct shellcheck what she’ll you target. There are multiple ways to do that as suggested in this thread. Closing.

**Comment by austin987** [comment]
> Not all systems have `sh` in `/bin/sh`

What system are you referring to?

**Comment by ale5000-git** [comment]
I think `#!/usr/bin/env sh` is the most compatible but there isn't a way that really work on 100% of the systems.

**Comment by superbonaci** [comment]
> > Not all systems have `sh` in `/bin/sh`
> 
> What system are you referring to?

Arch linux uses:
```
$ which -a sh
/usr/bin/sh
```
[Command-line shell (ArchWiki)](https://wiki.archlinux.org/title/Command-line_shell)


The same happens with `env`
, can be in at least 3 different locations, and unfortunately you can't do:
```
#!env bash
```
