### ISSUE TITLE
[snap] Unable to check files outside of home and media

### ISSUE THREAD

**Issue by TriMoon** [koalaman/shellcheck#2666]
Could you please allow us to use it on files outside `/home` and `/media`? :thinking: 
_(Or at least give info on how to remove the current confinement in it's description)_

Because as-is it is useless for me and had to download the prebuild version.
Although that is missing the manpage (https://github.com/koalaman/shellcheck/issues/2665), and is unable to auto-upgrade to new versions using package managers.

**Comment by port19x** [comment]
Can't reproduce (with native install)
![2023-01-16_06-55](https://user-images.githubusercontent.com/82055622/212608129-081ef932-1453-4318-9019-418580e5b628.png)

This confinement must be from snap, which as flatpak has some sort of sandbox and permission system as well iirc.
[source-1](https://github.com/keepassxreboot/keepassxc/issues/585)
[source-2](https://askubuntu.com/questions/1228899/how-to-access-files-outside-of-home-in-snap-apps)

**Comment by TriMoon** [comment]
@porter, please read the topic title, where it startes with **[snap]** for a reason :wink:

**Comment by TriMoon** [comment]
> This is how snap is designed.

Then this program is obviously **not fit** tobe distributed as a snap to begin with...
But ok, i can live with that as long as they keep distributing the prebuild versions and fix #2665
