### ISSUE TITLE
winget

### ISSUE THREAD

**Issue by Zamiell** [koalaman/shellcheck#2691]
Hello,

I am a Windows user wanting to use Shellcheck. In the readme, I see that it says that I should use `chocolatey` or `scoop` to install Shellcheck.

However, the standard way to install packages on Windows is with [`winget`](https://learn.microsoft.com/en-us/windows/package-manager/winget/), which is automatically installed on all Windows computers without having to do anything. For example, to install `git`, all you have to do on a modern Windows computer is to type: `winget install git`

For this reason, `chocolatey` and `scoop` should be considered deprecated.

I tried to run `winget install shellcheck`, but it didn't work, so it looks like you guys don't have a Windows package. Please consider creating one for your Windows users.

**Comment by port19x** [comment]
![2023-02-21_13-29](https://user-images.githubusercontent.com/82055622/220345241-b327813a-2528-4383-b279-b73fd7d3d1ae.png)

I doubt you'll get a winget package anytime soon.
I'd generally recommend scoop over chocolatey if you're choosing between those two

**Comment by koalaman** [comment]
The only upstream packages are the raw binary releases, plus Hackage, Docker and Snap.

All the chocolatey, scoop, pip, brew, and myriad of distro packages are maintained by independent volunteers (thanks, folks!)

**Comment by Okeanos** [comment]
FYI https://github.com/microsoft/winget-pkgs/pull/101322
