### ISSUE TITLE
SC1045 - conflicts with commands trying to run something in the background

### ISSUE THREAD

**Issue by osher** [koalaman/shellcheck#2708]
concerning:
https://github.com/koalaman/shellcheck/wiki/SC1045

this rule indiscrimentally rejects commands that I try to run in background.

Example:  consider this pseudo script:
```
# run my-service in backgorund
./my-service --port 3333 &;

sleep 2; 

# run a test against my-service
curl http://localhst:3333/test-this-or-that
```

**Comment by brother** [comment]
Either ignore the waring with a directive or remove the semicolons.

**Comment by brackendawson** [comment]
No, the check is correct, here's an example:

problematic:
```
nc -l 1337 &;
sleep 2;
nc -zv localhost 1337
```
correct:
```
nc -l 1337 &
sleep 2
nc -zv localhost 1337
```
Just remove the semicolons

**Comment by osher** [comment]
hmm. I stand corrected...
