### ISSUE TITLE
Sandbox resource constraints exceeded

### ISSUE THREAD

**Issue by MarkyMarkDE** [koalaman/shellcheck#2711]
if i paste some code, the error "#! /bin/sh Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally." come's up and i don't really know why?
So large isn't my code ... is there somehow a limit?

**Comment by brother** [comment]
in shellcheck.net? 
please file the error at that tracker then. https://github.com/koalaman/shellcheck.net

**Comment by MarkyMarkDE** [comment]
> in shellcheck.net? please file the error at that tracker then. https://github.com/koalaman/shellcheck.net

done
https://github.com/koalaman/shellcheck.net/issues/29

**Comment by brother** [comment]
it's  a command line tool. 
open a terminal
`$ shellcheck file`

**Comment by brother** [comment]
then it's probably well written. if you echo $? it will tell you either 0 (all fine) or 1(should have shown something because that's an unsuccessful execution),

Try adding something broken to the file to verify your observations.
