### ISSUE TITLE
Release binaries for darwin-aarch64

### ISSUE THREAD

**Issue by katexochen** [koalaman/shellcheck#2714]
Currently, only there are no binaries released for MacOS with arm arch (M1/M2), see related issue https://github.com/koalaman/shellcheck/issues/2680.

https://github.com/tpoechtrager/osxcross is currently used to build the darwin_x86_64 binary, the project also supports building for darwin_aarch64. Would be great if anyone could add this to the pipeline, thanks!

**Comment by reegnz** [comment]
AFAICT to get aarch64 builds going, we'd first need to change the osxcross docker image to a maintained one for the amd64 build.
This one seems to be maintained properly: [hub.docker.com/r/crazymax/osxcross/tags](https://hub.docker.com/r/crazymax/osxcross/tags)
Once that is tested with amd64 builds, we can probably do a new Dockerfile for the aarch64 too.

**Comment by koalaman** [comment]
I came across [macOS-cross-compiler – Compile binaries for macOS on Linux](https://github.com/shepherdjerred/macos-cross-compiler) on Hacker News. It took all weekend, but I managed to build a version of GHC that appears to successfully produce a macOS arm64 binary in 8c4c112c2504.

Unfortunately I don't have a macOS system to test it on. Can anyone tell me if this runs at all:  https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.darwin.aarch64.tar.xz

**Comment by b4nst** [comment]
Confirm it does work on M2 chip, at least on `14.2.1`

**Comment by reegnz** [comment]
@koalaman Also confirmed, that binary is properly working on an M1.

**Comment by koalaman** [comment]
I'm glad to hear it's working, thanks! The binary is huge (59MB) because A. stripping it breaks the linker default signature (and there's no `codesign` utility in the Docker image), and B. it can't use `-split-sections` + `ld -dead_strip` because the tooling only allows 16 character section names and the only compatible version of GHC I was able to build uses more.

Hopefully this will improve in the future.

**Comment by solsson** [comment]
Works. @koalaman Will you tag a new release in the near future? It's useful to have version-pinned binaries to download.

**Comment by reegnz** [comment]
> Hopefully this will improve in the future.
The homebrew built binary is 66MB, so it's already better than the only widespread darwin aarm64 build I know of.
Thants for the good work!
