### ISSUE TITLE
"Non-exhaustive patterns in lambda" error

### ISSUE THREAD

**Issue by vszakats** [koalaman/shellcheck#273]
This input:

```bash
#!/bin/sh

z=$(echo)
```

will generate this failure:
```
shellcheck: ShellCheck/Analytics.hs:(1536,55)-(1539,81): Non-exhaustive patterns in lambda
```

OS X Yosemite + homebrew, shellcheck version 0.3.5

**Comment by koalaman** [comment]
Nicely caught and very well reproduced. Fixed inc9aa133!

**Comment by vszakats** [comment]
Thank you for the fix, and for this very useful tool as well.
