### ISSUE TITLE
[Wiki] Updated SC3026: request of review

### ISSUE THREAD

**Issue by maxnikulin** [koalaman/shellcheck#2741]
I have expanded the [SC3026 In POSIX sh, `^` in place of `!` in glob bracket expressions is undefined.](https://github.com/koalaman/shellcheck/wiki/SC3026) wiki page. [ShellCheck wiki policy](https://github.com/koalaman/shellcheck/wiki/DevGuide#shellcheck-wiki-policy) offers to request review that may be necessary since I am not a shell expert.

I hope, granular commits make it easier to revert specific changes if you find added info inappropriate.

- Link to POSIX and rejected ticket for support of `^`,
- behavior of dash changed,
- a historical note,
- a warning concerning `[!c]` in interactive zsh,
- alternative for correct code for mksh users.

**Comment by maxnikulin** [comment]
Would you mind if I add a link to [SC3026 In POSIX sh, ^ in place of ! in glob bracket expressions is undefined.](https://github.com/koalaman/shellcheck/wiki/SC3026) from the "retired" page used in older versions [SC2039 In POSIX sh, /something/ is undefined.](https://github.com/koalaman/shellcheck/wiki/SC2039)?

**Comment by brother** [comment]
Please do.
