### ISSUE TITLE
How to workaround "SC2086" for command-line options

### ISSUE THREAD

**Issue by myint** [koalaman/shellcheck#277]
I'm not sure what the workaround is for cases such as the following.

`foo.bash`:

```
blah $FOO
```

```
$ shellcheck foo.bash

In foo.bash line 1:
blah $FOO
   ^-- SC2086: Double quote to prevent globbing and word splitting.
```

If I put `$FOO` in quotes, I will get behavior that I do not intend. For example, if `FOO` is `--something --nothing`, it will pass a single argument `--something --nothing` to `blah` rather than two separate arguments `--something` and `--nothing`.

Should I just explicitly suppress `shellcheck` for such cases?

**Comment by dualbus** [comment]
> ```
> blah $FOO
> ```

```
foo=(--something --nothing)
blah "${foo[@]}"
```

This was supposed to be documented here: http://mywiki.wooledge.org/BashFAQ/050

But it seems that the array solution was lost in the edits.

**Comment by koalaman** [comment]
dualbus is right. This is also the solution suggested by the wiki on https://github.com/koalaman/shellcheck/wiki/Sc2086

**Comment by myint** [comment]
Thanks.

**Comment by myint** [comment]
The array solution doesn't seem to work in the case I describe above where `FOO` is meant to be an environment variable.

**Comment by resuna** [comment]
The array solution is bash-only, it doesn't work for portable shell scripts.

Suggestion - a comment (eg "#pragma safe") for such cases.

EG:

#pragma safe FLAGS
FLAGS="-av --delete --delete-excluded --exclude=.DS_Store"

Rationale: all the world isn't bash (thank god).

**Comment by koalaman** [comment]
You can do this with a [shellcheck directive] (https://github.com/koalaman/shellcheck/wiki/Directive)
