### ISSUE TITLE
Compiling ShellCheck is very slow

### ISSUE THREAD

**Issue by treeowl** [koalaman/shellcheck#2774]
I have no idea whether the problem is in GHC, ShellCheck, or both, but even after all its dependencies are satisfied, `ShellCheck` takes an absurdly long time to compile. Would it be possible to look into that and see if there might be anything that can be handled easily? I haven't looked myself, but generally speaking there are often issues with compilation of large record types (especially when using generics), poorly written Template Haskell, expensive type family computations, etc.

**Comment by koalaman** [comment]
My 2019 era desktop builds ShellCheck in 2m40s, or 11s in interpreted mode for development. What kind of numbers are you seeing?
