### ISSUE TITLE
Shellcheck 1.1.0 xz: (stdin): File format not recognized

### ISSUE THREAD

**Issue by Sandeep7409** [koalaman/shellcheck#2798]
- I have one react application which using Shellcheck version 1.1.0 and when I try to npm install it fails
- My shellcheck version is 1.1.0

Following is error I got:

```
 command failed
npm ERR! command C:\Program Files\git\bin\bash.exe -c ./install.sh
npm ERR! xz: (stdin): File format not recognized
npm ERR! tar: Child died with signal 13
npm ERR! tar: Error is not recoverable: exiting now
npm ERR! node:events:505
npm ERR!       throw er; // Unhandled 'error' event
```

I feel like issue is with donwload.js file URL but not 100% sure. URL used in download.js file is below. I have windows 11 machine and I get process.platform value "win32" and If I replace that in below URL I get 404 not found because file does not exists on that URL.

const url = `https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.${process.platform}.x86_64.tar.xz`;

**Comment by koalaman** [comment]
There is no official ShellCheck NPM package, install.sh, or download.js. The latest version of ShellCheck is 0.9.0, so there is no 1.1.0. 

You can try to find who publishes this package, and file an issue with them.
