### ISSUE TITLE
rule for non existent function or command?

### ISSUE THREAD

**Issue by tooptoop4** [koalaman/shellcheck#2804]
i had code like:

`prinln somestuff`

but it did not complain that prinln does not exist

**Comment by aeiplatform** [comment]
Shellcheck doesn't evaluate $PATH.

**Comment by aeiplatform** [comment]
Even in docs is written Static Analysis, please google it.

**Comment by tooptoop4** [comment]
it can be a static check if you indicate that each script is self contained (ie not referencing any others), then u can even put ignore lines above any false positives
