### ISSUE TITLE
[QUESTION] How can I make shellcheck follow dynamic file

### ISSUE THREAD

**Issue by tbhaxor** [koalaman/shellcheck#2815]
The `$@` here expands to `Ports/*/package.sh`, where `*` can be any directory name.

#### Here's a snippet or screenshot that shows the problem:

```sh
# some code here

. "$@"

# some code here
```

#### Here's what shellcheck currently says:

It can't follow, and we have so many directories, also users can implement some functionality in different directory. 

#### Here's what I wanted or expected to see:

I want shellcheck to dynamically follow the file or all the files in the pattern

**Comment by tbhaxor** [comment]
`.shellcheckrc` worked.

**Comment by koalaman** [comment]
ShellCheck doesn't run scripts so it can't really track their runtime behavior such as sourcing files whose names are computed at runtime.

However, you can specify a static filename using `# shellcheck source=myfile` on the line before the `.` command. This could be `/dev/null` to silence the warning and just ignore anything that the files may include, or a representative file that defines functions or variables that you want the rest of the script to consider defined.
