### ISSUE TITLE
SC2059: Wiki page implies `printf %b` is not POSIX

### ISSUE THREAD

**Issue by J-M0** [koalaman/shellcheck#2828]
Currently, the wiki page for [SC2059](https://github.com/koalaman/shellcheck/wiki/SC2059) says this under Exceptions

>Sometimes you may actually want to interpret data as a format string, like in:
>
>```sh
>octToAscii() { printf "\\$1"; }
>octToAscii 130
>```
>
>In Bash, Ksh and BusyBox, there's a `%b` format specifier that expands escape sequences without interpreting other format specifiers: `printf '%b' "\\$1"`. In POSIX, you can instead [[ignore]] this warning.

According to the oldest version I could find[^1], POSIX has required `printf %b` since 1994.

I wanted to raise this issue here before I went and updated the wiki. Is there a reason `printf %b` isn't said to be POSIX?

[^1]: https://pubs.opengroup.org/onlinepubs/009656399/toc.pdf, page 583

**Comment by brother** [comment]
Relevant change:
https://github.com/koalaman/shellcheck/wiki/SC2059/_compare/95e980be0b8f8f02b5a700f1c325ffb056aff014...0c9cfe7e8811d3cafae8df60f41849ef7d17e296

**Comment by J-M0** [comment]
I updated the wiki page
