### ISSUE TITLE
SC1018: Unicode non-breaking space character, fix instructions do not work for MacOS

### ISSUE THREAD

**Issue by AriESQ** [koalaman/shellcheck#2829]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
SC1018

- My shellcheck version (`shellcheck --version` or "online"): 
Online

- [ ] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
The wiki page covers this but gives instructions that do not work on MacOS

- [x] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### For new checks and feature suggestions
- [ ] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```#!/bin/sh
# Enter unicode non-breaking-space via ALT+0160 on win, and CTRL-SPACE on macos
   
return 0
```

#### Here's what shellcheck currently says:
```
[Line 3:](javascript:setPosition(3, 1))
   
^-- [SC1018](https://www.shellcheck.net/wiki/SC1018) (error): This is a unicode non-breaking space. Delete and retype it.
 ^-- [SC1018](https://www.shellcheck.net/wiki/SC1018) (error): This is a unicode non-breaking space. Delete and retype it.
  ^-- [SC1018](https://www.shellcheck.net/wiki/SC1018) (error): This is a unicode non-breaking space. Delete and retype it.
```

#### Here's what I wanted or expected to see:
Same error, but the instructions for fixing this in the wiki do not work.

The wiki says to run 
```
sed -e $'s/\xC2\xA0/ /g' -e $'s/\xE2\x80\x8b//g' -i yourfile
```
On macos this returns:
`sed: -I or -i may not be used with stdin`  
Which is a known issue with BSD sed. https://stackoverflow.com/questions/21242932/sed-i-may-not-be-used-with-stdin-on-mac-os-x

Macos 13.5 / June 10, 2020  
There is no `sed --version` on BSD derived platforms, see https://stackoverflow.com/questions/37639496/how-can-i-check-the-version-of-sed-in-os-x 

If I `brew-install gnu-sed` and run the same command with `gsed` the command line is acceptable and the sed filter removes the problematic characters.

#### Proposed fix
I think it would be enough for the fix instructions to say "On MacOS or BSD you may need to install GNU-sed to use this one-liner".  
A bit more work would be supplying a SED filter that is bsd-sed compatible.  
I'm willing to make the wiki edits if someone points me in the correct direction (to submit a PR?)

Thank you.

**Comment by brother** [comment]
You can edit the wiki to be more verbose on the instruction for mac.
