### ISSUE TITLE
Add an optional check for `avoid-double-brackets`

### ISSUE THREAD

**Issue by Kreyren** [koalaman/shellcheck#2835]
I am trying to write my scripts to be as portable as possible to use `# shellcheck shell=sh` and try to replace bash-specific declaration with POSIX sh.

To aid that effort i am proposing to add `avoid-double-brackets` as an optional check which is supposed to encourage the removal of bash-specific double brackets for single-brackets that are compatible with POSIX sh.

**Comment by brother** [comment]
If you set your sehll to sh you should get a [SC3010](https://github.com/koalaman/shellcheck/wiki/SC3010) warning for `[[ .. ]]` - maybe I am not following your thoughts correct here...

**Comment by Kreyren** [comment]
> If you set your sehll to sh you should get a [SC3010](https://github.com/koalaman/shellcheck/wiki/SC3010) warning for `[[ .. ]]` - maybe I am not following your thoughts correct here... -- @brother (https://github.com/koalaman/shellcheck/issues/2835#issuecomment-1742527583)

You are right i didn't realize that i can set `shell=sh` in `.shellcheckrc` at the time to get this runtime so it doesn't make sense to include as an optional check.

FWIW the idea was to have this on `shell=bash` as a constant effort to turn a huge codebase into a more portable one through integrating POSIX sh syntaxes, but yes `shell=sh` works better for that.

**Comment by brother** [comment]
I've done something similar myself and used a alias to have --shell sh set back when. it's a nice help to get things pointed out.
