### ISSUE TITLE
Add check for x-hacks

### ISSUE THREAD

**Issue by Kreyren** [koalaman/shellcheck#2838]
Referencing https://www.vidarholen.net/contents/blog/?p=1035 x-hacks are an obsolete logical declaration used in the early days of shell/bash scripting to ensure compatibility across different shells

Proposing to implement a check for them as there are lot of projects that are still using them and they don't get caught by shellcheck e.g.
https://github.com/search?q=repo%3Aarmbian%2Fbuild+%2Fx%5C%24%28%5C%7B%7C%29%5Cw%2B%28%5C%7D%7C%29%2F&type=code

**Comment by brother** [comment]
You missed the end of the post I think?

> I think it’s time to retire this idiom, and ShellCheck [now offers](https://github.com/koalaman/shellcheck/commit/5669eb22037980c5a6b74b0d420cb452990bcf88) a style suggestion by default.

**Comment by Kreyren** [comment]
> You missed the end of the post I think?
> 
> > I think it’s time to retire this idiom, and ShellCheck [now offers](https://github.com/koalaman/shellcheck/commit/5669eb22037980c5a6b74b0d420cb452990bcf88) a style suggestion by default. -- @brother (https://github.com/koalaman/shellcheck/issues/2838#issuecomment-1742480370)

I did, my bad! Thanks for checking
