### ISSUE TITLE
SC1091 doesn't recognise local file

### ISSUE THREAD

**Issue by parsley72** [koalaman/shellcheck#2853]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC1091
- My shellcheck version (`shellcheck --version` or "online"): v0.34.0 (VSCode extension)
- [x] The rule's wiki page does not already cover this (e.g. https://shellcheck.net/wiki/SC2086)
- [ ] I tried on https://www.shellcheck.net/ and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/bash

source setup_config.in
```

where setup_config.in is in the same directory.

#### Here's what shellcheck currently says:

Not following: somefile was not specified as input (see shellcheck -x). shellcheck [SC1091](https://www.shellcheck.net/wiki/SC1091)

#### Here's what I wanted or expected to see:

No error.

**Comment by brother** [comment]
You need to specify both -a and -x to make it follow the source.

```
brother@janmayen:/tmp$ cat test.sh
#!/bin/bash

source setup_config.in
brother@janmayen:/tmp$ shellcheck test.sh
brother@janmayen:/tmp$ shellcheck -a test.sh
brother@janmayen:/tmp$ shellcheck -x test.sh
brother@janmayen:/tmp$ shellcheck -ax test.sh

In setup_config.in line 3:
	while str=$(caller $frame) ; do
                           ^----^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
	while str=$(caller "$frame") ; do

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

**Comment by parsley72** [comment]
I don't understand what I'm supposed to do. This is from the VSCode extension - is there a setting I can change?

**Comment by parsley72** [comment]
I think this is the discussion for the VSCode extension: https://github.com/vscode-shellcheck/vscode-shellcheck/issues/883

**Comment by brother** [comment]
That plugin is separate from shellcheck and have them offer a way to set command line option is probably a good idea. Having both a and x enabled for all might not be acceptable. 

The shellcheck help about the command line options.
```
Usage: shellcheck [OPTIONS...] FILES...
  -a                  --check-sourced            Include warnings from sourced files
...
  -x                  --external-sources         Allow 'source' outside of FILES
```

To have your case working as desired you need to have both active as I show earlier.

**Comment by parsley72** [comment]
I've can add those settings manually and it works: 
<img width="490" alt="image" src="https://github.com/koalaman/shellcheck/assets/1666601/7b30b293-12ba-46e6-b7f3-24cc75a158d9">

**Comment by YesILikePinaColadas** [comment]
> I've can add those settings manually and it works: <img alt="image" width="490" src="https://private-user-images.githubusercontent.com/1666601/279530914-7b30b293-12ba-46e6-b7f3-24cc75a158d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2MTk4MjQsIm5iZiI6MTczNzYxOTUyNCwicGF0aCI6Ii8xNjY2NjAxLzI3OTUzMDkxNC03YjMwYjI5My0xMmJhLTQ2ZTYtYjdmMy0yNGNjNzVhMTU4ZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMDgwNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTJiNjJiMWRjNmI1NWEwY2JhODM0YjhkZmQ2ODc2MTVjNzVkN2Q1OTgzY2MzMGJjMGJlN2Q0ZTljZTUyZjYxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LCSUHty8k4DshnwAB0ohzNfLHIJqnC9U-13HccJHNLs">

Adding this made shellcheck not run properly for me. Are you sure shellcheck kept on working properly for you even after adding this?
