### ISSUE TITLE
Using a `# shellcheck source` directive to fix just one SC1090 error seems to nullify all other SC1090 errors

### ISSUE THREAD

**Issue by dslatkin** [koalaman/shellcheck#2854]
I'm working on [my dotfiles repo](https://github.com/dslatkin/dotfiles) where I use shellcheck and I'm having a difficult time trying to get shellcheck to follow my non-constant sourced files.

I can confirm my `shellcheck` binary is on `0.9.0`:

```sh-session
$ shellcheck --version
ShellCheck - shell script analysis tool
version: 0.9.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
```

My issue is in [this file](https://github.com/dslatkin/dotfiles/blob/main/home/dot_bashrc.tmpl) where I have some non-constant sources. They generally would look like this:

```bash
# shellcheck shell=bash

source ~/.dotfiles/env
source ~/.dotfiles/aliases
source ~/.dotfiles/functions

...
```
```sh-session
$ shellcheck -x dot_bashrc.tmpl 

In dot_bashrc.tmpl line 3:
source ~/.dotfiles/env
       ^-------------^ SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.


In dot_bashrc.tmpl line 4:
source ~/.dotfiles/aliases
       ^-----------------^ SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.


In dot_bashrc.tmpl line 5:
source ~/.dotfiles/functions
       ^-------------------^ SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.

...
```

Running shellcheck against that file, I get the expected result. But if I add a directive to _only_ the first `source`, then errors for _all_ the non-constant sources go away and the check passes:

```bash
# shellcheck shell=bash

# shellcheck source=dot_dotfiles/env.tmpl
source ~/.dotfiles/env

source ~/.dotfiles/aliases

source ~/.dotfiles/functions
```

```sh-session
$ shellcheck -x dot_bashrc.tmpl
```

Is this expected? Am I using the directive wrong?

Thanks for the help!

**Comment by koalaman** [comment]
This happens because directives immediately after the shebang, before any other commands, are treated as file-wide. It's definitely confusing in this case.

There's no ideal workaround, but you can insert a dummy `:`/`true` or wrap the `source` statements and directives in a `{ .. }`.
