### ISSUE TITLE
escape string in function call with trap

### ISSUE THREAD

**Issue by wangjoshuah** [koalaman/shellcheck#286]
when we use trap, you need to add escape strings to call the function or some internal commands won't work (for loops for example)

so instead of 

trap function_name SIGUSR1

you need to put

trap 'function_name' SIGUSR1

I was using #!/bin/bash

**Comment by koalaman** [comment]
There's nothing to escape in that example. Do you have an example not covered by [SC2064](https://github.com/koalaman/shellcheck/wiki/SC2064)?

**Comment by wangjoshuah** [comment]
No, I had not escaped my function at all though, and I thought it was good
practice to always escape when you use trap

**Comment by koalaman** [comment]
Since this is a subjective call with no real benefits one way or another, and extended cases like `trap "myfunction $value" int` are already covered, Shellcheck will leave this one up to the script writers.
