### ISSUE TITLE
Improved busybox sh support

### ISSUE THREAD

**Issue by grische** [koalaman/shellcheck#2865]
#### For new checks and feature suggestions
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

Busybox SH is an ash derivative with a few features from ksh.
Running some tests, I noticed the following SCxxxx errors do not apply to busybox sh

- SC3010: [[ ]] in place of [ ]
- SC3014:  == in place of =
- SC3020: &> 
- SC3046/SC3051: 'source' in place of '.'
- SC3048: prefixing signal names with 'SIG'
- SC3057: string indexing 
- SC3060: string replacement

```sh
#!/bin/busybox sh

 X="thisisastring"

stop() {
    echo stopping
    exit 0
}
# SC3048
trap stop EXIT SIGTERM SIGINT

# SC3010 and SC3014
[[ $X == "thisisastring" ]] && echo "this shell supports == and [[ ]]"

# SC3020
echo "busybox sh supports &>" &> /dev/null

# SC3046/SC3051
source /dev/null

# SC3057
echo "${X:0:4} shell supports ${X:7} indexing" # "this shell supports string indexing"

# SC3060
echo "${X/string/magic}"

# for SC3048
sleep 3600
```

and the output is:
```
$ ./busyboxsh.sh
this shell supports == and [[ ]]
this shell supports string indexing
thisisamagic
^Cstopping
stopping
```

shellcheck 
```
In busyboxsh.sh line 1:
#!/bin/busybox sh
^---------------^ SC2187 (warning): Ash scripts will be checked as Dash. Add '# shellcheck shell=dash' to silence.


In busyboxsh.sh line 10:
trap stop EXIT SIGTERM SIGINT
               ^-----^ SC3048 (error): In dash, prefixing signal names with 'SIG' is not supported.
                       ^----^ SC3048 (error): In dash, prefixing signal names with 'SIG' is not supported.


In busyboxsh.sh line 13:
[[ $X == "thisisastring" ]] && echo "this shell supports == and [[ ]]"
^-------------------------^ SC3010 (error): In dash, [[ ]] is not supported.


In busyboxsh.sh line 16:
echo "busybox sh supports &>" &> /dev/null
                              ^----------^ SC3020 (error): In dash, &> is not supported.


In busyboxsh.sh line 19:
source /dev/null
^--------------^ SC3046 (error): In dash, 'source' in place of '.' is not supported.
^--------------^ SC3051 (error): In dash, 'source' in place of '.' is not supported.


In busyboxsh.sh line 22:
echo "${X:0:4} shell supports ${X:7} indexing" # "this shell supports string indexing"
      ^------^ SC3057 (error): In dash, string indexing is not supported.
                              ^----^ SC3057 (error): In dash, string indexing is not supported.


In busyboxsh.sh line 25:
echo "${X/string/magic}"
      ^---------------^ SC3060 (error): In dash, string replacement is not supported.
```

## Improvement

Even if busybox sh will not be a first-class shell, would it be possible to silence those warnings/errors for busybox sh?

**Comment by slycordinator** [comment]
IMO, this isn't valid.

busybox supports these only if it was built with bash-compatible extensions (ASH_BASH_COMPAT) enabled.

If busybox were built with CONFIG_ASH_BASH_COMPAT=y, then these options will be supported/included.
If busybox were built with CONFIG_ASH_BASH_COMPAT=n, then they will not.

**Comment by grische** [comment]
@slycordinator interesting note. I expanded my test environment and ran the above script successfully on those environments:
- Alpine Linux 3.18
- Arch Linux 
- Busybox Docker images (glibc, musl, ulibc)
- CentOS (with EPEL Next)
- Clear Linux
- Debian
- Fedora
- FreeBSD 14
- OpenWRT 
- Rocky Linux
- Ubuntu

**Comment by slycordinator** [comment]
If you have a look at:
https://git.busybox.net/busybox/tree/shell/ash.c#n193

From lines 210-256, you will see that all of these options are enabled when ENABLE_ASH_BASH_COMPAT and IF_ASH_BASH_COMPAT are set to true.

The options seem to be enabled by default when building busybox. But then a user could build it themselves with those disabled or run a system that disables them.

Perhaps this should be added to a "busybox bash" dialect or something for shellcheck?
