### ISSUE TITLE
Usage from android termux: Segmentation fault

### ISSUE THREAD

**Issue by Codammy** [koalaman/shellcheck#2874]
i get a segmentation faults every time i check a bash script from my termux could it be because of the version am using i shouldn't run it on termux.![Screenshot_20231204-130131~2.png](https://github.com/koalaman/shellcheck/assets/95567887/5541db09-e0a8-46f7-b738-ba059e05ee8b)

**Comment by Codammy** [comment]
> Which binary are you using? My understanding of Android/termux is that need to build specifically for that environment, rather than using e.g. the prebuilt Haskell GNU/Linux binary from this repo.

![Screenshot_20231218-213158](https://github.com/koalaman/shellcheck/assets/95567887/447ba4d1-1644-4a76-bf86-8605f7ac68b2)

it's *armv7*

**Comment by koalaman** [comment]
armv7 is your architecture, not the binary you are running. I'm assuming you're using this repo's GNU/Linux armv6hf binary meant for Raspberry Pi.

I don't know the specific differences between the environments, but it's not intended for Termux and certainly not built against the Android NDK. Termux does appear to have both shellcheck and ghc available on aarch64 though, correctly built for Termux (with installation of `libiconv`).

**Comment by AaHbsjjjb** [comment]
ممكن حلا
