### ISSUE TITLE
FYI: I revised bounds for ShellCheck-0.9.0 so that it builds with GHC 9.8

### ISSUE THREAD

**Issue by andreasabel** [koalaman/shellcheck#2875]
See revision 2: https://hackage.haskell.org/package/ShellCheck-0.9.0/revisions/
Builds with GHC 9.8 now.

I copied the bounds from current `master` to the released 0.9.0.

I also filed a PR to add ShellCheck to stackage again:
- https://github.com/commercialhaskell/stackage/pull/7194

**Comment by koalaman** [comment]
Very nice! I don't know too much about these inner workings of the Haskell ecosystem, so I really appreciate the help.

**Comment by andreasabel** [comment]
In general, it is good to have the latest release on Hackage build with the latest GHC (and, with the latest dependencies), so that the package stays in the stackage snapshots.  Then, you do not have to worry about Stackage.  
There is usually some delay though, atm Stackage sticks to GHC 9.6; so the updates do not have to happen immediately, yet it is good to stay on top of things.
