### ISSUE TITLE
Anyone can edit the Wiki

### ISSUE THREAD

**Issue by homersimpsons** [koalaman/shellcheck#2898]
The wiki in https://github.com/koalaman/shellcheck/wiki can get edited by anyone.

The `_Footer` and `_Sidebar` page were seemingly vandalized:
- https://github.com/koalaman/shellcheck/wiki/_Footer/_history
- https://github.com/koalaman/shellcheck/wiki/_Sidebar/_history

I think wiki edition should be restricted.

It looks like you can report the following users (based on the histories above):
- https://github.com/Bunyuh
- https://github.com/ritchiepapirin
- https://github.com/Mahan6697 (already deleted)

**Comment by brother** [comment]
Vandalism has been a minimum and it has served us well to have it open.
