### ISSUE TITLE
macOS brew install three versions of GHC

### ISSUE THREAD

**Issue by WuMingIT** [koalaman/shellcheck#2911]
`brew` lists the following deps among others:

ghc, ghc@9.4, ghc@9.6

and consequently downloads:

==> Fetching ghc
==> Fetching ghc@9.4
==> Fetching ghc@9.6

Any reason for it?

Also noticed Python is called twice every time. As example:

==> /usr/local/opt/python@3.11/libexec/bin/python -m pip install .
==> /usr/local/opt/python@3.12/libexec/bin/python -m pip install .

**Comment by koalaman** [comment]
The `brew` build is maintained by volunteers (thanks!) independently of this upstream repo. You'd have to ask them about this issue.
