### ISSUE TITLE
Stable version v0.10.0

### ISSUE THREAD

**Issue by grische** [koalaman/shellcheck#2918]
@koalaman it has been more than a year since the last release with some very nice features and improvements. It seems like a good time for a new release.

I ran the shellcheck candidate v0.10.0 (b5ab220652a97e33084c31f37a6454ed24b919ab) on some sample code and I did not spot any errors. There are considerable amount of `shellcheck: (Array.!): undefined array element` with v0.9.0 that were fixed with the v0.10.0 candidate.

I tested it applying this change on top:
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 897aa27..5c4d780 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,4 +1,4 @@
-## Git
+## v0.10.0 - 2024-02-02
 ### Added
 - SC2324: Warn when x+=1 appends instead of increments
 - SC2325: Warn about multiple `!`s in dash/sh.
diff --git a/ShellCheck.cabal b/ShellCheck.cabal
index 76516db..c688a8e 100644
--- a/ShellCheck.cabal
+++ b/ShellCheck.cabal
@@ -1,5 +1,5 @@
 Name:             ShellCheck
-Version:          0.9.0
+Version:          0.10.0
 Synopsis:         Shell script analysis tool
 License:          GPL-3
 License-file:     LICENSE
```

**Comment by lamyergeier** [comment]
@koalaman Please make a new release, as its is more than 15 months!

**Comment by grische** [comment]
@lamyergeier do you have a Mac and can test the latest master on MacOS?

**Comment by lamyergeier** [comment]
I installed the latest head version with homebrew. I am running on Fedora 39.

**Comment by koalaman** [comment]
v0.10.0 has now been released on Hackage, github, docker, precommit, and snap (armhf tbd, i386 deprecated)!
