### ISSUE TITLE
Enhancement: Allow reporting of issues to be disabled on a per-line basis (with a hint/comment?)

### ISSUE THREAD

**Issue by srcshelton** [koalaman/shellcheck#292]
It would be neat to be able to parse a file containing, for example:

```sh
    A && B || C # ~SC2015
```

... to prevent the raising of, in this case, warning SC2015 for this line.  This would be a neat and largely self-documenting way to prevent known issues from being reported - especially where contraindications (... is that really the correct word?  It seems to have only medical/drugs-trials relevance - might "Exceptions" or "Counterposition" be more widely understood alternatives?) exist, and so the warning really might be not a relevant warning.

**Comment by koalaman** [comment]
You can do this with (significantly more verbose) [shellcheck directives](https://github.com/koalaman/shellcheck/wiki/Directive).

And you're right, "Exceptions" would probably be better
