### ISSUE TITLE
`require-double-brackets` doesn't work in BusyBox `sh` even though `[[` is supported

### ISSUE THREAD

**Issue by GrantGryczan** [koalaman/shellcheck#2967]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2292
- My shellcheck version (`shellcheck --version` or 'online'): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/busybox sh
# shellcheck enable=require-double-brackets

[ -e /etc/issue ]
```

#### Here's what shellcheck currently says:

Nothing.

#### Here's what I wanted or expected to see:

```
Line 4	SC2292: Prefer [[ ]] over [ ] for tests.
```

**Comment by koalaman** [comment]
You're right of course. This test had not been updated for the recently added BusyBox support. Thanks!

**Comment by ale5000-git** [comment]
@koalaman
I'm using BusyBox for Windows and it does support glob matching.
I don't think the version for Linux would be so behind (maybe you have tried an outdated version).

**Comment by grische** [comment]
@koalaman @ale5000-git I opened a new issue for the glob matching #2998 2998
