### ISSUE TITLE
Consider killing zsh support

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#298]
Support for zsh is very poor. It would probably be better to disable it entirely.

**Comment by koalaman** [comment]
Zsh support removed in ed56a83

**Comment by chauncey-garrett** [comment]
I do hope that zsh support will remain a possibility for future releases. I've really enjoyed using this tool for bash scripts but use zsh as my go-to shell-scripting language.

**Comment by N4M3Z** [comment]
Please consider restoring Zsh support. With the advent of zsh package managers like oh-my-zsh, prezto or zplug, Zsh is becoming a major player that is definitely worth your time.

**Comment by igs-awilliams** [comment]
N4M3Z +1
