### ISSUE TITLE
empty test => parse error

### ISSUE THREAD

**Issue by tombrus** [koalaman/shellcheck#299]
`if [ ]; then echo never; fi`
=> SC1009 The mentioned parser error was in this if expression.
=> SC1073 Couldn't parse this test expression.
=> SC1072 Unexpected keyword/token. Fix any mentioned problems and try again.

`if test ]; then echo never; fi`
OK

**Comment by koalaman** [comment]
This is technically valid syntax, but I'm not sure if accepting it is more helpful than rejecting it.

**Comment by tombrus** [comment]
You can argue if it is worth a warning or an even error on the checking level, I agree.
But without any doubt the parser should accept it as valid syntax!

**Comment by koalaman** [comment]
Finally fixed in 5c01b6c7f!

**Comment by tombrus** [comment]
Thanks!
