### ISSUE TITLE
Report spam in the wiki

### ISSUE THREAD

**Issue by ale5000-git** [koalaman/shellcheck#2997]
Spam in the wiki:
https://github.com/koalaman/shellcheck/wiki/guerraart8
https://github.com/koalaman/shellcheck/wiki/guerraart8_Footer
https://github.com/koalaman/shellcheck/wiki/_Sidebar/_compare/ac8bbd0%5E...ac8bbd0

**Comment by brother** [comment]
The wiki is open for edits, by both good people and bad people. Just reverting the vandalism is fine, no need to ask about it in the future.

I've reverted these for now.

**Comment by ale5000-git** [comment]
@brother
I'm not completely sure but I think people with admin rights can also ban people to avoid future problems.
