### ISSUE TITLE
Warn about invalid return values

### ISSUE THREAD

**Issue by omajid** [koalaman/shellcheck#301]
Bash complains about negative return values:

    $ return -1
    bash: return: -1: invalid option
    return: usage: return [n]

shellsheck should warn about this if encounters it in scripts.

A simple test case:

    $ cat test.sh 
    return -1
    $ shellcheck test.sh 
    $ bash test.sh 
    test.sh: line 1: return: -1: invalid option
    return: usage: return [n]

**Comment by koalaman** [comment]
Great suggestion! Some support for this is included in 61b4b65.

It gives you the benefit of the doubt regarding variables and substitutions, but if will catch simple things like `return -1` and `return "hello world"`

**Comment by omajid** [comment]
Thanks!
