### ISSUE TITLE
shellcheck.net HTTPS certificate expired

### ISSUE THREAD

**Issue by kappa** [koalaman/shellcheck#3014]
![image](https://github.com/koalaman/shellcheck/assets/47310/0d48efc6-fa88-4092-b9c6-7fe68984e80b)

**Comment by o10gogogo** [comment]
I think this web use wrong certificate which named "vidarholen.net".

**Comment by EHJ-52n** [comment]
You need to check the certificate alternative names property:
![image](https://github.com/koalaman/shellcheck/assets/3839896/fee0c64b-1814-46ea-9dcb-045164b00fdb)

The certificate needs renewal, nothing more.

**Comment by koalaman** [comment]
Every single time, lmao. I really need to work on the automation
