### ISSUE TITLE
ShellCheck not available on DNF?

### ISSUE THREAD

**Issue by markjschreiber** [koalaman/shellcheck#3028]
From the ReadMe I tried to install ShellCheck on Amazon Linux 2023 which is fedora based.

```
sudo dnf install ShellCheck
```

The response I get is"
```
Last metadata expiration check: 0:04:43 ago on Thu Jul 25 14:12:38 2024.
No match for argument: ShellCheck
Error: Unable to find a match: ShellCheck
```

Is this package no longer available?

**Comment by josephcsible** [comment]
It's specifically Amazon Linux 2023 where it's unavailable. It's still available in DNF on basically every other Fedora-based distro. Details follow:

ShellCheck is still available in Fedora's repos, and in EPEL for RHEL-based distros. Amazon Linux 2 was roughly a clone of RHEL 7, and ShellCheck there came from EPEL, which itself came from Amazon-Linux-Extras. Unfortunately, Amazon Linux 2023 doesn't support that anymore: see https://repost.aws/knowledge-center/ec2-enable-epel and https://aws.amazon.com/linux/amazon-linux-2023/faqs/ for more details.

If you really want it from DNF, then switch to Fedora, RHEL, or one of RHEL's clones. If you're stuck on Amazon Linux 2023, then see https://github.com/koalaman/shellcheck/blob/master/README.md#installing for some non-DNF ways you can install it.
