### ISSUE TITLE
[Feature request] Is it time to deprecate UUOC (SC2002)?

### ISSUE THREAD

**Issue by edwardgalligan** [koalaman/shellcheck#3047]
The *UUOC Award* is so famous that it almost seems blasphemous to suggest this. Maybe 2024 is still too early in time to forget this rule. However...

- My instinct is that at this stage it's kept as an homage to Usenet, rather than a practical guidance for good script writing
- Other Shellcheck rules prevent real errors where your script will do something unintended. The pitfall being avoided with UUOC is a perf hit that's unlikely to exhibit - it seems in a different category to other solid practical Shellcheck rules
- the codebase [currently has 6 separate `verifyNot checkUuoc` calls](https://github.com/koalaman/shellcheck/blob/master/src/ShellCheck/Analytics.hs#L513-L519) & there are multiple open GH issues with other edge-cases yet to be excepted in code, showing it's not a clear-cut easy-to-follow rule in all cases
- comparisons like `cat x | cmd1 | cmd2` -vs- `<x cmd1 | cmd2` are well-known arguments for improved consistency & readability of scripts
- the Shellcheck wiki for this rule states that fixing it is "not necessarily a good use of time in practice, and rarely affects correctness" & recommends ignoring it

## Mitigations

I can easily add `-e SC2002` (as the Shellcheck wiki for this specific rule actually recommends) - but I'm sure many Shellcheck users, like me, do their best to stick to default settings wherever possible. Having just a single exception makes collab difficult. It would be fine to ignore if I were ignoring a large set of rules, but this is likely to be the only one for many people.

## Possible alternative approaches

Shellcheck doesn't currently have "off-by-default" rules - all rules are on & custom configs only disable some. I imagine adding off-by-default rules would be a non-trivial change to what is currently a beautifully simple tool, but this is another possible approach one could take.

## References
- There are thousands of documents online discussing the pros & cons of UUOC but [this SO answer is possibly the most succint I've found](https://stackoverflow.com/a/49254166)
- The Wikipedia section on UUOC [points out the readability issues](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat)

**Comment by brother** [comment]
> Shellcheck doesn't currently have "off-by-default" rules - all rules are on & custom configs only disable some. 

This is actually not true. There are "optional checks" that you need to explicitly activate. See [shellcheck --list-optional](https://github.com/koalaman/shellcheck/wiki/Optional).

**Comment by koalaman** [comment]
I would agree. This check was more fitting for back when shellcheck was an automated IRC pundit. Starting with 88e441453ba3bbb2aa0449dc178b8f82aaee5b4c, this check is off by default and can be enabled with `--enable=useless-use-of-cat` or equivalent. 

Verily the end of an era. Thanks!

**Comment by andrewhamon** [comment]
THANK YOU!
