### ISSUE TITLE
strange style warning

### ISSUE THREAD

**Issue by jmikedupont2** [koalaman/shellcheck#3071]
echo "MODIFIED_BRANCH_NAME=${name/\//-}" >> "$GITHUB_ENV"
^-- SC2129 (style): Consider using { cmd1; cmd2; } >> file instead of individual redirects.

I think this is a mistake

**Comment by wileyhy** [comment]
What does shellcheck.net say?

**Comment by koalaman** [comment]
You get this when you have 3 lines with the same redirects in a row. The example [from the wiki](https://www.shellcheck.net/wiki/SC2129) is:

```
echo foo >> file
date >> file
cat stuff  >> file
```

vs

```
{
  echo foo
  date
  cat stuff
} >> file
```

If you don't consider this an improvement, you can ignore the suggestion. If it's triggering where you didn't expect it, you can post a complete example.

**Comment by jmikedupont2** [comment]
Actually you can close this because it's it's saying I have multiple
instances of writing to the environment one line after the other I just
didn't understand but this bug is not a bug I'm going to close it

**Comment by jmikedupont2** [comment]
Yes thank you I didn't understand the message it's referring to the multiple lines and it's very much correct
