### ISSUE TITLE
Diff 1.0 was released

### ISSUE THREAD

**Issue by juhp** [koalaman/shellcheck#3075]
Just a heads-up that Diff-1.0 was released.

See https://github.com/commercialhaskell/stackage/issues/7559

**Comment by koalaman** [comment]
Nice! The package bounds have been updated.

**Comment by juhp** [comment]
Thanks, perhaps you want to do a Hackage revision too?

Or are you planning to release soon?

**Comment by koalaman** [comment]
Had to reacquaint myself with the process but 0.10.0 now has `Diff >= 0.4.0 && < 1.1`
