### ISSUE TITLE
Parse error on Bash case fallthrough statements

### ISSUE THREAD

**Issue by telotortium** [koalaman/shellcheck#308]
Bash supports fallthrough between branches of a case statement with `;&` and `;;&`. These cause a SC1072 error even though they are valid syntax.

**Comment by koalaman** [comment]
This should have been fixed in 3dd592a0 before version 0.3.4. Which version are you testing it? Can you make it fail on [shellcheck.net](http://shellcheck.net), which always runs the latest git commit?

**Comment by telotortium** [comment]
I was using the version in Ubuntu 14.04, which is apparently too old. It works on the latest commit. Sorry!
