### ISSUE TITLE
Sc2086 incorrectly warns about using quotes even when the result is obviously ignored

### ISSUE THREAD

**Issue by sstewartgallus** [koalaman/shellcheck#310]
I don't expect super duper static analysis but maybe things like the following should be ignored.

~~~shell
: ${LINTED_CLANG:=clang}
~~~

**Comment by koalaman** [comment]
The result isn't entirely ignored. It's subject to word splitting and globbing as usual, so `failglob` could cause the invocation to fail (potentially snowballing with `set -e`).

**Comment by sstewartgallus** [comment]
Dang, you're right. I'll have to think of a new idiom instead of that.

**Comment by koalaman** [comment]
You could just quote it

**Comment by sstewartgallus** [comment]
Yeah but `: "${LINTED_CLANG:=clang}"` is really ugly.

**Comment by koalaman** [comment]
If you say so. I'll close this bug in the mean time.
