### ISSUE TITLE
SC1056 Expected a '}'

### ISSUE THREAD

**Issue by Enkouyami** [koalaman/shellcheck#311]
With the code below which has a "}", shellcheck states that I either don't have one or should a ";" or "\n" in front of it, but there's no apparent reason as to why I would need to add that since it works just fine as is.

    #!/bin/bash
    counter=1
    #-----------#
    #   Dots    #
    #-----------#
    # This simply prints three Dots. It waits .1 seconds between each dot.
    Dots() {
    while [ $counter -le 3 ]
    do
    echo -n "."
    sleep .1
    ((counter++))
    done
    let counter=1
    echo ""
    done
    } # END Dots

**Comment by brother** [comment]
Remoe the last "done" just before the last "}" and your syntax is then complete and good and you have no warnings.

**Comment by bittorf** [comment]
brother: the 'done' belongs to the 'do' of 'while' - the '}' marks the end of the function

**Comment by dualbus** [comment]
On Tue, Feb 17, 2015 at 06:44:02AM -0800, Bastian Bittorf wrote:
> brother: the 'done' belongs to the 'do' of 'while' - the '}' marks the end of the function
Check again. There are two 'done's.

**Comment by koalaman** [comment]
It doesn't work fine as is for me:

    $ ./script 
    ./script: line 16: syntax error near unexpected token `done'
    ./script: line 16: `done'

**Comment by Enkouyami** [comment]
@brother @dualbus Removing the last 'done' fixes it, thanks.

**Comment by koalaman** [comment]
Ideally yes, but it's very hard for a parser to deduce what the underlying human error was when there just happens to be an extra keyword somewhere (is there an extra `done` or missing `while`?). 

In this case, you got advice more suited for situations like `if true; then foo() { date; echo foo}; fi`, which also terminates a syntactic element not started in the brace group. 

As this is not a typical or systematic error, I'll close the bug.
