### ISSUE TITLE
not always valid: SC2046: Quote this to prevent word splitting.

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#312]
test $(grep -c STRING file) -gt 5
grep -c will always return '0' or an integer, so there is no need to quote the $()

**Comment by dualbus** [comment]
On Tue, Feb 17, 2015 at 06:49:47AM -0800, Bastian Bittorf wrote:
> test $(grep -c STRING file) -gt 5
> grep -c will always return '0' or an integer, so there is no need to quote the $()
Shellcheck is not aware (and it's not possible for it to be aware) if a program
is going to return a number or a string with no spaces. There are ways to turn off
messages that you know are false positives (or you could just quote the
expansion, it won't make your code less correct).

**Comment by koalaman** [comment]
Your example is actually one where `grep -c` does not return an integer:

    $ test $(grep -c STRING file) -gt 5
    grep: file: No such file or directory
    -bash: test: -gt: unary operator expected

Since it doesn't output anything, quoting is required to preserve the empty string.

**Comment by bittorf** [comment]
you are right, but both case produce the same error-code
{{{
$ test $(grep -c STRING file) -gt 5 || echo $?
$ test "$(grep -c STRING file)" -gt 5 || echo $?
}}}

i will close this issue for now...
