### ISSUE TITLE
--exclude does not work reliable

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#313]
{{{
user@box:~$ shellcheck --exclude SC1010 myscript | grep -c 'SC1010:'
6
user@box:~$ shellcheck myscript | grep -c 'SC1010:'
6

i also tried the short '-e' and '1010' instead of 'SC1010'

**Comment by koalaman** [comment]
Oh, well caught! `-e` did not exclude 1xxx class errors. Fixed in 955ad60
