### ISSUE TITLE
Saner shebang check

### ISSUE THREAD

**Issue by nikolay** [koalaman/shellcheck#317]
There are many library scripts, which are never executed directly and are only sourced. Shebang mostly makes sense if the script has the executable flag.

**Comment by koalaman** [comment]
Shellcheck needs to know the type of file it's checking. You can specify the shell with e.g. `-s bash` if you don't want to use a shebang.

**Comment by nikolay** [comment]
I see. I thought it's the shebang, but it's not that. Thanks for the clarification!
