### ISSUE TITLE
SC2143: Possible wrong suggestion

### ISSUE THREAD

**Issue by bayandin** [koalaman/shellcheck#319]
In my code I used this condition:
```bash
if [ -z "$(grep 'Europe/Moscow' /etc/timezone)" ]; then
    echo Europe/Moscow > /etc/timezone
    dpkg-reconfigure --frontend noninteractive tzdata
fi
```

Shellcheck catches this with the following suggestion:
```bash
if [ -z "$(grep 'Europe/Moscow' /etc/timezone)" ]; then
     ^-- SC2143: Instead of [ -z $(foo | grep bar) ], use ! foo | grep -q bar .
```

My first reaction was fix my condition by something like this:
```bash
if ! /etc/timezone | grep -q 'Europe/Moscow'; then
...
```
But the right way it is a
```
if ! grep -q 'Europe/Moscow' /etc/timezone; then
...
```

It would be better if shellcheck can split cases like `cmd | grep smth` and `grep smth filename`.

**Comment by koalaman** [comment]
That is indeed confusing. Improved in 00c470f

**Comment by bayandin** [comment]
Awesome! Thanks.
