### ISSUE TITLE
hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#324]
one of my testfiles throws this error, but i cannot debug it, see:
https://github.com/bittorf/kalua/blob/master/openwrt-addons/etc/kalua/pdf
(maybe at line 114?)

**Comment by koalaman** [comment]
Your file is iso-8859-1 (`sed 's/&acute;/Â/g`) but your system's LC_* is probably UTF-8. 

ShellCheck could definitely be handling this better.

**Comment by bittorf** [comment]
yeah, that works:

tr -cd '\11\12\15\40-\176' <"$file" >"$newfile"
shellsheck "$newfile"

the "$newfile" is 1 byte smaller...

**Comment by koalaman** [comment]
You can also iconv the file, or use `LC_ALL=C shellcheck ..`

**Comment by bittorf** [comment]
`LC_ALL=C shellcheck ..` does NOT work, this was also my first attempt

**Comment by koalaman** [comment]
It works with e.g. `LC_ALL=en_US.iso88591 shellcheck ..`. I guess the Haskell libraries assume UTF-8 if nothing else is specified. Good for them!

**Comment by nomeata** [comment]
shellcheck should probably read the files as binary data, and not try to interpret them as text of any encoding. That would imply not using `hGetContents`, though.

This has been reported against the Debian package as well, see http://bugs.debian.org/786781

**Comment by koalaman** [comment]
Fixed in 46fb91b. Files are now always interpreted leniently as UTF-8, and will fall back to ISO-8859-1 (Latin1) failing that. The Haskell libraries are no longer involved in the decoding.
