### ISSUE TITLE
Doesn't ignore SC2148

### ISSUE THREAD

**Issue by davidosomething** [koalaman/shellcheck#325]
```
# shellcheck disable=SC2148
```
this directive is ignored -- still getting errors about missing shebang

**Comment by koalaman** [comment]
It's a bit of a special case; it doesn't actually warn about a missing shebang but about shellcheck not knowing how to interpret your script because it has no shebang and no `-s`. 

Is there any reason why a shellcheck comment would be more convenient than a shebang comment?

**Comment by davidosomething** [comment]
Not sure -- my shell as I defined by chsh is zsh
The file in question is my openbox autostart, which runs using whatever shell you're using
Would it start a bash in the background if I were to add a shebang?
In that case I wouldn't want it, but otherwise I would want it

What about adding a check for current shell in shellcheck and assuming that as the script runner if this directive is provided?

**Comment by koalaman** [comment]
If you add a shebang, it would run it with whatever the shebang says. 

If I had to guess, I would guess it runs with sh instead of your login shell if the shell is not specified. 

The fact that we have no idea is even more of a reason to add an explicit shebang.

**Comment by koalaman** [comment]
2c2e419 makes it more explicit why shellcheck is looking for a shebang
