### ISSUE TITLE
Can't parse { ... } &!

### ISSUE THREAD

**Issue by superlukas** [koalaman/shellcheck#326]
That comment has been in my zlogin for a while now.

```zsh
# Compile the completion dump in the background.
{
  d=${ZDOTDIR:-$HOME}/.zcompdump
  if [[ -s ${d} && ( ! -s ${d}.zwc || ${d} -nt ${d}.zwc ) ]]; then
    zcompile "${d}"
  fi
} &! # Shellcheck can't parse this line.
```

Shellcheck version 0.3.5 says: "SC1072: No command. Fix any mentioned problems and try again."
It always points to the last character in the line. I figure it's a parser error of some kind.

I wish I had more information for you, but I don't.

**Comment by koalaman** [comment]
You're entirely right. Zsh support in ShellCheck has never been up to par, and I've removed it in ed56a83. Sorry about that.
