### ISSUE TITLE
SC2029 false positive

### ISSUE THREAD

**Issue by rassie** [koalaman/shellcheck#327]
SC2029 is reported for this line:

```
ssh -f -N -R 60000:localhost:60000 "user@$ip"
```

I suppose SC considers `"user@$ip"` something that's executed on the remote server, but it's not.

**Comment by hpollinger** [comment]
I got the same false positive with this:

```
ssh "root@$user" "$scriptdir/script.sh $scriptargs"
```

SC reports SC2029 for $scriptdir
and with different quoting:

```
ssh "root@$user" "$scriptdir/script.sh" "$scriptargs"
```

SC reports SC2029 for $scriptargs.

**Comment by dotdoom** [comment]
@hpollinger I think your case is actually documented (see "Exceptions" at https://github.com/koalaman/shellcheck/wiki/SC2029) and is not related to this issue.

**Comment by hpollinger** [comment]
You are right, thats a different problem which can safely be ignored.

**Comment by kurahaupo** [comment]
On Wed, 13 Jul 2016, hpollinger wrote:
> ```
> ssh "root@$user" "$scriptdir/script.sh $scriptargs"
> ```

Surely that's root@$host rather than root@$user?

I would strongly recommend that for scripting one should use
```
ssh -l "$user" "$host" ...
```

Or even put "User remoteusername" in your .ssh/config under the appropriate
"Host" entry.

**Comment by hpollinger** [comment]
It should even have been "$user@$host", but copy&paste&edit sometimes is difficult... ;-)

Using the "-l" option instead is a good recommendation, thank you!

**Comment by Tsutsukakushi** [comment]
Found another case when checking my script.

I was doing `ssh -o BatchMode=yes "$host"` and it kept telling me that `$host` is expanded on the clientside, which is quite obvious.

Quick testing showed that same happens with ssh options that take an argument. Shellcheck seems ton interpret the argument as the host.

I tried with `-L 1234:somehost:1234` and `-D 1234` and both will complain about this same thing.

Also adding such options after the host will also cause the error to trigger about their options. `ssh "$host" -D "$port"` triggers SC2029 for `$port`.

**Comment by blueyed** [comment]
Just for reference: https://github.com/koalaman/shellcheck/issues/934 adds a failing test for it.

**Comment by blueyed** [comment]
A workaround is to use `ssh -oBatchMode=yes "$host"`.

**Comment by blueyed** [comment]
Fixing this might be hard: ShellCheck would need to know about options that take an arg.

**Comment by koalaman** [comment]
A more pragmatic solution might be to just not warn when there are options.

**Comment by koalaman** [comment]
Kindly fixed by @mkhl. Thanks!
