### ISSUE TITLE
Borrow some ideas from checkbaskisms?

### ISSUE THREAD

**Issue by peti** [koalaman/shellcheck#330]
The tool http://sourceforge.net/projects/checkbaskisms/ features some tests that might be useful for shellcheck, too, maybe?

**Comment by koalaman** [comment]
Most of these checks are already implemented, just make sure the shebang says `#!/bin/sh` (or use `shellcheck -s sh`). Are there any warnings in particular you're missing?

**Comment by peti** [comment]
No, none in particular.

**Comment by koalaman** [comment]
Went over the list and added several new checks since last time in cc86aab
