### ISSUE TITLE
SC1083 false positive

### ISSUE THREAD

**Issue by cdown** [koalaman/shellcheck#333]
for in_filename in Camera/*.{JP{,E}G,jp{,e}g}; do
                                                ^-- SC1083: This } is literal. Check expression (missing ;/\n?) or quote it.

Full script is at https://github.com/cdown/dotfiles/blob/master/bin/rename-photos.

**Comment by cdown** [comment]
Still happening in 0.3.6

**Comment by koalaman** [comment]
Additionally, `echo {1..$((${var}))}` is a parsing error

**Comment by koalaman** [comment]
Fixed in 6076f0b
