### ISSUE TITLE
SC2086 too widely scoped

### ISSUE THREAD

**Issue by pepa65** [koalaman/shellcheck#334]
I get SC2086 within (( )) scopes where it doesn't apply (as it's only doing arithmetic evaluation, and no globbing/wordsplitting applicable.

**Comment by koalaman** [comment]
Example?

**Comment by pepa65** [comment]
It's not always, but it seems that it's due to my old version, because this gets triggered locally, but not online:
#!/bin/bash
Quota() {
  if ((quotafail))
  then
    echo "ERROR: Continued failure to get quota"
  else
    quotafail=1
    echo "Failure to get quota, will update server and try again..."
  fi
}

**Comment by pepa65** [comment]
I want to say that I really appreciate your speedy follow up, but even more, this excellent and useful tool that you're sharing with us and keep improving!
(When I discovered that it was in the ubuntu repos, I just installed it like that. It seems like getting a more recent version requires me to download 135M to get cabal...)

**Comment by koalaman** [comment]
Glad you like it! 

Unfortunately I don't have a great solution for that yet. Hopefully it'll matter less as shellcheck matures, and if I fix a series of outstanding issues wrt Haskell and the build process, packaging should get less burdensome and therefore maybe go through quicker.
