### ISSUE TITLE
Shellcheck does not compile with GHC 7.10

### ISSUE THREAD

**Issue by taladar** [koalaman/shellcheck#335]
There seem to be lots of ambigious type errors, probably due to the FTP changes and lack of explicit type signatures in shellcheck as well as some inferred types that require the FlexibleContexts language extension from what I can tell.

Full log here https://gist.github.com/taladar/1395ecdc5d28d47d184a

**Comment by koalaman** [comment]
Huh, I've been taking FlexibleContexts for granted all this time. Give it a go with 47b971c, it compiles successfully for me on 7.10.1
