### ISSUE TITLE
SC2046 misapplied to command

### ISSUE THREAD

**Issue by pepa65** [koalaman/shellcheck#336]
In a number of cases I got this flagged with SC2046: "$(command ...)"
(with command being an executable and ... the rest of the list)

**Comment by koalaman** [comment]
Do you have an example? 

The typical problem is accidentally unquoting: `echo "foo "$(date)" bar"` where `$(date)` has a double quote on either side but is still unquoted. ShellCheck tries to explicitly warn about that too.

**Comment by pepa65** [comment]
On closer inspection, I see that I didn't have those double-quotes around $(  ), and that's what it's pointing out. I thought it was about the command being seen as a variable somehow...
