### ISSUE TITLE
bash case operators ;;& and ;& unparsable

### ISSUE THREAD

**Issue by pepa65** [koalaman/shellcheck#337]
It couldn't parse the bash case operators ;;& and ;& but if I replaced them by ;; it was fine.

**Comment by koalaman** [comment]
Do you have an example?

**Comment by pepa65** [comment]
Hmm... cooked this up, but the online checker says it's all good. But my local version from the standard repos (0.3.3-1~ubuntu14.04.1) complains.
#!/bin/bash
case "$1" in
 a) echo "first" ;;&
 b) echo "second" ;&
 c) echo "third" ;;
esac

**Comment by koalaman** [comment]
That explains it. This was fixed in 3dd592a for 0.3.4, while the latest version is 0.3.6 (and the online version always runs the latest commit)
