### ISSUE TITLE
trap ERR should throw a warning for /bin/sh

### ISSUE THREAD

**Issue by daxtens** [koalaman/shellcheck#341]
`trap ERR` is not part of the [OpenGroup shell standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_28). However, when run over a `/bin/sh` script, ShellCheck doesn't throw an error or warning when `ERR` is listed as part of a `trap`.

For example, see https://github.com/torvalds/linux/blob/master/scripts/link-vmlinux.sh: it doesn't throw a warning on the line with `trap ERR`.

**Comment by koalaman** [comment]
Indeed. Fixed in 081751c

**Comment by daxtens** [comment]
Thanks :)
