### ISSUE TITLE
SC2129 false positiv

### ISSUE THREAD

**Issue by Pitterling** [koalaman/shellcheck#344]
##sucessor line causes false positiv SC2129

#! /bin/sh -

TMPDIR='/tmp'
TMPDIRph="${TMPDIR}/perf_history"
TOPASHISTORYDIR='/var/perf/daily'
LOGPERFHIST="${TMPDIR}/perfhist.log"
HistTarZipFile="${TMPFILE}_perf_history.tgz"

if [ "$(find ${TOPASHISTORYDIR} -name '*.topas' | wc -l )" != 0 ]; then

	find "${TOPASHISTORYDIR}" -name '*.topas' -type f -mtime -14 -exec cp {} "${TMPDIRph}" \; 2>>"${LOGPERFHIST}"
	find "${TMPDIRph}" -name '*.topas' -type f -exec topasout -a {} \; >>"${LOGPERFHIST}"

	#next line cause SC2129 false positiv in line 12
	{ cd "${TMPDIRph}";tar cvf - ./*.csv | gzip > "${HistTarZipFile}" ;} 2>>"${LOGPERFHIST}"

	#...

fi

**Comment by brother** [comment]
Shellcheck.net only warns about the first find not the one after the comment.
