### ISSUE TITLE
Encourage ${VAR} for adjacent concatenations

### ISSUE THREAD

**Issue by mcandre** [koalaman/shellcheck#346]
I've run into problems multiple times with forgetting to use curly brackets (`${VAR}`) instead of regular `$VAR`, when concatenating variables with other adjacent text.

E.g., `pgrep "test*$DATABASE*logger"` may fail, whereas `pgrep "test*${DATABASE}*logger"` works.

Could ShellCheck add a new rule to warn when curly braces should be used?

**Comment by koalaman** [comment]
This would definitely be a good thing, but always requiring curly braces seems like overkill.

In your particular example it doesn't matter, but in e.g. `mv file.jpg "$prefix_$number.jpg"` it does. 

For lowercase variables, assumed to be shell local, that have not been assigned, you get something like `SC2154: prefix_ is referenced but not assigned (did you mean 'prefix'?).`

For uppercase variables, assumed to be mostly environment variables, where a (very) similar name has been assigned, you get `SC2153: Possible misspelling: PREFIX_ may not be assigned, but PREFIX is.` 

Do you have some real world examples not caught by those that could help determine when to warn?

**Comment by mcandre** [comment]
Agreed, curly braces aren't needed everywhere.

Whenever there's a non-quote, non-whitespace character adjacent (left or right) of a shell variable name, it would be nice to warn the user to use curly braces.

**Comment by koalaman** [comment]
Given that this is mostly a style decision where one could fall on either side, I'll close it.
