### ISSUE TITLE
$@: Double quote array expansions, otherwise they're like $* and break

### ISSUE THREAD

**Issue by mcandre** [koalaman/shellcheck#357]
I often write shell scripts like:

whizzbang <host> <port>

```
#!/bin/sh
java -jar whizzbang.jar $@
```

that act as shell scripts, invoking Java classes behind the scenes. But ShellCheck wants me to surround `$@` with double quotes, which would actually be a mistake--I *want* to pass arguments expanded, not try to fit them into a single string.

How should I write this script, or could we tweak shellcheck to ignore globs for `$@` and `$*`?

**Comment by koalaman** [comment]
Shellcheck is right: you want `"$@"` here. It will be equivalent to `"$1" "$2" "$3" ..`

Fitting them in a single string, I.e. `"$1 $2 $3.." ` would be `"$*"`, and is not ShellCheck's recommendation.

**Comment by mcandre** [comment]
Thanks for clearing that up!

**Comment by koalaman** [comment]
Np. Reopening to fix the message. It should explicitly say it's mangling individual elements

**Comment by koalaman** [comment]
Fixed in c785d43
