### ISSUE TITLE
shellcheck's parser is confused about directives before a done redirect in a while loop

### ISSUE THREAD

**Issue by aw-altiscale** [koalaman/shellcheck#375]
We've hit a case where we need to disable SC2046 in a while/done that takes input from a subshell. I've been able to simplify the case to this:

```bash
while read line
do
echo bar
 # shellcheck disable=SC2046
done <  foo
```

Running this against shellcheck 0.3.6 & 0.3.7 results in:

```
while read line
^-- SC1073: Couldn't parse this while loop.

In 6 line 5:
done < foo
     ^-- SC1072: Expected "#". Fix any mentioned problems and try again.
```

... which is a little bizarre.  Replacing the shellcheck disable with some other comment, shellcheck is fine.

**Comment by koalaman** [comment]
Directives are per semantic shell script structure and not per line, so ShellCheck is confused when a directive is applied to half a while loop.

Can you expand on the example a bit? I don't see where the SC2046 (unquoted command expansion) would come from.

**Comment by aw-altiscale** [comment]
Sure.  The original done was:

```
done < <(docker inspect -f '{{.Id}},{{.State.Running}},{{.State.FinishedAt}}' $(docker ps -qa) 2>/dev/null)
```

It complains that $(docker ps -qa)  needs to be quoted.

**Comment by koalaman** [comment]
You're right, this is a bit of an edge case. It's tricky to disable the message while also minimizing scope. 

I would just have disabled it for the entire loop:

    # shellcheck disable=SC2046
    while read line
    do
      echo bar
    done <  <(docker inspect -f '{{.Id}},{{.State.Running}},{{.State.FinishedAt}}' $(docker ps -qa) 2>/dev/null)


You can technically apply it to just the command in the process substitution, but it's awkward:

    while read line
    do
      echo bar
    done <  <(
        # shellcheck disable=SC2046
        docker inspect -f  $(docker ps -qa) 2>/dev/null)

You obviously shouldn't have to restructure working code to please ShellCheck, but writing around it is a third option:

    get_docker_stats() {
      # shellcheck disable=SC2046
      docker inspect -f "$1" $(docker ps -qa) 2>/dev/null
    }
   
    while read line
    do
      echo bar
    done <  <(get_docker_stats '{{.Id}},{{.State.Running}},{{.State.FinishedAt}}')

**Comment by aw-altiscale** [comment]
Yeah, I'll probably re-arrange the code to work around it rather than escape the entire while loop, given the contents of it.

I hadn't thought to try the directive inside the subshell.  Thanks for the insight!

**Comment by deryni** [comment]
Rewriting to collect the lines in an array could avoid the problematic code in the first place too.

**Comment by aw-altiscale** [comment]
*nods* Lots of way to avoid the situation, but then this edge case would have remained hidden for longer. ;)

**Comment by koalaman** [comment]
I'll close this as WAI for now, since it does work, just awkwardly.
