### ISSUE TITLE
Japanese char issue on Windows

### ISSUE THREAD

**Issue by Xanardi** [koalaman/shellcheck#378]
When the Japanese character is used, a result becomes strange.
It's strange by the Windows environment, but it seems normal by Linux.

ex.
#!/bin/bash
list1=$(ls -la) # NGﾊﾟﾀｰﾝcomment
list2=$(ls -la) # コレもNGcomment

**Comment by koalaman** [comment]
How are you running it on Windows?

**Comment by Xanardi** [comment]
Yes. shellcheck is often used on Windows.
Linux on Virtual Machine has been developed with that.

**Comment by koalaman** [comment]
You use shellcheck in a Linux Virtual Machine? Or in Cygwin?

**Comment by Xanardi** [comment]
shellcheck is being used by Windows native.

**Comment by koalaman** [comment]
I tried the test program on native Windows in a file saved in Notepad.exe with "Encoding: UTF-8", and this is what happened:

    C:\Users\vidar_000\Desktop\shellcheck-master>dist\build\shellcheck\shellcheck.exe test.sh

    ←[1mIn test.sh line 1:←[0m
    ←[0m∩╗┐#!/bin/bash←[0m
    ←[31m^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang
    .←[0m


    ←[1mIn test.sh line 2:←[0m
    ←[0mlist1=$(ls -la) # NG∩╛è∩╛ƒ∩╛Ç∩╜░∩╛¥comment←[0m
    ←[33m^-- SC2034: list1 appears unused. Verify it or export it.←[0m


    ←[1mIn test.sh line 3:←[0m
    ←[0mlist2=$(ls -la) # πé│πâ¼πééNGcomment←[0m
    ←[33m^-- SC2034: list2 appears unused. Verify it or export it.←[0m

Is this what you mean by strange?

**Comment by koalaman** [comment]
Ansi escapes are fixed in 7fff088, but unicode input/output is still strange

**Comment by Xanardi** [comment]
And I 've tried , it was useless .

Japanese characters in the UTF-8 , the length of one character is the length of the multiple bytes .
When to input the character to shellcheck, it seems become NG.

**Comment by koalaman** [comment]
Apparently in `cmd.exe` and `powershell.exe`:
1. Make sure `chcp` says `65001` (UTF-8). This can be set with `chcp 65001`
2. Make sure to use a TrueType font, not a Raster Font, in Properties->Font.

In Powershell ISE you may additionally have to:
3. `[Console]::OutputEncoding = [System.Text.Encoding]::UTF8`
because chcp doesn't change it automatically.

Does that help?

**Comment by koalaman** [comment]
Windows instructions have been added in aea0310

**Comment by koalaman** [comment]
Please reopen if this does not work for you.

**Comment by Xanardi** [comment]
Sorry .
Response had been delayed .
I tried the Ver.0.38 but would return an error .

>C:\Temp\src>shellcheck.exe test.sh
>shellcheck.exe: test.sh: hGetContents: invalid argument (invalid byte sequence)
