### ISSUE TITLE
SC2115 error

### ISSUE THREAD

**Issue by gdbtek** [koalaman/shellcheck#379]
Hi I got following warning but I have no idea how to fix it. Any thought? Thanks

```
    rm -f -r "/usr/local/$(getFileName "${MYSQL_INSTALL_FOLDER:?}")"
             ^-- SC2115: Use "${var:?}" to ensure this never expands to /usr/local .
```

**Comment by gdbtek** [comment]
I tried this and it worked but I'm wondering if there is a shortcut way rather I have to create an extra local var.

```
    local -r installFolderName="$(getFileName "${MYSQL_INSTALL_FOLDER}")"
    rm -f -r "/usr/local/${installFolderName:?}"
```

**Comment by brother** [comment]
no.
and using rm with -f will hide errors - just a heads up if that's a unwanted side effect of the -f.
