### ISSUE TITLE
Change license to something else

### ISSUE THREAD

**Issue by gleber** [koalaman/shellcheck#383]
Probably won't work, but still worth asking if there's even a minuscule chance.

Can the license be changed to something less restrictive than AGPL? GPL, MIT, Apache or almost any other license would allow me to use this for internal startup needs.

**Comment by koalaman** [comment]
What kind of internal use do you have where AGPL vs GPL makes a difference?

**Comment by gleber** [comment]
Our lawyer said we should avoid AGPL at all costs, since even after looking at the code it might make things tricky to clear up in case of any legal dispute.

**Comment by koalaman** [comment]
What does your lawyer say about rejecting AGPL under section 9, "You are not required to accept this License in order to receive or run a copy of the Program", and just not modifying or redistributing it as with any other proprietary tool?

**Comment by gleber** [comment]
It gets complicated, since we only build stuff with our compilers and only from our own source tree.

**Comment by koalaman** [comment]
You said "internal startup needs". Are you actually trying to get shellcheck into google3?

**Comment by koalaman** [comment]
Taking this offline.

**Comment by mightyoj** [comment]
What happened here?

**Comment by brother** [comment]
> Our lawyer said we should avoid AGPL at all costs, since even after looking at the code it might make things tricky to clear up in case of any legal dispute.

Looking at open source code and then go ahead and implement stuff behind closed doors (or vice versa) is by all means a very bad idea. Scrubbing the knowledge away is hard to impossible. That's why we have clean rooms.
