### ISSUE TITLE
"SC1072: Unexpected eof." reported on valid shell script

### ISSUE THREAD

**Issue by eldering** [koalaman/shellcheck#384]
shellcheck (version 0.3.4 from Debian Jessie) reports

    ^-- SC1072: Unexpected eof. Fix any mentioned problems and try again.

on the following valid shell script:

    #!/bin/sh
    # nothing to compile

**Comment by koalaman** [comment]
In later versions this is a marginally more helpful "No command.", but yes, it should probably accept empty files. This also applies to empty command substitutions.

**Comment by koalaman** [comment]
Fixed in ca37794
