### ISSUE TITLE
"Module `Control.Monad.Trans.Error' is deprecated", and more

### ISSUE THREAD

**Issue by thalesfsp** [koalaman/shellcheck#387]
Just informing this warnings:

Compiling Control.Monad.Primitive ( Control/Monad/Primitive.hs, dist/build/Control/Monad/Primitive.o )

Control/Monad/Primitive.hs:39:1: Warning:
    Module `Control.Monad.Trans.Error' is deprecated:
      Use Control.Monad.Trans.Except instead

Control/Monad/Primitive.hs:98:11: Warning:
    In the use of type constructor or class `Error'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

Control/Monad/Primitive.hs:98:47: Warning:
    In the use of type constructor or class `ErrorT'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

Control/Monad/Primitive.hs:99:19: Warning:
    In the use of type constructor or class `ErrorT'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

Warning: 'license: AGPL-3' is not a recognised license. The known licenses
are: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, BSD3, MIT, Apache, Apache-2.0,
PublicDomain, AllRightsReserved, OtherLicense

shellcheck.hs:21:1: Warning:
    Module `Control.Monad.Trans.Error' is deprecated:
      Use Control.Monad.Trans.Except instead

shellcheck.hs:48:10: Warning:
    In the use of type constructor or class `Error'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:48:10: Warning:
    In the use of type constructor or class `Error'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:49:5: Warning:
    In the use of `noMsg' (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:81:31: Warning:
    In the use of type constructor or class `ErrorT'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:87:13: Warning:
    In the use of `throwError'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:97:51: Warning:
    In the use of `runErrorT'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:304:36: Warning:
    In the use of type constructor or class `ErrorT'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:315:13: Warning:
    In the use of `throwError'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:317:19: Warning:
    In the use of data constructor `ErrorT'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:333:13: Warning:
    In the use of `throwError'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:339:9: Warning:
    In the use of `throwError'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:344:13: Warning:
    In the use of `throwError'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

shellcheck.hs:351:9: Warning:
    In the use of `throwError'
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

**Comment by koalaman** [comment]
This has been fixed in 72eeafe0
