### ISSUE TITLE
FAIL: [ $a -gt $b 2>/dev/null ] but OK: test $a -gt $b 2>/dev/null

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#402]
FAIL:
[ $a -gt $b 2>/dev/null ]

OK:
test $a -gt $b 2>/dev/null

error about redirection

**Comment by koalaman** [comment]
Redirections inside `[` are usually unintentional, as in `[ 1 > 2 ]`, so they're unsupported by design. You can redirect after the `]`
