### ISSUE TITLE
SC1073: FAIL: $(( \ (new line) expression ))

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#404]
e.g. this will fail with SC1073: Couldn't parse this $((..)) expression.

<pre>
  local log_mask=$(( \
                  ($log_80211  << 0) | \
                  ($log_8021x  << 1) | \
                  ($log_radius << 2) | \
                  ($log_wpa    << 3) | \
                  ($log_driver << 4) | \
                  ($log_iapp   << 5) | \
                  ($log_mlme   << 6)   \
          ))
</pre>

**Comment by koalaman** [comment]
Fixed in 0522a5f
