### ISSUE TITLE
SC2086 exception: Wild card inside double quote

### ISSUE THREAD

**Issue by baxeno** [koalaman/shellcheck#406]
When fixing SC2086 issues there is an exception when the string contain a wild card.

**Problem code - Remove multiple files:**
```
rm ${DATABASE_STORAGE}/NetworkList*
   ^-- SC2086: Double quote to prevent globbing and word splitting.
```

**Solution with pitfall:**
```bash
rm "${DATABASE_STORAGE}/NetworkList*"
```

**Solution without pitfall:**
```bash
 find "${DATABASE_STORAGE}" -name "NetworkList*" -print0 | xargs -0 -r rm -f
```

**Comment by b-long** [comment]
:+1:

**Comment by koalaman** [comment]
ShellCheck just wanted you to quote the variable, but this is not obvious since it points to the start of the argument without telling you where to stop: `rm "${DATABASE_STORAGE}"/NetworkList*`.

I've updated the wiki to mention this
