### ISSUE TITLE
Fail to adhere to "shopt -s extglob" in a "case" command

### ISSUE THREAD

**Issue by BohrShaw** [koalaman/shellcheck#411]
#!/usr/bin/env bash
    
    shopt -s extglob
    case "$*" in
      +([[:alpha:]]) ) ;; # shellcheck report "unexpected token `('
    esac

Shellcheck Version: 0.3.3, related #223.

**Comment by koalaman** [comment]
This particular snippet fails because `# shellcheck report` is considered a malformed shellcheck directive, though the error really needs fixing. 

The code without the comment works fine.

**Comment by BohrShaw** [comment]
Then I must upgrade my Shellcheck!

**Comment by koalaman** [comment]
Due to the way annotations are implemented (being considered part of the following command rather than a comment), fixing the error message is not straight forward. I'll just close this.
