### ISSUE TITLE
re-assignment of for loop var

### ISSUE THREAD

**Issue by aw-altiscale** [koalaman/shellcheck#414]
There should probably be a warning or error if the variable in a for loop is re-assigned or used 
again in another for statement.  For example:

A:

```bash
for i in 1 2; do
   for i in 2 3 ; do
        echo $i
   done
done
```

B:

```bash
for i in 1 2; do
  for ((i=2; i>=0; i--)); do
    echo $i
  done
done
```
It's extremely unlikely that either case is what the user intended.

**Comment by koalaman** [comment]
Indeed. A warning has been added in 83adcba
