### ISSUE TITLE
Wrong error

### ISSUE THREAD

**Issue by pujan14** [koalaman/shellcheck#415]
Hi Pasting following code on shellcheck shows error, I don't think its an error.

#!/bin/sh
​

if true ; then
  echo hello
fi

​if true ; then
​  echo test
​fi

sorry for bad description.

**Comment by deryni** [comment]
You have some zero-width spaces on some of your lines. Those are confusing shellcheck. Remove them and the problem goes away.

Specifically, you have one on the second line and one at the start of each of the lines in the last `if` statement.

**Comment by koalaman** [comment]
cbda90e will warn about zero-width spaces, similar to `&nbsp;` before
