### ISSUE TITLE
bats support

### ISSUE THREAD

**Issue by aw-was-here** [koalaman/shellcheck#417]
It would be nice if shellcheck supported/understood bats' @test nomenclature so that we could run shellcheck over bats input files.

**Comment by nicolaiskogheim** [comment]
+1

**Comment by koalaman** [comment]
What would be required to do this?

* Parse @test as brace groups
* Ignore the variables `status`, `lines` and `output`
* Assume `bats` in the shebang means `bash`

Am I missing anything?

**Comment by aw-altiscale** [comment]
I think that's it.  If nothing else, it's a good start and the blanks can get filled in as we hit them.
 Awesome thanks!

**Comment by bertvv** [comment]
+1!

**Comment by Skilgarriff** [comment]
Any update on this? Otherwise a point in the right direction as to where we could help make this happen would be awesome!

**Comment by dougm** [comment]
Using bats-preprocess works well and preserves the original .bats file line numbers, column numbers, etc:

```
/usr/local/libexec/bats-preprocess < foo.bats | shellcheck -
```

**Comment by dougm** [comment]
Using this approach via Emacs + flycheck works well too: https://github.com/dougm/bats-mode/commit/001187c7544085c62c0141b380b43d8d77a497fb

**Comment by Skilgarriff** [comment]
@dougm I was looking for a solution that would eventually then be able to port to Atom - Plus it would be nice to be able to be checking Bats formatting with shellcheck instead of first processing it to bash.

**Comment by dougm** [comment]
@Skilgarriff agreed, it would be ideal for shellcheck to have native bats support.

**Comment by koalaman** [comment]
I took a crack at this, but it seems to have more edge cases than I imagined.

I implemented the outlined additions, but bats apparently has a whole little DSL for including files and such that I didn't attempt to duplicate. It seems to work fine with bats' own tests. 

If anyone wants to try it out, check the `bats` branch: https://github.com/koalaman/shellcheck/tree/bats

**Comment by edouard-lopez** [comment]
related:
* [sstephenson/bats: Why BATS syntax raises so many shellsheck errors?](https://github.com/sstephenson/bats/issues/188)
* [AtomLinter/linter-shellcheck: Why BATS syntax raises so many shellsheck errors?](https://github.com/AtomLinter/linter-shellcheck/issues/84)

**Comment by zmarouf** [comment]
I just tested the ```bats``` branch with a few of my files. It works great :) Thanks!
(Note: I don't use the ```load```  feature extensively)

**Comment by edouard-lopez** [comment]
The `bats` branch is in version `0.4.4`, latest master release is in `0.4.6`.

@koalaman Is there something blocking the merging into master?

**Comment by koalaman** [comment]
@edouard-lopez Lack of testing and interest. 

Thanks to zmarouf for giving it a go.

**Comment by edouard-lopez** [comment]
@koalaman I use the `bats` branch for all my new shell projects and didn't notice issues so far. I'm using it through `atom` editor
Projects include:
* [progress-bar.sh](https://github.com/edouard-lopez/progress-bar.sh) ;
* [Coaxis/OPT](https://github.com/Coaxis-ASP/opt/blob/master/daemon/test/add-channel.tests.bats) ;
* [backup-docker-to-ftp](https://github.com/edouard-lopez/backup-docker-to-ftp/blob/master/test_backup.bats) ;
* [logo-groupe-trevise](https://github.com/akema-fr/logo-groupe-trevise/generate-logo.bats).

I'm not using advanced features but still would recommend to merge to rise interest and feedback.

**Comment by ELLIOTTCABLE** [comment]
I'd love to see this merged. I depend heavily on Bats, and I hate having to disable Syntastic right now. (Might have to give @dougm's preprocessing approach a try, but it's a bit of a hack!)
