### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib

### ISSUE THREAD

**Issue by jeanmichelcote** [koalaman/shellcheck#420]
Now that everything is installed, here is the error popping up when i load in Vim on OSX:

`syntastic: error: checker output:
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/bin/shellcheck
  Reason: Incompatible library version: shellcheck requires version 13.0.0 or later, but libgmp.10.dylib provides version 12.0.0
syntastic: error: checker sh/shellcheck returned abnormal status 133`

So I did a `brew update && brew upgrade` and even a `brew upgrade gmp` but it said: `Error: gmp 6.0.0a already installed`

How should i get that version 13.0.0 instead of that 12.0.0 that i've got?

**Comment by deryni** [comment]
You got `libgmp` from `brew`? Did you get `shellcheck` from `brew` also? Or did you get a binary of it from somewhere else? Does rebuilding `shellcheck` help?

**Comment by jeanmichelcote** [comment]
Is `gmp` and `libgmp` the same?
Yes, got bothk from brew.

**Comment by deryni** [comment]
Yes, `gmp` and `libgmp` should be from the same package.

I don't use `brew` but it looks like `brew reinstall shellcheck` might do it.

But I wouldn't have expected `brew` to have installed a version of shellcheck that isn't compatible with the version of `libgmp` that it installs. Does `brew doctor` report anything?

**Comment by jeanmichelcote** [comment]
There you go, sir.

`brew reinstall shellcheck` did it.
