### ISSUE TITLE
Warn about "local" can only be used in a function in Bash

### ISSUE THREAD

**Issue by rony36** [koalaman/shellcheck#424]
"local" can only be used in a function in Bash.
It will causes an execution error.
Here is a simple example.

```bash
#!/bin/bash

local word="hi"
echo $word
exit 0
```
**line 3: local: can only be used in a function**

May shellcheck check for this error?

**Comment by koalaman** [comment]
You're right, and this is a useful check. It was fixed a while ago, and I forgot to update this bug!
