### ISSUE TITLE
Warn about starting a bracket expression with an unquoted ^

### ISSUE THREAD

**Issue by kergoth** [koalaman/shellcheck#436]
According to the standard:

"[...]a bracket expression as in XBD RE Bracket Expression , except that the <exclamation-mark> character ( '!' ) shall replace the <circumflex> character ( '^' ) in its role in a non-matching list in the regular expression notation"

Most shells support both (e.g. `[!a-z]` and `[^a-z]`), but the latter gives unspecified results according to the standard:

"A bracket expression starting with an unquoted `<circumflex>` character produces unspecified results."

I was recently bitten by this with a couple of my shell scripts on a dash system, and also on an embedded system with a feature-limited /bin/sh.

**Comment by koalaman** [comment]
Wow, I had no idea! A warning has been added in f653362
