### ISSUE TITLE
clear known issues

### ISSUE THREAD

**Issue by misteralexander** [koalaman/shellcheck#437]
I'm working on a script and I validate it every few logic blocks or so.  I get warnings / code suggestions on areas we have chosen to do it a certain way.  It would be cool if you could clear/close certain comments if you know you're doing it for a specific reason.  Example:

        #!/bin/bash
        for c in $(cat "/home/user/file")
        do echo $c
        done;

**To read lines rather than words, pipe/redirect to a 'while read' loop. (SC2013)**

My file only has single words each on their own line. If I could clear/close/ignore this, that would be cool.

**Comment by koalaman** [comment]
You can do this with a [directive] (https://github.com/koalaman/shellcheck/wiki/Directive). Discoverability of this feature is still a work in progress.

Note that if one of your words is `*` it could still explode.
