### ISSUE TITLE
SC2154 var is referenced but not assigned

### ISSUE THREAD

**Issue by valiko-ua** [koalaman/shellcheck#442]
prj_path is assigned using "eval" but shellcheck reports it's not assigned:

```bash
eval prj_path=\$$prj_var
                ^––SC2086 Double quote to prevent globbing and word splitting.
if [ -z "$prj_path" ]; then
        ^––SC2154 prj_path is referenced but not assigned.
```

**Comment by koalaman** [comment]
Unfortunately there's no good way for ShellCheck to figure out assignments that happen based on runtime information, like with `eval`. https://github.com/koalaman/shellcheck/wiki/SC2154 contains various workarounds.

Fun fact: the variable is not necessarily assigned. If `prj_var='1 true'` or `prj_var=\'`  then the variable will remain unset.
