### ISSUE TITLE
SC2154 triggers incorrectly on ${!prefix*} expansions.

### ISSUE THREAD

**Issue by deryni** [koalaman/shellcheck#443]
This script:
```
#!/bin/bash

# shellcheck disable=SC2034
osfoo=osfoov osbar=osbarv osblah=osblahv

echo "${!os*}"
```
results in this output from the shellcheck site
```
   1  #!/bin/bash
   2  
   3  # shellcheck disable=SC2034
   4  osfoo=osfoov osbar=osbarv osblah=osblahv
   5  
   6  echo "${!os*}"
            ^––SC2154 os is referenced but not assigned.
```

But that's not what `${!os*}` is doing. That expansion is getting the list of variables that match that prefix.

The output from running that script is `osbar osblah osfoo`.

**Comment by koalaman** [comment]
Nice catch! This has been fixed in 10276c8
