### ISSUE TITLE
bogus SC1068 for non-assignment

### ISSUE THREAD

**Issue by mauke** [koalaman/shellcheck#444]
echo ===

produces
```
 1  echo ===
    ^––SC2034 echo appears unused. Verify it or export it.
         ^––SC1068 Don't put spaces around the = in assignments.
```

But the code is fine and simply outputs `===`. There are no variables involved.

**Comment by koalaman** [comment]
Yes indeed. From d0029ae, ShellCheck will warn about using two equal signs, and ignore three or more assuming it's some kind of ascii art line.
