### ISSUE TITLE
Missing FlexibleContexts in Parser.hs prevents compilation with GHC 7.10

### ISSUE THREAD

**Issue by mbeniamino** [koalaman/shellcheck#445]
First time I compile a Haskell project, but as long as I understand this commit:

https://github.com/koalaman/shellcheck/commit/f85441add9ef4f6b739dcc34d79ad9070f86967b

broke the compilation for GHC 7.10. I'm issuing a pull request, check if it's ok.

**Comment by mbeniamino** [comment]
Yhis is the pull request:

https://github.com/koalaman/shellcheck/pull/446

**Comment by mbeniamino** [comment]
Since the pull request has been accepted and this fixes the compilation for me I close the issue.

Thank you.

**Comment by koalaman** [comment]
Thanks for the fix!
