### ISSUE TITLE
Fails to process long scripts (>1000 lines)

### ISSUE THREAD

**Issue by footflaps** [koalaman/shellcheck#451]
When I paste in a long script it seems to think about it for a few seconds and then just fail / hang with no error message. The same script is successfully parses if entered in as two halves.

Example script (1164 lines) here: https://www.dropbox.com/s/jx29xnaytw9rh7c/shellcheck_bug_report.sh?dl=0

**Comment by koalaman** [comment]
This works locally but failed on shellcheck.net because the web version runs with limited CPU time and memory. I bumped the limits a bit for now, and I'll make sure you get a proper error message in the near future.

**Comment by koalaman** [comment]
The near future turned out to be Jun 2018, and you now get a "Sandbox resource constraints exceeded. Try a smaller script, or run ShellCheck locally." in such cases
