### ISSUE TITLE
excluding SC1007 doesn't work

### ISSUE THREAD

**Issue by dfong** [koalaman/shellcheck#454]
i wish to exclude SC1007 from the shellcheck report.  i tried `shellcheck -e SC1007,SC...` but shellcheck is still cranking out SC1007 warnings.  shellcheck version 0.3.5.  i am able to successfully exclude other shellcheck warnings, but strangely SC1007 keeps showing up.

**Comment by koalaman** [comment]
You're right. This affected all SC1xxx errors (parse time warnings), and was fixed in 955ad60 right before 0.3.6.
