### ISSUE TITLE
SC2028, SC2039 and dash as /bin/sh

### ISSUE THREAD

**Issue by Arthur2e5** [koalaman/shellcheck#461]
`dash` is a popular and the default option for a minimal `sh` for Debian systems, including Ubuntu. However, its echo, by default, interprets all backslash options (like in [XCU](http://pubs.opengroup.org/onlinepubs/7908799/xcu/echo.html)) and it can't be overridden by flags, e.g. by GNU echo's `-E`. And unlike XCU, it interprets the `-n` option.

Since Debian is quite popular, I think the description of `SC2028` should be ‘In POSIX sh, echo with operands containing backslashes causes undefined results’, and `SC2039` should be ‘with flags causes..’.

POSIX.1:2008 [echo](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html): 
> **string**: A string to be written to standard output. If the first operand is -n, or if any of the operands contain a <backslash> character, the results are implementation-defined.
> ***APPLICATION USAGE*** It is not possible to use echo portably across all POSIX systems unless both -n (as the first argument) and escape sequences are omitted. [...] New applications are encouraged to use printf instead of echo.

SUSv2 XCU [echo](http://pubs.opengroup.org/onlinepubs/7908799/xcu/echo.html):
> **string**: A string to be written to standard output. If any operand is -n, it will be treated as a string, not an option. The following character sequences will be recognised within any of the arguments:

**Comment by Arthur2e5** [comment]
The wiki items should be changed accordingly too, but I think I can do that myself.

**Comment by kurahaupo** [comment]
I have yet to find a use for ```env``` that I actually trust, since ```~/bin``` or even ```~attacker/rootkit/bin``` might be early in ```PATH```.

The usual suggestion is to use ```printf``` instead, which is unambiguous, or if it's too much hassle to edit existing code, to define a shell function like ```echo() { printf '%b\n' "$*"; }``` (XPG) or ```echo() { if [[ $1 = -n ]] ; then shift ; printf '%s' "$*" ; else printf '%s\n' "$*" ; fi ; }``` (BSD).

**Comment by koalaman** [comment]
Dash is easier to support and way more common than ksh, so it should really have first class support in shellcheck rather than being an alias for POSIX sh.

**Comment by Arthur2e5** [comment]
@koalaman I mean we need a rephrase concerning those things (like *unspecified behavior*), given that dash **does** interpret `echo` backslashes (SC2028)..

**Comment by koalaman** [comment]
f778216 changes this message to "undefined", and also adds dash as a first class shell.
