### ISSUE TITLE
Document and implement return values of shellcheck

### ISSUE THREAD

**Issue by mulle-nat** [koalaman/shellcheck#470]
It would be good to have it defined (and coded), what shellcheck returns when it finds problems, so it can be queried in a script.

Like maybe 0: no problems, 1: suggestions (green) 2: warnings (yellow),  -1: errors (red).

**Comment by kurahaupo** [comment]
> -1: errors (red)

Nope. Return codes are limited to 0~255 (an unsigned 8-bit integer).

**Comment by mulle-nat** [comment]
Ok, I could live with errors 3 :)

**Comment by koalaman** [comment]
Good point! Error codes have been defined for a while (and used by e.g. syntastic). As of 3b36c2c they are documented in the man page.

They don't differentiate between style/warning/error type codes, but these are kind of fluid categories anyways.

**Comment by mulle-nat** [comment]
I would have liked to have seen this, so that I could do a git pre-commit phase and check that there aren't any "real" errors. I rarely write a shell script, that has no warnings though :) An alternative would be to have a (growing) list of SC codes to ignore, that one could query. e.g. Give me all SCs < red. But I still think a return code would be more convenient.

**Comment by koalaman** [comment]
For a precommit, you can do this today with `shellcheck -f json files... | jq '.[].level' | grep error`

In the near future, shellcheck is likely to get a verbosity option where you can choose from "nitpick on any minor potential issue" to "only if I'm about to [steam someone](https://github.com/ValveSoftware/steam-for-linux/issue%73/%33671#asdf)".

**Comment by mulle-nat** [comment]
Nice, thx for the idea with json.

**Comment by tdmalone** [comment]
> In the near future, shellcheck is likely to get a verbosity option where you can choose...

@koalaman Just wondering if this was still on the roadmap :D

**Comment by koalaman** [comment]
It definitely is, I was just too optimistic about the timeline
