### ISSUE TITLE
Alias suppression is not interpreted properly

### ISSUE THREAD

**Issue by RedX2501** [koalaman/shellcheck#485]
`grep` is an alias in my bashrc. `\grep` forces bash to use the unaliased command. This is not regarded correctly by the checker.

![2015-10-01_12-00-10](https://cloud.githubusercontent.com/assets/929932/10216696/9647ea72-6848-11e5-9f02-6ed51e16f0fc.png)

**Comment by koalaman** [comment]
Normally in a script, aliases are not expanded at all, but in `.bashrc` and otherwise sourcing from an interactive shell, you're right.

How would you feel about using the more explicit (and POSIX compliant) `command grep ...` to override functions and aliases?

**Comment by RedX2501** [comment]
Maybe the best approach to write a notice about the behaviour. Something like:

    \<command> only suprresses aliases in interactive shell. Alias suppression is not necessary in scripts. \<letter> will be treated as <letter>. Posix compliant is command <command>

**Comment by Arthur2e5** [comment]
The initial version of SC1001 version already tells you about that suppression thing, at https://github.com/koalaman/shellcheck/wiki/SC1001/2e061da9cf95cf3db2af05602db45da416a45d63.

**Comment by RedX2501** [comment]
Oh, i did not realise that the error code was clickable.

Thank you.
