### ISSUE TITLE
SC2166: Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#489]
i read the wiki page, but do not understand it.
how can e.g. this fail?
```
test -z "$FOO" -a -n "$FOO"
```

**Comment by koalaman** [comment]
I don't know of any specific systems in which this fails, but according to[ POSIX `test`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html):

    >4 arguments:
        The results are unspecified.

**Comment by tr00per** [comment]
GNU coreutils manual doesn't mention any unspecified behavior for `test`: www.gnu.org/software/coreutils/manual/coreutils.html
That's what major distributions use, so the SC2166 advice is useless in practice.

**Comment by SpecLad** [comment]
The Git coding guidelines have an example of how `-a` can be unreliable:

https://github.com/git/git/blob/v2.6.0/Documentation/CodingGuidelines#L154

**Comment by deryni** [comment]
The coreutils don't document the parsing at all which is the stage at which POSIX indicates the unspecified behavior. Also what coreutils does (or does not do) at the moment isn't really relevant to what the spec says is required (or rather what is specified) so yes, warning about spec incompliance is absolutely worthwhile to my mind.

**Comment by bittorf** [comment]
ok, i will close - maybe it's not relevant in practise, but the error-message is valid:
```
user@box:~ x='='
user@box:~ test -n "$x" -a 1 -eq 1
ash: 1: unknown operand
```
thanks for the comments!
