### ISSUE TITLE
Syntax Highlighting for Strings Spanning Multiple Lines

### ISSUE THREAD

**Issue by Herst** [koalaman/shellcheck#499]
Syntax highlighting differs for strings spanning multiple lines, e.g. shell builtin are highlighted inside multi-line strings.

1. Go to http://www.shellcheck.net/.
2. Enter the following:
  ```bash
echo "and break break continue eval exec exit export if readonly return set"

echo "
and break break continue eval exec exit export if readonly return set"
```
3. Look at syntax highlighting.

**Comment by koalaman** [comment]
Thanks! Syntax highlighting is provided by [prettify](https://github.com/google/code-prettify). I've updated the library to the latest version, which does not have this issue.
