### ISSUE TITLE
SC2039 - misleading "in POSIX sh - 'local' is not supported"

### ISSUE THREAD

**Issue by bittorf** [koalaman/shellcheck#502]
testcase
```shell
#!/bin/sh

x()
{
  local x=0
  return $x
}

x
```
according to dash https://wiki.ubuntu.com/DashAsBinSh#local and the wikientry SC2039 it is allowed but behaves differently than in bash. so we should only warn if e.g.
```shell
local a=1 b=2
```
but the testcase should me fine, should'nt it?

**Comment by Arthur2e5** [comment]
`local` is NOT in POSIX. However it's supported by most POSIX-compatible shells, making it a *de facto*.

In this case, it sounds more like a dash bug.

**Comment by bittorf** [comment]
thanks for making this clear. oh my god. thats bad.
http://stackoverflow.com/questions/18597697/posix-compliant-way-to-scope-variables-to-a-function-in-a-shell-script
http://thread.gmane.org/gmane.linux.debian.devel.bugs.general/122267/focus=3271

so can we at least have another SCxyz for this special case, otherwise when muting this message i also mute maybe useful ones...

**Comment by koalaman** [comment]
Some time in the not-too-distant future, dash is likely to become a first class supported shell. You'll then be able to specify `#!/bin/dash` to use dash specific features just like you can specify `#!/bin/bash` to use bash specific features.

**Comment by bittorf** [comment]
i will close an open another issue for changing the error-code

**Comment by mgedmin** [comment]
> i will close and open another issue for changing the error-code. thank you!

Did you ever open another issue for this?  I cannot find it.

(I'm interested in this basically for the same reason as listed in #664 -- I want my script to be compatible with `bash` and `dash`, both of which have `local`, which is not in the POSIX sh; but I don't want to disable the entire SC2039.)

**Comment by koalaman** [comment]
There's #1341 for this
