### ISSUE TITLE
inconsisten check for invalid condition

### ISSUE THREAD

**Issue by MarcinAtgithub** [koalaman/shellcheck#509]
This is checked properly and shows errors:
"SC1073 Couldn't parse this test expression" 
"SC1072 Expected test to end here. Fix any mentioned problems and try again."
and warning: "SC1009 The mentioned parser error was in this if expression."

#!/bin/bash
if "a" != "b" ]]
then
echo ok
fi

This does not report any problems:

#!/bin/bash
if "a" != "b" ]]
then
echo ok
fi

Is it possible to validate the second case?

**Comment by knirch** [comment]
Something got lost when you reported this, both examples are identical, however the report implies they aren't.

**Comment by koalaman** [comment]
I assume the intention was `[[ ...` vs `... ]]`, which is a valid point. A check for this has been added in 8f5f91f.
