### ISSUE TITLE
Allow command line to define root for external-sources check

### ISSUE THREAD

**Issue by knirch** [koalaman/shellcheck#510]
It might|would be nice if something like

knirch@traktor:~/source/linux-dist$ shellcheck -x --root-path=$PWD -f gcc $(git grep -l '^#!/bin/bash')

would let shellcheck translate "source /usr/lib/shell/db-functions" to "source /home/knirch/linux-dist/usr/lib/shell/db-function"

I do know about the source=file directive, but it's going to add lots of noise; 
$ shellcheck -f gcc $(git grep -l '^#!/bin/bash' ) | grep -c SC1091
628

I could perhaps move some parts to dotfiles, but that would sadly remove the benefit of source checking.

**Comment by koalaman** [comment]
With 301705edea you can now do this with `-P "$PWD"`, which changes the search path both for what's considered the root in absolute paths, and for the base path of relative paths.

This should probably also be part of the new `.shellcheckrc` functionality, but isn't yet.

(Happy 3.5 year anniversary for this issue!)
