### ISSUE TITLE
$variables inside of $()

### ISSUE THREAD

**Issue by eadsjr** [koalaman/shellcheck#515]
source: https://github.com/eadsjr/git-meld/blob/master/bin/git-hide

It doesn't seem to like $folders being inside a $(...)

"$(dirname $folders)"
> Double quote to prevent globbing and word splitting.

'$(dirname "$folders")'
> Expressions don't expand in single quotes, use double quotes for that.

"$(dirname \"$folders\")"
> Double quote to prevent globbing and word splitting.

**Comment by eadsjr** [comment]
This one is giving it some trouble too...

&2 echo "ERROR: file ""$(basename ""$path"")"" already exists at $install_target_path"
> The surrounding quotes actually unquote this. Remove or escape them.
> Double quote to prevent globbing and word splitting.

&2 echo "ERROR: file ""$(basename \"$path\")"" already exists at $install_target_path"
> Double quote to prevent globbing and word splitting.

**Comment by bittorf** [comment]
this is the correct syntax:
```shell
#!/bin/sh
folders=foo
VAR="$(dirname "$folders")"
echo "$VAR"
```

**Comment by deryni** [comment]
Inside a `$(...)` expression you have an entirely new parsing context. The inner quotes don't interfere with the external quotes and the external quotes don't quote the internal contents.

For a quick illustration run the following and look at the output. Notice how every version with "unquoted" at the end outputs `argc: 5`?

    c ()
    {
        printf 'argc: %s\n' "$#";
        printf 'argv: %s\n' "$@"
    }

    echo '# unquoted'
    c a b c d e
    echo '# quoted'
    c a "b c d" e
    echo '# unquoted'
    : $(c a b c d e >&2)
    echo '# unquoted quoted'
    : $(c a "b c d" e >&2)
    echo '# quoted unquoted'
    : "$(c a b c d e >&2)"
    echo '# quoted quoted'
    : "$(c a "b c d" e >&2)"
