### ISSUE TITLE
build on centos 6.6 requires -lz

### ISSUE THREAD

**Issue by dfong** [koalaman/shellcheck#519]
i tried building the latest shellcheck from source on my centos 6.6 machine.  i ran into a problem, after the message saying that it was linking.  the error message was something like:
```
/usr/bin/ld: -lz not found
```
sorry, i did not save the exact output.

i was able to build successfully after doing "sudo yum install libz.so.1".

**Comment by Arthur2e5** [comment]
https://github.com/koalaman/shellcheck/wiki/More-Installation-Guides
Updated. Note: You can change it yourself.

**Comment by koalaman** [comment]
Thanks for the fix!
