### ISSUE TITLE
inappropriate SC2154 

### ISSUE THREAD

**Issue by dfong** [koalaman/shellcheck#520]
i am getting SC2154 "referenced but not assigned" in a place that doesn't make sense.  this is with shellcheck 0.4.1.

```
In bb.sh line 8:
	if [[ $A -eq "somestring" ]]; then
                     ^-- SC2154: somestring is referenced but not assigned.
```
it's as if shellcheck believes that "somestring" is a variable reference, or that this is a double-paren expression rather than a double-bracket expression.

i am not arguing that the code is correct or sensible, but the shellcheck message seems inappropriate.

**Comment by koalaman** [comment]
ShellCheck is correct. When using `-eq`, each operand is evaluated in an arithmetic context which means that "somestring" will be dereferenced as a variable name. This example prints "true":

        A=42
        somestring=42
        if [[ $A -eq "somestring" ]]; then
                echo "true"
        fi

If you want to compare to a string, use `=`. `[[ $A = "something" ]]` would do a string comparison, which would not result in a variable lookup.

**Comment by dfong** [comment]
thanks for the explanation.

typos courtesy of my iphone
