### ISSUE TITLE
New POSIX UB: lastpipe

### ISSUE THREAD

**Issue by Arthur2e5** [koalaman/shellcheck#523]
Common form of the error:

```sh
blah | while read ... # or any other thing that changes the current shell env
```

This breaks things in a silent way, and is almost definite (the only exception being experiment/test scripts).

**Comment by koalaman** [comment]
Do you mean that shellcheck should warn that this might overwrite the environment?

**Comment by Arthur2e5** [comment]
The problem quite the opposite. Users often expect it to change the environment instead.

**Comment by deryni** [comment]
Indeed. That's why the SO question ([Modifying variable inside while loop is not remembered](http://stackoverflow.com/questions/16854280/modifying-variable-inside-while-loop-is-not-remembered)) is listed in the SO bash tag wiki.

**Comment by koalaman** [comment]
Isn't this covered by SC2030 and SC2031 already?

**Comment by Arthur2e5** [comment]
No. `echo a | read -r b; echo $b` gives All good.

**Comment by Arthur2e5** [comment]
This also exposes a problem that shellcheck thinks `b` needs to be used.

**Comment by koalaman** [comment]
When I paste `echo a | read -r b; echo $b` on shellcheck.net, I get this:

      echo a | read -r b; echo $b
                       ^––SC2030 Modification of b is local (to subshell caused by pipeline).
                               ^––SC2031 b was modified in a subshell. That change might be lost.
                               ^––SC2086 Double quote to prevent globbing and word splitting.

**Comment by Arthur2e5** [comment]
Uh-oh. I looked at `echo a | read -r b`, got a unused and simply thought…

**Comment by koalaman** [comment]
No problem, assuming current support is sufficient and closing
