### ISSUE TITLE
SC2005 false positive on `echo "$(<1.txt)"`, and new bashism.

### ISSUE THREAD

**Issue by Arthur2e5** [koalaman/shellcheck#526]
This is a bashism.

In the bash manpage, `"$(<1.txt)"` is said to be faster than `"$(cat 1.txt)"` if you only need one file. From that, people naturally gets `echo "$(<1.txt)"` (a second thought may let people switch to `printf %s\\n` though).

**Comment by koalaman** [comment]
Very true. d985380 fixes both SC2005 and adds a bashism warning.
