### ISSUE TITLE
'declare -p var' should be interpreted as usage.

### ISSUE THREAD

**Issue by hansbogert** [koalaman/shellcheck#527]
Using `declare -p var` construct is used to forward associative arrays to functions. Currently the shellcheck considers var $var unused.

See: http://stackoverflow.com/questions/4069188/how-to-pass-an-associative-array-as-argument-to-a-function-in-bash for example usage

**Comment by Arthur2e5** [comment]
What a coincidence. Closing #528.

**Comment by koalaman** [comment]
Indeed. Fixed in 6739c4a

**Comment by hansbogert** [comment]
@Arthur2e5  Beat you to it ;)
@koalaman  Thanks
