### ISSUE TITLE
unexpected '<' for the line: gpio -p mode $ModePin up </p><p># Main Program Loop

### ISSUE THREAD

**Issue by asyariamir** [koalaman/shellcheck#530]
#!/bin/bash 
# Detect motion on PiFace and play scary video.

# Define PiFace Pins
MotionPin=207 
TriggerPin=200 
VolUpPin=201 
VolDownPin=202 
ModePin=203

Volume=1500
Volstep=50 
CurrentState=0 
CurrentMode=0

DoFlip="" 
# If you need to flip the video upside down, uncomment the following line
# DoFlip="--orientation 180" 

# Assign numbered videos to one of three video modes. Also define the order in which the videos appear
VidMode=0 # 0=Not Scary, 1=Scary, 2=Extra Long 
VidOrder[0]="14 30 46 62" 
VidOrder[1]="12 32 44 64 16 28 48 60" 
VidOrder[2]="6 22 38 54" 
PriorVid=$VidMode 

# Use piface internal pullup resistors on tactile button pins 
gpio -p mode $TriggerPin up 
gpio -p mode $VolUpPin up 
gpio -p mode $VolDownPin up 
gpio -p mode $ModePin up </p><p># Main Program Loop 
clear
while : ; do 
  for i in ${VidOrder[$VidMode]}; do 
    if [ $VidMode -ne $PriorVid ] ; then echo -ne "Video Set $VidMode\r" ; PriorVid=$VidMode; break ; fi 
    while : ; do 
      PriorState=$CurrentState 
      PriorVolume=$Volume 
      PriorMode=$CurrentMode 
      let "CurrentState=(! `gpio -p read $TriggerPin`) | (`gpio -p read $MotionPin`)" 
      let "Volume += ( (! `gpio -p read $VolUpPin`) - (! `gpio -p read $VolDownPin`) )* $Volstep" 
      let "CurrentMode=(! `gpio -p read $ModePin`)" 
      if [ $Volume -ne $PriorVolume ] ; then echo -ne "$Volume\r" ; fi 
      if [ $CurrentMode -gt $PriorMode ] ; then let "VidMode = ($VidMode + 1) % 3"; break ; fi 
      if [ $CurrentState -gt $PriorState ] ; then 
        omxplayer -b --vol $Volume $DoFlip ./Video/$i.mp4 >> /dev/null 
        clear 
        break 
      fi 
    done 
  done
done

**Comment by brother** [comment]
@asyariamir maybe edit that text and wrap it in ``` to make a code block.

**Comment by brother** [comment]
Btw. Not sure where you found the error, after adjusting it and pasting it into shellcheck.net I only see a warning about missing quotes at the omxplayer line.

**Comment by asyariamir** [comment]
@brother I'm sorry, I'm quite new to this and I'm using a ready made code. So, I am to wrap which text to make a code block?

**Comment by brother** [comment]
This is how I inteded it.
```bash
#!/bin/bash
# Detect motion on PiFace and play scary video.
# Define PiFace Pins

MotionPin=207
TriggerPin=200
VolUpPin=201
VolDownPin=202
ModePin=203

Volume=1500
Volstep=50
CurrentState=0
CurrentMode=0

DoFlip=""
# If you need to flip the video upside down, uncomment the following line
# DoFlip="--orientation 180"
# Assign numbered videos to one of three video modes. Also define the order in which the videos appear

VidMode=0 # 0=Not Scary, 1=Scary, 2=Extra Long
VidOrder[0]="14 30 46 62"
VidOrder[1]="12 32 44 64 16 28 48 60"
VidOrder[2]="6 22 38 54"
PriorVid=$VidMode
# Use piface internal pullup resistors on tactile button pins

gpio -p mode $TriggerPin up
gpio -p mode $VolUpPin up
gpio -p mode $VolDownPin up
gpio -p mode $ModePin up

# Main Program Loop
clear
while : ; do
	for i in ${VidOrder[$VidMode]}; do
		if [ $VidMode -ne $PriorVid ] ; then echo -ne "Video Set $VidMode\r" ; PriorVid=$VidMode; break ; fi
		while : ; do
			PriorState=$CurrentState
			PriorVolume=$Volume
			PriorMode=$CurrentMode
			let "CurrentState=(! gpio -p read $TriggerPin) | (gpio -p read $MotionPin)"
			let "Volume += ( (! gpio -p read $VolUpPin) - (! gpio -p read $VolDownPin) )* $Volstep"
			let "CurrentMode=(! gpio -p read $ModePin)"
			if [ $Volume -ne $PriorVolume ] ; then echo -ne "$Volume\r" ; fi
			if [ $CurrentMode -gt $PriorMode ] ; then let "VidMode = ($VidMode + 1) % 3"; break ; fi
			if [ $CurrentState -gt $PriorState ] ; then
				omxplayer -b --vol $Volume $DoFlip "./Video/$i.mp4" >> /dev/null
				clear
				break
			fi
		done
	done
done
```

**Comment by brother** [comment]
What does you line 32 in ./scareme.sh contain? After I tried to understand things line 32 is empty =)

**Comment by asyariamir** [comment]
In PiFace the line: gpio -p mode $ModePin up </p><p># Main Program Loop
is line 32 and not 31.

Anyway, thank you for your help but now the error lies in line 42-44
Example error: line 42: let: CurrentState=(!gpio -p read 0) | (gpio -p read 7): missing ')' (error token is "read 0) (gpio -p read 7)*)

It's the same as the 43 and 44 as well.

**Comment by asyariamir** [comment]
![20151029074002](https://cloud.githubusercontent.com/assets/15379855/10821775/12d19226-7e8f-11e5-892d-a5b0d3c348d2.jpg)

**Comment by brother** [comment]
I do no think this is a shellcheck issue.

**Comment by koalaman** [comment]
For problems with shell scripts that are not related to shellcheck, try [stackoverflow](http://www.stackoverflow.com).

**Comment by asyariamir** [comment]
@brother is it? I see. But is it possible to have the code read as shown?

**Comment by kurahaupo** [comment]
This whole problem is because an ordinary newline has been replaced by HTML paragraph tags `</p><p>`, which @brother apparently can't see using his editor -- to him it just looks line an ordinary newline. Apparently he can't see them in the error message either.

@brother I suggest you use an editor which does *not* interpret HTML tags, but actually shows them to you in raw form.

**Comment by brother** [comment]
@kurahaupo my emacs is working just fine. Are you confusing me with @asyariamir the original poster? If not your message is very unclear.
As I stated earlier, this is not a shellcheck bug and the code is fine, a missing quoting issue just.
