### ISSUE TITLE
SC2070 title is misleading when in 'sh' mode

### ISSUE THREAD

**Issue by alexjurkiewicz** [koalaman/shellcheck#537]
Current: `SC2070: Always true because you failed to quote. Use [[ ]] instead.`

Suggested: `SC2070: Always true because you failed to quote. Quote the argument or use [[ ]] instead.`

**Comment by koalaman** [comment]
You're right. The current message isn't even correct, it's not always true (like for multiword strings).

d00ca0c updates it to "-n doesn't work with unquoted arguments. Quote or use [[ ]]."

**Comment by alexjurkiewicz** [comment]
Nice!
