### ISSUE TITLE
SC2094 and `sponge'

### ISSUE THREAD

**Issue by teresaejunior** [koalaman/shellcheck#541]
There is a package by Joey Hess which is becoming pretty popular recently called [`moreutils`](https://joeyh.name/code/moreutils/). One of its tools is called `sponge`, which allows for writing safely into a file read in the same pipeline, and could be ignored by SC2094:

    NAME
       sponge - soak up standard input and write to a file

    SYNOPSIS
       sed '...' file | grep '...' | sponge file

    DESCRIPTION
       sponge  reads  standard  input and writes it out to the specified file.
       Unlike a shell redirect, sponge soaks up all its input  before  opening
       the  output file. This allows constructing pipelines that read from and
       write to the same file.

**Comment by koalaman** [comment]
Indeed. This is fixed in 8bc98d8.
