### ISSUE TITLE
Syntax error uncaught

### ISSUE THREAD

**Issue by danimateos** [koalaman/shellcheck#546]
The line:

`function hello{ echo 'hello' }`

evokes a  `syntax error near unexpected token 'echo'` in `bash -n` but not in shellcheck

**Comment by deryni** [comment]
I get at number of warnings/errors from shellcheck for that line of code using shellcheck locally and http://www.shellcheck.net.

Are you not getting any warnings/errors (which version of shellcheck) or are you just not getting what you expect?

**Comment by koalaman** [comment]
You're entirely right, `function hello{` is invalid in shells but accepted by ShellCheck. This has been fixed in c7964a7.

The reason why it doesn't show up here is that there's a second syntax error in your example -- a missing semicolon/linefeed before the `}`.
