### ISSUE TITLE
Possible Parse error bug...

### ISSUE THREAD

**Issue by si-rbrisita** [koalaman/shellcheck#547]
It is being reported that this code can not be parsed:

LATEST_BACKUP=$(ssh "$USER@$BACKUP_HOST" << EOF
	sudo su
	cd $REMOTE_BACKUP_PATH
	ls | tail -1
EOF)

**Comment by si-rbrisita** [comment]
Never mind, moving the closing parentheses to the next line fixes it.

**Comment by deryni** [comment]
That's still a parser error in shellcheck. The shell handles this correctly.
