### ISSUE TITLE
sc2124 Suggestion is a potential bug/security hole according to tldp.org 

### ISSUE THREAD

**Issue by newgiin** [koalaman/shellcheck#549]
From http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_02.html#sect_03_02_05, there is a note that says

> $* vs. $@
>
> The implementation of "$*" has always been a problem and realistically should have been replaced with the behavior of "$@". In almost every case where coders use "$*", they mean "$@". "$*" Can cause bugs and even security holes in your software.

but this [suggestion](https://github.com/koalaman/shellcheck/wiki/SC2124#rationale) says to use $* instead of $@.
> If you want to assign N elements as 1 element by concatenating them, use * instead of @

Which one should I follow?

**Comment by koalaman** [comment]
ShellCheck's.

The TLDP description is half oversimplified and half wrong.

**Comment by dualbus** [comment]
TLDP is known to host guides providing bad and insecure advise. It's funny that
they warn about security issues, when following their ABS will probably make
your scripts a lot more insecure.

-- 
Eduardo Bustamante
https://dualbus.me/

**Comment by deryni** [comment]
Yeah, the TLDP bash guides are poor at best.
