### ISSUE TITLE
Shellcheck Codes Cheatsheet

### ISSUE THREAD

**Issue by DevynCJohnson** [koalaman/shellcheck#554]
This is not a bug report. Rather, I wanted to share with you the PDF cheatsheet I made that lists all error codes and their meaning. The free cheatsheet can be found on my website.

http://dcjtech.info/topic/free-pdf-cheatsheets/#shell

WARNING: My website has ads, but the ads are harmless.

**Comment by koalaman** [comment]
You weren't kidding about the ads :|

I'm closing and removing as much of this as github lets me.
