### ISSUE TITLE
Check for if foo == bar; then ..

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#56]

**Comment by georgeryoung** [comment]
Here's a concrete example:

$  if a==b; then echo yes; fi
yes
$  echo ${a=}   # yowza!  I just set the variable who's name is 'a=' to the value '=b'.
=b

Yikes!  That's _really_ not what I meant!   
It would be nice if shellcheck would warn fiercely about this.

**Comment by deryni** [comment]
You set the variable `a` to the value `=b` actually. Not `a=`.

`${a=}` is the unset-only version of the `:=` default value assignment expansion (i.e. it sets the value of the variable `a` to the empty string if `a` is unset at the time of that expansion.

**Comment by koalaman** [comment]
It's definitely an issue, but I had a hard time finding real world examples of it so I'll close it until the next time I see it.
