### ISSUE TITLE
SC2079 triggers weirdly for associative array indices

### ISSUE THREAD

**Issue by koalaman** [koalaman/shellcheck#561]
This is another side effect of parsing associative array indices as numeric:

```
declare -A foo
foo[2015.12.14]=foo
```

SC2079 (( )) doesn't support decimals. Use bc or awk.

**Comment by kurahaupo** [comment]
OK, this is weird; I see the issue on github has the index '2015.12.14', yet
in email (both HTML and plaintext) it shows as '20151214' (with the dots are
missing).

Is this a general github thing, or just this ticket?

**Comment by brother** [comment]
@kurahaupo something github, I've seen it in web URLs as well. http://my.example.com (a test =))

**Comment by koalaman** [comment]
Fixed in 3e5ecaa2
