### ISSUE TITLE
False positive on SC1037 with "$$-$foo"

### ISSUE THREAD

**Issue by AloisMahdal** [koalaman/shellcheck#570]
With following code:

    #!/bin/sh
    foo=bar
    echo "$$-$foo"

ShellCheck raises problem 1037 with the last line

    In sc-doldol line 3:
    echo "$$-$foo"
            ^-- SC1037: $$-$ is equivalent to ${$}-$.

While the hint seems to be technically true (changing to `"${$}-$foo"` works the same), I don't see what this has to do with "SC1037 - Braces are required for positionals over 9, e.g. ${10}" at least as how it is documented now. With regards to the SC name, "Braces are required" is actually *false* about `$$`.

Also I'm not convinced it improves the code anyway. Quite contrary: I'd say `${$}` is much less readable and less common. (I've seen it first time after over 2 years of active Bash scripting).

**Comment by koalaman** [comment]
Agreed. I don't think anyone would expect the `-` to be part of the variable name in this case.

**Comment by koalaman** [comment]
This appears to have been already fixed in a8ff7a from 2014 (for version 0.3.6).
