### ISSUE TITLE
Warn about invisible/weird whitespace runes

### ISSUE THREAD

**Issue by maxnordlund** [koalaman/shellcheck#574]
On Mac Alt+Space creates a non-breakable space, which in general breaks shells in all sorts of ways. It would be nice if shellcheck could detect that.

Something like for every unicode whitespace, make sure it's in this whitelist of space, newline, tab and maybe something more.

**Comment by koalaman** [comment]
Non-breaking space and zero-width space are already covered by SC1018:

    In test line 2:
    if true; then true; fi
                 ^-- SC1018: This is a unicode non-breaking space. Delete and retype it.

I haven't seen any others (like "OGHAM SPACE MARK" and "IDEOGRAPHIC SPACE") pop up IRL.

**Comment by koalaman** [comment]
Please reopen if you have a specific suggestion for a space character

**Comment by AriESQ** [comment]
SC1018 Addresses this.

https://github.com/koalaman/shellcheck/wiki/SC1018
