### ISSUE TITLE
install error 0.4.2

### ISSUE THREAD

**Issue by gdbtek** [koalaman/shellcheck#575]
I tried to install 0.4.2 on my Ubuntu 14.04.3 x64 and got following errors, any thought what seem to be the issue?

```
In-place registering QuickCheck-2.8.1...
Installing library in /root/.cabal/lib/QuickCheck-2.8.1/ghc-7.6.3
Registering QuickCheck-2.8.1...
Installed QuickCheck-2.8.1
Downloading ShellCheck-0.4.2...
[1 of 1] Compiling Main             ( /tmp/ShellCheck-0.4.2-23628/ShellCheck-0.4.2/Setup.hs, /tmp/ShellCheck-0.4.2-23628/ShellCheck-0.4.2/dist/setup/Main.o )

/tmp/ShellCheck-0.4.2-23628/ShellCheck-0.4.2/Setup.hs:15:25:
    Module `System.Process' does not export `callCommand'
Failed to install ShellCheck-0.4.2
cabal: Error: some packages failed to install:
ShellCheck-0.4.2 failed during the configure step. The exception was:
ExitFailure 1
```

**Comment by koalaman** [comment]
Try `cabal install process` first. There's a dependency on process-1.2.0.0+ that didn't make it into the cabal file until yesterday :<

**Comment by gdbtek** [comment]
@koalaman  , it does not seem to solve the issue. Note that I reran another installation on a *fresh* machine

I ran:
```
    cabal update
    cabal install process
    cabal install 'shellcheck'
```

Errors output
```
In-place registering QuickCheck-2.8.1...
Installing library in /root/.cabal/lib/QuickCheck-2.8.1/ghc-7.6.3
Registering QuickCheck-2.8.1...
Installed QuickCheck-2.8.1
Downloading ShellCheck-0.4.2...
[1 of 1] Compiling Main             ( /tmp/ShellCheck-0.4.2-24532/ShellCheck-0.4.2/Setup.hs, /tmp/ShellCheck-0.4.2-24532/ShellCheck-0.4.2/dist/setup/Main.o )
Linking /tmp/ShellCheck-0.4.2-24532/ShellCheck-0.4.2/dist/setup/setup ...
Configuring ShellCheck-0.4.2...
Failed to install ShellCheck-0.4.2
cabal: Error: some packages failed to install:
ShellCheck-0.4.2 failed during the configure step. The exception was:
ExitFailure 11
```

**Comment by aw-altiscale** [comment]
Also seeing this error this morning from our docker container install. :(

**Comment by aw-altiscale** [comment]
Looks like ubuntu/trusty (which is what we've got wired up) ships with 7.6.3.  So I'm guessing anyone on Ubuntu LTS is hitting this issue.

**Comment by koalaman** [comment]
This appears to be the base cause:

```
$ runghc Setup.hs configure

GHCi runtime linker: fatal error: I found a duplicate definition for symbol
   runInteractiveProcess
whilst processing object file
   /usr/local/google/home/holen/.cabal/lib/process-1.4.1.0/ghc-7.6.3/HSprocess-1.4.1.0.o
This could be caused by:
   * Loading two different object files which export the same symbol
   * Specifying the same object file twice on the GHCi command line
   * An incorrect `package.conf' entry, causing some object to be
     loaded twice.
GHCi cannot safely continue in this situation.  Exiting now.  Sorry.
```

**Comment by koalaman** [comment]
Also a problem on latest Debian stable :/

**Comment by koalaman** [comment]
I pushed d473fb88 which should fix this (by allowing uses of older `process` versions).

Would any of you care to verify it?

It seems to build fine from scratch on 7.6.3 on Debian stable, and 7.8.4 on Debian testing, and 7.6.3 again on a Ubuntu LTS derived distro.

**Comment by aw-altiscale** [comment]
It failed for me. :(

https://builds.apache.org/job/PreCommit-YETUS-Build/228/consoleText

**Comment by gdbtek** [comment]
I would love to test but I don't know how to test your PR. If you have any doc on how to test it, let me know.

**Comment by aw-altiscale** [comment]
It was pushed to master, so rebuilding via cabal should test it, right?

**Comment by koalaman** [comment]
Yes, you'd have to clone the repo and `cabal install` from that directory. Specifying a package name, I.e.  `cabal install shellcheck` would instead download from Hackage.

**Comment by aw-altiscale** [comment]
OK, let me try this again then. haha.  :8ball:

**Comment by aw-altiscale** [comment]
:+1: worked here with cabal install from a source check out on U LTS.

**Comment by gdbtek** [comment]
same here, I'm trying to verify it too

**Comment by gdbtek** [comment]
worked for me too! Good to go!

**Comment by aw-altiscale** [comment]
When does this make it to the cabal systems?  Just wondering if I should force our current docker builds to use 0.4.1 in the short term.

**Comment by koalaman** [comment]
I just pushed 0.4.3 with this fix. 

One of these days I'll manage a release that doesn't require a bugfix immediately afterwards -__-

**Comment by aw-altiscale** [comment]
Just a confirmation that our cabal installs from within docker are working again.  Thanks for the quick fix!

BTW, as to your frustration, it might be time to invest in setting up a travis-ci job to test things.  Also, I opened a JIRA against Apache Yetus to add cabal support as a potential part of that solution in the future as well.  Given how reliant we are on shellcheck to test our code, it'd be neat to have Yetus be used to help test shellcheck's patches! :smiley:

**Comment by koalaman** [comment]
Since it supports multiple GHC versions, I'll definitely look into that!
