### ISSUE TITLE
Detect when multi line command does have white spaces after \ before EOL

### ISSUE THREAD

**Issue by slashbeast** [koalaman/shellcheck#576]
When spliting long line into multiple by adding at the end \, shellcheck should detect if there's any white chars after \ and before new line, as it would render the whole split not working.

**Comment by koalaman** [comment]
Nice one. Definitely.

**Comment by arth1** [comment]
Just make sure it doesn't catch intended backslash-space, like:

echo "foo bar" | tr -d \

**Comment by koalaman** [comment]
A warning has been added in 92473b5.  

It also catches `tr -d \  ` at the end of a line because depending on trailing whitespace is madness.
