### ISSUE TITLE
let expressions do not require dollars

### ISSUE THREAD

**Issue by lyokha** [koalaman/shellcheck#588]
Like ``(( ... ))`` ``let`` does not require dollar signs, 

```sh
let "a = b + c"
```

is quite valid, so using dollars for variable expansions like ``let "a = $b + $c"`` should symmetrically give warning ``SC2004`` like in ``(( ... ))`` case.

Accordingly, ``let`` expressions should also collect all variables written without dollars to avoid warning ``SC2034`` about unused variables if they were defined on top of a script and further used only in ``let`` expressions.

**Comment by koalaman** [comment]
`let` should preferably be deprecated. There's `$((..))` in posix and `((..))` in bash.

**Comment by bittorf** [comment]
let has it's own goodies, e.g. the endcondition:
```
J=10
while let J-=1; do echo $J; done
```

**Comment by deryni** [comment]
`((..))` in bash is documented as being exactly equivalent to `let` so for bash (and ksh) at least `let` isn't necessary and `let` appears (from the little I can find right now) to be a bash-ism itself... unless someone knows better.

**Comment by bittorf** [comment]
@deryni - seems you are right, this works:
```
#!/bin/bash
J=10
while (( J-=1 )); do echo $J; sleep 1; done
```

**Comment by koalaman** [comment]
This has been somewhat improved in 86999ded1
