### ISSUE TITLE
there's no automated way to be notified of new releases

### ISSUE THREAD

**Issue by eatnumber1** [koalaman/shellcheck#593]
I just noticed that ShellCheck is up to 0.4.3. As far as I can tell, there's no way to sign up to e.x. a mailing list to get notified of new releases. Can one be made?

**Comment by bittorf** [comment]
@eatnumber1 you can add yourself to the watchlist of github and so you are notified (check your settings) via mail or ...

**Comment by eatnumber1** [comment]
that will add me to every bug filed though. no? What I'm thinking of is more of an announcements mailing list.

**Comment by koalaman** [comment]
Github provides native RSS/Atom feeds for new releases: https://github.com/koalaman/shellcheck/releases.atom

If you prefer email, there are a variety of RSS/Atom-to-email services as well as some github release notification services.

**Comment by eatnumber1** [comment]
cool, didn't know about the feeds. thanks!
