### ISSUE TITLE
Blue on black

### ISSUE THREAD

**Issue by lynnoyoung** [koalaman/shellcheck#596]
Hi,

Thank you for shellcheck.

Reading blue on black is difficult for some of us.

Sincerely,
Lynn

**Comment by bittorf** [comment]
when does this happen? on http://www.shellcheck.net/ ?

**Comment by koalaman** [comment]
For the link text on shellcheck.net? Very true, this is awful. 

I've updated it to #99F which is way brighter and easier to read.

Please reopen if there is other dark blue text I missed.
