### ISSUE TITLE
Wouldn't it be useful to simply verify the pairing of brackets?

### ISSUE THREAD

**Issue by dexdyne** [koalaman/shellcheck#599]
I've had a couple of error reports miles away from the line that caused them.

They were caused by missing brackets on a much earlier line which put the parser right off.

Sure ly a bash command is terminated by EOL - so if you find a line with unpaired, or badly nested brackets - that should be enough to generate a warning.

**Comment by koalaman** [comment]
Do you have an example?

Sometimes one bracket will accidentally but correctly match up with another one, and it's tricky for ShellCheck to know that a syntactically valid construct is unintentional.

**Comment by kurahaupo** [comment]
tl;dr: there is no easy way out.

It is not correct to suppose that a bash command is terminated by EOL.

Bash commands finish when they are complete, however many lines that takes.
Any sort of compound command can span multiple lines, including function
definitions, if/then/else/fi blocks, for-loops, while-loops, braces,
brackets, and pipelines.

And quoted "words" can span multiple lines too.

**Comment by dexdyne** [comment]
yup, k. I understand all that.

I'm not suggesting it should be the primary means of analysis.

However - in a situation where a fault has been detected, it can be caused by a mispaired bracket miles away from the first tagged issue ( take that from me )
What I'm suggesting is a pass over the source using simple "continuation line" rules which understand backslash || && and pipe continuations, and that during that pass flag mis-paired brackets. It WOULD have helped me find my issue much more quickly, which is what the s/w is meant to do.

**Comment by koalaman** [comment]
I'm trying to visualize it. Do you have an example of some bad code showing how it would work?

**Comment by koalaman** [comment]
Feel free to reopen with an example
