### ISSUE TITLE
bug reporting could work better.

### ISSUE THREAD

**Issue by dexdyne** [koalaman/shellcheck#601]
If I have a script on-screen, showing an issue I'd like to submit a bug about, it would be really good to have something to click equivalent to "submit the thing I'm looking at as an attachment to a new bug report"

**Comment by koalaman** [comment]
shellcheck.net now has a "Report bug" link that autofills the template with whatever you see on screen!

https://github.com/koalaman/shellcheck.net/commit/e0c06f3
