### ISSUE TITLE
handling of new paste-ins is clunky.

### ISSUE THREAD

**Issue by dexdyne** [koalaman/shellcheck#603]
When you paste a new script into the top box, couldn't it either 
1. Automatically remove the "It's all good" message and repalce it with "I've not worked on that yet"
or
2. Automatically parse the dratted thing.

?

**Comment by koalaman** [comment]
It should have automatically parsed the dratted thing, and the old version did/does for me on Chrome. 

In any case, please reopen if this is still a problem on the new web interface.

**Comment by dexdyne** [comment]
wilco.
