### ISSUE TITLE
Making small corectiions seems very difficult.

### ISSUE THREAD

**Issue by dexdyne** [koalaman/shellcheck#604]
When a problem in line 399 is reported I would like to be able to go to the top box, find line 399 and fix it.

I haven't worked out if this is possible at all - it certainly isn't obvious.

**Comment by koalaman** [comment]
I assume you mean on the web interface on shellcheck.net, and yes, it's not exactly a debugging IDE. 

It's mostly for demo purposes, and not intended to replace a good programmer's editor with shellcheck installed locally.

**Comment by dexdyne** [comment]
koalaman.

OK - I've clearly missed that idea.
I would love to have this capability on my desktop.
I would pay blood to have it within the eclipse IDE - the shelled extension to that is worse than useless. 
I will go and look at the website again and see if I can find what you are talking about :-)

**Comment by dexdyne** [comment]
OK - I'm getting there. 

I found shellcheck through Google. That landed me on http://www.shellcheck.net/

Now that page does mention "and for local installation guide", but doesn't actually sell or point out the idea that "This web interface will give you a flavour, but for full benefit you should install this on your machine and connect it to your editor"

The meta text "ShellCheck is a free, online and offline tool that detects problems and suggests improvements to shell scripts." is good - but you don't actually see it on-screen... though it does show up in the google description.

**Comment by koalaman** [comment]
I definitely agree. The current web interface is in desperate need of an update.

**Comment by koalaman** [comment]
The web interface has finally been improved, and is now also available as a github project: for pull requests and such: https://github.com/koalaman/shellcheck.net 

It now strongly encourages people to install it locally, while retaining the ability to use/demo it online. Instead of a textarea, it uses a proper javascript editor (Ace) with many standard shortcuts such as Ctrl-F and Ctrl-L for find and go-to-line. 

Try it out and feel free to reopen

**Comment by dexdyne** [comment]
Excellent - many thanks for that. 

Now all we need is eclipse integration :-) 

D 

----- Original Message -----
