### ISSUE TITLE
What is the edit button for on the github page?

### ISSUE THREAD

**Issue by dexdyne** [koalaman/shellcheck#605]
I hit "edit" in the hope of correcting the mis-spelled title of a bug report, but nothing seemed to happen!. I appreciate this isn't the place to report github issues, but if there's a simple answer :-) ??

**Comment by dexdyne** [comment]
If I hover over "New Issue" I see "https://github.com/koalaman/shellcheck/issues/new" at the bottom of the screen - hovering over edit does nothing - checked in chrome and firefox.

**Comment by dexdyne** [comment]
This is a test

**Comment by dexdyne** [comment]
I seem also to have an issue in chrome where clicking "Comment" does send the comment to github, but doesn't refresh the page.

**Comment by dexdyne** [comment]
this is a test in firefox - the other one was chrome.

**Comment by dexdyne** [comment]
On FIrefox the screen DOES refresh. Ho Hum.

**Comment by koalaman** [comment]
No idea, but feel free to keep testing
