### ISSUE TITLE
SC2128: False positive

### ISSUE THREAD

**Issue by derliebemarcus** [koalaman/shellcheck#609]
For debugging reasons, we echo "${*}" inside functions. Shellcheck, however, complains about that. As the suggested solutions are not possible for $* and $@, SC2128 should ignore them. Excluding it from the checks performed is not helpful either.

**Comment by deryni** [comment]
Formatting bit your comment a bit.

That said can you show us a specific example of what you are talking about here? Also with what version of shellcheck you are seeing this? (Do you see this with http://www.shellcheck.net/?)

**Comment by derliebemarcus** [comment]
Sorry for that. The error was totally on my end.
