### ISSUE TITLE
Warn about missing ;; in case

### ISSUE THREAD

**Issue by VanNostrand** [koalaman/shellcheck#611]
if you write this, the bash and shellcheck will not bother:
```
#!/bin/sh
case FOO in
1) ;;
*) 
esac
```
but the syntax is not right due to documentation, where each list is terminated by ;; token, which includes the list of the * pattern. This is from the bash man page:
`case word in [ [(] pattern [ | pattern ] ... ) list ;; ] ... esac`
I don't know how other shells treat this, but the missing ;; in the code above should be detected by shellcheck.

**Comment by koalaman** [comment]
Looks like this is [explicitly allowed in POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/):

>The compound-list for each list of patterns, with the possible exception of the last, shall be terminated with ";;". 
>The ";;" is optional for the last compound-list.
