### ISSUE TITLE
SC2148 on sourced files

### ISSUE THREAD

**Issue by zimbatm** [koalaman/shellcheck#617]
Hi,

when using sourced files it feels weird to have to add the shebang for shellcheck to pick the proper shell flavour. Would it be possible to add another comment pragma that shellcheck can pick instead ? I know that it's possible to pass the flavour using `-s` but syntastic doesn't know how to pass the right shell either.

PS: I love shellcheck ! Thanks a lot for that tool.

**Comment by brother** [comment]
What's the problem with having the bang if having "something else" is ok?

**Comment by brother** [comment]
Also see #581

**Comment by zimbatm** [comment]
Because it's not meant to be executed. Adding a shebang is a signal that the file is supposedly executable.

Thanks, closing duplicate
