### ISSUE TITLE
ShellCheck-0.4.3 fails to install: requires Cabal library version -any && >=1.8 but no suitable version is installed

### ISSUE THREAD

**Issue by moschlar** [koalaman/shellcheck#618]
Installing with Cabal fails on a CentOS 7 system:

``` shell-session
$ cabal install shellcheck
Resolving dependencies...
Failed to install ShellCheck-0.4.3
cabal: Error: some packages failed to install:
ShellCheck-0.4.3 failed during the configure step. The exception was:
user error (The package requires Cabal library version -any && >=1.8 but no
suitable version is installed.)

$ cabal --version
cabal-install version 1.16.1.0
using version 1.16.0 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

**Comment by koalaman** [comment]
I'm not sure why cabal doesn't install the new version of `cabal`, but updating it pulls in a new version of `process` that breaks this three years out of date GHC release. The 0.4.3 was specifically supposed to fix this, but I guess the ecosystem moved on.

I tried it on a fresh install and got it working with

    cabal update
    cabal install process-1.1.0.2 cabal
    cabal install shellcheck

**Comment by michaelmhoffman** [comment]
I got an error with `cabal install process-1.1.0.2 cabal`. The package name seems to require an uppercase `Cabal`.

Deleting my `~/.cabal` and `~/.ghc` and then
```
cabal update
cabal install process-1.1.0.2 Cabal
cabal install shellcheck
```
seems to work.

**Comment by willemdh** [comment]
Tried all of the above but  wasn't able to install..
~/.cabal/bin/shellcheck doesn't exist.

`cabal --version
cabal-install version 1.16.1.0
using version 1.16.0 of the Cabal library
`

**Comment by koalaman** [comment]
Please reopen (with an error message) if this is still a problem.

**Comment by kmatt** [comment]
`yum install ghc-shellcheck-devel` got me past the filepath <-> Cabal dependency
