### ISSUE TITLE
Checking if on a tty fails

### ISSUE THREAD

**Issue by mat813** [koalaman/shellcheck#619]
The standard ```if [ -t ]``` to determine if stdin is currently a terminal makes shellcheck give a lot of errors:

```
In rollover.sh line 16:
if [ -t ]
   ^-- SC1073: Couldn't parse this test expression.
        ^-- SC1019: Expected this to be an argument to the unary condition.
         ^-- SC1072: Unexpected keyword/token. Fix any mentioned problems and try again.
```

**Comment by koalaman** [comment]
Shellcheck is right, even if not especially pedagogic:

     SC1019: Expected this to be an argument to the unary condition.

What you have is equivalent to `[ -n "-t" ]` which is always true. To check if stdin is a terminal, use `[ -t 0 ]`.
