### ISSUE TITLE
Add warning that `dash`doesnt support multi-digit FD in redirection

### ISSUE THREAD

**Issue by redbaron** [koalaman/shellcheck#620]
Just spend an  hour narrowing down error in my shell script to:

Breaks:
``` 
/bin/sh -c '(date) 10>/tmp/lock'
```

Works:
```
/bin/sh -c '(date) 9>/tmp/lock'
```

might be useful if shellcheck warned about it

**Comment by koalaman** [comment]
Didn't know that! 6af1aeb fixes this for sh/dash scripts, but not for embedded `sh -c` type commands.
