### ISSUE TITLE
SC2164: `cd || exit` less useful in process substitution case

### ISSUE THREAD

**Issue by Herst** [koalaman/shellcheck#624]
For

``` bash
#!/bin/bash
comm <(cd dir1; find | sort) <(cd dir2; find | sort)
```

I get "[SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164) Use cd ... || exit in case cd fails."  advising me specifically to use `exit` while I could just as well be doing:

``` bash
#!/bin/bash
comm <(cd dir1 && find | sort) <(cd dir2 && find | sort)
```

Now there might be a case when simply adding an `exit` might seem less awkward, e.g.:

``` bash
#!/bin/bash
main_cmd <(cd dir || exit; cmd1; cmd2; cmd3; cmd4; cmd5; cmd6)
```

But those I would guess such a case to be quite rare. Also note that one of the main "features" of `exit`, the exit code, can't be utilized at all. So I am in fact not sure what the best advise should be, maybe simply adding a little note to the wiki page concerning the process substitution case? Just some food for thought.

**Comment by koalaman** [comment]
I've added a note to this to the wiki. Thanks!
