### ISSUE TITLE
emoji causes user error (Text.Regex.Posix.String died: (ReturnCode 17,"illegal byte sequence"))

### ISSUE THREAD

**Issue by dasilvacontin** [koalaman/shellcheck#635]
Contents of rocket.sh:

``` bash
#!/usr/bin/env bash
echo 🚀
```

From travis build:

``` bash
$ echo $LC_CTYPE

$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

> shellcheck rocket.sh
user error (Text.Regex.Posix.String died: (ReturnCode 17,"illegal byte sequence"))
```

https://travis-ci.org/dasilvacontin/contrib-rocket/jobs/119016424

Works locally, but not on Travis' machines. Let me know if you need more info.

**Comment by dasilvacontin** [comment]
Let me know if you have any thoughts regarding this issue.

**Comment by koalaman** [comment]
Which shellcheck version is this?

**Comment by dasilvacontin** [comment]
Latest I guess, it's being installed via `brew`. I'll give an exact number asap.

**Comment by koalaman** [comment]
It's been two years. Please re-open if you get that version number :P
