### ISSUE TITLE
Feature Request: Produce Suggested Fixes

### ISSUE THREAD

**Issue by eatnumber1** [koalaman/shellcheck#636]
It would be extremely useful if ShellCheck produced suggested fixes for the findings it produces.

One possible way this could be accomplished is by making checks edit the AST (or generate a new one) that they are traversing after they've decided that there's an issue, then new code could be generated. It would then generate JSON looking like the following:

``` json
{"file": "foo.sh",
 "line": 42,
 "startColumn": 42,
 "endColumn": 128,
 "code": 2086,
 "suggestedFix": "\"$foo\""}
```

What kinds of changes would need to happen within ShellCheck to make this happen? I'm happy to contribute code, but my Haskell skills may not be up to this challenge without it being broken down into smaller pieces.

**Comment by koalaman** [comment]
This would primarily require start and end positions for all nodes. At that point one could output character based fixes.

For other than small fixes, it would be helpful to have the ability to serialize chunks of the AST into well formatted bash code. 

You would also need a list of fix deltas at possibly different positions than the main error, and a strategy for merging multiple fixes around the same positions.

Which errors would this be most helpful for?

**Comment by eatnumber1** [comment]
At the moment the biggest help will be for SC2086 and SC2046 since those are the ones that seem to be most confusing people.

**Comment by koalaman** [comment]
Cleaning up old issues, thanks for making this happen!
