### ISSUE TITLE
Documentation for SC2171

### ISSUE THREAD

**Issue by aaronjwood** [koalaman/shellcheck#639]
It would be great to have some documentation on this rule.

In my case this gets thrown for a line like this `each_node=$(echo $each_node | tr -d "'" | tr -d [ | tr -d ])` with the exact message being "Found trailing ] outside test. Missing [? [SC2171]

I'd be more than happy to help contribute documentation for this but I'm not very familiar with the syntax of what's indicated in the message. It seems that quoting the brackets passed to the `tr` command suppresses the warning. What is `[?` that is supposedly missing?

**Comment by kurahaupo** [comment]
> with the exact message being "Found trailing ] outside test. Missing [? [SC2171]

Fair point about the general case, however when Shellcheck highlights code
for some oddball reason, it's worth taking another look anyway.

> `each_node=$(echo $each_node | tr -d "'" | tr -d [ | tr -d ])`

In this case, "tr -d" can take a string of multiple characters, so there's
no need for the isolated ]:

    tr -d "'[]"

And moreover, variable substitution can do what you want better and MUCH
faster:

    each_node=${each_node//[\'\[\]]/}

**Comment by aaronjwood** [comment]
Good to know, thanks!

**Comment by phs75** [comment]
I feel like aaronjwood: It would be great to have some documentation on this rule.

If we don't, we must at least remove the automatic message
 
    For more information:
      https://www.shellcheck.net/wiki/SC2171 -- Found trailing ] outside test. Mi...

**Comment by koalaman** [comment]
I've updated the message and added a wiki page, thanks!
