### ISSUE TITLE
SC2086 may not be catching up on some variables

### ISSUE THREAD

**Issue by mat813** [koalaman/shellcheck#642]
For the following code snippet:

``` sh
function echo2() {
    echo=$1
    shift
    foo="$*"
    $echo $foo
}
```

it outputs

```

Line 5:
    $echo $foo
          ^-- SC2086: Double quote to prevent globbing and word splitting.
```

I think it should say both should be quoted.

**Comment by koalaman** [comment]
Maybe. This is intentional, with the rationale being that you're way more likely to have flags that shouldn't be quoted than you are to have a command name with special characters that do need to be quoted.
