### ISSUE TITLE
add a changelog

### ISSUE THREAD

**Issue by jschauma** [koalaman/shellcheck#651]
Please consider adding a changelog to shellcheck, showing what changes were made between versions.  This will make it easier to identify when a new feature was added and whether or not the current version should have a given features or check.

**Comment by philoserf** [comment]
A change log or release notes would be appreciated.

**Comment by zapashcanon** [comment]
[Keep a changelog](http://keepachangelog.com/) tries to be kinda like semver. Could be used.

**Comment by koalaman** [comment]
A changelog has been added in e801da06
