### ISSUE TITLE
Variables used as references declared as unused

### ISSUE THREAD

**Issue by Earnestly** [koalaman/shellcheck#652]
Sorry if there's already an issue about this however bash's recent `declare -n` feature can confuse shellcheck when variables are past to them by reference, here is a small test case:

``` bash
#!/bin/bash

printarray() {
    declare -n a=$1
    printf '%s\n' "${a[@]}"
}

foo=(One day through the primeval wood)

printarray foo
```

Here shellcheck warns us that: `shellcheck: foo appears unused. Verify it or export it. [SC2034]`

**Comment by rico-chet** [comment]
this affects me too

**Comment by koalaman** [comment]
This is intentional behavior. I have updated the [SC2034 wiki page](https://github.com/koalaman/shellcheck/wiki/SC2034) to be more explicit about this.
