### ISSUE TITLE
SC2034: Doesn't recognize variables used inside a regex

### ISSUE THREAD

**Issue by teancom** [koalaman/shellcheck#656]
<pre>
#!/bin/bash

foo=7
bar="1234567"

if [[ $bar =~ ^[0-9]{$foo}$ ]]; then
  echo 'got here'
fi
</pre>

In that snippet, 'foo' is marked as being unused.

**Comment by koalaman** [comment]
Well caught! This happened for `{$..` due to an overly eager parsing function. Fixed 40136fe
