### ISSUE TITLE
Enhancement: support ignoring single line

### ISSUE THREAD

**Issue by mikeroll** [koalaman/shellcheck#657]
It would awesome to be able to ignore just a single line regardless of the errors in it.
```bash
# this yeilds an SC1083
this_is_a_{template} 

# this will disable SC1083's in the whole file, but I only want one line
# shellcheck disable=SC1083
this_is_a_{template} 

# this is the desired behaviour
this_is_a_{template}  # shellcheck ignore
```

**Comment by mikeroll** [comment]
Alternatively, there could be an option to enable the disabled codes again after the offending line:
```bash
# shellcheck disable=SC1083
this_is_a_{template}
# shellcheck enable=SC1083
```

**Comment by mikeroll** [comment]
Sorry, didn't pay enough attention, `# shellcheck disable=SC1083` works as desired already.

**Comment by koalaman** [comment]
Easy mistake to make. 

Any directives that appear after the shebang and before any command will apply to the entire file. Therefore, if you try to ignore something on the first line you can easily end up ignoring it in the entire file.
