### ISSUE TITLE
Shellcheck does not detect variable usage under let

### ISSUE THREAD

**Issue by kromanenko** [koalaman/shellcheck#659]
Test piece of script:
gt_cpus=`cat /proc/cpuinfo |grep processor|wc -l`
let "total_vcpus = gt_cpus * 3"

Actual result:
$ shellcheck myscript
Line 1:
gt_cpus=`cat /proc/cpuinfo |grep processor|wc -l`
^-- SC2034: gt_cpus appears unused. Verify it or export it.

It would be good if shellcheck could to detect usage of variables under let.

**Comment by koalaman** [comment]
Well caught. There was an old TODO about `let` not handling expressions in quotes which has been improved in 86999de.

This also fixes a bug that caused the unused warning to go missing for total_vcpus
