### ISSUE TITLE
SC2103 not silenced by `set -e`

### ISSUE THREAD

**Issue by me-and** [koalaman/shellcheck#667]
Using `set -e` silences [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164), on the grounds that with `set -e`, the `cd` command cannot fail. However [SC2103](https://github.com/koalaman/shellcheck/wiki/SC2103) is not silenced by `set -e`, despite the rationale being effectively the same.

**Comment by me-and** [comment]
Simple example code that generates SC2103 and shouldn't (fixing with a subshell means setting `var` is lost, and fixing by switching to `cd "$1" || exit` or similar introduces redundant code thanks to the `set -e` line):

```bash
#!/usr/bin/env bash
set -e

cd "$1"
var=$(do_stuff "$2")
cd -

do_other_stuff "$var"
```

**Comment by koalaman** [comment]
Fixed by @contivero, thanks!
