### ISSUE TITLE
${foo:=bar} not recognized as assignment

### ISSUE THREAD

**Issue by charles-dyfis-net** [koalaman/shellcheck#672]
: "${foo:=bar}"

...yields `SC2154: foo is referenced but not assigned.`

However, this particular idiom is explicitly an assignment to `foo` that acknowledges the possibility that it *may not* have had a value previously set. The warning is thus not appropriate in this case.

**Comment by koalaman** [comment]
Indeed. Fixed in 4fc4899, thanks!
