### ISSUE TITLE
regression in SC2034 bar=1 ; ((foo=bar)) doesn't count as use of $bar

### ISSUE THREAD

**Issue by knirch** [koalaman/shellcheck#676]
```bash
foo=1
((t=foo))
```

Yields `foo appears unused. Verify it or export it. [SC2034]`

**Comment by koalaman** [comment]
Great catch! Fixed in 85e69f8

This only happens for 1-on-1 assignments like this, and fortunately not e.g. `(( t = foo + 1 ))`.
