### ISSUE TITLE
SC2154 doesn't understand read -a array [more options]

### ISSUE THREAD

**Issue by knirch** [koalaman/shellcheck#679]
``` bash
read -a foo -r <<<"foo bar"
read -r -a bar <<<"foo bar"
read -a baz -r baz <<<"foo bar"
echo "$foo $bar $baz"
# Line 4:
# echo "$foo $bar $baz"
#       ^-- SC2154: foo is referenced but not assigned.
```

I'm guessing fixing this bug will make shellcheck identify them as arrays, so no point in creating issues about missing array warnings?

**Comment by knirch** [comment]
Looking through my refactor branches that aim to be 100% shellcheck clean I noticed a later commit that changed my use of $foo to ${foo[0}, so it probably worked at some point.

**Comment by koalaman** [comment]
Fixed by @ngzhian. Thanks!
