### ISSUE TITLE
SC2034 detect

### ISSUE THREAD

**Issue by gorgone** [koalaman/shellcheck#681]
shellcheck _get_config_con

In _get_config_con line 33:
                es="${e:0:-2}";USE_vars[$es]=;
                ^-- SC2034: es appears unused. Verify it or export it.

In _get_config_con line 42:
                es="${e:0:-2}";USE_vars[$es]=;
                ^-- SC2034: es appears unused. Verify it or export it.

this is in a function that clears array entry's

**Comment by koalaman** [comment]
This does not appear to be a problem as of the latest commit (testable on shellcheck.net).

Please reopen if you can still reproduce this!
