### ISSUE TITLE
SC2102 not only chars ; associative arrays can handle words

### ISSUE THREAD

**Issue by gorgone** [koalaman/shellcheck#682]
In _get_config_con line 35:
                USE_vars[${e:0:-2}]=;
                        ^-- SC2102: Ranges can only match single chars (mentioned due to duplicates).

**Comment by koalaman** [comment]
I wasn't able to reproduce this on the latest version on shellcheck.net, but I think I see where it'd come from. There are multiple bugs at work. 

I've filed #701 for the fact that `echo var[$foo]` parses as `var[\$foo]`, leading shellcheck to produce SC2102 thinking you have two identical chars in a `[..]` glob. Additionally, associative arrays were poorly supported up until today's 3e5ecaa2. This commit would fix many cases of misparsed assignments like `foo[baar-]=42` which would have fallen back on generic glob parsing and result in this error.

If you can still reproduce this in an assignment statement on the latest version, please reopen this bug.
