### ISSUE TITLE
SC2093 doesn't recognize redirections w/ auto-allocated FD numbers

### ISSUE THREAD

**Issue by charles-dyfis-net** [koalaman/shellcheck#697]
```
        exec {dest_fd}>>"$dest_file"
        ^-- SC2093: Remove "exec " if script should continue after this command.
```

However, in 4.1 or newer this is a redirection of the same form as `exec 3>>"$dest_file"`, but using an auto-allocated FD and storing that FD number to a variable named `dest_fd`.

**Comment by koalaman** [comment]
I'm not getting this error on the latest commit (conveniently testable on shellcheck.net), so it appears to have been fixed.

Please reopen if you can reproduce it on the latest version.
