### ISSUE TITLE
SC2154 overzealous on associative arrays

### ISSUE THREAD

**Issue by JasonYao** [koalaman/shellcheck#705]
## Issue
SC2154 appears to be flagged in associative arrays when certain GNU tool names (e.g. tar, grep, sed, etc.) are used as keys.

## Environment
**OS**: macOS 10.11.5
**Shellcheck version**: 0.4.4

## Reproduction Steps
```sh
# Inside test.sh
#!/usr/bin/env bash

declare -A flagged_packages
flagged_packages[grep]=--with-default-names
flagged_packages[gnu-sed]=--with-default-names
flagged_packages[gnu-tar]=--with-default-names
```

## Testing
```sh
shellcheck test.sh
```

## Output
![shellcheck_flags](https://cloud.githubusercontent.com/assets/3739191/16440860/4cbd7a4e-3df8-11e6-9fb4-36812496604c.png)

**Comment by koalaman** [comment]
Yes indeed. This was fixed just a couple of days ago for #359.
