### ISSUE TITLE
SC2086: Also mention that double quotes guarantee that there will be an argument.

### ISSUE THREAD

**Issue by Herst** [koalaman/shellcheck#706]
I was about to edit the wiki page of SC2086 to also note that double quotes also guarantee you that there will be an argument which I think is worth mentioning.

But I realized that I am not entirely sure about that POSIX-wise but AFAIK:

```sh
printf '<%s>' a $foobar b
```
will output
```
<a><b>
```
if the variable `foobar` is not defined, while
```sh
printf '<%s>' a "$foobar" b
```
will always output:
```
<a><><b>
```

Am I correct? Also, maybe it could also be mentioned separately in `shellcheck` for the case that the variable might be undefined in case people use the unquoted form because they need the splitting or such.

**Comment by Herst** [comment]
I just came across something related again:

```bash
some_cmd "$([ "$some_val" -eq 1 ] && printf '%s' '--some-option')" # causes some_cmd to be always called with a parameter either '--some-option' or '', latter breaks it because it expects non-option arugments to have some other meaning
some_cmd $([ "$some_val" -eq 1 ] && printf '%s' '--some-option') # causes some_cmd to be called with a parameter --some-option or none, this works but shellcheck does not like it
```

**Comment by koalaman** [comment]
You're right, this is standard behavior and quoting would break it.

ShellCheck currently understands when you implement this through arrays with 0 or 1 elements, or with alternate values like `some_cmd ${some_val:+ --some-option}`.

I added a paragraph about this to the wiki. Feel free to improve on it.

**Comment by Herst** [comment]
Great explanation, I love it! :+1:
