### ISSUE TITLE
Allow override of shell type 

### ISSUE THREAD

**Issue by vancluever** [koalaman/shellcheck#707]
Sample code:

```
# vi: ft=sh
# shellcheck shell=bash

# message prints text with a color.
message() {
  declare -A __colors=(
    ["red"]="31"
    ["yellow"]="33"
    ["green"]="32"
    ["reset"]="0"
  )
  local __color="$1"
  local __message="$2"
  if [ -z "${__colors[$__color]}" ]; then
    __color="reset"
  fi
  echo -e "\e[${__colors[$__color]}m${__message}\e[0m"
}
```

When run thru `shellcheck -s sh`, this snippet still produces `SC2039`.

After doing some messing around it looks like the source of the issue is [Syntastic](https://github.com/scrooloose/syntastic) and the fact that it can't check the shell type because there is no shebang, so it defaults to `sh`, passing that to shellcheck.

Would be nice if that could be overridden (it seems a little confusing that if something is explicit in the file via a directive that a global setting would take precedence over that).

**Comment by koalaman** [comment]
You can override the default with a shebang, you can override the shebang with an annotation, and you can override the annotation with a flag. But you can't override the flag.

This mimics shell behavior: `./foo` with no shebang runs a default, `./foo` with a shebang runs the shebang, and `sh foo` runs with sh regardless of what the file says. 

My suggestion would be to instead either configure Syntastic or add a shebang like `#!/bin/bash -n` which will additionally prevent `./foo` from running your script with the wrong shell.
