### ISSUE TITLE
Sub-array expansion not recongnized

### ISSUE THREAD

**Issue by zhatt** [koalaman/shellcheck#712]
The subarray expansion below returns one element not the entire array.

declare -a myarray=( a b c)
status=${myarray[@]:(-1)}                                          
echo "$status"

$ shellcheck myscript
 
Line 3:
status=${myarray[@]:(-1)}                                          
       ^-- SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.

**Comment by koalaman** [comment]
`"${myarray[@]:(-1)}"` actually returns a list of zero or one elements, depending on whether `myarray` is empty.

If you want it to be either a single element or an empty string, you can use `"${myarray[*]:(-1)}"`
