### ISSUE TITLE
False positive: SC2050 ("this expression is constant")

### ISSUE THREAD

**Issue by mokus0** [koalaman/shellcheck#714]
The following example triggers a false-positive SC2050 (the test is not actually a constant expression because the first operand expands iff foo is a valid user name, which is what is being tested here):

    if [[ ~foo = "~foo" ]]; then
      echo "achoo!"
    fi

(Thanks for the excellent tool BTW... if I find the time I'll be happy to fix this particular issue and maybe some others, but time is scarce these days - I'm sure you know how that goes)

**Comment by koalaman** [comment]
Boy, do I ever. This has been fixed in cd489619, thanks!
