### ISSUE TITLE
Add option for formatting script

### ISSUE THREAD

**Issue by AnselmHa** [koalaman/shellcheck#715]
It would be great if there would be an optional formatting (indentation) of given source.

**Comment by ADTC** [comment]
I search "format shell script" on Google and your tool is the number 1 hit. But it has no feature to do it. :(

**Comment by koalaman** [comment]
The top google hit for "format shell script" ought to be `shfmt` on https://github.com/mvdan/sh . 

Hopefully this mention will help make that happen ^^
