### ISSUE TITLE
Create packages for Ubuntu 12.04 LTS and/or 14.04 LTS 

### ISSUE THREAD

**Issue by elyezer** [koalaman/shellcheck#721]
It would be great to have shellcheck built for Ubuntu 12.04 LTS and/or 14.04 LTS because we can easily install it on Travis-CI environment and make shellcheck run for every PR sent to a repository.

If the package is available then the `.travis.yml` file would be like the following:

```
sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y shellcheck
script:
    make lint
```

Instead of needing to compile from source. In this case, the `.travis.yml` will look like the following:

```
sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y cabal-install
    - cabal update
    - git clone https://github.com/koalaman/shellcheck.git
    - cd shellcheck
    - cabal install
    - cd ..
    - export PATH="$HOME/.cabal/bin:$PATH"
    - which shellcheck
script:
    shellcheck ...
```

Also the advantage of having the package is that the build executing time is much faster.

**Comment by elyezer** [comment]
For more information about the build environment Travis offers check https://docs.travis-ci.com/user/ci-environment/.

**Comment by agilgur5** [comment]
A published version newer than v0.3.3 https://launchpad.net/ubuntu/trusty/+package/shellcheck (a _very_ old version...) would really make installation simpler, faster, and use less disk space for non-cabal users. I'm actually a little surprised there's a generic "Debian installation" section when some of the packages aren't maintained..

**Comment by koalaman** [comment]
Totally agree. Any volunteers?

**Comment by Ichimonji10** [comment]
Interestingly, even [Ubuntu 16.04 ships](http://packages.ubuntu.com/xenial/shellcheck) shellcheck 0.3.7, which was [released](https://github.com/koalaman/shellcheck/releases) in April 2015.

**Comment by elyezer** [comment]
It seems this won't be done... closing it.
