### ISSUE TITLE
Warn when comparing the return value to zero

### ISSUE THREAD

**Issue by KellerFuchs** [koalaman/shellcheck#726]
Lots of code cargo-cult the following style:
```sh
do_something
if [ $? -ne 0 ]; then
  handle_error
fi
```

This has several issues, most notably:
- It is easy to accidentally mask the return value, introducing a bug.
- It makes the code non-reuseable under `set -e`.
- It is less clear than using `if ! do_something`.

As such, a warning that suggest the following would make sense:
```sh
if ! do_something; then
  handle_error
fi
```

I've attempted to implement this, but the codebase is fairly difficult to navigate.
Any advise?

**Comment by KellerFuchs** [comment]
CC @lrvick

**Comment by koalaman** [comment]
Agreed. This has been added in 47a7065.

Most of the checks are simple AST matches, but the functionality available to do so is indeed pretty disorganized :/

**Comment by KellerFuchs** [comment]
@koalaman Thanks a bunch  <3
