### ISSUE TITLE
Solution for a lightweight Docker image for shellcheck

### ISSUE THREAD

**Issue by NLKNguyen** [koalaman/shellcheck#727]
Docker Hub has many shellcheck images that are hundreds or gigabytes. The recent PR #722 also has a large image size. I have a way to get rid of those gigabytes. 

My Docker image for shellcheck is only 22 MB. Download size is only 6 MB. Check this out https://hub.docker.com/r/nlknguyen/alpine-shellcheck/. 

The link above has the size breakdown and instruction how to use this image as CLI shellcheck program across OSes (including Windows) as well as using it in a CI. 

The compilation part happens in a separate Docker image, and the necessary binaries are collected to put into a clean Docker image based on the same Alpine distro.

Alpine main package repostitory doesn't have shellcheck, and even if there is, I don't think the package size could be smaller. Furthermore, those packages in the repositories tend to be outdated very soon. Containerizing the program like this Docker image provides an easy way to distribute the up-to-date version to any machine that has Docker, and soon every dev's machine will have Docker just like they all have Git.

The image is automatically built weekly to keep track of the changes from this repo. I can set it to daily though.

I can send a PR  to add reference to this Docker image on README if you want. 

Or, I can set up the Dockerfile and Travis CI script on your repo similarly to my [current repo](https://github.com/NLKNguyen/alpine-shellcheck) that uses Travis CI to build and push the image to Docker Hub. This way the image is built and pushed to Docker Hub after each commit to this repo. This, however, requires the owner of shellcheck repo to setup some Docker credential environment variables https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry

What are your thoughts on this?
P.S. Shellcheck is a very nice tool. I like it a lot. That's why I want to make it more available.

**Comment by koalaman** [comment]
That's awesome. 

There's no more overhead than you'd have with a single, statically compiled binary, but you get all the Docker goodness.

I don't know what Docker convention is, but setting up a dockerfile and Travis CI script on this main repo sounds like a great idea. I'll be happy to do any setup/signup/whatever.

How do we start?

**Comment by NLKNguyen** [comment]
Great,

If you don't have a Travis account yet, then sign up one for free, link to your GitHub account, and enable this repo in your Travis CI page.

To set your Docker Hub credentials securely as environment variables in Travis CI build,  use [Travis Client CLI program](https://github.com/travis-ci/travis.rb#readme) by following [this tutorial](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry) OR via the web, in your repo's settings in Travis. 3 env variables to be set as your Docker Hub credentials: `DOCKER_EMAIL`, `DOCKER_USERNAME`, `DOCKER_PASSWORD`

In your Docker Hub, create a normal repository for the image destination. We don't use Docker's Automated Build repo because it's not flexible enough for our case. We use Travis to do custom build and then push the final image to a normal Docker Hub repo. Give me your [docker-username]/[docker-repo-name] so that I can add to Travis build script.

**Comment by NLKNguyen** [comment]
I've just made the PR. Let's see if it works out.

**Comment by NLKNguyen** [comment]
Thanks for merging. Please let me know how you would want to do documentation about the Dockerfiles. I can bring what I have in my repos over.
