### ISSUE TITLE
SC2059 too strict on printf

### ISSUE THREAD

**Issue by arth1** [koalaman/shellcheck#730]
Consider this:

```bash
logpath=$(/usr/sbin/exim -bP log_file_path | cut -d' ' -f3)
mainlog=$(printf "$logpath" main)
rejectlog=$(printf "$logpath" reject)
```
It seems that SC2059 is overzealous by telling users "Don't use variables in printf patterns" and setting the level as high as warning.  External patterns are often designed with printf in mind.  `sysctl kernel.core_pattern` is another common source.
An info seems more appropriate.

**Comment by koalaman** [comment]
You're right, this should probably be an info message. Additionally, here it's used with parameters, so a message might not even be necessary (unless people frequently think printf works like echo, which I'll look into)

**Comment by arth1** [comment]
There are even some semi-legit cases for using printf for echo, like when in a posix sh and not having `echo -n`.  Of course, it should then be `printf %s "$variable"` and not `printf "$variable"` - in the latter case a warning might be in order if $variable is tainted or contains a %.

**Comment by koalaman** [comment]
I meant if you use `printf` with `echo` semantics, such as replacing `echo $greeting world` with `printf $greeting world`.

This didn't appear to be the case, and it was more common to have a valid format. Still, not much data to go on so I left it as is but changed the level to an info in 87481dc.

This also adds a warning for too many variables in the printf string (`printf '%s %s' foo`) and no variables but additional arguments (`printf foo bar`). Both require the format string to be literal so this can be accurately determined.
