### ISSUE TITLE
$(( expression )) error?

### ISSUE THREAD

**Issue by wisecracker-bazza** [koalaman/shellcheck#739]
Take the code below.
[code]
#!/bin/sh
txt="1234567890"
echo "$(( $txt ))"
echo "$(( ${#txt} - 1 ))"
echo "$(( #txt - 1 ))"
[/code]
Shell Check ERROR window.

[code]
$ shellcheck myscript
 
Line 3:
echo "$(( $txt ))"
          ^-- SC2004: $/${} is unnecessary on arithmetic variables.

$
[/code]
Your code says '$/${} are unnecessary with no other errors.
Now try running line 5 on sh, bash, ksh and zsh.
This is at least one exception to the rule.
TIA.
Bazza.

**Comment by koalaman** [comment]
You're right, but shellcheck also does not produce a warning for `echo "$(( ${#txt} - 1 ))"`. 

It only produces a warning where the `$` is unnecessary, on line 3. 

I've updated the wiki to mention this explicitly.
