### ISSUE TITLE
SC2126 Wrongly warning when using `grep -o`

### ISSUE THREAD

**Issue by andlrc** [koalaman/shellcheck#743]
This post assumes GNU grep. BSD grep also supports `-o` and according to the man page the same would apply.

Using `grep -o pattern file | wc -l` yields SC2126 error, and suggest replacing with `grep -c` instead. 

But `grep -c` count lines matches while `-o` extracts matches strings. And can therefore output multiply strings / pr line, i.e

    $ grep -o a <<< "abc abc"
    a
    a

While `grep -c` with or without `-o` will output:

    $ grep -co a <<< "abc abc"
    1

As the above proves it cannot be safely assumed that the pipe to `wc -l` can be substituted for `grep -c` when `grep -o` is also used.

**Comment by koalaman** [comment]
Indeed. Fixed in 1a8e34b. Thanks!

**Comment by andlrc** [comment]
Wow, thanks for the quick response and fix! :open_mouth: :+1:
