### ISSUE TITLE
Defining function without curly braces gives "SC1073: Couldn't parse this function"

### ISSUE THREAD

**Issue by rasguanabana** [koalaman/shellcheck#748]
According to [documentation](https://www.gnu.org/software/bash/manual/html_node/Shell-Functions.html#Shell-Functions) following function definitions are valid. `for` loop is a compound command, just like any list of commands surrounded by curly braces.
```
function abc()
 for name in "$@"; do
  echo "$name"
 done
```
It could trigger a warning, but it is still a legal syntax.

**Comment by koalaman** [comment]
You're right, of course. Both POSIX and Bash accept any compound command as the function body.

I looked at this for #93, but changing it to accept any compound command muddled more error messages than it fixed. This is a way more common case:

```
function abc()
 for name in "$@"; do
  echo "$name"
 done
}
```

It's sad when valid code fails to parse. I hope it helps to know that having to add `{..}`s helps less advanced users.

**Comment by rasguanabana** [comment]
Is it in any way possible to ignore this with `#shellcheck disable`? Not a big problem, just asking out of curiosity.

**Comment by koalaman** [comment]
No. ShellCheck stops on parsing errors, and will not continue even if disabled.

**Comment by kurahaupo** [comment]
But it might worth noting perhaps that using the "function" keyword like
that is a bash extension, not POSIX.

```
function abc()
 for name in "$@"; do
  echo "$name"
 done
```
