### ISSUE TITLE
shellcheck fails to parse explicit subshell with heredoc

### ISSUE THREAD

**Issue by allanlw** [koalaman/shellcheck#749]
The following is valid in bash:

``` bash
( cat <<FOO )
blah
FOO
```

shellcheck fails to parse this:
```

In test_heredoc.sh line 1:
( cat <<FOO )
^-- SC1073: Couldn't parse this explicit subshell.


In test_heredoc.sh line 4:

^-- SC1072: Unexpected eof. Fix any mentioned problems and try again.
```

**Comment by allanlw** [comment]
Note that another similar, and useful, test case is:
```
( cat <<FOO; cat <<BAR )
blah
FOO
blah blah
BAR

**Comment by brother** [comment]
The example executes fine in shellcheck.net.

And locally at version 0.4.4 built from git some days ago.

`
brother ~$ shellcheck -s sh /tmp/test_heredoc.sh
brother ~$ shellcheck -s dash /tmp/test_heredoc.sh
brother ~$ shellcheck -s ksh /tmp/test_heredoc.sh
brother ~$ shellcheck -s bash /tmp/test_heredoc.sh
brother ~$ cat /tmp/test_heredoc.sh
( cat <<FOO )
blah
FOO
`

**Comment by allanlw** [comment]
Oops! Thank @brother! Evidently I am just running an old version.

Sorry about that! Closing.
