### ISSUE TITLE
Warn about lack of brace expansion inside [[ ]] 

### ISSUE THREAD

**Issue by knirch** [koalaman/shellcheck#761]
Too many times to count have I erroneously tried to use brace expansion inside [[ ]], would be nice if shellcheck could warn about the different expansions that are disabled within [[ ]]. Kind of like SC2144.

**Comment by koalaman** [comment]
Do you have some examples? I haven't seen this in the wild

**Comment by knirch** [comment]
Sorry, I have been email crippled for the past month. Don't really recall what sort of magic I thought might work, but I'm guessing I've at some point in time tried stuff like [[ /tmp/foo == /tmp/{foo,bar} ]], [[ -e /tmp/{foo,bar} ]] etc. Luckily they have all been caught in review/testing here, I sure hope you haven't seen broken code like that in the wild. The test might be more trouble than it's worth for sure.

**Comment by koalaman** [comment]
I've seen globs and arrays used like that, so I can definitely imagine in happening in the same context. Warnings for all three have been added in 6aee12a.
