### ISSUE TITLE
Enhancement: Warn on 'return -#'

### ISSUE THREAD

**Issue by swizca** [koalaman/shellcheck#767]
\# in 'return # ' may not be negative.

Could shellcheck show a warning when encountered?

Had knee jerk:
[[ error condition ]] && return -1

Oops. Chased my tail on that for a bit.

**Comment by kurahaupo** [comment]
More generally please check that any traceable argument to `exit` or
`return` is a decimal number in the unsigned-8-bit range (0~255)?

(Unless the (currently hypothetical) `shopt -s wide_status` is in effect.)

>  # in 'return # ' may not be negative.
>
> Could shellcheck show a warning when encountered?

**Comment by koalaman** [comment]
There's already some support for this: https://github.com/koalaman/shellcheck/wiki/SC2152

It only handles literal values, no variable tracing at this time. 

Try it out on shellcheck.net (which always runs the latest commit) and feel free to reopen if it doesn't cover what you want!
