### ISSUE TITLE
Building v0.4.5 results in compilation error

### ISSUE THREAD

**Issue by jsilverman-blispay** [koalaman/shellcheck#778]
#### For bugs
- My shellcheck version 0.4.5

This is on Ubuntu 14.04 

```# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

Running `cabal install` results in a compile error

#### Here's a snippet or screenshot that shows the problem:

```
# cabal install
Resolving dependencies...
Configuring ShellCheck-0.4.5...
Building ShellCheck-0.4.5...
Preprocessing library ShellCheck-0.4.5...

...(snip many lines of successful compiling)...

[17 of 18] Compiling ShellCheck.Analyzer ( ShellCheck/Analyzer.hs, dist/build/ShellCheck/Analyzer.o )

ShellCheck/Analyzer.hs:41:19:
    Not in scope: `mconcat'
    Perhaps you meant `concat' (imported from Data.List)
Failed to install ShellCheck-0.4.5
cabal: Error: some packages failed to install:
ShellCheck-0.4.5 failed during the building phase. The exception was:
ExitFailure 1
```

Note: I checked out tag v0.4.4 and the build finished OK. So appears to be only a problem in tag v0.4.5

**Comment by PeterDaveHello** [comment]
FYI, I have no problem on Debian 8.

**Comment by hcpl** [comment]
`cabal install` also fails to build v0.4.5 [on Travis CI](https://travis-ci.org/hcpl/pomfload/builds/175618626) under Ubuntu 12.04. Switching to `stack` and using `stack install` solved the issue for me.

**Comment by arth1** [comment]
The mconcat error also occurs on Red Hat Enterprise Linux 6 and ScientificLinux 6, with ghc-7.6.3, all up to date as per cabal update.
Building 0.4.5 from the cabal repository works; building from the svn repository does not.

**Comment by koalaman** [comment]
`mconcat` is probably accidentally exported by some module on some versions. a40efff explicitly adds the right import.

Please reopen if this is still an issue.
