### ISSUE TITLE
SC2181: what about capturing output?

### ISSUE THREAD

**Issue by ljharb** [koalaman/shellcheck#782]
https://github.com/koalaman/shellcheck/wiki/SC2181 seems to be a new warning.

I read through it, and I was wondering what I should do about cases where I want to capture *both* the output and the exit code, and then branch based on the exit code?

**Comment by kurahaupo** [comment]
```
if  var=$( somecmd )
then echo SomeCmd succeeded with output "$var"
else echo SomeCmd failed with status $?
fi
```

**Comment by koalaman** [comment]
Like kurahaupo says, Assignments like `var=$(cmd)` have the exit code of `cmd` so you can use it directly in if statements.

The code in the issue you linked to doesn't use `$?` for anything other than the branch itself, but if you wanted to do that, it would be better to assign it to another variable since branching based on it will also change it. 

Feel free to reopen with any comments or questions!

**Comment by ljharb** [comment]
Thanks, appreciate the help!

**Comment by ljharb** [comment]
(It'd be helpful to add this to the documentation for the error)

**Comment by nicolaiskogheim** [comment]
I want to echo the sentiment of adding this to the relevant documentation.

I came here because I had

```sh
   commit_dates=$(dates "$path")
   [ $? -gt 0 ] && exit 255
```

It worked nicely to change it to

```sh
      if ! commit_dates=$(dates "$path")
      then
          exit 255
      fi
```

**Comment by koalaman** [comment]
Done.

**Comment by antofthy** [comment]
There is another case for use of $?  when you don't know or care which command generated it!
```
case "$(sh -c 'ping -\? 2>&1')" in
*-w*) # we can give a wait deadline       (Linux/FreeBSD)
         ping -c 1 -w 5 $Vamp >/dev/null 2>&1 ;;
*-c*) # yes so give it a -c option
        ping -c 1 $Vamp >/dev/null 2>&1 ;;
*)    # No -c option, so don't provide it (very old style - Solaris)
       ping $Vamp 5 >/dev/null 2>&1 ;;
esac
if [ $? -ne 0 ]; then
  echo >&2 "ERROR: Client Host \"$Vamp\" does not seem to be online!"
  exit 0;
fi
```
From a old script (almost 30 years old) that ran on a LOT of different machines.
PPS: the use of sh was needed on very old shells (that predated the use of $(...)  )
