### ISSUE TITLE
shellcheck: unable to decommit memory: Invalid argument (0.4.4)

### ISSUE THREAD

**Issue by austin987** [koalaman/shellcheck#785]
Howdy,

I recently upgraded my project to using shellcheck 0.4.4 on travis-ci.org to take advantage of the new global file exclusions (#777). After doing so, shellcheck is throwing lots of errors on my project, with the message:
+shellcheck -s sh src/winetricks
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument
shellcheck: unable to decommit memory: Invalid argument

What's interesting is that it only occurs on Linux (Ubuntu):
https://travis-ci.org/Winetricks/winetricks/jobs/177866938

But not OS X with 0.4.5:
https://travis-ci.org/Winetricks/winetricks/jobs/177866939

is this a known issue with 0.4.4? I glanced through the commits between 0.4.4 and 0.4.5, but didn't see anything relevant. Unfortunately, Ubuntu's latest is 0.4.4:
https://launchpad.net/ubuntu/+source/shellcheck

so if it is fixed in 0.4.5, I'd like to know so I can ask Ubuntu to bump it.

P.S., I hate filing a bug for this since it's a previous version, but I couldn't find an IRC channel to ask about this. Is there one I'm unaware of?

**Comment by koalaman** [comment]
I haven't seen this error before. From what I can tell from GHC issues [12865](https://ghc.haskell.org/trac/ghc/ticket/12865) and [12495](https://ghc.haskell.org/trac/ghc/ticket/12495), it may happen when GHC/shellcheck is built on a newer system but runs on one with an older kernel.

**Comment by austin987** [comment]
Makes sense. How should I proceed? I can reliably reproduce, so I can file
a Ubuntu bug, but I'm curious if there's a testcase you would like to to
try, or something else, first.

**Comment by koalaman** [comment]
I don't really have any good suggestions. If your Ubuntu kernel and all related packages are up to date and you're still getting this, I would just file a Ubuntu bug and see what they say.

**Comment by austin987** [comment]
Well it's travis-ci, so I assume they are ;).

I didn't know if you wanted some sort of logs or something. Thanks.

**Comment by austin987** [comment]
Reported upstream:
https://bugs.launchpad.net/ubuntu/+source/shellcheck/+bug/1650846

**Comment by renekliment** [comment]
We're experiencing the same thing over at https://github.com/alexa-pi/AlexaPi/pull/120 This is very unfortunate.
@austin987 Have you tried running it under Ubuntu 14.04 instead of 12.04?

**Comment by austin987** [comment]
@renekliment I'm testing under trusty / 14.04:
https://github.com/Winetricks/winetricks/blob/master/.travis.yml#L6

**Comment by kurahaupo** [comment]
If you need an IRC channel, you could try #bash on freenode. It's not strictly a shellcheck channel, but Koalaman and I both hang out there, as do a number of other serious shellcheck users.

**Comment by renekliment** [comment]
@austin987 I've tried it also and wasn't able to make it work. I see it doesn't work for you either (almost wasn't able to spot those error messages in the build log - https://travis-ci.org/Winetricks/winetricks/jobs/187364963#L360, haha). Too bad :disappointed:

**Comment by renekliment** [comment]
@austin987 Ended up using `trusty-backports/universe shellcheck amd64 0.3.3-1~ubuntu14.04.1`. At least `trusty-backports` is available when using `sudo: required` and the thing builds and works (example: https://travis-ci.org/alexa-pi/AlexaPi/jobs/187689160).

There is a PR for whitelisting that repo ( https://github.com/travis-ci/apt-source-whitelist/pull/308 ), but looking at the number of PRs and issues, I wouldn't be very enthusiastic about it, although this is a repo that makes sense.

**Comment by austin987** [comment]
Thanks for the suggestion, but downgrading isn't a serious solution for me.

**Comment by ccztux** [comment]
Hi!

I also get this error when using shellcheck in conjunction with travics ci, but not using the debian package. I use the latest docker image:

[glsysbackup](https://travis-ci.org/ccztux/glsysbackup)

**Comment by sobolevn** [comment]
Same issue here:

```yaml
   - os: linux
      sudo: required
      language: ruby
      addons:
        apt:
          sources:
          - debian-sid
          packages:
          - shellcheck
```

Generates: 

> shellcheck: unable to decommit memory: Invalid argument

Link to job: https://travis-ci.org/sobolevn/git-secret/jobs/208007733

**Comment by edannenberg** [comment]
I can confirm the issue, but it doesn't seem to affect the test outcome. Valid code passes the build, lint warnings are detected and fail the build. The decommit messages appear in either case.

**Comment by deiga** [comment]
This also happens when running inside docker (koalamans image) on Debian 3.16.39

**Comment by PeterDaveHello** [comment]
This also happens when running inside official docker image (v0.4.6)

**Comment by wknapik** [comment]
Also seeing this in containerized jenkins builds based on debian-stretch. Shellcheck 0.4.4 from the distro package.

**Comment by runejuhl** [comment]
@zeldor 
Had the same problem with our CI pipeline; ended up just using a newer shellcheck. My image is based on Ubuntu xenial but adds artful sources and installs shellcheck from artful (`apt-get install -y -t artful shellcheck`).

**Comment by zeldor** [comment]
@runejuhl thank you for your reply and constructive suggestion. 
Will try out to add some newer repository with shellcheck.
