### ISSUE TITLE
Parse error when disable instruction above a one-line case item

### ISSUE THREAD

**Issue by Pawamoy** [koalaman/shellcheck#787]
- Rule Id: SC1073, SC10723, SC1085
- My shellcheck version: 0.4.4 
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [x] It is reproducible on shellcheck.net

#### Here's a snippet that shows the problem:
```sh
#!/bin/bash

## \brief Create a new virtualenv in WORKON_HOME.
## \require coreutils

include core/shellman.sh

[ $# -eq 0 ] && usage

main() {
  while [ $# -ne 0 ]; do
    case $1 in
      ## \option -p, --python
      ## Python interpreter to install in the virtualenv
      -p|--python) VENV_OPT="--python=$2"; shift ;;
      ## \option -h, --help
      ## Prints this help and exit
      -h|--help) shellman -t "$0"; exit 0 ;;
      # shellcheck disable=SC2086
      *) [ -d "${WORKON_HOME}" ] && virtualenv ${VENV_OPT} "${WORKON_HOME}/$1" ;;
    esac
    shift
  done
}

## \usage mkvirtualenv [-p PYTHON] <VENV_NAME>
main "$@"

```

#### Here's what shellcheck currently says:
```
In bin/mkvirtualenv line 19:
      # shellcheck disable=SC2086
      ^-- SC1073: Couldn't parse this case item.
        ^-- SC1072: Expected ) to open a new case item. Fix any mentioned problems and try again.
        ^-- SC1085: Did you forget to move the ;; after extending this case item?
```

#### Here's what I wanted or expected to see:
I expected shellcheck to be able to parse the disable instruction above a one-line case item :+1:

**Comment by Pawamoy** [comment]
I just tried on version 0.4.5 and it behaves the same :haircut_man:

**Comment by koalaman** [comment]
This is currently working as intended: annotations are only supported in front of complete commands/structures. Hopefully it's not too annoying to rewrite it as:

```
*) 
  # shellcheck disable=SC2086
  [ -d "${WORKON_HOME}" ] && virtualenv ${VENV_OPT} "${WORKON_HOME}/$1" ;;
```

**Comment by Vladimir-csp** [comment]
Just stumbled on this trying to annotate an expression in a case item. Case structure can be pretty long, annotating the whole thing to silence one false positive for a single variable in a single item would also silence a lot of potential real problems.
