### ISSUE TITLE
SC2046 and command substitutions in arrays

### ISSUE THREAD

**Issue by AladW** [koalaman/shellcheck#790]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
SC2046

- My shellcheck version (`shellcheck --version` or "online"): 
shellcheck --version
ShellCheck - shell script analysis tool
version: 0.4.5
license: GNU General Public License, version 3
website: http://www.shellcheck.net

- [X] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### For new checks and feature suggestions
- [X] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [X] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:
The following script splits on spaces due to an unquoted command substitution (SC2046):
```
#!/bin/bash
array=($(printf %s\\n 'foo bar' baz))
set -- "${array[@]}"
printf %s\\n "$@"
```
Output:
```
foo
bar
baz
```
Which is effectively the same as:
```
#!/bin/bash
set -- $(printf %s\\n 'foo bar' baz)
printf %s\\n "$@"
```
Output:
```
foo
bar
baz
```

#### Here's what shellcheck currently says:
Shellcheck gives no warning on the script using the array, unlike the script using the command substitution directly.
```
archie@thinkpad ~ % shellcheck shellcheck-sc2046.sh
archie@thinkpad ~ % shellcheck shellcheck-sc2046-2.sh

In shellcheck-sc2046-2.sh line 2:
set -- $(printf %s\\n 'foo bar' baz)
       ^-- SC2046: Quote this to prevent word splitting.
```

#### Here's what I wanted or expected to see:

I expect shellcheck to also warn when using unquoted command substitutions in arrays, as the problematic described in SC2046 also applies there.

**Comment by koalaman** [comment]
Specialized warnings specific to arrays have been added in 3c75674. See also #864

**Comment by AladW** [comment]
Thanks
