### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by majgis** [koalaman/shellcheck#791]
What are your thoughts on supporting npm packaging?

**Comment by majgis** [comment]
https://www.npmjs.com/package/shellcheck

**Comment by koalaman** [comment]
For the shellcheck web frontend?

**Comment by wsxiaoys** [comment]
would love to have this for ease of integrating into a node js server

**Comment by koalaman** [comment]
I'm not up to speed on these things. What functionality is it you're looking for in node? A function `shellcheck(scripttext, options, callback)` that produces an array of warnings?

**Comment by wsxiaoys** [comment]
Sort of. While I'm fine doing this through a subprocess with exec as long as binary dependencies can be handled, just like https://github.com/imagemin/pngquant-bin/tree/master/vendor

**Comment by MoritzKn** [comment]
You can pack all sort of stuff into npm packages -- not just JavaScript. Shellcheck as npm package would be helpful because other npm packages could depend on it and use it to use internal scripts and stuff without requiring developers to install anything but the npm package.

**Comment by Aghassi** [comment]
Second @MoritzKn . We have a bunch of build scripts for our NPM repos that we want shellchecked. For now, we use CircleCI + the docker container to check those things. But, if we could have it earlier it would be nice.

**Comment by lonix1** [comment]
Is there a current and supported npm package? Or even better, an eslint plugin?

All I could find is [npmjs.com/package/shellcheck](https://www.npmjs.com/package/shellcheck), which seems abandoned (and there's no associated github repo).
