### ISSUE TITLE
New check: tempfile is deprecated

### ISSUE THREAD

**Issue by szepeviktor** [koalaman/shellcheck#793]
As its man page says: tempfile is deprecated, use mktemp

Please add a rule.

Thank you.

**Comment by Speeddymon** [comment]
http://www.unix.com/man-page/linux/1/tempfile/

On CentOS 6 and 7, tempfile is not even available in the repositories.

If this is a valid command on any modern OS, it should indeed be noted in shellcheck that it is deprecated in favor of mktemp.

**Comment by koalaman** [comment]
`tempfile` is part of `debianutils`. cf1c46d adds a warning.
