### ISSUE TITLE
Arithmetic evaluation (( )) should be preferred over 'let'

### ISSUE THREAD

**Issue by facutuesca** [koalaman/shellcheck#813]
let is very similar to (( - the only difference being let is a builtin (simple command), and (( is a compound command. The arguments to let are therefore subject to all the same expansions and substitutions as any other simple command - requiring proper quoting and escaping - whereas the contents of (( aren't subject to word-splitting or pathname expansion (almost never desirable for arithmetic). For this reason, the arithmetic compound command should generally be preferred over let.[0]

http://wiki.bash-hackers.org/commands/builtin/let

**Comment by koalaman** [comment]
Agreed. There is now a warning for this in `bash` and `ksh` scripts (`sh`/`dash` still notifies that `let` is undefined)
