### ISSUE TITLE
Failure downloading ghc while brew installing shellcheck

### ISSUE THREAD

**Issue by gregt590** [koalaman/shellcheck#821]
While trying to resolve a problem with Atom 1.12.9 crashing with an "Error: spawn shellcheck ENOTENT error" I attempted to install shellcheck on my mac OS X 10.12.2 desktop system and ran into the following error:

Gregs-Mac:~ Greg$ brew install shellcheck
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing dependencies for shellcheck: ghc, cabal-install, gmp, pandoc
==> Installing shellcheck dependency: ghc
==> Downloading https://downloads.haskell.org/~ghc/7.10.3/ghc-7.10.3b-src.tar.bz2
######################################################################## 100.0%
curl: (22) The requested URL returned error: 405 Not Allowed
Error: Failed to download resource "ghc"
Download failed: https://downloads.haskell.org/~ghc/7.10.3/ghc-7.10.3b-src.tar.bz2
Gregs-Mac:~ Greg$ 

Is anyone else running into this problem?

**Comment by DomT4** [comment]
Your Homebrew is _way_ out of date. Try:

```bash
cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update
```
And try your initial step again.

**Comment by gregt590** [comment]
Thanks for the suggestion.  I had problems updating Homebrew as well and eventually determined various problems were likely caused by anaconda which was substituting curl and had other side effects.   Clearing it out solved the various problems including the earlier Atom shellcheck issue.
