### ISSUE TITLE
SC2154: should not fail on "[[ -v foo ]]"

### ISSUE THREAD

**Issue by sumpfralle** [koalaman/shellcheck#828]
- SC2154
- 0.4.4
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/bash

[[ -v foo ]] && echo bar
```

#### Here's what shellcheck currently says:
  `^-- SC2154: foo is referenced but not assigned.`

#### Here's what I wanted or expected to see:
Everything should be fine, since I just test, if a variable is defined.
The bash manpage describes the `-v` test:
  `True if the shell variable varname is set (has been assigned a value).`
Thus I assume that it should be acceptable to test for the existence of a variable.

Thank you for your time!

**Comment by sumpfralle** [comment]
The same happens for `: ${foo:=2}`. I am not sure, if this is related.

**Comment by koalaman** [comment]
You're right. This has been fixed in 41b6e3d. Thanks!
