### ISSUE TITLE
Disable directives are ignored inside of heredoc

### ISSUE THREAD

**Issue by austin987** [koalaman/shellcheck#832]
- Tested with shellcheck 0.4.5 and shellcheck.net
- [Y] I tried on shellcheck.net and verified that this is still a problem on the latest commit

This is a trimmed down version of some production code. I can see why the parser would be confused by it, but it's not worth rewriting, so I put in a disable directive:
```sh

#!/bin/bash
time foo <<EOF
# shellcheck disable=SC2183
foobar | grep "$(printf "%03s %03s % 2s" $(date | awk '{ print $1, $2, $3 }'))"
EOF

```

Shellcheck still warns though. If I move it out of a heredoc, then shellcheck respects the directive (and complains that $(date ..) isn't quoted, which is, of course, expected:
```sh

#!/bin/bash
# shellcheck disable=SC2183
foobar | grep "$(printf "%03s %03s % 2s" $(date | awk '{ print $1, $2, $3 }'))"

```

**Comment by koalaman** [comment]
It's a constant source of confusions and so maybe shouldn't have been done this way, but directives are only accepted when they appear as comments in front of commands (including compound commands).

You could do this:

```
# shellcheck disable=SC2183
time foo <<EOF
foobar | grep "$(printf "%03s %03s % 2s" $(date | awk '{ print $1, $2, $3 }'))"
EOF
```

If it's a literal string and not a comment, then shellcheck won't respect it. This includes when it's in single quotes, double quotes or in here docs.
