### ISSUE TITLE
Inappropriate SC2086 on : line

### ISSUE THREAD

**Issue by pepa65** [koalaman/shellcheck#835]
shellcheck version: 0.4.5, also online
SC2086 Double quote to prevent globbing and word splitting.

I'm currently using code like `: ${TLDR_DESCRIPTION_STYLE:= Space Yellow }` in order to give a default to environment variables when they are empty.
I think when unquoted variables are found after a `:` this flag should not come up, because any globbing/wordsplitting would be irrelevant in principle (unlike after eg. `test`).

Depending on your taste/styleguide another message might be shown of course.

**Comment by koalaman** [comment]
While not a practical problem, there are actually some theoretical edge cases that warrants quoting. See #826 and #480.

**Comment by pepa65** [comment]
Excellent, thank you for your patience and explanation!
