### ISSUE TITLE
SC2004 : False positive on $(( ${!foo} )) construct in bash

### ISSUE THREAD

**Issue by waptaff** [koalaman/shellcheck#868]
This construct using an [indirect reference](http://www.tldp.org/LDP/abs/html/ivr.html) triggers a warning on shellcheck 0.4.6:

```
#!/bin/bash
foo=bar
bar=1234
echo $(( ${!foo} + 1 ))
# Previous echo outputs 1235
```
shellcheck complains: `SC2004: $/${} is unnecessary on arithmetic variables.`

I *think* there should be an exception in SC2004, allowing indirect references, like in the `${#var}` and `${var%-}` cases.

**Comment by koalaman** [comment]
Good catch! Additionally, the same bug triggered on `(( $! ))`. 

Fixed in 8e5e77a
