### ISSUE TITLE
Add a command line switch equivalent to `# shellcheck source=`

### ISSUE THREAD

**Issue by LukeShu** [koalaman/shellcheck#882]
- [X] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

To borrow the example from the SC1090 wiki page:

```
. "$(find_install_dir)/lib.sh"
```

will cause shellcheck to throw SC1090.  The solution is to throw in a directive:

```
# shellcheck source=src/lib.sh
. "$(find_install_dir)/lib.sh"
```

If there are a bunch of such includes, I don't want to have to add an ugly directive before each of them.  I don't want to disable SC1090 either.

What I would like is to be able to set up a mapping of expression to file location that shellcheck uses.  Perhaps via command line arguments: `shellcheck --source='$(find_install_dir)/lib.sh=src/lib.sh' --source='$(find_install_dir)/msg.sh=src/msg.sh'`

Of the 3 directives that shellcheck supports, `source=` is the only one without a flag equivalent.

**Comment by koalaman** [comment]
Do you have multiple statements that source the same file, or are these a bunch of different files all sourced from the same directory?

If you source the same file many times, could you use a directive to cover all of them or are they interleaved?

**Comment by LukeShu** [comment]
My actual usecase involves around 35 scripts that have header sections that look like

    . "$(librelib messages)"
    . "$(librelib conf)"

Where there are around 10 different library files that might get included.

**Comment by LukeShu** [comment]
What about being able to specify a separate program that when given a non-constant expression for a file, it returns a filepath that shellcheck should use for it?  Offload the file resolution to a separate tool?

**Comment by reidpr** [comment]
I have the following in my scripts:

```
LIBEXEC="$(cd "$(dirname "$0")" && pwd)"
. "${LIBEXEC}/base.sh"
```

One can run the scripts either from the source directory or installed to a standard location for executables. If installed, we rewrite `LIBEXEC` to a constant string containing the appropriate directory, which is not the same as the scripts.

For example, if the source code is in `/usr/local/src/foo`, the scripts as well as `base.sh` reside in `/usr/local/src/foo/bin`. If we then `make install PREFIX=/usr/local`, the scripts go in `/usr/local/bin` and `base.sh` goes in `/usr/local/libexec/foo`. (This is consistent with FHS.)

Thus, in addition to not wanting to put a directive in every script, I cannot without modifying the installation procedure to rewrite two things, and that's pretty ugly.

Currently I disable SC1090. I'd prefer to provide a command line switch saying "files you can't find are in this directory".

**Comment by matthewpersico** [comment]
I routinely just exception away all sourcing because I use environmental bars to locate my files. Can you add —source-from 
=none to totally turn that functionality off?

**Comment by koalaman** [comment]
This would just be changing what `.` means in `source=./src/lib/libname.sh`, instead of always having it be ShellCheck's current working directory.

**Comment by esgott** [comment]
This would be super useful

**Comment by koalaman** [comment]
With 301705edea you can specify `-P SCRIPTDIR`  to search relative to the script's directory, or `-P /my/path` to search relative to a path in the filesystem.

This affects both relative and absolute paths, both in `source` directives and literal pathnames handed to `source`/`.`
