### ISSUE TITLE
Wiki #:SC2078 Missing!

### ISSUE THREAD

**Issue by redsoxno10** [koalaman/shellcheck#890]
#### For bugs
- Rule Id (if any, e.g. SC1000): SC2078
- My shellcheck version (`shellcheck --version` or "online"): Latest version as of 4/26/17
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:
<img width="1017" alt="screen shot 2017-04-26 at 12 05 39 am" src="https://cloud.githubusercontent.com/assets/13617534/25422142/af62b020-2a14-11e7-8b8e-3453a241c595.png">

your script here

>...
>if [ "$1" = "revert" ]; then
>>if [[ "grep '# defmacaddr' ~/extention-programs/mac.sh | head -1" ]]; then

>echo "ONE!"
>...

#### Here's what shellcheck currently says:

<nothing, there is no entry>
https://github.com/koalaman/shellcheck/wiki/SC2078

#### Here's what I wanted or expected to see:
a wiki page for it.

ty!

**Comment by koalaman** [comment]
Oops! I've added this page, thanks.
