### ISSUE TITLE
Question: specify `source=...` with path relative to current file

### ISSUE THREAD

**Issue by zbeekman** [koalaman/shellcheck#895]
Is there a way to specify `#shellcheck source={dir-of-this-file}/other-file.sh`? By default shellcheck interprets paths in `source=` directives as relative to the location from which shellcheck is launched.

Many thanks

**Comment by koalaman** [comment]
Currently no, but there's #769

**Comment by nihilus** [comment]
You should use 'proot' for chroot'ing to the parent directory of your scripts, if that is desirable.
