### ISSUE TITLE
Why is -x option not enabled by default?

### ISSUE THREAD

**Issue by CeleritasCelery** [koalaman/shellcheck#902]
The -x option seems useful but doesn't really have a downside. Is there some reason you would not want it enabled?

**Comment by seriousben** [comment]
To me it seems like it is not enabled because normally you would pass files allowed to be sourced as part of the FILES arguments. The `-x` flag is defined as `"Allow 'source' outside of FILES.`

**Comment by koalaman** [comment]
It's an overly cautious default, mostly inspired by the web interface, CI systems and me running shellcheck on people's random scripts on IRC on a regular basis. Flycheck would be perfectly fine having `-x` as a default. 

Here's from https://github.com/koalaman/shellcheck/wiki/Integration

## Decide whether you want to follow `source`d files that are not specified as input

Shell scripts can source/`.`/include arbitrary files. ShellCheck will by default not follow such include statements (unless specified on the command line), in case a hostile script tries to `source /dev/zero` to DoS the system, or `source ~/.ssh/id_rsa` to try to crash with an interesting message.

```
$ shellcheck foo
In foo line 2:
source bar
^-- SC1091: Not following: bar was not specified as input (see shellcheck -x).
```

This is useful for remote services like shellcheck.net which accepts arbitrary input from untrusted users, but mostly pointless for e.g. a local editor plugin.

Add `-x` to shellcheck if you would like it to trust the script and follow all includes. To only follow certain includes, add them as file arguments.

**Comment by CeleritasCelery** [comment]
Thank you for that explanation.

**Comment by cpitclaudel** [comment]
Thanks, indeed. I'm a bit wary about this:

>  in case a hostile script tries to source /dev/zero to DoS the system, or source `~/.ssh/id_rsa`

Flycheck hasn't traditionally been very security-conscious, but I'd like it to get better.  If indeed the only risk is performance, though, I'm fine with using `-x` as the default in Flycheck.  Thanks for taking the time to explain :)

**Comment by brodygov** [comment]
Not sure I fully understand the security implications of the default, but I ran into this through

https://github.com/vim-syntastic/syntastic/issues/1957

Perhaps we could at least add some documentation to https://github.com/koalaman/shellcheck/wiki/SC1091 describing the background? I had to do some digging to understand whether `-x` was something I wanted.
