### ISSUE TITLE
Windows Distribution.

### ISSUE THREAD

**Issue by aadrian** [koalaman/shellcheck#915]
Please add a Windows distribution too.

Thank you.

**Comment by Nightfirecat** [comment]
You can install this on Windows just fine [via Cabal](https://github.com/koalaman/shellcheck#installing):

```
cabal update
cabal install ShellCheck
```

**Comment by aadrian** [comment]
> You can install this on Windows just fine via Cabal

No, I can't, nor can most windows users :) .

**Comment by Nightfirecat** [comment]
I've had no issues doing that on each of my Windows boxes... Can you explain a little further why that didn't work for you? What have you tried, and what did or didn't work?

**Comment by aadrian** [comment]
@Nightfirecat There's a distribution for each OS, only for Windows there's none.

I haven't asked for **yet another package manager** that I need to install only to be able to install what I actually needed. Also cabal needs to be able to get out throughout corporate portals, or users need to learn how to do that too.

**Comment by koalaman** [comment]
The distro releases are independently maintained by awesome individuals. 

What's the package manager you currently use for Windows?

**Comment by aadrian** [comment]
> What's the package manager you currently use for Windows?

There are no widely used package managers for Windows applications, hence the widespread use of installers when distributing them: https://en.wikipedia.org/wiki/List_of_installation_software
Few already used with Haskell too: 
  - https://github.com/ndmitchell/nsis
  - http://hackage.haskell.org/package/bamse
  
If the application consists of a single EXE file (no dependencies), than a simply zip with it will also do it.

**Comment by ksrb** [comment]
@aadrian the [Chocolatey project](https://github.com/chocolatey/choco) has some traction you can submit a request for a package [here](https://github.com/chocolatey/chocolatey-package-requests).

**Comment by koalaman** [comment]
I've convinced TravisCI to build Windows executables by running Wine in Docker (5cece759c). Builds are pushed to GCS. 

The latest commit is now available on https://storage.googleapis.com/shellcheck/shellcheck-latest.zip , and I've added this to the readme.

**Comment by aadrian** [comment]
> I've convinced TravisCI to build Windows executables by running Wine in Docker 

https://www.appveyor.com/  is practically Travis for Widows. It's also free for open source projects.

> The latest commit is now available on https://storage.googleapis.com/shellcheck/shellcheck-latest.zip , and I've added this to the readme.

This is fantastic :) !.

Thank you very much!

**Comment by theimpostor** [comment]
FWIW you can easily install cabal on windows with https://chocolatey.org/, simply run:

`choco install ghc -y`

Then you can do

```
cabal update
cabal install ShellCheck
```

**Comment by Kristinita** [comment]
### 1. Choice

**If** you not a Haskell developer:

    Scoop is quick solution — 5.5 MB.

**else** [**@theimpostor method**](https://github.com/koalaman/shellcheck/issues/915#issuecomment-350845520):

    you need to install big dependency [**ghc**](https://chocolatey.org/packages/ghc) — 180 MB.

### 2. Demonstration

```text
C:\Users\SashaChernykh>scoop install shellcheck
Installing 'shellcheck' (0.4.7) [64bit]
shellcheck-v0.4.7.zip (5.5 MB) [==============================================================================] 100%
Checking hash of shellcheck-v0.4.7.zip… ok.
Extracting… done.
Running pre-install script…
Linking ~\scoop\apps\shellcheck\current => ~\scoop\apps\shellcheck\0.4.7
Creating shim for 'shellcheck'.
'shellcheck' (0.4.7) was installed successfully!

C:\Users\SashaChernykh>refreshenv
Refreshing environment variables from registry for cmd.exe. Please wait…Finished..

C:\Users\SashaChernykh>shellcheck
No files specified.

Usage: shellcheck [OPTIONS…] FILES…
  -a                --check-sourced          Include warnings from sourced files
  -C[WHEN]          --color[=WHEN]           Use color (auto, always, never)
  -e CODE1,CODE2..  --exclude=CODE1,CODE2..  Exclude types of warnings
  -f FORMAT         --format=FORMAT          Output format (checkstyle, gcc, json, tty)
  -s SHELLNAME      --shell=SHELLNAME        Specify dialect (sh, bash, dash, ksh)
  -V                --version                Print version information
  -x                --external-sources       Allow 'source' outside of FILES
```

Thanks.

**Comment by unixandria-xda** [comment]
The linked google storage is dead.

I'll make the same points as above: i don't want to install yet another package manager, which also requires a bunch of other stuff to be installed, so we're up to 5+ programs you have to install just to install shellcheck, and then it's not available to eg vscode by default because of the weird install location.

**Comment by unixandria-xda** [comment]
Choco itslef drags in python, and various visual studio dependencies
