### ISSUE TITLE
Pre-defined rules in ShellCheck

### ISSUE THREAD

**Issue by Rajeswa** [koalaman/shellcheck#918]
I want to know the pre-defined rules used in Shellcheck for code analysis or the location where i can get the rules so that we can decide whether it matches our needs & implement it.

**Comment by brother** [comment]
Something like this: https://github.com/koalaman/shellcheck/blob/master/ShellCheck/Checks/Commands.hs ?

A great portion of the actual shellcheck code is the rules. Make sure to read the wiki as well: https://github.com/koalaman/shellcheck/wiki

**Comment by koalaman** [comment]
The wiki is the closest thing to a list.
