### ISSUE TITLE
SC1001 should at least acknowledge alias suppression as the potential intent of a backslash-quoted initial command-name letter

### ISSUE THREAD

**Issue by mklement0** [koalaman/shellcheck#927]
#### For bugs
- SC1001 
- online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

I know that there are preexisting, closed issues (#552, #485, #188), but I think the issue is worth revisiting.

Unlike what the [wiki](https://github.com/koalaman/shellcheck/wiki/SC1001) entry states:

* `\foo` for alias suppression _is_ POSIX-compliant (as are `'foo'` and `"foo"`), from what I can tell (see below). `dash`, probably the strictest implementation of the POSIX shell spec, accepts it.

   * Note that even though alias expansion in _scripts_ (non-interactive shells) is disabled by default, the mechanism is still needed on occasion, such as when writing _functions_ that are _sourced_ for interactive use.

* `command foo` is _not_ a substitute for `\foo`, because, unlike `\foo`, it also bypasses _shell functions_ - see the [`command` POSIX spec](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html).

---

As for why `\foo` to suppress alias expansion of `foo` _is_ POSIX-compliant:

[2.3.1 Alias Substitution](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_03_01) states (emphasis added):

> After a token has been delimited, but **before applying the grammatical rules in [Shell Grammar](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10)**, a resulting word that is identified to be the command name word of a simple command shall be examined **to determine whether it is an unquoted, valid alias name**.

Note that quote removal has NOT yet happened at this stage, so, if the alias name is `foo`, `\foo` is clearly _not_ the same.

**Comment by koalaman** [comment]
This long standing annoyance has now been fixed. Any leading `\` for a command will now be ignored.
