### ISSUE TITLE
wiki/SC2018 and wiki/SC2019 are missing

### ISSUE THREAD

**Issue by Androbin** [koalaman/shellcheck#929]
ShellCheck Output:
```
PLATFORM="$(uname -s | tr 'A-Z' 'a-z')"
                                ^-- SC2018: Use '[:lower:]' to support accents and foreign alphabets.
                          ^-- SC2019: Use '[:upper:]' to support accents and foreign alphabets.
```

Neither of the rules SC2018 and SC2019 are present.
When following the link, it redirects to the wiki home.

**Comment by brother** [comment]
Something like this?

- https://github.com/koalaman/shellcheck/wiki/SC2018
- https://github.com/koalaman/shellcheck/wiki/SC2019

**Comment by Androbin** [comment]
Thanks, working again!

**Comment by miaLDN** [comment]
SC2018 and SC2019 aren't appropriate for GNU `tr`

```bash
$ tr '[:lower:]' '[:upper:]' <<< "My fiancée ordered a piña colada."
MY FIANCéE ORDERED A PIñA COLADA.
```
