### ISSUE TITLE
Warn about missing [[ ]] when it's possible to guess

### ISSUE THREAD

**Issue by knirch** [koalaman/shellcheck#938]
Had a long lived bug due to sloppy refactoring;

```sh

#!/bin/bash
if [[ ${opt_file:-} ]] \
&& -e /path/to/config/file; then
   :
fi
```

#### Here's what shellcheck currently says:

Nothing.

#### Here's what I wanted or expected to see:

Commands rarely start with -, did you forget [[ ]] ? or similar.

**Comment by koalaman** [comment]
Great suggestion! This is sure to catch a lot of miscellaneous problems.
