### ISSUE TITLE
SC2173 traps word "stop" inside signal handler

### ISSUE THREAD

**Issue by dallaylaen** [koalaman/shellcheck#946]
#### For bugs
- SC2173
- online
- [x ] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/sh

stop() {
        echo "signal"
}

trap "stop" INT

sleep 5


```

#### Here's what shellcheck currently says:

$ shellcheck myscript
 
Line 7:
trap "stop" INT
     ^-- SC2173: SIGKILL/SIGSTOP can not be trapped.

$ 

#### Here's what I wanted or expected to see:

Nothing. `stop` is a function to be called and not a signal to be trapped.

**Comment by koalaman** [comment]
Fixed, thanks!
