### ISSUE TITLE
Wiki documentation for SC2049 missing

### ISSUE THREAD

**Issue by Takios** [koalaman/shellcheck#969]
Hey,

running into this warning (it is `=~ is for regex. Use == for globs`), I wasn't exactly sure what it tried to tell me so I tried to look in the wiki for examples and a more detailed explanation. However, the wiki page is missing: https://github.com/koalaman/shellcheck/wiki/SC2049. 

Greetings

PS: The affected code was `[[ ${foo} =~ ^\* ]]` and the fixed code is `[[ ${foo} =~ ^\*.+$ ]]`. Testing if ${foo} begins with a literal '*'

**Comment by koalaman** [comment]
This totally fell through the cracks, but at least it's fixed now.  Your code was of course correct, and some parsing fixes for #1367 will make shellcheck realize this in the future
