### ISSUE TITLE
Missing Wiki page for SC2106

### ISSUE THREAD

**Issue by qoheniac** [koalaman/shellcheck#975]
There is no Wiki page for SC2105: "This only exits the subshell caused by the (..) group."

**Comment by brother** [comment]
Typo in the body of the report.

```
brother ~$ wiki-shellcheck.sh SC2106
SC2106 not found.
brother ~$ wiki-shellcheck.sh SC2105
SC2105: `break` is only valid in loops
```

**Comment by Gandalf-** [comment]
Both SC2105 and SC2106 both exist now, this could be closed

- https://github.com/koalaman/shellcheck/wiki/SC2105
- https://github.com/koalaman/shellcheck/wiki/SC2106

**Comment by koalaman** [comment]
Indeed, thanks!
