### ISSUE TITLE
Text after shellcheck annotation is erroneously parsed as script

### ISSUE THREAD

**Issue by vfaronov** [koalaman/shellcheck#981]
#### For bugs
- My shellcheck version (`shellcheck --version` or "online"): online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/sh
foo=1 # shellcheck: ignore=SC2034; for reasons
```

#### Here's what shellcheck currently says:

```
Line 2:
foo=1 # shellcheck: ignore=SC2034; for reasons
                                   ^-- SC1073: Couldn't parse this for loop.
 
Line 3:

^-- SC1058: Expected 'do'.
^-- SC1072: Expected 'do'. Fix any mentioned problems and try again.
```

#### Here's what I wanted or expected to see:

```
No issues detected!
```

**Comment by koalaman** [comment]
Wow, that's pretty weird.

I'll hopefully fix this at some point, but until then, note that shellcheck comments have to come before the line/structure they apply to, and that you can add additional comments after a second `#`:

```
#!/bin/sh
# shellcheck ignore=SC2034 # for reasons
foo=1 
```

**Comment by vfaronov** [comment]
> note that shellcheck comments have to come before the line/structure they apply to

Huh. But if I don’t use a semicolon in that annotation, SC2034 is disabled. So this appears to be a deeper issue. This disables SC2034 as well:

```
#!/bin/sh
foo=1 # shellcheck
```

But this doesn’t:

```
#!/bin/sh
foo=1 # shell check
```

Should I report this as a different issue?

**Comment by koalaman** [comment]
This was an interesting case. Since annotations are not parsed as comments, it ended up being a literal string instead, similar to  `foo=1 '#' shellcheck` . It appeared to suppress the warning because this is the syntax that passes a variable to a single command.

You should now get a warning and improved behavior in most of these cases. Nice catch.
