### ISSUE TITLE
NATE

### ISSUE THREAD

**Issue by nathaniel112** [koalaman/shellcheck#989]
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 
- [ ] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### For new checks and feature suggestions
- [x] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/your/interpreter
your script here

```

**Comment by Nightfirecat** [comment]
This seems to be related to the branch in your shellcheck fork that has a `HELP` file created with these contents:

```
$ shellcheck myscript
 
Line 4:
<!DOCTYPE html>
^-- SC1009: The mentioned parser error was in this simple command.
              ^-- SC1073: Couldn't parse this redirection.
               ^-- SC1072: Fix any mentioned problems and try again.
```

It seems like you're trying to run shellcheck on an HTML file... This project is meant to be used on shell scripts, not HTML documents.

**Comment by nathaniel112** [comment]
Something is seriously wrong with my computer and it's getting worse and spreading to other systems 

I don't know anything about computers but I've tried anti viruses etc 

But what ever it is it seems too be deeply fixed to the point I'm not sure how to get rid of it ?

**Comment by Nightfirecat** [comment]
@nathaniel112 I'm not sure this is the place to get help... This is a software repository for an open source shell-script static code analyzer, not a general computer troubleshooting forum.

**Comment by koalaman** [comment]
I have no idea what's going on ¯\_(ツ)_/¯
