### ISSUE TITLE
Failure to detect illegal option set -o pipefail in POSIX sh (dash)

### ISSUE THREAD

**Issue by JoshuaRLi** [koalaman/shellcheck#990]
#### For bugs
- My shellcheck version: 0.4.6 
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit

#### Here's a snippet that shows the problem:

```sh
[josh@kek ~ ]$ cat test.sh 
#!/usr/bin/env sh
set -eo pipefail
false | true
printf 'done\n'
[josh@kek ~ ]$ sh test.sh 
test.sh: 3: set: Illegal option -o pipefail
[josh@kek ~ ]$ shellcheck -s sh test.sh 
[josh@kek ~ ]$ echo $?
0
[josh@kek ~ ]$ shellcheck -V
ShellCheck - shell script analysis tool
version: 0.4.6
license: GNU General Public License, version 3
website: http://www.shellcheck.net
[josh@kek ~ ]$ which sh
/bin/sh
[josh@kek ~ ]$ ll /bin/sh
lrwxrwxrwx 1 root root 4 Jun 28 12:26 /bin/sh -> dash
```

#### Here's what shellcheck currently says:

Nothing, exit code 0.

#### Here's what I wanted or expected to see:

Something like `Option pipefail not supported in (da)sh`.

**Comment by nihilus** [comment]
Most likely SC2169. Nota bene that the busybox Almquist shell implementation does support pipefail.
