### ISSUE TITLE
sheklcheck attempts to figure out dynamic variables

### ISSUE THREAD

**Issue by orbea** [koalaman/shellcheck#998]
#### For bugs
- Rule Id:  SC2154
- My shellcheck version: online
- [x] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### Here's a snippet or screenshot that shows the problem:

```sh

#!/bin/sh

set -eu

example='example:foo:bar:test'

for i in a b c; do
  eval "$i=\"\${example##*:}\""
  example="${example%:*}"
done

echo "a = $a" # test
echo "b = $b" # bar
echo "c = $c" # foo
echo "example = $example" # example

```

#### Here's what shellcheck currently says:

```
Line 12:
echo "a = $a" # test
          ^-- SC2154: a is referenced but not assigned.
 
Line 13:
echo "b = $b" # bar
          ^-- SC2154: b is referenced but not assigned.
 
Line 14:
echo "c = $c" # foo
          ^-- SC2154: c is referenced but not assigned.
```

#### Here's what I wanted or expected to see:

Nothing.

The variables are dynamically set with eval in a for loop hence they are always set, but shellcheck is attempts to resolve them anyways. I could silence shellcheck with `${a:?}`, but that is largely redundant with `set -eu`.

**Comment by koalaman** [comment]
You're right of course, but it's ShellCheck's intention not to try to figure out whether a variable may be set or referenced dynamically.

If your file makes heavy use of dynamically assigned values, consider just disabling SC2154 with a filewide annotation.

**Comment by orbea** [comment]
Okay, thanks for the response.
